### ISSUE TITLE
[FEATURE]  Hide unnecessary / long values 

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#1001]
The ability to hide long values and adjust column sizes would be great ! 

![image](https://github.com/frangoteam/FUXA/assets/25065897/46e96039-b9e8-405f-b081-9c3fc5eb4839)

![image](https://github.com/frangoteam/FUXA/assets/25065897/2d6be856-1661-49aa-a317-ec0f0105001b)

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
