### ISSUE TITLE
[BUG] Only one Action can be set per tag, hide/show not possible

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#1003]
As per title

This seems true for all actions. 

**To Reproduce**
1. Create shape
2. Click on shape
3. Click on Properties 
4. Click on actions
5. Select show on x tag ==1
6. Click +
7. Select hide on x tag == 0
8. Click ok
9. Go back into properties / actions, there is only one action so toggle hide show is not possible using the same tag 

**Screenshots**

Set details, click ok
![image](https://github.com/frangoteam/FUXA/assets/25065897/fb2ac7b9-42e6-4d60-8651-9086112711b9)

On return...
![image](https://github.com/frangoteam/FUXA/assets/25065897/acc8534f-329f-427d-85ed-b11b6790c725)

**Environment**
 - FUXA version: 1.1.15-1368

**Comment by unocelli** [comment]
Hi, I can't confirm the issue, I have just tested it and it works as expected.

**Comment by lewsut** [comment]
> Hi, I can't confirm the issue, I have just tested it and it works as expected.

It looks like it's just happening on a few specific shapes, I'll see if I can narrow it down.
