### ISSUE TITLE
[FEATURE] Touch & click events similar to click, mouse down, mouse up for touch screen / mobile browsers 

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#1005]
For example, clicking stuff to see a mouse down up event on a mobile browser is poor.  Sometimes clicks are recognised, sometimes they are not, mouse down, mouse up is never shown. 

How things look on a PC 
![pc](https://github.com/frangoteam/FUXA/assets/25065897/a5fb7c74-143e-47ac-ad36-6c69c452f7bd)

How things look on android
![android](https://github.com/frangoteam/FUXA/assets/25065897/40be4679-dfe5-45c0-a69f-dd0f3272eac8)

**Comment by Miroslav999** [comment]
This is also relevant for me

**Comment by unocelli** [comment]
Hi, This issue should be fixed in the current master branch 2b38e320dfae056308a1ad7a2ab3eff8e13a83ad. let me know if you have any issues.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by Miroslav999** [comment]
@unocelli , I still have this problem (

**Comment by unocelli** [comment]
@Miroslav999 please provide a project where you can reproduce the issue

**Comment by Miroslav999** [comment]
@unocelli , sorry, i mean another scenario, open live demo https://frangoteam.github.io/home -> open developer tools (F12) -> tap Toogle device toolbar -> set dimensions any android (Example pixel ) -> tap burger button 
Result: burger button does not respond to pressing
