### ISSUE TITLE
Proposal: Gauge actions by more than one variable

### ISSUE THREAD

**Issue by NikolayMurha** [frangoteam/FUXA#101]
Hello.
I need to display an element by two values. 
For example, when 'a=1 && b=0'

**Comment by unocelli** [comment]
Hi,
I think that a good way to implement this feature is to give the possibility to define script.
Every view could be bind to one script, where you can define simple logic and variable to bind at gauges present in the view
The script will be in javascript, working in frontend. 
In my todo list I have also planned the scripts in the backend but for the logic of the processes

**Comment by NikolayMurha** [comment]
Now I solve it on controller side. 
Return analog one variable by OPCUA with three posible values instead of boollean

**Comment by unocelli** [comment]
Can be done using scripts, so I am closing this issue.
