### ISSUE TITLE
[FEATURE] Option to copy a shape's properties

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#1015]
When  copying  and pasting shapes with properties, actions and events defined these get removed in the pasted item.

**Comment by robbudge** [comment]
now this depends on the Shape, 'Shapes' or Objects
Objects , grouped or not will loose the configuration
if you are using 'Shapes' and group them, especially with an event on the group.Most times the configuration of items within the group are maintained.
when this fails, i refresh the page and its good again.

objects always loose configuration. but this is a work around.
take 2 shapes, say a squares. configure fill based on a tag.
group them.
save page.
copy and paste.

**Comment by lewsut** [comment]
I see and agree, thanks, I find grouping very buggy and annoying. From other SCADA/HMI designers, I have seen multiple  Copy "special " option, with everything, with just shape, with just tags and such like. Perhaps that would be nice?

**Comment by unocelli** [comment]
Hi, the copy and paste function of the shapes that I have tested work as expected, please indicate for which shapes the problem occurs.

**Comment by lewsut** [comment]
> Hi, the copy and paste function of the shapes that I have tested work as expected, please indicate for which shapes the problem occurs.

empty view, simple square, one property:


![props](https://github.com/frangoteam/FUXA/assets/25065897/2f97e011-8c00-4ed4-b29f-0bf8d75b9b86)

**Comment by unocelli** [comment]
Hi, Thanks for the report.
Yes effectively the copy/paste of shapes in General category does not work as it should.
That is to be fixed.
