### ISSUE TITLE
Parse JSON from MQTT

### ISSUE THREAD

**Issue by 23Errors** [frangoteam/FUXA#1018]
Hey, is it possible to parse json data coming over MQTT?
The json data I get looks like this:
`"payload": {
      "object1": 500,
      "object2": 300,
      "object3": 999
}`

I can´t access the single values because the json data is only parsed once by FUXA and then I get an object with this 3 values in it back.
How can I change this?

**Comment by lewsut** [comment]
You can use forEach in scripts if it's an object, you may need to use JSON.parse but I do something similar with success 

`Your_MQTT_Tag.forEach(item =>{
  
console.log(item.object1);
 
});`

**Comment by 23Errors** [comment]
Nice, thanks.
