### ISSUE TITLE
I want to ack alarm through the API, but I don't know how to fill in this Alarm ID?

### ISSUE THREAD

**Issue by Doboo** [frangoteam/FUXA#1019]
Hi;
I  can  get alarms like this 
![PixPin_2023-12-16_09-18-19](https://github.com/frangoteam/FUXA/assets/12352436/8f74ad3d-e5c5-4c65-9471-b9108d2a226e)

I don't konw how to fill in this  Alarm ID?

`msg.payload={
    "params": Alarm ID
}
return msg;`

**Comment by unocelli** [comment]
Hi, you have to set the name:
`
{
    "params": "seconds^~^high"
}
`
we were not always consequent :confused:

**Comment by Doboo** [comment]
> Hi, you have to set the name: `{ "params": "seconds^~^high" }` we were not always consequent 😕

Thanks for the reply! It works fine.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
