### ISSUE TITLE
Cannot read property 'numberOfItems' of undefined

### ISSUE THREAD

**Issue by NikolayMurha** [frangoteam/FUXA#102]
Hello.

After resizing some grouped objects I have error on save:

`core.js:1673 ERROR TypeError: Cannot read property 'numberOfItems' of undefined`
 

Apparently, this is a rare error, but I have it.

Step for reproduce:
1. Load project https://gist.github.com/NikolayMurha/ceb0e5d365c011089d5a6f759bbc8e60
2. Save and reload (just in case)
3. Resize green object
4. Try to save

P.S. Pull request soon

**Comment by unocelli** [comment]
Great job Nikolay, I hope to see a demo of your shapes ;)
