### ISSUE TITLE
[FEATURE] Port change

### ISSUE THREAD

**Issue by Bundyra** [frangoteam/FUXA#1021]
Chaning default port from 1881 to custom port. Currently in settings we can only see port on which server is working, but we cannot change it. It would be nice to have that option, so we admin doesn't have to change port manually in files.

**Comment by mauroalexandre** [comment]
Hi.

Look this line https://github.com/frangoteam/FUXA/blob/1467713dfdd30299fc4bd34ef045804c22133f44/server/settings.default.js#L10

First, FUXA tries to read the environment variable PORT; if it does not exist, it uses the value 1881.

You can change the default port setting your enviroment var PORT, for example to use port 9090:

```
[upmauro@archlinux server]$ export PORT=9090
[upmauro@archlinux server]$ npm start
&gt; fuxa-server@1.1.15-1376 start
&gt; node main.js
2023-12-20T17:31:59.075Z [INF] 	FUXA started!
2023-12-20T17:31:59.077Z [INF] 	WebServer is running http://127.0.0.1:9090/
```

**Comment by Bundyra** [comment]
But what if i want to run two fuxa servers on the same machine?

**Comment by Bundyra** [comment]
It doesn't work for me either. Any ideas why?
![image](https://github.com/frangoteam/FUXA/assets/79423733/470e269e-1d17-4b08-8406-8a4467937fc9)

**Comment by Bundyra** [comment]
It's not working for me. Any ideas why?
![image](https://github.com/frangoteam/FUXA/assets/79423733/0a5cc8ce-6629-4e20-a886-2056b815eef4)

**Comment by unocelli** [comment]
setting.js is the default setting, but changes from UI are saved in mysettings.json and overwrite the values of settings.js (look uiPort)

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by Bundyra** [comment]
Im still a bit confused.. 
My problem still occurs.
My scenario:
Environment variable PORT=1884
![image](https://github.com/frangoteam/FUXA/assets/79423733/42484d1a-9669-49a2-b3f1-9a6e839b01d4)
I made some changes in client dir, for example changed favicon and title in index.html, so i did ng build.
I start server once again:
![image](https://github.com/frangoteam/FUXA/assets/79423733/657d4d31-1bfa-4d15-9578-5853c01cac0d)
![image](https://github.com/frangoteam/FUXA/assets/79423733/75d39dec-72c3-4555-be32-2ff83962620e)
![image](https://github.com/frangoteam/FUXA/assets/79423733/e63a5f81-1cf1-4768-970e-b7c2c5838270)

**Comment by Bundyra** [comment]
Im still a bit confused..
My problem still occurs.
My scenario:
I changed environment variable PORT=1884.
![image](https://github.com/frangoteam/FUXA/assets/79423733/41607110-3dc2-48ae-b9f4-ccbae09d4541)
Server starts, fuxa is loading.
Next, i do some changes in the client dir, for example I change title of the site in index.html and change favicon.
I do ng build.
Start server again:
![image](https://github.com/frangoteam/FUXA/assets/79423733/f70238d3-deac-4028-a32f-504b27aab0f7)
and then:
![image](https://github.com/frangoteam/FUXA/assets/79423733/9f9ea72e-a016-442f-ac7f-9db38ff11deb)
![BUG](https://github.com/frangoteam/FUXA/assets/79423733/2288109f-de90-45fd-b233-b2c54d454eba)
What am I doing wrong?
