### ISSUE TITLE
[FEATURE]svg cannot flash as a whole

### ISSUE THREAD

**Issue by 2697403929** [frangoteam/FUXA#1022]
Hello, after I imported the svg and configured it as shown in the picture, why only the area I circled in the picture is flashing? Normally the entire object should be flashing. I tried many, either a small part of it would flash, or it wouldn't flash at all. Why is this happening?
![3ab5b56935e175436d66f9fb232b5e7](https://github.com/frangoteam/FUXA/assets/102354144/d4170db8-4d70-4786-8b16-3a029566a37f)
![5297272b4be1a624c90e2535dfdfb8a](https://github.com/frangoteam/FUXA/assets/102354144/2687c442-8ec0-452f-9f76-a6ff27b0ab44)
![a2e25a3cbb0d58570e0215f24a1e57d](https://github.com/frangoteam/FUXA/assets/102354144/896bfa2f-cd7a-40bb-a374-8d820aa999c0)

**Comment by mauroalexandre** [comment]
Can you attach SVG?

**Comment by 2697403929** [comment]
![设备01](https://github.com/frangoteam/FUXA/assets/102354144/669b50cc-7154-416b-9f88-34231c8f6f2c)
![资源 1](https://github.com/frangoteam/FUXA/assets/102354144/29c3045f-a14f-43b2-a374-37ffd0bf6301)
This is the original file

**Comment by 2697403929** [comment]
![设备01](https://github.com/frangoteam/FUXA/assets/102354144/e238e872-e743-46e7-a594-ab6e60a89340)
![资源 1](https://github.com/frangoteam/FUXA/assets/102354144/d7779f2a-0f68-4bb0-828b-cbbb0c539c4a)

**Comment by unocelli** [comment]
Hi, 
these images consist of more than 1000 elements, I honestly find it a challenge to try to select one or a group of them to edit, for your goal I would add a new element on over.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
