### ISSUE TITLE
[FEATURE]Can variable links be preserved when copying elements or cloning views?

### ISSUE THREAD

**Issue by pystudy123** [frangoteam/FUXA#1025]
**Describe the feature**
The requirement is, for example, I made an indicator light with many colors that change according to various variables. Then if I copy this indicator light to the current or other views, the indicator light will return to its original appearance, and the color changes based on the data will disappear, which is very inconvenient.

**Describe the solution you'd like**
When pasting, can I choose whether to keep the link or keep the function?

**Additional context**
![Snipaste_2023-12-22_08-43-08](https://github.com/frangoteam/FUXA/assets/57655202/4060495a-71a1-4123-a59c-751a1e551b69)

**Comment by pystudy123** [comment]
Or maybe I have done many effects in one attempt, and after cloning a similar attempt, I have to do it again.

**Comment by unocelli** [comment]
I suppose you have try with Shapes of General section. For all other Shapes or Controls the property should be copied too.
There is already a issue open #1015

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
