### ISSUE TITLE
[FEATURE]Can I add a tab page to the view?

### ISSUE THREAD

**Issue by pystudy123** [frangoteam/FUXA#1026]
**Describe the feature**
That is, in a view page, I can click the button to display different content

**Describe the solution you'd like**
It is worth not clicking the button to display different view pages. For example, if there are too many view pages, reaching dozens, I would like to think of some, such as several attempts, through an effect similar to a tab page, to achieve it in one view.

**Additional context**
![Snipaste_2023-12-22_08-49-50](https://github.com/frangoteam/FUXA/assets/57655202/efba85f0-0d75-4e54-9b89-ba9bbc0b4405)

**Comment by unocelli** [comment]
Hi, I suppose it is the same feature discussed in #925, it is coming soon.

**Comment by unocelli** [comment]
is available in the latest version,  let me know if you have any issues.
