### ISSUE TITLE
[QUESTION] Can I change TAG VALUE from internal device using script?

### ISSUE THREAD

**Issue by mauroalexandre** [frangoteam/FUXA#1032]
I would like to provide a straightforward example: I'm aiming to create a clock in my interface to display the current date and time. I'm curious, is it possible to change the value of a tag using either server-side or client-side scripting?

**Comment by lewsut** [comment]
Like this?

Create a script to write to a string tag the date and time every second...
![image](https://github.com/frangoteam/FUXA/assets/25065897/748bb5ff-e94a-411c-8eb6-09695056ae27)

then display that tag...

![image](https://github.com/frangoteam/FUXA/assets/25065897/f960e117-8b07-4c24-b6e5-68e3fa119a92)


edit script for the time format you want....

![image](https://github.com/frangoteam/FUXA/assets/25065897/d8d4f61a-7d2a-4cf8-8118-2721267ee1ca)

**Comment by mauroalexandre** [comment]
Wow @lewsut thanks for yout help. Now I see "functions" in editor. My fault.

Thanks alot.

**Comment by Jue07** [comment]
> Like this?
> 
> Create a script to write to a string tag the date and time every second... ![image](https://private-user-images.githubusercontent.com/25065897/293043806-748bb5ff-e94a-411c-8eb6-09695056ae27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjQ4MjQsIm5iZiI6MTcwODU2NDUyNCwicGF0aCI6Ii8yNTA2NTg5Ny8yOTMwNDM4MDYtNzQ4YmI1ZmYtZTk0YS00MTFjLThlYjYtMDk2OTUwNTZhZTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAxMTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZThmODc0NzRhOTdlNDcwZGRmMWVhOTljM2YzNmY1Mzg3MzIxM2M2YzRlZDg0NjI5NDE4MDViODU5YmU1ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YTm5_6NPSvDXEOCGWQoPtVO_oHk-Olm3l_29S-KUSZ4)
> 
> then display that tag...
> 
> ![image](https://private-user-images.githubusercontent.com/25065897/293043968-f960e117-8b07-4c24-b6e5-68e3fa119a92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjQ4MjQsIm5iZiI6MTcwODU2NDUyNCwicGF0aCI6Ii8yNTA2NTg5Ny8yOTMwNDM5NjgtZjk2MGUxMTctOGIwNy00YzI0LWI2ZTUtNjhlM2ZhMTE5YTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAxMTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNWI0Njg5NjA3ZmE4NjhlZjk2ZWVmOTE4YTAyYjI4NDU4YjdhMDhjYjM3ZmQ2MTUyNWVhNmNlZDZkYzVlOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rN3EOZmeT7bPOuPTGI_jixXGw2NV8sIeyXf40iYE6CM)
> 
> edit script for the time format you want....
> 
> ![image](https://private-user-images.githubusercontent.com/25065897/293044068-d8d4f61a-7d2a-4cf8-8118-2721267ee1ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjQ4MjQsIm5iZiI6MTcwODU2NDUyNCwicGF0aCI6Ii8yNTA2NTg5Ny8yOTMwNDQwNjgtZDhkNGY2MWEtN2QyYS00Y2Y4LTgxMTgtMjcyMTI2N2VlMWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAxMTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NjNkZDZmZTA3NGRmODA0NDlhNTE0NDlhMWE3MWEyMjk1MDY3NDRhMTE3YjFlNmVkNzkwZWQ3MjA1Y2U4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vR2uzSGf0Q57XrPhQP1_Z2qrl6RvqVnPSuKDSnZvt6g)

Hi, the date time script does not appear in the tag selection. How to configure it?
