### ISSUE TITLE
[FEATURE] Add the 'name' attribute to the element when rendering the view as an SVG.

### ISSUE THREAD

**Issue by mauroalexandre** [frangoteam/FUXA#1033]
To make it easier for a frontend script to find an element through the selector, it would be fantastic if the name of the element was in some SVG attribute created when the view is rendered.

**Comment by mauroalexandre** [comment]
@unocelli hello, does this pull request make sense to you? #1103

If so, it would be interesting to be able to apply the same attribute to elements such as Rect, Text, and especially to svg-ext-shapes-image.

With this, it would be possible to switch between images, texts, etc., through the execution of scripts using selectors.

**Comment by unocelli** [comment]
It is available in the latest version, Thanks!
