### ISSUE TITLE
[FEATURE]Options select in control tab display

### ISSUE THREAD

**Issue by liulujian00** [frangoteam/FUXA#1039]
Options select in control, I want the second select option to be displayed differently depending on the first select option，How to achieve。
<img width="277" alt="1212" src="https://github.com/frangoteam/FUXA/assets/57060942/fe0907fe-fb00-4345-9af4-8dff2c7a4c7f">

**Comment by unocelli** [comment]
Hi, you can show/hide the 2 different 'second select' on depend of 'first select'

**Comment by liulujian00** [comment]
Thank you, did I put the second option box in the same position and show/hide it? I tried it and it worked.
