### ISSUE TITLE
[BUG]Timer works bad

### ISSUE THREAD

**Issue by Brandix97** [frangoteam/FUXA#1040]
First of all I have Node 16.10.2 version and FUXA V 1.1.16

When I create a script that runs every second, and in this script, I add a code like "var++;", this variable takes approximately 2-3 seconds to change.

**Comment by unocelli** [comment]
I can not confirm this issue and in any case it depends on so many related factors including the platform you use, your description is really poor

**Comment by unocelli** [comment]
I’m closing this issue since there is nothing feasible and due to inactivity.
