### ISSUE TITLE
[BUG] Clunky keypad entry, Decimal Point key causes number deletion.

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#1047]
Generally the selection of numbers, is not so intuitive, personally I would expect to type a new number in after I click the box not add to what is there. However that could just be preference. 

Then the decimal point key seems to cause deletion of the entry.

Version 1.1.17-1399

![props](https://github.com/frangoteam/FUXA/assets/25065897/3f3dcb3d-1692-437f-bdaa-57bc413a7c0d)

Additionally entry limits in my case 30min 100max seemingly do nothing I am able to enter whatever I want without restriction 

![image](https://github.com/frangoteam/FUXA/assets/25065897/d428a84b-5038-4ae2-8518-f48fdf2ab89c)

![image](https://github.com/frangoteam/FUXA/assets/25065897/5d7fa792-5184-43aa-a914-0a19c09b5d38)

**Comment by robbudge** [comment]
I did notice the same, but was only on Safari not chrome.

**Comment by lewsut** [comment]
Mine was on chrome and firefox

**Comment by unocelli** [comment]
Hi, the Virtual Keyboard with input type number have some issue, I think that I have found a compromise in the last commit.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
