### ISSUE TITLE
Port change problem still occurs.

### ISSUE THREAD

**Issue by Bundyra** [frangoteam/FUXA#1048]
Im still a bit confused..
My problem still occurs.
My scenario:
I changed environment variable PORT=1884.
![image](https://github.com/frangoteam/FUXA/assets/79423733/41607110-3dc2-48ae-b9f4-ccbae09d4541)
Server starts, fuxa is loading.
Next, i do some changes in the client dir, for example I change title of the site in index.html and change favicon.
I do ng build.
Start server again:
![image](https://github.com/frangoteam/FUXA/assets/79423733/f70238d3-deac-4028-a32f-504b27aab0f7)
and then:
![image](https://github.com/frangoteam/FUXA/assets/79423733/9f9ea72e-a016-442f-ac7f-9db38ff11deb)
![BUG](https://github.com/frangoteam/FUXA/assets/79423733/2288109f-de90-45fd-b233-b2c54d454eba)
What am I doing wrong?

_Originally posted by @Bundyra in https://github.com/frangoteam/FUXA/issues/1021#issuecomment-1880554295_

**Comment by unocelli** [comment]
Hi, I can only confirm in FUXA it works as expected! so the problem lies in your modifications, I would look there

**Comment by Bundyra** [comment]
I just reproduced it without making any changes in the files, so i wouldn't be so sure about the problem with my modifications. All i did was npm install in the server directory, then npm install and ng build in the client directory.
I start fuxa: 
![image](https://github.com/frangoteam/FUXA/assets/79423733/29ac0f4c-b420-4529-a945-8e02de239bde)
And then:
![image](https://github.com/frangoteam/FUXA/assets/79423733/781376d0-1b72-482a-9b0f-0e395550363a)
But if you are sure that everything is working as expected then ok.
Thank you for your answer.

**Comment by unocelli** [comment]
try 
`ng build --configuration=production`

**Comment by Bundyra** [comment]
Works perfect. Thank you for your help!

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
