### ISSUE TITLE
[BUG] Date and Time option in Input control doesn't work correctly

### ISSUE THREAD

**Issue by KamilGrabowski01** [frangoteam/FUXA#1050]
**Describe the bug**
While attempting to insert data into the input control, using both date/time and separate date and time input types, two windows appear simultaneously. One displays the date/time, while the other presents a numeric keyboard. It is not possible to save the date in the first window; clicking elsewhere prevents the date from being saved, and the window closes, leaving only the numeric keyboard window. If you attempt to input data using the numeric keyboard, it does not function as expected, as it always leave the default data, no matter what you click. The only option for data insertion is to utilize the first window to input date/time and subsequently save it by pressing 'Enter' in the second window.

**To Reproduce**
1. Create input control with date/time or separate date and time input types.
2. Click on it to insert data.
3. Notice that two windows have popped up simultaneously—one with date/time and the other with a numeric keyboard.
4. Try to insert any date/time.
5. See that any attempt to save data using only one of the windows is not possible.

**Expected behavior**
In the date/time selection window, there should be an 'Enter' button that saves the date/time to a variable, and the window with the numeric keyboard should not open.

**Screenshots**
Creating input control.
![image](https://github.com/frangoteam/FUXA/assets/91898420/265d53ce-5d88-4df1-94cf-08a6669752a3)
Trying to insert data, see that two windows appear simultaneously.
![image](https://github.com/frangoteam/FUXA/assets/91898420/3f7a1860-c6df-4895-bac4-5528c3e38032)
After choosing the date, the second window with the numeric keyboard remains open.
![image](https://github.com/frangoteam/FUXA/assets/91898420/1f1aeef5-4a37-417f-92aa-ef0c419323dc)
If we click enter, it will save the choosen date.
![image](https://github.com/frangoteam/FUXA/assets/91898420/0a6ec5e2-8a03-4871-93c7-cdac284e4fb5)
But if we click any other button, it will reset the date.
![image](https://github.com/frangoteam/FUXA/assets/91898420/915773d4-d392-439e-9cf3-2c0cd62e0b6b)

**Environment**
 - FUXA version: 1.1.17 - 1399
 - Node.js version: 16.20.2
 - npm version: 8.19.4
 - Platform/OS: Windows 10
 - Browser: Opera

**Comment by unocelli** [comment]
Hi, Thanks for the report.
let me try to fix it

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
