### ISSUE TITLE
[Question] What to input in modbus-rtu Serial port config on Windows OS.

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#1053]
Hi I don't see any related tutorials or wikis about this, but I am struggling on what to put on the "SerialPort" options on Modbus-RTU settings? 
Basically I only input the COM port# in other SCADA system like "COM1", "COM2" or etc.
In Fuxa, how do I input this? is it the same? 
![image](https://github.com/frangoteam/FUXA/assets/49782655/90d2339a-143c-45c7-abe4-aa3e71248a99)

Thanks and regards,
Henjoe

**Comment by unocelli** [comment]
Hi, 
If you have COM4 in Windows then It should be right.

**Comment by henjoe** [comment]
Thanks @unocelli
