### ISSUE TITLE
Press and hold on touch screen devices

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1056]
Hi,

I'm running FUXA on a device with touch screen and Windows 10 OS. I'm facing the following problem as you can see in [my video](https://gemoo.com/tools/upload-video/share/606955599585480704?codeId=PYadWqkp2BqpJ&card=606955594510372864).
On the circle is a toggle bit function. If bit's value is true, circle's color is red. Otherwise, circle's color is gray.  If I use the left mouse click on touch screen device, it works always as expected. If I use the finger on touch screen device, two scenarios arise:
1) When I hold the finger a little bit longer on the screen, appears the menu corresponding for right click action. This right-click menu shouldn't be appearing if I hold the finger on touch screen for any time period. It happens even though I adjust the touch's sensitivity. I have disabled from control panel (on Pen and Touch section) the option "Enable press and hold from right-clicking".  This option has no effect upon the web browser. 
2) When shortly taping the circle, the toggle function doesn't execute always.

**Comment by robsori** [comment]
Yes, I also confirm this problem. On any Touch Screen, when you press a button, the menu dedicated to the right mouse button appears and becomes annoying for operation. I was not able to remove this menu from the windows operating system settings. Maybe there should be a configurable option in Fuxa to remove this menu for working with the Touch Screen.

**Comment by unocelli** [comment]
Hi, are you sure it is not a setting on the OS? it seems to me that you can also set the hold delay.

**Comment by IonuDragomir1** [comment]
Hi,
This option is available only on touch screen devices.  I have disabled from control panel the hold setting. It has effect only on Windows OS, but not on browser. So, as @robsori wrote, it should be a configurable option in Fuxa to remove this menu but only on runtime.

**Comment by unocelli** [comment]
Hi, should be fixed in recent commits, please try with current master branch

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
