### ISSUE TITLE
Something wrong with charts display in the editor in Chrome

### ISSUE THREAD

**Issue by NikolayMurha** [frangoteam/FUXA#106]
Hello.
When I insert chart to canvas text and rulers are not displayed. I try to change colors but not work.

[Screenshot 1](https://www.dropbox.com/s/vgz4b8paepq8n4p/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202021-02-05%20%D0%B2%2021.01.07.png?dl=0)

Mac OS Big Sure
Chrome 88.0.4324.146

**Comment by unocelli** [comment]
Ciao,
the same problem by 'Circular Gauge' and 'Slider' controls, the reason is the scrollbar showed and some DOM with 'position: absolute'. I fixed the chart and circular gauge and I'm looking for the slider.
