### ISSUE TITLE
[Question]  mapping floating point value in modbus

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#1060]
Hi,

I have a modbus device (which is a power meter) with holding register 6-7 (two holding registers) being its voltage value.
it is a floating point value as per their documentation. 
My question is how can I map the data in the Fuxa? I am using modbus RTU for this.

is my configuration below is correct?
![image](https://github.com/frangoteam/FUXA/assets/49782655/7919daaf-7e61-4292-9bd4-d60e909b4c0a)

and also, what is the meaning of divisor? 
Thanks!

Regards,

**Comment by IonuDragomir1** [comment]
I have encountered the same issue. More details at [#682](https://github.com/frangoteam/FUXA/issues/682)

**Comment by GrantC27** [comment]
I successfully read 32 bit floats from a Schneider PLC and an ABB PLC. The type I use is Float32MLE. If I look at the value in Modbus poll I use little endian swap byte. Seems to work well for me - I'm sure RTU has the same config. The register address is 1 more than what is stated in the PLC. For example, the value in the below screenshot is actually at %MW514

<img width="637" alt="Screenshot 2024-01-24 112145" src="https://github.com/frangoteam/FUXA/assets/67634279/fb705737-9de2-4149-b42a-10c1d2f54ce1">

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
