### ISSUE TITLE
[BUG] Text display with numbers doesn't work as expected

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#1066]
Annoyed by issue #1063 I thought until it's fixed I would use a walk around of a text input and interpret the string to get my hh:mm values. Unfortunately this doesn't work as expected either, I get my values to the back end correctly, however the frontend fails to display numbers followed by a non number correctly.

Setup:

![image](https://github.com/frangoteam/FUXA/assets/25065897/cd66815f-1cf3-4965-8f15-a8be054158f6)

![image](https://github.com/frangoteam/FUXA/assets/25065897/286d72f8-708f-4411-9a1b-3d8ae9c91d3a)

Entering my string 

![image](https://github.com/frangoteam/FUXA/assets/25065897/13e3fdef-8fcd-4d00-9628-8ba0a11b84de)

press enter...

![image](https://github.com/frangoteam/FUXA/assets/25065897/35e28fe9-9158-46ea-9a55-f0a8cd8babbb)

This is a text string I expect to see 09:55 

Back to the drawing board, I'll use two separate number input boxes for now, however it's impossible to display a leading 0 in an input box so it doesn't look good.

**Comment by unocelli** [comment]
Hi, thanks for the report. I will fix it as soon as possible. however feel you free to do a PR with the fix.

**Comment by lewsut** [comment]
> Hi, thanks for the report. I will fix it as soon as possible. however feel you free to do a PR with the fix.

I wish I had the know how to help fix these issues myself! Thanks for your work man, I know I report a lot of bugs!!!

My knowledge is c/c++ and PLCs, so I'm a bit useless, I wish I could help more!

**Comment by lewsut** [comment]
Same issue, different place 

![image](https://github.com/frangoteam/FUXA/assets/25065897/238a8b02-155a-47f2-b861-58b3dfc1477d)

**Comment by unocelli** [comment]
with last commit should be fixed, Thanks!

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
