### ISSUE TITLE
[BUG] move tools with arrows

### ISSUE THREAD

**Issue by Tsigh** [frangoteam/FUXA#1067]
**Describe the bug**
When moving chosen items text and figure moves in different pace than output value/LED gauge.

**To Reproduce**
Make a block and chose everything in it and the figure itself.

**Expected behavior**
Move the block with the arrows left, right, up and down. 
Left and up only moves LD and output value.
Right and down has different paces for text/figure and LED/output value.

**Screenshots**

This is going right, then left the same number of steps.

![image](https://github.com/frangoteam/FUXA/assets/77735511/b736c282-f849-40a8-ab25-8860d99b4cf1)

![image](https://github.com/frangoteam/FUXA/assets/77735511/ae147aeb-4bec-4903-bd7a-25fe858e887f)

![image](https://github.com/frangoteam/FUXA/assets/77735511/abbf3309-3ccd-4ee5-a44b-57a93c922a33)

**Environment**
 - FUXA version: 1.114-1243
 - Node.js version: -
 - npm version: -
 - Platform/OS: Windows
 - Browser: FireFox

**Comment by unocelli** [comment]
Hi, with the current version 1.1.17 I cannot reproduce it, some problems with the editor have been fixed

**Comment by Tsigh** [comment]
Now in FUXA  1.1.17 -1399

The text follows along, but the buttons (and LED as well) doesn't

![image](https://github.com/frangoteam/FUXA/assets/77735511/f69f43b5-09c7-4439-8950-3699d1847873)
chosing everything.
![image](https://github.com/frangoteam/FUXA/assets/77735511/1c0f83a4-3ecb-42b8-b43f-7744163dc966)
moving down 10 steps by arrow down.
![image](https://github.com/frangoteam/FUXA/assets/77735511/f9bb4d84-fbda-46da-a562-ff4c95a0c018)
then regretting and going up 10 steps by arrow up.
![image](https://github.com/frangoteam/FUXA/assets/77735511/f48813dd-3a46-4699-981f-d78701427ad7)

**Comment by unocelli** [comment]
I wonder if it is a browser problem, did you try to reproduce it with the chrome browser?

**Comment by Tsigh** [comment]
Yes indeed, Chrome solves the problem! Thanks for the help. FUXA gets
better and better the more I use it!

Den søn. 4. feb. 2024 kl. 17.03 skrev Umberto Nocelli <
***@***.***>:
