### ISSUE TITLE
[BUG]When entering numbers, the virtual keyboard cannot enter floating-point numbers.

### ISSUE THREAD

**Issue by jingshui127** [frangoteam/FUXA#1070]
**Describe the bug**
When entering numbers, the virtual keyboard cannot enter floating-point numbers.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - FUXA version: 
 - Node.js version: 
 - npm version:
 - Platform/OS:
 - Browser:

**Comment by unocelli** [comment]
is fixed in recent commits, master branch or docker. not in npm version.
