### ISSUE TITLE
What's the use of Panel control?

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1071]
Hi,

I have read several times [#925](https://github.com/frangoteam/FUXA/discussions/925) but I couldn't  understand panel's usage. Could you please explain it's purpose and how could be used? 

Thanks in advance!

**Comment by unocelli** [comment]
Hi,
![control-panel](https://github.com/frangoteam/FUXA/assets/48684550/a2da3ee9-46c8-4dd9-94a6-f2b87bd09593)
