### ISSUE TITLE
[FEATURE] Call alarm control on a view

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1072]
Hi,

I have seen that now, on a MVC's container can be added the alarms. A very useful feature would be to call the alarms/history alarms control on a simple view. The need comes for observing the alarms of certain mechanism. For example, when the user clicks on pump P1, a view with it's alarms should be opening. The easiest way I see at first thought would be to filter through database for alarms which have group's name "Pump1" and then display them on the control called on a simple view.

**Comment by unocelli** [comment]
Hi,
the idea would be to add to the table control, the possibility of having the data from a query. As UI a json editor to configure the table properties.

**Comment by IonuDragomir1** [comment]
Hello,
So the table control which would contain only the alarms of a certain mechanism should be colored according to mechanism's configured alarms. Please see an example of how the table should be looking like.

![image](https://github.com/frangoteam/FUXA/assets/58516894/ca89bd8b-5456-4768-a172-cfdeab8bc8c6)

**Comment by unocelli** [comment]
Hi, is available in the latest version (Table control), let me know if you have any issues.
