### ISSUE TITLE
Report not generating with tag value,

### ISSUE THREAD

**Issue by shyamc2u** [frangoteam/FUXA#1077]
Report not generating on schedule time with tag values,  
time stamp generating as i set to 5mins, but tag values at that time is not generated in reports, 
tag value live data is displayed on the Modbus tags and SCADA pages is normal.
i checked the sqlite db, tag values are available. 

**Please help me what to do for report generation with tag values.** 
_**kindly give me solution**_ 

and alarms report is generating is good.

**Comment by unocelli** [comment]
Hi,
I just tested and for me is working as expected. can you send me the project?

**Comment by shyamc2u** [comment]
[fuxa-project.json](https://github.com/frangoteam/FUXA/files/14216142/fuxa-project.json)
I am restarting the PC (server start time is 9 am to 5 pm), fuxa running well but reports with tag values did not appear in the 
pdf 
file.

**Comment by Jue07** [comment]
Hi..I am also facing the same issue..can you help me?

**Comment by shyamc2u** [comment]
It's working fine, but don't restart PC , don't shutdown PC and don't close the fuxa application, for 24x7 365 days. If you did anything reports not generate for 24 hrs. Then again next  day on words it's working fine.

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
