### ISSUE TITLE
[BUG]Scripts timer doesn't execute well

### ISSUE THREAD

**Issue by Brandix97** [frangoteam/FUXA#1086]
I have made a script that updates the date every second, and sometimes it runs every second and other times every 2 seconds

To Reproduce
1. Go to 'editor'
2. Create a script every second
3. Write this script:"var fechaActual = new Date();setag......"
4. put a text that the value is the date
5. Watch the error

**Environment**
 - Raspberry Pi
 - Node.js version:  14.21.3
 - Platform/OS: Raspbian x64
 - Browser: Opera GX

**Comment by MatthewReed303** [comment]
I set my scripts only on start and then use the set interval JS function. 

```
//Dynamically grab tag ID
let tagNumber_1_ID = $getTagId('tagNumber_1');
let randomNumber = 0;
let inc = 1;
//Constant Vars
const minNum = 0;
const maxNum = 100;

let myVar = setInterval(funRandomNumber, 100);
function funRandomNumber() {
	randomNumber += inc;
	if(randomNumber == minNum || randomNumber == maxNum){inc = -inc;}
	$setTag(tagNumber_1_ID /* FuxaServer - tagNumber_1 */, randomNumber);
	//console.log(randomNumber);
}
```

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
