### ISSUE TITLE
[BUG] Icon not assigned to a button added on header bar

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1095]
Hi,

I've just added a button on header bar from Layout. 
![image](https://github.com/frangoteam/FUXA/assets/58516894/cefb5fad-53dc-4d4d-beb4-336ca1e5753c)
The button has assigned an icon which is not displayed on runtime. Name "Test" was assigned from button's property.

![image](https://github.com/frangoteam/FUXA/assets/58516894/7099f42d-cc58-42fa-8549-03899be188ce)

Environment:
FUXA version: 1.1.18 - 1431
Node.js version: v14.21.3
npm version: 6.14.18
Platform/OS: WIN 10
Browser: Chrome

**Comment by unocelli** [comment]
Hi, the Icon is to use with Type: Image

**Comment by andy8601** [comment]
In addition, the button added on the title bar does not have the user authorization option. I tried to set the authorization in the page, but it did not take effect, and users without authorization can still see and click to access the contents of the button after landing.

**Comment by andy8601** [comment]
> 嗨，图标将与 Type： Image 一起使用

此外，在标题栏上添加的按钮没有用户授权选项。我尝试在页面中设置授权，但没有生效，未经授权的用户登陆后仍然可以看到并点击访问按钮的内容。

**Comment by andy8601** [comment]
> 嗨，图标将与 Type： Image 一起使用

In addition, the button added on the title bar does not have the user authorization option. I tried to set the authorization in the page, but it did not take effect, and users without authorization can still see and click to access the contents of the button after landing.

**Comment by mauroalexandre** [comment]
Pull request for fix [here](https://github.com/frangoteam/FUXA/pull/1485)

**Comment by unocelli** [comment]
Thanks @mauroalexandre

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
