### ISSUE TITLE
[FEATURE]add single sign on logic

### ISSUE THREAD

**Issue by sxyseeuu** [frangoteam/FUXA#1096]
Hello, if I want to integrate Fuxa into my project and for the sake of project security, I need to add login information. Can I add single sign on logic and skip login？

Or do you have any good suggestions?

Looking forward to your reply.

**Comment by sxyseeuu** [comment]
Is FUXA a front-end and back-end separation project？

**Comment by unocelli** [comment]
Hi, fuxa is a single project, what you mean with 'Can I add single sign on logic'?

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
