### ISSUE TITLE
[BUG] Bar chart doesn't work as expected

### ISSUE THREAD

**Issue by KamilGrabowski01** [frangoteam/FUXA#1099]
**Describe the bug**
Regardless of the selected data range in the bar chart, it consistently displays data from the last 12 hours.

**To Reproduce**
1. Create a view containing a bar chart.
2. Choose any data range within the bar chart settings.
3. Observe that the chart consistently shows data from the past 12 hours, regardless of the selected range.

**Expected behavior**
When selecting a specific data range, such as the last hour, the bar chart should accurately reflect data from that selected time frame. This behavior should apply consistently across all data range options available.

**Screenshots**
![image](https://github.com/frangoteam/FUXA/assets/91898420/6ce96d76-0e72-4d68-b0de-2889b34ba062)
![image](https://github.com/frangoteam/FUXA/assets/91898420/5bd9c964-7eba-400f-8bd7-930a7e577ab1)
![image](https://github.com/frangoteam/FUXA/assets/91898420/47922fa9-ae4a-44c1-acc2-6b858369bdeb)
![image](https://github.com/frangoteam/FUXA/assets/91898420/7f9ddc7c-0185-4bfb-ad82-657b6204b227)

**Environment**
- FUXA version: 1.1.17 - 1399
- Node.js version: 16.20.2
- npm version: 8.19.4
- Platform/OS: Windows 10
- Browser: Opera

**Comment by Bundyra** [comment]
I observed the same problem.

**Comment by unocelli** [comment]
Hi, what is your goal, show current Tag data (realtime) or the Tag history values typically used for KWh?
I tested and for me work as expected.
![image](https://github.com/frangoteam/FUXA/assets/48684550/51d83d67-d709-45e5-be00-ec34c73ef622)

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
