### ISSUE TITLE
[BUG] MODBUS TCP Doesn't Re-Establish after Link Loss

### ISSUE THREAD

**Issue by SFTP-ChZeman** [frangoteam/FUXA#1104]
**Describe the bug**
MODBUS TCP communications don't re-establish automatically after a link loss.

**To Reproduce**
1. Verify you are receiving data from a MODBUS TCP device.
2. Disconnect Ethernet from the device and verify loss of link in FUXA.
3. Reconnect Ethernet and watch the Connections screen in FUXA. It will continually cycle between orange and green, but never re-establish communications.
4. Save the project as-is and communications will re-establish.

**Expected behavior**
I expected communications to re-establish and data begin updating on the screen again after the PLC was reconnected.

**Environment**
 - FUXA version: 1.1.17-1399
 - Node.js version: 18.19.1
 - npm version: 10.4.0
 - Platform/OS: Debian 12
 - Browser: Firefox 122.0.1 (64-bit)

**Comment by robsori** [comment]
I confirm this problem on Windows OS as well.

**Comment by unocelli** [comment]
Hi, Thanks for the report, we will try to solve the problem as soon as possible...any suggestion is welcome

**Comment by unocelli** [comment]
Hi, a fix to test is available in master branch, would be nice to have feedback

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
