### ISSUE TITLE
Input Dialog Opens, when dialog containing Input field is opened

### ISSUE THREAD

**Issue by robbudge** [frangoteam/FUXA#1110]
Testing Beta 1.18.1445
I created a page with a number of numerical input fields.
When the page is opened as a dialog the first declared input field is selected and activated with the on screen keyboard without any user interaction
If the page is opened as a page this event does not occur.
![image](https://github.com/frangoteam/FUXA/assets/15365138/81b2f958-7dd5-495b-9a44-b86717006def)

**Comment by robbudge** [comment]
@unocelli Can you push this fix to the beta files ?

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by robbudge** [comment]
Just verified, all good and fixed.
Keep up the great work.


On Mar 17, 2024, at 1:47 PM, Umberto Nocelli ***@***.***> wrote:

﻿

I’m going to close this as resolved. let me know if you have any issues.
