### ISSUE TITLE
How to implement device reverse write through webApi interface

### ISSUE THREAD

**Issue by CHONGE** [frangoteam/FUXA#1114]

**Comment by CHONGE** [comment]
我想通过按钮点击调用方法修改值到设备

**Comment by CHONGE** [comment]
I want to modify the value to the device by clicking the button to invoke the method

**Comment by unocelli** [comment]
Hi, I'm not sure what you mean but maybe is the same issue #874

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile.
