### ISSUE TITLE
Can Timescale be supported

### ISSUE THREAD

**Issue by zk12668** [frangoteam/FUXA#1119]
**Describe the feature**
Can Timescale be supported
Timescale Is very popular
Many projects are based on Timescale
Supporting Timescale allows for more projects to migrate over
**Describe the solution you'd like**
Describe your proposed solution here.

**Additional context**
If applicable, add screenshots to help explain your idea.

**Comment by zk12668** [comment]
![微信图片_20240319195448](https://github.com/frangoteam/FUXA/assets/39478579/ae006e76-f48b-4df5-b52e-99e615b678eb)

**Comment by zk12668** [comment]
Timescale The database not only supports the temporal database,
The relational database is also supported,
It is much easier and more convenient to use,
Some of our previous projects were the Timescale,
I think some of the features are implemented with fuxa,
It would be nice to support the Timescale,
thanks very much!

**Comment by unocelli** [comment]
Hi, fuxa support influxdb timeserie database for DAQ, for project and configuration a single file database like sqlite makes fuxa much more portable and light.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
