### ISSUE TITLE
How to config the DAQ storage while using influxdb(2.0)?

### ISSUE THREAD

**Issue by jayjayhust** [frangoteam/FUXA#1128]
I installed influxdb 2.0 and locally ran it on my PC(http://localhost:8086/).
<img width="1106" alt="influxdb-local-server" src="https://github.com/frangoteam/FUXA/assets/78330209/5db947ee-80ea-45f5-ac41-820e96f6622f">

BUT in FUXA, how can i config the settings under the DAQ storage setting tab?
![fuxa-settings-DAQ storage-influxdb](https://github.com/frangoteam/FUXA/assets/78330209/d7a1b53d-b5e4-4e97-97d7-6d174efaaafd)

I didn't see any clues in the tutorial, maybe we can add up some instructions about DAQ storage in the tutorial in future.

Many thanks~

**Comment by unocelli** [comment]
Hi, is working? 
We will make a video in fuxa channel [youtube]( https://www.youtube.com/@umbertonocelli5301)

**Comment by jayjayhust** [comment]
> Hi, is working? We will make a video in fuxa channel [youtube](https://www.youtube.com/@umbertonocelli5301)

Great~ 
It's still not working. Looking forward to your update on youtube :)

**Comment by unocelli** [comment]
https://youtu.be/UuE_uLSXWGM?si=szvDja1O-OC5ynNR

**Comment by jayjayhust** [comment]
> https://youtu.be/UuE_uLSXWGM?si=szvDja1O-OC5ynNR

Nice to hear the latest update, cheers~
