### ISSUE TITLE
[Modbus TCP] _readMemory error! Error: Data length error, expected 9 got 6

### ISSUE THREAD

**Issue by Ralience123** [frangoteam/FUXA#1148]
Hi！
I found a following error when using modbus tcp. Before testing fuxa,We checked the data type,tcp address and the slave address.They are correct,then I use modbus poll to read, there is no problem.
![image](https://github.com/frangoteam/FUXA/assets/166285520/27ef6670-149b-4c0b-a20d-e87a0fead270)
But when I use fuxa to read, the following error occurs. I tried to set up polling 5 sec,but it didn‘t work.
![image](https://github.com/frangoteam/FUXA/assets/166285520/cc347731-fb47-4075-a0d6-c82f89a5f97d)
Your support is appreciated.

**Comment by rvbatista** [comment]
Do you know why Modbus pool is showing -- for two registers? Are you able to use Wireshark with both?

**Comment by Ralience123** [comment]
Yes,I use Wireshark to check the message both of them,and it didn't show any alarms or errors.
![image](https://github.com/frangoteam/FUXA/assets/166285520/382b9c93-a66d-440e-a0c3-fbd7322c714e)
![image](https://github.com/frangoteam/FUXA/assets/166285520/d634bb57-0685-4565-aa2b-f7925d2776bc)


> Do you know why Modbus pool is showing -- for two registers? Are you able to use Wireshark with both?

**Comment by rvbatista** [comment]
The device is answering with different lengths for the same request?
Could you also get the Wireshark requests for those answers?

**Comment by Ralience123** [comment]
I found something new today：There are no details about ‘Register’ under ‘Modbus’. Normally it should show up,like pic 2. Perhaps these messages were not recognized? 
pic 1
![image](https://github.com/frangoteam/FUXA/assets/166285520/6214b3f5-b82f-4f8a-b57b-bf9f155dbe69)

pic 2
![image](https://github.com/frangoteam/FUXA/assets/166285520/b679916e-dfa8-4576-a766-de02f20b07d8)

> The device is answering with different lengths for the same request? Could you also get the Wireshark requests for those answers?

**Comment by IonuDragomir1** [comment]
Hi,
I get the same error for Modbus RTU. Did you find any solution to this?
My error message: `2024-04-12T11:16:53.352Z [ERR]  'ModbusRTU' _readMemory error! Error: Data length error, expected 11 got 1`
After restarting the server, I get the values, but beside the above error, I also get this error: `2024-04-12T11:19:09.757Z [ERR]  'ModbusRTU' _readMemory error! Error: CRC error`

**Comment by Ralience123** [comment]
> Hi, I get the same error for Modbus RTU. Did you find any solution to this? My error message: `2024-04-12T11:16:53.352Z [ERR] 'ModbusRTU' _readMemory error! Error: Data length error, expected 11 got 1` After restarting the server, I get the values, but beside the above error, I also get this error: `2024-04-12T11:19:09.757Z [ERR] 'ModbusRTU' _readMemory error! Error: CRC error`

Hi，
You can use some modbus software like Modbus Poll or QModMaster to check the message. I think maybe your device did not parsing the message correctly，you also can find the error code in the message.

**Comment by Github-User-002** [comment]
Hi I get the same CRC error on my polling, it only happens on ID: 5,  holding register 2024 and duplpicate id: 1, 2001 and id: 5, HR: 2001, but only ID: 5 is showing the _readmemory error

Those messages look fine on modbus poll and wireshark, so I can't think the slave is doing anything wrong, it must be a bug in the FUXA

**Comment by unocelli** [comment]
Hi, have you try to update the modbus library to [v8.0.16](https://github.com/yaacov/node-modbus-serial/releases/tag/v8.0.16?)

**Comment by Ralience123** [comment]
> Hi, have you try to update the modbus library to [v8.0.16](https://github.com/yaacov/node-modbus-serial/releases/tag/v8.0.16?)

Hi, I haven't upgraded this library yet, but I will do it later  :）

**Comment by Ralience123** [comment]
> Hi, have you try to update the modbus library to [v8.0.16](https://github.com/yaacov/node-modbus-serial/releases/tag/v8.0.16?)

Hi. after checking the tcp server, I found that there was a byte error in the reply message, which caused the number of bytes to be incorrect. Now I have updated the server version and the problem has been resolved, thanks for your help and you can close the issue :)

**Comment by maufc** [comment]
Hi.
I have this problem using ModbusTCP and Telnet, as a way to use ModbusRTUoverTCP.
I am not completly sure if it is supported or not.
I find that 'trick' here:
https://github.com/frangoteam/FUXA/pull/780
 Thanks!
