### ISSUE TITLE
Not able to use register offset higher than 1000 with tcp modbus

### ISSUE THREAD

**Issue by tornadoman625** [frangoteam/FUXA#115]
When I attempt to set a register to anything higher than an offset of 1000, I get the following error:
![image](https://user-images.githubusercontent.com/60356230/111198472-f8757280-8595-11eb-9c69-47ee4b1a8575.png)

**Comment by unocelli** [comment]
Hi, thanks...I have to fix it.

**Comment by tornadoman625** [comment]
That fixed it, thanks for all the hard work you've put into this project!
