### ISSUE TITLE
[BUG] Tag options window's OK button not available sometime

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1150]
Hi,

As you can see in the below video, if someone accidentally presses on linear scalling and then on No scallling option, the OK button isn't available anymore. It becomes available only after filling in the fields from linear scalling.

**Expected behavior**
When passing from linear  scalling (without typing the corresponding values) to No scalling, the OK button should be available.

https://github.com/frangoteam/FUXA/assets/58516894/06a52228-3f44-449a-b233-0d7195819320

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
