### ISSUE TITLE
OPTION TO ADD IMAGE INSTEAD OF PREDEFINED ICON IN HEADER [FEATURE]

### ISSUE THREAD

**Issue by Kiruthick-Roxx** [frangoteam/FUXA#1159]
Hi FUXA,

Description:
Allow users to upload custom images as buttons or labels in the header section instead of using predefined icons. This feature provides greater customization options, allowing users to personalize the header to better reflect their brand or specific functionality. I image below shows where an option can be added to upload custom images.
![Screenshot 2024-04-21 180313](https://github.com/frangoteam/FUXA/assets/129523146/8d02c472-dca1-4e66-b0a8-f404b76efe02)

Proposed Solution:
Implement an option to upload custom images directly from the user's device. Users can then resize and position the image within the header section as needed.

Thank you in advance

**Comment by unocelli** [comment]
Hi, duplicates #1095
