### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by danlesbm** [frangoteam/FUXA#116]
Hi frangoteam
I am trying FUXA. But it had some errors as follows
1. Graph: The value isn't stable. But value show at sceen design, it ok. I think it has undefined values that you don't remove from the graph.
2. Alarm: It doesn''t work with API connection while TCP is ok
3. Device: Frequent connection failures if set timeout is short. Specifically: if left less than 30 seconds, there will be errors
4. The password is set, but the default start-up page is still visible to everyone
5. if you can add the tabular history and can export  * .csv file. I think it will be better 
I feel the software very good, if it fixes the above errors 
Thank you and Best regards!
![graph](https://user-images.githubusercontent.com/65875578/112779711-83b03700-9071-11eb-8d5b-73a6ed3be6d4.jpg)

![alarm](https://user-images.githubusercontent.com/65875578/112779708-81e67380-9071-11eb-9a62-0e680201a495.jpg)
![device property](https://user-images.githubusercontent.com/65875578/112779709-8317a080-9071-11eb-8222-1cc78e640eaa.jpg)

**Comment by danlesbm** [comment]
I reviewed Graph carefully, i think the reasons:
if using many parameters in 1 graph: 
- This parameter mistakenly takes the value of another parameter 
-  At different times, have undefined parameters
 -> show error

![image](https://user-images.githubusercontent.com/65875578/113224443-ae8acd00-92b5-11eb-8edb-409eaa5a53ba.png)

**Comment by unocelli** [comment]
Hi, thanks for your report and I'm looking in it...I would be thankful if you can split in 5 issues ;)

**Comment by danlesbm** [comment]
> Hi, thanks for your report and I'm looking in it...I would be thankful if you can split in 5 issues ;)

Ok. I have splitted

**Comment by unocelli** [comment]
Graph: The value isn't stable #124
Alarm: It doesn''t work with API connection while TCP is ok #125
Device: Frequent connection failures #126
Set password #127
export * .csv file #128
