### ISSUE TITLE
[BUG] Updating modbus tag values in several scenarios 

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1161]
Hi,

After downloading an update in PLC on Modbus, the tags created in FUXA are not updated anymore. In order to get again tag's updated values, the user has to disable the connection and then enable it, to edit an existing tag or to create a new one. Also, after a power loss, the connection between FUXA and device through Modbus is not reestablished automatically. This issue might exist on FUXA for other communication protocols.

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
