### ISSUE TITLE
requirements of data upload

### ISSUE THREAD

**Issue by zjjczzs** [frangoteam/FUXA#117]
I want to transfer data to cloud platform through mqtt, such as thingsboard. Can this function be realized?

**Comment by unocelli** [comment]
What is your goal?
FUXA make process visualization, I think there are better software than FUXA to act as a gateway.

**Comment by zjjczzs** [comment]
In some small data acquisition cases, gateways, HMI, and data processing are expected to be integrated into a device for cost reasons. I've had cases like this in an actual project. FUXA, on the other part, has the potential to do just that. Thank you!

**Comment by zjjczzs** [comment]
> What is your goal?
> FUXA make process visualization, I think there are better software than FUXA to act as a gateway.

In some small data acquisition cases, gateways, HMI, and data processing are expected to be integrated into a device for cost reasons. I've had cases like this in an actual project. FUXA, on the other part, has the potential to do just that. Thank you!

**Comment by unocelli** [comment]
Hi,
In case you're still interested, I've made some changes in MQTTclient, so you can now publish tags from other devices.

**Comment by unocelli** [comment]
This feature was implemented. I will therefore close this issue, feel free to re-open it if something is still not working.

**Comment by zjjczzs** [comment]
I tested using mqtt to publish and subscribe. The subscription function works well, but the publishing function doesn't work. In addition, I updated zh-cn.json




从 Windows 版邮件发送

发件人: Umberto Nocelli
发送时间: 2021年11月17日 5:37
收件人: frangoteam/FUXA
抄送: zjjczzs; Author
主题: Re: [frangoteam/FUXA] requirements of data upload (#117)

This feature was implemented. I will therefore close this issue, feel free to re-open it if something is still not working.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by unocelli** [comment]
Hi,
I'm coming from test the publish and i don't see problem. can you send me how you have configured it?
about language update you can make a PR or send me the file

**Comment by zjjczzs** [comment]
I created an mqtt server, which can be used in https://cloud-intl.emqx.com/ Login, user name: ***@***.*** , password: o000000o


从 Windows 版邮件发送

发件人: Umberto Nocelli
发送时间: 2021年11月25日 3:20
收件人: frangoteam/FUXA
抄送: zjjczzs; Author
主题: Re: [frangoteam/FUXA] requirements of data upload (#117)

Hi,
I'm coming from test the publish and i don't see problem. can you send me how you have configured it?
about language update you can make a PR or send me the file
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zjjczzs** [comment]
I accidentally replaced the demo in GitHub. Please check and restore it

从 Windows 版邮件发送

发件人: Umberto Nocelli
发送时间: 2021年11月25日 3:20
收件人: frangoteam/FUXA
抄送: zjjczzs; Author
主题: Re: [frangoteam/FUXA] requirements of data upload (#117)

Hi,
I'm coming from test the publish and i don't see problem. can you send me how you have configured it?
about language update you can make a PR or send me the file
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by unocelli** [comment]
Don't worry the demo save the project only in your browser (localStorage)

I try to publish a opcua tag value and it work really good...
![image](https://user-images.githubusercontent.com/48684550/143497228-854c8e81-06b1-441a-af36-ad05fc2380bb.png)

![image](https://user-images.githubusercontent.com/48684550/143497286-f8a696e7-ffa6-4bb9-ac57-b4c76afbac88.png)

**Comment by zjjczzs** [comment]
I public the Modbus connection data of tag type and it can work. However, using the three types of constant, topic and timestamp in the publishing type, there is no response or prompt after clicking the Publish button.
    In addition, during the test, it was found that once I disconnected the connection in the modsim, the corresponding connection in fuxa turned red and an error prompt popped up. After restoring the modsim connection, fuxa could not automatically reconnect, and the red and pop-up error prompt were always displayed.


从 Windows 版邮件发送

发件人: Umberto Nocelli
发送时间: 2021年11月26日 4:29
收件人: frangoteam/FUXA
抄送: zjjczzs; Author
主题: Re: [frangoteam/FUXA] requirements of data upload (#117)

Don't worry the demo save the project only in your browser (localStorage)
I try to publish a opcua tag value and it work really good...


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by unocelli** [comment]
Can you send me a screenshot of the data that you can not publish please?

**Comment by zjjczzs** [comment]
从 Windows 版邮件发送

发件人: Umberto Nocelli
发送时间: 2021年11月27日 2:24
收件人: frangoteam/FUXA
抄送: zjjczzs; Author
主题: Re: [frangoteam/FUXA] requirements of data upload (#117)

Can you send me a screenshot of the data that you can not publish please?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
