### ISSUE TITLE
Feature - Alarm Action - Run Script

### ISSUE THREAD

**Issue by unocelli** [frangoteam/FUXA#1185]
### Discussed in https://github.com/frangoteam/FUXA/discussions/1184

<div type='discussions-op-text'>

<sup>Originally posted by **martinjug** May  9, 2024</sup>
Hi,

This feature would enhance flexibility when alarms occur, allowing for various actions to be triggered. For instance, it could enable sending SMS messages via an SMS API or calling other HTTP APIs. Additionally, it could facilitate the execution of more complex procedures in response to specific events.

Regards,
Martin

![image](https://github.com/frangoteam/FUXA/assets/10573052/3ab4ca22-11f7-4a82-92dc-ee47a88f5569)

</div>

**Comment by mauroalexandre** [comment]
@unocelli I checked here, and this option already seems to have been implemented. This issue should be closed, right?

**Comment by unocelli** [comment]
@mauroalexandre Yes, Thank you, I normally close them when I do the release, for the time being I change the label so you can see what has been implemented (solved or fixed)

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
