### ISSUE TITLE
脚本，希望得到帮助

### ISSUE THREAD

**Issue by andy8601** [frangoteam/FUXA#1186]

**Comment by andy8601** [comment]
var a = $getTagValue('t_f085eaee-a00a4860'); // 获取空调泵1的状态
var b = $getTagValue('t_c84ba0b8-6cc846f7'); // 获取空调泵2的状态

if (a === true && b === true) {
    $enableDevice('t_c0087254-0a034051', false); // 如果a和b都为true，则关闭空调泵3
}

**Comment by MatthewReed303** [comment]
@andy8601 translate to English please
