### ISSUE TITLE
[BUG] Toggle value action not working always

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1190]
Hi,

Please see the below video:

https://github.com/frangoteam/FUXA/assets/58516894/8680a158-de4e-4de6-b44a-7b90faeef8ba

I am running FUXA v1.1.18 on Windows 10 PRO using Chrome browser. The error might appear also when using external tags.

**Comment by unocelli** [comment]
Hi, you have to set the init value, without init the value is null, not true and not false

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by maxopa** [comment]
Hi, i have the same issue(
TAGs receive data via ModBusTCP. TOGGLE does not work until i set it to 1 manualy, but the initial value of the tag is 0. Also helps to change the modbus address and change it back.
