### ISSUE TITLE
[BUG]Failed to Write the Real or Dword Type Register address of the S7 Device

### ISSUE THREAD

**Issue by HugeShao** [frangoteam/FUXA#1191]
Hi：
**Describe the bug**
Failed to Write the Real or Dword Type Register address of the S7 Device
If I Use Int or Word Type Register address  Write to the S7 Device can succeed！
![image](https://github.com/frangoteam/FUXA/assets/50111235/4def20b9-6a51-4aca-8c03-277260e18485)
![image](https://github.com/frangoteam/FUXA/assets/50111235/64006cd6-3489-472c-89cf-c79b7f1d1e50)

**Environment**
 - FUXA version: 1.1.19-1592
 - Node.js version: v14.21.3
 - npm version:6.14.18
 - Platform/OS: Windows 10
 - Browser: Google Chrome
 
think you hope to get help！

**Comment by unocelli** [comment]
Hi, I can't confirm the issue, I tested with my simulator and are working for both type

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
