### ISSUE TITLE
Multiple Slave on single IP Modbus TCP can connect only one slave

### ISSUE THREAD

**Issue by Safe2024** [frangoteam/FUXA#1193]
When a Modbus Gateway is used for connecting multiple slaves on single IP only one slave data is recieved.

I used a mgate as a gateway to connect multiple energy meters on single IP 
I created multiple modbusTCP devices and connected all it showed connected with different slave IDs.
But when I click on link and add register no data is recieved.
I also tried fragmented and also buffered port but faced same issue.

As it must scan every slave using I'd one after the another .

**Environment**
 - FUXA version: 1.1.18-1445
 - Node.js version: 16.20.2
 - npm version:8.19.4

**Comment by Safe2024** [comment]
![Uploading 17157567972692823423867440541569.jpg…]()

**Comment by rvbatista** [comment]
Same as #211

**Comment by Safe2024** [comment]
I have test some things found that for multiple IDs it creats different connections even if it has same IP.
The grouping must be done under same IP in which scaning can be better.

**Comment by unocelli** [comment]
I suppose that is the feature added from @rikugun (#1312) is now available in master branch

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
