### ISSUE TITLE
How can I set a random number to a local variable

### ISSUE THREAD

**Issue by luoge** [frangoteam/FUXA#1195]
Hello,
I want to use some non-real data in the system, such as an ammeter reading. I want it to update a value every 5 seconds. and display it in chart statistics.
My idea is to create a local variable (an internal device DeviceA?) and run a script to change this device's variable (DeviceA - Volt) every 5 seconds. I tried, but neither $getTag nor $setTag can get the device or the value of the device.

Looking forward to your answer, thanks.

![微信截图_20240517142514](https://github.com/frangoteam/FUXA/assets/6559705/f75e496b-b3ef-4527-adad-893756714676)
![微信截图_20240517143045](https://github.com/frangoteam/FUXA/assets/6559705/16a09bab-3873-4098-833c-b87fc633da97)

**Comment by IonuDragomir1** [comment]
$setTag('t_91ed5c10-83f74b4f', Math.floor(Math.random() * 101)); //random integer from 0 to 100:
