### ISSUE TITLE
[Question] Script scheduler

### ISSUE THREAD

**Issue by AllmarkPL** [frangoteam/FUXA#1200]
Hello,
quick question about script scheduler - how many times should the script be executed by server when set on specific hour? I assumed that if I set it e.g. for 6:00 it will be run just once, but it appears that it continues to run for whole hour and then stops... I set a simple script which get current value from device, then stores it into tag, and then get value from previous hour and substracts one from another (basic delta value), but as the script keeps on going the value keeps on incrementing...

I'm attaching script code and graph for this issue. 

![image](https://github.com/frangoteam/FUXA/assets/168782821/dd2ec092-f485-4f06-9906-e24a15887c83)

![image](https://github.com/frangoteam/FUXA/assets/168782821/8e681c12-f34d-40e1-84ea-f67b299b6c9f)

![image](https://github.com/frangoteam/FUXA/assets/168782821/0051c3e8-e328-48db-985a-81c6cc755003)

**Comment by unocelli** [comment]
Hi, Thanks for the report

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
