### ISSUE TITLE
mysql plugin

### ISSUE THREAD

**Issue by rooberobson** [frangoteam/FUXA#1202]
Is it possible to connect your database to read values directly from it?

If not, how can such a plug-in be written by yourself?

**Comment by MatthewReed303** [comment]
@rooberobson odbc is currently being worked on which has an mysql driver, see the odbc branch and install via docker build, just run the docker file to create a docker image and then use that image. @unocelli can you please merge the updated docker file into the odbc branch for easier install

**Comment by abishur** [comment]
Using the odbc driver is it possible to load an sql query into a table directly?

**Comment by unocelli** [comment]
Hi, wiki about odbc is coming
