### ISSUE TITLE
Easier ODBC installation [FEATURE]

### ISSUE THREAD

**Issue by Kapket** [frangoteam/FUXA#1217]
Is it possible to add an ODBC installation like EthernetIP? I see that the plugin is already in the appropriate tab, but the option to add is missing.

Currently adding ODBC is quite troublesome. When I managed to put up a server using Dockerfile, I had no option to change the database connection port, but when I try to put up a server by 'npm start' and install the plugin manually, the system does not detect the installation.

**Comment by MatthewReed303** [comment]
Hi @Kapket please see this issue where I describe how to use it, please note it's not in the current release and you have to use the odbc branch https://github.com/frangoteam/FUXA/issues/1204

**Comment by unocelli** [comment]
Hi, thanks to @MatthewReed303 we will be able to merge on the master branch soon
