### ISSUE TITLE
SPS connect failed 665420

### ISSUE THREAD

**Issue by feiyiban** [frangoteam/FUXA#122]
I use Siemens S7 200 connection is not successful！I use other software connection successfully

**Comment by unocelli** [comment]
I don't have a 200 PLC to test, please can you send me the error output?

**Comment by feiyiban** [comment]
I don’t have a testing environment for the time being, and the computer I’m testing is someone else’s. Then I will post the error message during testing.

**Comment by feiyiban** [comment]
[api.log](https://github.com/frangoteam/FUXA/files/6294111/api.log)
[fuxa.log](https://github.com/frangoteam/FUXA/files/6294112/fuxa.log)
[fuxa-err.log](https://github.com/frangoteam/FUXA/files/6294113/fuxa-err.log)

**Comment by feiyiban** [comment]
it's solved, maybe i use the error params
