### ISSUE TITLE
What's the usage of Monitor action event?

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#1220]
Hi,

When I set the monitor action event on MyButton button

![image](https://github.com/frangoteam/FUXA/assets/58516894/e23c4e86-ed78-4ecd-973a-c8bc538e125c)

what I get is the following:

![image](https://github.com/frangoteam/FUXA/assets/58516894/d01b3fb3-ff54-4a73-af55-946909930efa)

What should have been displayed, or what is its purpose?

**Comment by unocelli** [comment]
Hi, #1105

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
