### ISSUE TITLE
[BUG] - Input box(input type: Time) is not displayed correctly in browser

### ISSUE THREAD

**Issue by martinjug** [frangoteam/FUXA#1221]
Input box(input type: Time) is not displayed correctly in browser.
Chrome and Brave browsers ignore text align settings
Firefox respects text align settings, but does not display icon(clock) 

- Chrome(Version 125.0.6422.142 (Official Build) (64-bit))
- Brave (Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit))
- Firefox (126.0.1 (64-bit))

![image](https://github.com/frangoteam/FUXA/assets/10573052/fb947102-2aff-44db-a1ab-96d7035982b8)

**Environment**
 - FUXA version: 1.1.19-1619
 - Platform/OS: Docker

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
