### ISSUE TITLE
[BUG] Input box - Event "Enter" not exectued when using Dialog Mode "Dialog"

### ISSUE THREAD

**Issue by martinjug** [frangoteam/FUXA#1222]
**Describe the bug**
InputBox doesn't execute event "Enter" when using Dialog Mode "Dialog"
When using other dialog modes("Disabled, Virtual-keyboard") event gets executed.
I think the problem is that when you click blue checkmark it doesn't send event "Enter" like other dialog modes.

**Screenshots**
![image](https://github.com/frangoteam/FUXA/assets/10573052/ea7fefef-ae28-4bb2-8d30-03fc68f0a67a)

![image](https://github.com/frangoteam/FUXA/assets/10573052/750bcc8a-f678-4a86-ab16-14dc2d9da9b0)

**Environment**

- FUXA version: 1.1.19-1619
- Platform/OS: Docker
- Browser: All

**Comment by unocelli** [comment]
Hi, Thanks for the repoprt

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
