### ISSUE TITLE
[BUG] html-chart lable will show forever since I delete this control on svg-editor

### ISSUE THREAD

**Issue by YUHAI0** [frangoteam/FUXA#1240]
![image](https://github.com/frangoteam/FUXA/assets/13551902/f81d96db-90d1-423f-8cc3-4c9bbfba341d)
 As shown above, the lable can't disappear since I delete the html-chart control.

**Comment by YUHAI0** [comment]
> Hi, describe how to reproduce it please

OK, I focus the pointer on the html-chart until it show the label, then I delete the control use the delete key, then the label can't disappear

**Comment by YUHAI0** [comment]
![tqmjkhakpp](https://github.com/frangoteam/FUXA/assets/13551902/a8080e20-df0e-4b95-b3a0-8b7944049340)
@unocelli
Althrough this is a small bug, but I think it's importan to user experience, if you have enough time I recommend you to check it and merge the PR that fixed this issue.

**Comment by unocelli** [comment]
@YUHAI0 Thanks
