### ISSUE TITLE
Too many Errors in the installation of FUXA using NPM command in CMD

### ISSUE THREAD

**Issue by abdulbasit0001** [frangoteam/FUXA#1243]
![Screenshot (75)](https://github.com/frangoteam/FUXA/assets/100510359/282639b1-8813-4d75-9f1c-a7330376cdef)

#Facing these issues while the installation of FUXA. Please tell me how to resolve it? I changed the Python version but it did not work. What else can I do?

**Comment by abdulbasit0001** [comment]
There is not a single error there are too many errors I do not know how to resolve it. As soon as I use this command 
**npm install -g --unsafe-perm @frangoteam/fuxa** the errors appears.

**Comment by unocelli** [comment]
Hi, try the [version](https://www.npmjs.com/package/@frangoteam/fuxa-min) without node-snap7 (Siemens S7 communication) 
`npm install -g --unsafe-perm @frangoteam/fuxa-min`

**Comment by mariorl** [comment]
Hi, in my case (Windows) I'm almost sure this problem (and more concrete "cant find any visual studio installation to use") can be avoided when you install node, during that (last step), you are asked about the installation of some external dependencies (from powershell). Click yes and be patient because it takes time. Please if you get fixed in this way tell us.

**Comment by abdulbasit0001** [comment]
> Hi, try the [version](https://www.npmjs.com/package/@frangoteam/fuxa-min) without node-snap7 (Siemens S7 communication) `npm install -g --unsafe-perm @frangoteam/fuxa-min`

![Screenshot (81)](https://github.com/frangoteam/FUXA/assets/100510359/ec912f86-a6fa-4d1f-9c2e-ba1a6596aec6)

Still it is not working, I am unable to install FUXA after attempting many attempts this method still not working.

**Comment by abdulbasit0001** [comment]
Still it is not working, I am unable to install FUXA after attempting many attempts this method still not working.

**Comment by abdulbasit0001** [comment]
> Hi, in my case (Windows) I'm almost sure this problem (and more concrete "cant find any visual studio installation to use") can be avoided when you install node, during that (last step), you are asked about the installation of some external dependencies (from powershell). Click yes and be patient because it takes time. Please if you get fixed in this way tell us.

![Screenshot (82)](https://github.com/frangoteam/FUXA/assets/100510359/64e89376-a221-4667-ba57-4f107ed0d2a7)


After attempting this method I cannot solve my issue in installation.

**Comment by abdulbasit0001** [comment]
After attempting this method I cannot solve my issue in installation.

**Comment by mariorl** [comment]
seems you need to install node before, since npm command is not recognized

**Comment by sephi251090** [comment]
Hello, you need to install Node.js with npm first. Check your windows Path after. And, it's now better to user PowerShell in windows, instead of cdm :)

**Comment by abdulbasit0001** [comment]
I have resolved my issue successfully and now FUXA has insatalled without any error. There were several issues which I am mentioning here for the help of others:

1. Install the Python latest version and the correct path in Environmental Variables (C:\Program Files\Python312)
2. Install and update Visual Studio latest version and do not forget to download the feature name Desktop development with C++
3. Install specific version of Node JS and NPM i.e Node 14.21.3 NPM 6.14.18 (Do not use latest version only this)
4. Run the command in the last to install FUXA successfully without any errors. Warnings are acceptable.
