### ISSUE TITLE
[FEATURE] Item List Group, show / hide item

### ISSUE THREAD

**Issue by sephi251090** [frangoteam/FUXA#1248]
**Describe the feature**
A feature can be helpfull, group item in a "folder" or this likes this. The items list can be clearer and improved :)
We can imagine to move all groups in the same time, or show / hide visibility in editor.

Thanks !

**Comment by sephi251090** [comment]
I just see that possible to goup. Sorry ! Fuxa is amazing

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
