### ISSUE TITLE
[FEATURE] Add a tcp port to receive device data that device proactive send to fuxa

### ISSUE THREAD

**Issue by YUHAI0** [frangoteam/FUXA#1252]
I am not sure if fuxa now can receive data that device send to or not, I think this feature could be a choice to connect to device and get the data.

**Comment by unocelli** [comment]
Hi, can you explain better what you mean.

**Comment by rvbatista** [comment]
Maybe a weight balance?

**Comment by YUHAI0** [comment]
My thought is like this, fuxa have some api for example http rest api, that device send device to this api, and in the fuxa view, the bind control can change it's value when device pushed data to fuxa.

**Comment by mauroalexandre** [comment]
> My thought is like this, fuxa have some api for example http rest api, that device send device to this api, and in the fuxa view, the bind control can change it's value when device pushed data to fuxa. 

I believe you can solve your problem by creating a Web API type device in Fuxa, but in this case, Fuxa will poll your endpoint, it won't be passive.

**Comment by YUHAI0** [comment]
> > My thought is like this, fuxa have some api for example http rest api, that device send device to this api, and in the fuxa view, the bind control can change it's value when device pushed data to fuxa.
> 
> I believe you can solve your problem by creating a Web API type device in Fuxa, but in this case, Fuxa will poll your endpoint, it won't be passive.

I know this way, but this will tak a lot network flow if I bind a lot device tag. If use the open api way ( I have mentioned above), only device value change will make a network connection

**Comment by unocelli** [comment]
Then you make a listening option, but I will in any case use Web API.

**Comment by unocelli** [comment]
#650
I’m going to close this as resolved. let me know if you have any issues.
