### ISSUE TITLE
How to build fuxa for production

### ISSUE THREAD

**Issue by isau24** [frangoteam/FUXA#1255]
Hi, can you help me how to build fuxa for production ?

**Comment by unocelli** [comment]
Hi, from client folder `ng build --configuration=production`

**Comment by isau24** [comment]
Oke thanks, then should we copy dist directory into public directory web server (nginx) ?, not run npm start again in /server directory ?

**Comment by unocelli** [comment]
Yes, copy dist in public directory. Yes, if you don't need server don't start it
