### ISSUE TITLE
FUXA is running but unable to add Connections/Devices

### ISSUE THREAD

**Issue by abdulbasit0001** [frangoteam/FUXA#1258]
I am using the Chrome Browser and it is updated to latest version yet all the things are working fine except that I can not add any connections or devices. I tried to run it on Edge browser and it is working fine. Please tell me how to resolve this.

![Issue](https://github.com/frangoteam/FUXA/assets/100510359/f0e6f037-eea2-4500-83e9-6f14510a1ead)

![issue3](https://github.com/frangoteam/FUXA/assets/100510359/66a22f3f-dfe6-4141-b0b2-3bce866e9328)

**Comment by unocelli** [comment]
Hi, what message is shown in the browser console?

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
