### ISSUE TITLE
[BUG]The component color cannot be displayed correctly when blink stops.

### ISSUE THREAD

**Issue by wyplzx** [frangoteam/FUXA#1260]
**Describe the bug**
There are two fields, VALUE and ERR. 
The field of VALUE  controls the display color of components (such as rectangles), and the  field of ERR  controls the blink action of the components.
When its VALUE=0, set the color of the component to green. When its VALUE=1, set the color of the component to red. 
When its ERR=1, set the component to blink, the blink color is between yellow and blue.

**To Reproduce**
1. set VALUE=0 and ERR=0.   the color of the component is green, and  the component does not blink.
![01-01](https://github.com/frangoteam/FUXA/assets/158828126/082843d8-bf04-4919-8e33-89299df089a9)

3. set VALUE=0 and ERR=1.  the component blinks.
![02-01](https://github.com/frangoteam/FUXA/assets/158828126/54ac9233-33cb-4733-a33d-755ea989b36b)
![02-03](https://github.com/frangoteam/FUXA/assets/158828126/ccff6ddf-22dc-4547-8751-585e70a52529)

5. set VALUE=1 and ERR=0.  the component stops blink, but the color of the component is green, not red.
![03-01](https://github.com/frangoteam/FUXA/assets/158828126/1811fde5-e98f-4320-a4d6-fbd46c397f25)

7. See error

**Expected behavior**
at step of No.3. 
when set VALUE=1 and ERR=0.  the component stops blink, the color of the component should be red.

**Screenshots**

**Environment**
 - FUXA version: 1.1.19   (installed in docker)  (frangoteam/fuxa:latest)
 - Node.js version: 
 - npm version:
 - Platform/OS:  centos
 - Browser:  chrome

**Comment by unocelli** [comment]
Hi, can you share a project example please?

**Comment by Pelikan-71-57-1** [comment]
Does this help you 
(got more or less the same Problem)
if you have Questions I will try to help

you can see the Problem in the 0_0_0_Main_Screen window
the tiles Schlafzimmer and ROBO should change colore
it was working in the Previous Version
[fuxa-project(1).json](https://github.com/user-attachments/files/16134272/fuxa-project.1.json)

**Comment by wyplzx** [comment]
It uses fuxa server variables as test parameters. Because fuxa server parameters cannot modify two field variables at the same time. Reproduce using the same ERR parameter in the test demo.
For component color settings:
ERR=0: Display in green.
ERR=1: Display red and provide flashing (alternating yellow/blue colors).
Reproduction process:
1. When setting ERR=0, green is displayed. (Normal)
2. When setting ERR=1, it flashes. (Normal)
3. When setting ERR=0, stop flashing. But it shows red instead of green.
[test_fuxa-project.json](https://github.com/user-attachments/files/16137130/test_fuxa-project.json)
pictures:
(1).Initial Screen
![01](https://github.com/frangoteam/FUXA/assets/158828126/b10b3c41-6b51-4220-b3ee-4edf74bea1bc)
(2). set initial value: (OUT=0, ERR=0)
![03](https://github.com/frangoteam/FUXA/assets/158828126/072add71-e2de-4060-a1a7-8a4a8916e71f)
(3).set ERR=1:
The shape turns the color red, then blinks.
![04](https://github.com/frangoteam/FUXA/assets/158828126/d66eeea0-34e5-4a66-8376-bb2e6a4eb847)
![05](https://github.com/frangoteam/FUXA/assets/158828126/c5b47f70-9e53-452e-ab78-a91ce298ca9c)
(4).reset ERR=0:
the shape does not blink, but the color is red, not green.
![06](https://github.com/frangoteam/FUXA/assets/158828126/0d337727-7f26-499d-be6c-9b9def892aee)

**Comment by unocelli** [comment]
Hi, Thanks for the report. we fix it as soon as possible

**Comment by wyplzx** [comment]
hi,  @unocelli  @Pelikan-71-57-1, Thank you very much.  Good job.  Looking forward to the release of the new repaired version.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by wyplzx** [comment]
hi,  @unocelli
    Which version branch this bug has been merged and resolved to?
    I upgrade my environment to FUXA V.1.2.0-1815 (install by docker. )
    After checking, the fault seems still exist.
    Thank you..
![QQ20240905-172001](https://github.com/user-attachments/assets/42b47ce4-2f92-4b77-aa19-8f743e512ec0)
