### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by sxyseeuu** [frangoteam/FUXA#1270]
Excuse me, if I create a new view, does it have the function to be used after publishing, or the function to view the version history of the view?

Looking forward to your reply

**Comment by mauroalexandre** [comment]
Currently, no. A suggestion would be to use version control systems (e.g., Git) for the project's JSON file.

**Comment by unocelli** [comment]
Hi, you can create your own backup versions by simply saving the project.

**Comment by unocelli** [comment]
I’m closing this issue since there is nothing feasible
