### ISSUE TITLE
[FEATURE]Is there a publishing function?

### ISSUE THREAD

**Issue by sxyseeuu** [frangoteam/FUXA#1271]
Excuse me, if I create a new view, does it have the function to be used after publishing, or the function to view the version history of the view?

Looking forward to your reply

**Comment by sxyseeuu** [comment]
hi，I have another question. Can different views be changed to different port numbers?

**Comment by unocelli** [comment]
Hi, port no, but you can link the View into the url:
- http://localhost:1881/home?viewName=[Your View name]
- http://localhost:1881/view?name=[Your View name]

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
