### ISSUE TITLE
[FEATURE] Reduce the amount of data loaded

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#1273]
Browsing an empty page requires loading 7.8M of data. Can it be optimized to reduce the loading amount?
![image](https://github.com/user-attachments/assets/2c66b9c2-6090-4426-8a94-8c84590560a0)

**Comment by mauroalexandre** [comment]
I understand that my suggestion does not directly address the problem, but perhaps something that you can do is to set up a web server (e.g., nginx) to perform a proxy pass for Fuxa. On it, you can enable gzip, which will surely significantly reduce the size of the data being transferred.

**Comment by hxjackcn** [comment]
Is it possible to implement compression directly in fuxa?
