### ISSUE TITLE
Want to ask question

### ISSUE THREAD

**Issue by PengPeng-JunJun** [frangoteam/FUXA#1280]
This is my first time use FUXA.Now I want to build a demo with Modbus RTU.But when I create a new devices with web.After input modbus information and click "OK" button.The window show without setting information. But I can see the serialport info modefy.Please tell me why.

**Comment by unocelli** [comment]
Hi, look some video:
- https://youtube.com/playlist?list=PLxrSjjYyzaaK8uY3kVaFzfGnwhVXiCEAO&si=1Revch3BWYNvtqwX
- https://www.youtube.com/@umbertonocelli5301
- https://youtu.be/aHFseA1HVsk?si=U1KzjzVr74nQqPjg
