### ISSUE TITLE
[BUG] Fill color doesn't work without a point attached

### ISSUE THREAD

**Issue by sgocken** [frangoteam/FUXA#1290]
**Describe the bug**
Using a Proc. Eng. Object to just be a static object doesn't use Fill unless a point is attached to the object

**To Reproduce**
1. Add Proc Eng Object
2. Set Fill
3. Run project and object is still white
4. Attach point to object
5. Run and see the object now has color

**Expected behavior**
That fill on the properties page would fill even without a point

**Environment**
 - FUXA version: 1.2.0-1772
 - Docker image: frangoteam/fuxa

**Comment by unocelli** [comment]
Hi, I suppose it has since been solved, tested with  frangoteam/fuxa:latest (1.2.0-1784) it works as expected.

**Comment by sgocken** [comment]
Still not working for me in FUXA V.1.2.0-1784

Created new object from Proc Eng and configed as shown in first pic, all other tabs are default. Only added a fill color.

<img width="581" alt="Screenshot 2024-08-01 084051" src="https://github.com/user-attachments/assets/fe659ce5-8c44-4bf4-b507-d7ebbbe02c28">
<img width="89" alt="Screenshot 2024-08-01 084133" src="https://github.com/user-attachments/assets/227d2a0c-1281-4b44-82b3-7c5e7f36efef">

**Comment by sgocken** [comment]
I figured it out. There needs to be a value set between min/max. In case someone else runs into this issue.

<img width="572" alt="Screenshot 2024-08-01 085134" src="https://github.com/user-attachments/assets/58e051ab-13d3-4f54-8e8b-bbf857a42dbc">

**Comment by unocelli** [comment]
if you do not intend to associate the colours with a tag logic, it is better to use the colours tool 
![image](https://github.com/user-attachments/assets/54050882-39f7-475b-9165-94241e4f370b)

**Comment by sgocken** [comment]
Mind Blown! I never even noticed that toolbar down at the bottom.
Thanks for the help

**Comment by unocelli** [comment]
I’m closing this issue since there is nothing feasible
