### ISSUE TITLE
[QUESTION] How exactly does 'customized chart data' work?

### ISSUE THREAD

**Issue by Bundyra** [frangoteam/FUXA#1295]
I want to make chart with my own custom data. How can i do it?
![image](https://github.com/user-attachments/assets/34fa079f-a83b-49c1-bf5c-68426ce674a6)
I know there is a template for this functionality but, how does it exactly works?

**Comment by unocelli** [comment]
Hi, look this example
[custom_chart_with_param.json](https://github.com/user-attachments/files/16458544/custom_chart_with_param.json)

**Comment by Bundyra** [comment]
Thank you for answer :)
