### ISSUE TITLE
[BUG] The background coloring for the output value does not work

### ISSUE THREAD

**Issue by robsori** [frangoteam/FUXA#1296]
Hi. I noticed that changing the background color for the output value does not work.
However, the only browser it works on is Safari.

https://github.com/user-attachments/assets/ddf52ebe-544f-41aa-a03f-6908c006b898

**Comment by unocelli** [comment]
Hi, currently a output control is a simple svg text, don't support background attribute

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
