### ISSUE TITLE
about Internationalization 

### ISSUE THREAD

**Issue by zjjczzs** [frangoteam/FUXA#130]
I compiled a document for Chinese translation, named ch.json , and copy it to the folder of ⁃ client ⁃ SRC ⁃ assets ⁃ I18N, and then what can I do to load the new language in the settings?

**Comment by unocelli** [comment]
You have to add in 'client/src/app/editor/app-settings/app-settings.component.ts' to 'languageType' array variable:
` { text: 'dlg.app-language-ch', value: 'ch' }`

**Comment by zjjczzs** [comment]
> You have to add in 'client/src/app/editor/app-settings/app-settings.component.ts' to 'languageType' array variable:
> ` { text: 'dlg.app-language-ch', value: 'ch' }`

I've added array elements, but that doesn't work out：
 languageType = [ { text: 'dlg.app-language-en', value: 'en' }, { text: 'dlg.app-language-ru', value: 'ru' }, { text: 'dlg.app-language-ua', value: 'ua' }, { text: 'dlg.app-language-ch', value: 'ch' } ];

**Comment by unocelli** [comment]
You have to compile the client:
`cd .\client`
`npm install`
`ng build --prod`

**Comment by zjjczzs** [comment]
> You have to compile the client:
> `cd .\client`
> `npm install`
> `ng build --prod`

I've compiled the client and I can choose Chinese in the settings menu, but the interface is still in English, what should I do next?

**Comment by unocelli** [comment]
You can send me the ch.json file so that I can try

**Comment by zjjczzs** [comment]
> You can send me the ch.json file so that I can try

Has been sent to the FUXA@noreply.github.com, please check

**Comment by unocelli** [comment]
Sorry, I don't have a FUXA@noreaply.github.com email, please send me to 4frango@gmail.com

**Comment by zjjczzs** [comment]
Translation is immature, need to be further improved according to hmi, so please provide me with a test environment, thank you!
















At 2021-04-23 03:03:41, "Umberto Nocelli" ***@***.***> wrote:

Sorry, I don't have a ***@***.*** email, please send me to ***@***.***

**Comment by unocelli** [comment]
You have in your 'zh.cn.json' file at line 448 a syntax error  """ " you have to change with "": ""
don't forget to add ` { text: 'dlg.app-language-zh-ch', value: 'zh-cn' }` at `languageType` variable in 'app-settings.component.ts'
It's work for me :)

**Comment by zjjczzs** [comment]
thanks
















At 2021-04-23 14:19:15, "Umberto Nocelli" ***@***.***> wrote:

You have in your 'zh.cn.json' file at line 448 a syntax error """ " you have to change with "": ""
don't forget to add { text: 'dlg.app-language-zh-ch', value: 'zh-cn' } at languageType variable in 'app-settings.component.ts'
It's work for me :)

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.

**Comment by zjjczzs** [comment]
ok
















在 2021-04-26 03:07:42，"Umberto Nocelli" ***@***.***> 写道：

Closed #130.

**Comment by unocelli** [comment]
Good work, Thanks a lot :D

**Comment by zjjczzs** [comment]
Add：, { text: 'dlg.app-language-zh-cn', value: 'zh-cn'}
Translation is immature and needs to be further refined according to hmi

发送自 Windows 10 版邮件应用

发件人: Umberto Nocelli
发送时间: 2021年4月20日 0:06
收件人: frangoteam/FUXA
抄送: zjjczzs; Author
主题: Re: [frangoteam/FUXA] about Internationalization (#130)

You can send me the ch.json file so that I can try
