### ISSUE TITLE
[FEATURE]support Snap7 protocol in Nodejs 16 or 18

### ISSUE THREAD

**Issue by jiansiting** [frangoteam/FUXA#1304]
**Describe the feature**
I see snap7 already supports Nodejs version 16, but why is our library still only Nodejs version 14? (Link : https://github.com/mathiask88/node-snap7)

**Comment by unocelli** [comment]
Hi, what do you mean? currently for docker in version 1.2 we are using nodejs version 16.

**Comment by jiansiting** [comment]
you can support snap7 on Nodejs18?




剑思庭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月2日(星期五) 凌晨0:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] [FEATURE]support Snap7 protocol in Nodejs 16 or 18 (Issue #1304)





 
Hi, what do you mean? currently for docker in version 1.2 we are using nodejs version 16.

**Comment by unocelli** [comment]
Hi, you have to try your self or install it via docker, that work!
