### ISSUE TITLE
[BUG] After undo action, zoom with shortkey(shift + wheel) will broken

### ISSUE THREAD

**Issue by YUHAI0** [frangoteam/FUXA#1305]
After undo action, zoom with shortkey(shift + wheel) will broken

**Comment by unocelli** [comment]
Hi, I can't confirm, for me it works as expected

**Comment by YUHAI0** [comment]
You should reload the editor page, it appears when do nothing but undo

**Comment by unocelli** [comment]
Hi, please make a video

**Comment by YUHAI0** [comment]
![chrome_pW5JqhWDU8](https://github.com/user-attachments/assets/c371c3b2-4ef8-4189-87b3-5fa1ddcd0914)
After undo, I use shift + scroll up/down to zoom, the bug appear

**Comment by unocelli** [comment]
OK, yes it is a bug, the zoom has nothing to do with it, it is the editor's history that has issues

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
