### ISSUE TITLE
[QUESTION OR FEATURE] Mapped Tag value to a string

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#1307]
**Describe the feature**
I wanna map data to a text, let say for example the value of TAG1 = 1 then instead of 1 value being displayed on output element, I can map it to a string like "Running" and if TAG1 = 0 , I can mapped the value to "Stop". 

The mapped value could only be seen on Frontend, let say for display purposes only, it doesn't need to change the actual value of the Tag. 

Currently, I don't know how to do it, or maybe there are some work around? 

Thanks!

**Comment by unocelli** [comment]
Hi, you can use the select value control as readonly 
![image](https://github.com/user-attachments/assets/0aed4ae0-bc82-4e1e-a499-be89e6f0f45f)

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
