### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andy8601** [frangoteam/FUXA#1309]
1. logs The time does not match the system time。
2.When the script runs periodically, the FUXA service crashes after saving the project。
**Environment**
 - FUXA version: 1.2.0-1784
 - Node.js version: 
 - npm version:
 - Platform/OS:docker
 - Browser:chrome

**Comment by andy8601** [comment]
System time The log time is UTC+0, which is inconsistent with the time zone of the server or the system time in the upper right corner.

**Comment by andy8601** [comment]
The system log time is UTC+0, which is inconsistent with the time zone of the server or the system time in the upper right corner.

**Comment by LordNetro** [comment]
> 1. 2.When the script runs periodically, the FUXA service crashes after saving the project。
>    **Environment**

Do you have any useful information displayed in the console?

**Comment by unocelli** [comment]
I’m closing this issue since there is nothing feasible and due to inactivity.
