### ISSUE TITLE
MQTT doesn't work

### ISSUE THREAD

**Issue by fedex-12** [frangoteam/FUXA#131]
Hello,
i used the MQTT driver, but it doesn't work.
I tried to connect to the broker: broker.hivemq.com
Is there a guide?
Thank you.

**Comment by unocelli** [comment]
Hi,
sorry for the delay, which error you receive?

**Comment by amaloma** [comment]
Me too
![image](https://user-images.githubusercontent.com/2215464/115945467-2c717b00-a4e6-11eb-9164-028c095878c5.png)
![image](https://user-images.githubusercontent.com/2215464/115945474-34311f80-a4e6-11eb-9a1c-431a4d57f893.png)
![image](https://user-images.githubusercontent.com/2215464/115945479-3abf9700-a4e6-11eb-936f-59036d7e12fd.png)

**Comment by unocelli** [comment]
Thanks for the report, I'm looking for

**Comment by unocelli** [comment]
Fixed

**Comment by amaloma** [comment]
connect ok, but it doesn't work to subscribe.

![image](https://user-images.githubusercontent.com/2215464/115982314-55683d80-a5c4-11eb-9b4a-5287b4391fa2.png)
![image](https://user-images.githubusercontent.com/2215464/115982324-644ef000-a5c4-11eb-8cb0-4224398d2266.png)
![image](https://user-images.githubusercontent.com/2215464/115982353-9c563300-a5c4-11eb-8ea2-9a809fc82ccb.png)
![image](https://user-images.githubusercontent.com/2215464/115982361-a841f500-a5c4-11eb-9fd3-e90156742483.png)
![image](https://user-images.githubusercontent.com/2215464/115982369-b2fc8a00-a5c4-11eb-9e5a-e5e44a95f735.png)

**Comment by unocelli** [comment]
@amaloma Thanks for the report, I'm looking for

**Comment by unocelli** [comment]
Fixed

**Comment by amaloma** [comment]
It works, Thanks.

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
