### ISSUE TITLE
[FEATURE] Alarm view without folding

### ISSUE THREAD

**Issue by mariorl** [frangoteam/FUXA#1310]
**Describe the feature**
Sometimes it is desirable to get a view where user doesnt need to click to view alarms / events

**Describe the solution you'd like**
It would be nice to have an alarm control in wich alarm / events are not folded. Usually in Scadas it is achieved by
two controls, an alarm / events table, and alarm bar. Alarm table is a sort of Fuxa existing one, but witout folding, and embeedable in pages only on demand. But it implies no to be avaliable on every page, in order to avoid redundance. Alarm bar is a single line version, usually used for alarms but not for events. 

Also there is many times a challenge with the managing of alarms acknowledges. I usually work with PLC logic in order to get three states for every alarm:
-- The cause of the alarm is active. (Example: thermal motor protection still tripped) You can't acknowledge it during this phase.
-- The alarm is active but not the cause (you need to acknowledge it)
-- The alarm is not active (usually is still shown in alarm table/list as hystoric item, for diagnostic purpouses)

Thanks for all, Fuxa is Great.

**Comment by unocelli** [comment]
Hi, is available in the latest version (Table control), let me know if you have any issues.
