### ISSUE TITLE
[FEATURE] About window size self-adaption

### ISSUE THREAD

**Issue by qaiu** [frangoteam/FUXA#1311]
**Describe the feature**
window size self-adaption 

**Describe the solution you'd like**
It can adapt to small screens or low resolution devices (mobile devices) instead of displaying scrollbars and only showing partial images.

The current adaptation requires triggering when the window size changes

**Additional context**
![image](https://github.com/user-attachments/assets/db934eaf-f43d-490d-b6c8-04d37c08bcc8)

thanks!

**Comment by henjoe** [comment]
There is a settings in the Layout related to Zoom. 
Just set it to "Automatic"

**Comment by MatthewReed303** [comment]
@qaiu try to use multi view and adjust grid settings to suit your view. The multi view is setup to auto fit screens and shift grids automatically based on screen size

**Comment by qaiu** [comment]
> There is a settings in the Layout related to Zoom. 
> Just set it to "Automatic"

Already set, but still not working

**Comment by qaiu** [comment]
> @qaiu try to use multi view and adjust grid settings to suit your view. The multi view is setup to auto fit screens and shift grids automatically based on screen size 

It works, but it is not adaptive. However, it can be adapted to different resolutions through multiple

**Comment by unocelli** [comment]
Hi, try the last version and explains again what is not working

**Comment by qaiu** [comment]
Good! The new version is OK.
At version 1.9 even if autoresize is enabled, it doesn't work the first time you open it
> Hi, try the last version and explains again what is not working
