### ISSUE TITLE
[FEATURE] "Input value" element - Write on lost focus 

### ISSUE THREAD

**Issue by martinjug** [frangoteam/FUXA#1314]
**"Input value" element - Write on lost focus**
Behavior of the element when entering a value:
- **Active**: The value is immediately written when the control element loses focus or Enter key is pressed. Pressing the Esc key cancels the input, and the value is not written.
- **Inactive**: The value is only written after confirming with the Enter key. Pressing the Esc key cancels the input, and the value is not set.

**Describe the feature**
This feature enhances usability by reducing the chance of mistakenly thinking a value has been entered into a field. However, if you don’t press Enter afterward, the value isn’t actually applied, leading to a mismatch between the input field and the variable it should update.

![image](https://github.com/user-attachments/assets/fec995ff-0d07-4edd-8cec-37a16da7d449)

**Additional context**
Problem
The value isn’t actually applied, leading to a mismatch between the input field and the variable it should update
![image](https://github.com/user-attachments/assets/3c611631-3942-4783-b2c1-1846bb40ea4a)

**Comment by unocelli** [comment]
Hi, if you take the current master branch and you set the flag 'Enable update' by ESC the input field will be update with the current value. However, I realise that this could be a problem for the case where you want to create a settings dialog with several input fields and a confirmation button to write values on the tags. 
So your proposal is the best solution. Thanks

**Comment by wagod835512** [comment]
HI, @unocelli

I've tried the latest version 1.2.0, but it seems that it's still not working as we discussed. The option to write a value without pressing enter (Write on lost focus) is still not available.

**Comment by unocelli** [comment]
Hi, sorry for the misunderstanding, for me you always have to confirm the value with Enter, it does not seem to me to be a feature applicable to an hmi or scada.

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
