### ISSUE TITLE
[BUG]I While using the same view, the names of the points change by themselves.

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#1315]
Earlier versions did not have this problem.

https://github.com/user-attachments/assets/42b7cb72-c13c-491b-88fe-b45be8f3f5f7

**Comment by hxjackcn** [comment]
![image](https://github.com/user-attachments/assets/4e94fa52-0907-4491-8072-d477c7423ece)

**Comment by hxjackcn** [comment]
In this case, value transfer control cannot be achieved.

**Comment by hxjackcn** [comment]
@unocelli

**Comment by unocelli** [comment]
Hi, in thwe new versions we will use the placeholder, it is definitely an improvement. we will investigate about the support of old functionality with internal device

**Comment by hxjackcn** [comment]
@unocelli I didn't notice the problem with placeholders before, it's great, I will use placeholders from now on.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
