### ISSUE TITLE
Accepts mq messages to control the node values of another device

### ISSUE THREAD

**Issue by ZXiaoPang** [frangoteam/FUXA#1320]
FUXA version：1.2.0-1815

![截屏2024-08-14 13 15 26](https://github.com/user-attachments/assets/6ffeb37e-2833-486e-960e-8c2ddd51216e)
This image shows the commands received from the topic I subscribed to.

![截屏2024-08-14 13 18 44](https://github.com/user-attachments/assets/51843dce-07e1-45b3-9d93-2dd88f2601b2)
How can I modify the value of a node on another device in the image at the same time I receive this command?

I wrote a script, but in the MQTT subscription tag section, the dropdown list does not show my script, and I cannot select any script.
![截屏2024-08-14 15 19 20](https://github.com/user-attachments/assets/a1f79d66-fb55-40ed-b571-651b4c687386)
![截屏2024-08-14 15 19 34](https://github.com/us
![截屏2024-08-14 15 19 42](https://github.com/user-attachments/assets/fe3facb8-ed51-4dac-b562-e386fa0a2447)
er-attachments/assets/483b68d2-2b54-4117-b7a0-60668c12128a)

**Comment by haslish** [comment]
@ZXiaoPang Did you manage to get your script to show up in the dropdown list?

**Comment by ZXiaoPang** [comment]
> @ZXiaoPang Did you manage to get your script to show up in the dropdown list?

I can't get the script to appear in the list.
