### ISSUE TITLE
[BUG]SiemensS7 Plugin

### ISSUE THREAD

**Issue by somiom** [frangoteam/FUXA#1321]
Dear frangoteam,

After i updated Fuxa from version 1.1.19 to version 2.0.0., connection to S7 stop to work. In logs I saw that Siemen S7 plugin is mising.

![image68](https://github.com/user-attachments/assets/bad29ce2-ef08-48fc-ab7c-fddde6b6b696)

**Environment**
 - FUXA version: 1.2.0
 - Node.js version: v22.6.0
 - npm version:
 - Platform/OS: Ubuntu / docker container
 - Browser: Chrome

**Comment by unocelli** [comment]
Hi, in docker try frangoteam/fuxa:snap7-1.2.0

**Comment by AlexCastro-Prog** [comment]
Hi Frango team,

I installed on docker and I didn't see the Rockwell Automation node or connection to be added.

I have 7 rockwell PLC's that I need add on Fuxa but I didn't where the connection to connect rockwell plc.

**Comment by MatthewReed303** [comment]
@AlexCastro-Prog have you gone into plugins and then press the + next to EthernetIP?

**Comment by AlexCastro-Prog** [comment]
Yes. I got it. Thank you!

Other question is: Is it possible to update for a new version of fuxa with the current project?

**Comment by MatthewReed303** [comment]
@AlexCastro-Prog you cab use save project as and this will download a json of your current project, then open new version of Fuxa and open project and wait, if it's a large project it takes a little time.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by jmcastillejo** [comment]
> Dear frangoteam,
> 
> After i updated Fuxa from version 1.1.19 to version 2.0.0., connection to S7 stop to work. In logs I saw that Siemen S7 plugin is mising.
> 
> ![image68](https://github.com/user-attachments/assets/bad29ce2-ef08-48fc-ab7c-fddde6b6b696)
> 
> **Environment**
> 
> * FUXA version: 1.2.0
> * Node.js version: v22.6.0
> * npm version:
> * Platform/OS: Ubuntu / docker container
> * Browser: Chrome

snap7 driver not installed in latest docker version. Install with: "docker exec -it <CONTAINER ID> npm i node-snap7"
