### ISSUE TITLE
[BUG] Multi view element background color

### ISSUE THREAD

**Issue by TMC-PC** [frangoteam/FUXA#1322]
**Describe the bug**
~~In a multi view: the gridster-item no longer sets the background color property inline. It now inherits from the gridster-item css class as white.~~
The background color for each view in multi view is always white. (this.view.profile.bkcolor?)

**To Reproduce**
FUXA v1.2.0-1815

**Expected behavior**
Perhaps not expected, but in my previous version ~17XX, this was not the case.

**Comment by unocelli** [comment]
Thanks fo the report

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
