### ISSUE TITLE
Feature Request: Support for Differential Data Calculation Based on Time Units in Bar Chart Module

### ISSUE THREAD

**Issue by Fragile-boy** [frangoteam/FUXA#1328]
Hello, first of all, thank you for open-sourcing this excellent project.

### Background:

Our data is **accumulated in registers**, and **the values continuously increase with production**.
（ Honestly, I'm not very clear on the functions of the three buttons shown below; if you could also explain those, I would be very grateful.）
![image](https://github.com/user-attachments/assets/3e9f6870-7ebe-422a-8cc0-8152a58982c6)

### Requirement:

We want to see the production volume, number of faults, fault handling time, etc., on an hourly and daily basis. Therefore, what we need is **the differential value of the data over time units**.
![image](https://github.com/user-attachments/assets/b500c626-d7c8-4496-a193-1593cc56d7cd)
The effect shown above is achieved by saving the total daily production in several registers. Now, we want to view the hourly production totals, but using 24 registers for this purpose feels a bit inelegant.

### Current Situation:

In the bar chart module, after selecting the "data and time" option for the X-axis, the only available data operations are "hour sum" and "sum," which is clearly not what I need.
![image](https://github.com/user-attachments/assets/03c3af9c-0330-4898-af13-e4cf252a181d)

Is there a feature that I might have overlooked? Please let me know, so I can implement it to meet my needs.

**Comment by Fragile-boy** [comment]
It seems that #1283 solves my problem perfectly. I will update the version and try again.

**Comment by Fragile-boy** [comment]
Today I noticed that when using SQLite as the database, after terminating the project with ctrl+C, the $getHistoricalTags function can no longer retrieve historical data. However, when using FluxDB, it continues to work.

Are you aware of this issue?

**Comment by unocelli** [comment]
Hi, do not mix issues, influxdb is a motor that work autonomously, Sqlite is a files based database, fuxa will be the interface to the files, if you stop it you have to read yourself the files located in _db

**Comment by Fragile-boy** [comment]
Hi, thank you for your response. Here is my understanding of your answer:

When using SQLite as the database, every time Fuxa is started, it creates a new DB file where the data is stored, and it can only interact with the data in this DB file.

When using InfluxDB as the database, regardless of the situation, there is only one database, and all operations are conducted solely within this configured database.

Is my understanding correct?

**Comment by henjoe** [comment]
> It seems that #1283 solves my problem perfectly. I will update the version and try again.

Did you manage to do this using the script? I am looking for similar things. How do you populate the integral values from the Scripts results in the Bar chart?

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
