### ISSUE TITLE
make the bar gauge have action like button

### ISSUE THREAD

**Issue by DHIAFIQ** [frangoteam/FUXA#1335]
I want to set the Bar Gauge value base on the value selected,
For example:
If selected value = 20, set the max of the bar gauge is 20
If selected value = 50, set the max of the bar gauge is 50,

can u provide same function setting like button or put action hide and show, so i can hide and show the bar gauge base on value selected.
Can FUXA be set up? Can you recommend? Please

**Comment by unocelli** [comment]
#609
