### ISSUE TITLE
MQTT json data

### ISSUE THREAD

**Issue by amaloma** [frangoteam/FUXA#134]
Please add mqtt json key to tag name for input data
and can send json data for output.

e.g. 
1. topic = my/test/topic, message = 55
2. topic = test/topic/sensor, message = { "Temperature":  25, "Humidity": 40 }

![image](https://user-images.githubusercontent.com/2215464/115995592-0e9b3780-a606-11eb-85f0-3bd488ac8230.png)

**Comment by unocelli** [comment]
I understand your request...what should I send to the broker if in FUXA with a button I change only the 'Temperature' value?
if I send only the json with 'Temperature' I lost the other attribute ('Humidity') in 'test/topic'?

**Comment by unocelli** [comment]
Hi,
I make some improvments in MQTT client for the publish functionality...

**Comment by MRIIOT** [comment]
In my case my payload looks like this:

```
[{"address": "%M55.0", "keys": ["counter.0.value"], "value": 778, "_ts": 1629498395587}]
```

**Comment by unocelli** [comment]
Hi,
where the expression check should be done? in the backend? is something you want to be able to configure to every topics?

**Comment by MRIIOT** [comment]
> Hi,
> where the expression check should be done? in the backend? is something you want to be able to configure to every topics?

Ideally it would be done when binding control.  In my case, different I/O data arrives on the same topic. One control might be bound to value of %M55.0, another to value of %M55.1.

I don't know that JSONata is the correct answer as it only works with JSON.  Are there ways to extend Node with another scripting language (eg JS, Lua, Python) to give user ability to write scripts?  Maybe 'safe-eval' https://github.com/hacksparrow/safe-eval.

**Comment by unocelli** [comment]
Hi,
I did some refactoring in MQTT client...maybe solve the issues.

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
