### ISSUE TITLE
[BUG] Archiving Siemens S7 Tag's values in sqlite db

### ISSUE THREAD

**Issue by gabrielbalincaaeg** [frangoteam/FUXA#1341]
**Describe the bug**
Archiving Siemens S7 Tag's values in SQLite DB doesn't work and no the values aren't there, I used SQLite Studio to check if they are there. I installed FUXA 1.2.0-1832 on fresh windows 10 virtual machine and tested with Siemens S7 1500 PLC and Modbus Simulator (ModRSsim2) and KEPServerEX 6 (OPC UA driver). Values are refreshing (so I guess the driver works ) but I can't see them in the database. With Modbus simulator and KEPServerEX 6 everything works fine.

**To Reproduce**
Just add an Siemens S7 connection and activate the registration.
1. Add Siemens S7 Connection
2. Press Tag Options
3. Activate Registration Enabled or/and Save if changed

**Expected behavior**
See the history values of Siemens S7 Tags in charts.

**Environment**
 - FUXA version: 1.2.0-1832
 - Node.js version: 18.20.4
 - npm version: 10.7.0
 - Platform/OS: Windows 10
 - Browser:-

**Comment by MatthewReed303** [comment]
@gabrielbalincaaeg create a PR for the Fix and @unocelli can review it

**Comment by martinjug** [comment]
Hi,

I'm experiencing the same issue the S7 driver is functioning and values are refreshing, but they are not being stored in the SQLite database, which means historical values can't be displayed in charts.

**Comment by unocelli** [comment]
Hi, @gabrielbalincaaeg Thanks a lot for the report and the fix. 
I just commit in master branch

**Comment by zblack88** [comment]
Hi,

I'm experiencing the same issue the S7 driver, how to get the fix?
Thank you

**Comment by unocelli** [comment]
@zblack88 Hi, please try the last version in master branch

**Comment by zblack88** [comment]
I tried, but the last version in master branch does not have the plugin for the S7, so it does not work at all. Is required a special installation for the plugin?

**Comment by zblack88** [comment]
Ok solved by installing the S7 plugin manually. Thanks
