### ISSUE TITLE
[BUG]_readMemery Error When Enabling Multiple Devices with 150 Tags Each

### ISSUE THREAD

**Issue by Fragile-boy** [frangoteam/FUXA#1343]
**Describe the bug**
I have configured two devices, which together have approximately 150 tags. Each device is connected to the server using ModbusTCP. Additionally, the two devices are connected to each other using RS485 through a serial server, which is then connected to the company’s internal network.
![image](https://github.com/user-attachments/assets/a7abdf34-4622-44ac-9bfa-e5c25a53e26d)
![image](https://github.com/user-attachments/assets/8e2f5326-2092-4b9b-bf89-82bd1a524640)

When I enable either device individually, Fuxa works normally without any issues. However, when I enable both devices simultaneously, the log persistently reports errors.

![image](https://github.com/user-attachments/assets/b87af73d-2933-4bf5-95e5-952fd892b53e)

I have already tried the solutions mentioned in issues #154 and #191, but unfortunately, they didn't resolve the problem. The errors still occur when both devices are enabled at the same time.

Additionally, I attempted to enable the fragmented flag, but this caused another issue: the application was unable to read all tag values properly.
![image](https://github.com/user-attachments/assets/664e81ae-1c05-4899-9794-1de7615aa7f9)

Could you please provide further assistance or suggest any additional steps I can take to resolve this issue?

Thank you!

**Environment**
 - FUXA version: 1.2.0
 - Node.js version: 
 - npm version:
 - Platform/OS: docker
 - Browser:chrome 128.0.6613.114

**Comment by unocelli** [comment]
Hi, have you try the version in master branch with PR #1312 ?

**Comment by Fragile-boy** [comment]
> Hi, have you try the version in master branch with PR #1312 ?

Hi, thanks! I followed your instructions and after applying the update, it perfectly solved the problem.

**Comment by Fragile-boy** [comment]
> > Hi, have you try the version in master branch with PR #1312 ?
> 
> Hi, thanks! I followed your instructions and after applying the update, it perfectly solved the problem.

I'm sorry, this issue still exists. Below are my relevant settings.

The process is like this: I first closed all connections. Then, I opened the first connection on the left. After I was able to stably see the data, I turned on the Socket reuse switch, and then I started the second one.

After that, the second connection and the first one began alternating in updating data, but only part of the data could be updated, and the console started continuously reporting various errors, such as 'read_memory Error,' or 'length too long, expect 87 got 107,' and similar ones.
![image](https://github.com/user-attachments/assets/08c688dd-a770-4705-a862-5eaa35a6cd6b)
![image](https://github.com/user-attachments/assets/3b69331d-6a34-4971-b905-beb2a2bf806d)
![image](https://github.com/user-attachments/assets/98611f55-3143-462f-b3a8-5c56407f4f8f)
![image](https://github.com/user-attachments/assets/eec49e7d-f1bb-46b1-8b77-1bd030b7486e)

**Comment by unocelli** [comment]
@rikugun Hi, do you have an idea of the issue?

**Comment by Fragile-boy** [comment]
> @rikugun Hi, do you have an idea of the issue?

Sorry for the late reply.

The background of my issue is that I have a serial server connected to multiple PLCs via RS485. The PLCs only support Modbus RTU communication, so the serial server performs Modbus TCP to RTU conversion.

Although socket reuse shares a single connection, RTU is half-duplex communication, and the serial server does not implement a message queue. As a result, when two Modbus TCP requests arrive at the serial server almost simultaneously, one of them is discarded. This leads to issues with some updates not being processed correctly. (Later, I used Python to create my own message queue, simulating requests sent from FUXA, and all requests received correct responses.)

My suggestion:
Add a new option, whether to enable the message queue function. For the same socket, the next request would only be sent after receiving the response for the previous request. (Our situation is somewhat special, so I think this might not be very meaningful.)

**Comment by rikugun** [comment]
I have a similar problem when use rtu to tcp , I'm trying to solve.

**Comment by rikugun** [comment]
hi @Fragile-boy ,  I make a read/write mutex when use  socket reuse , I'd tested with my devices, can you help me to  test your devices on my branch 

https://github.com/rikugun/FUXA/tree/feat/modbus-tcp-mutex

![QQ_1727398186213](https://github.com/user-attachments/assets/2e520405-4a03-49bc-bc48-d8a7f388b4b1)

**Comment by Fragile-boy** [comment]
Thank you for your hard work. I apologize for the delay, but I have transitioned to using a cloud platform with secondary development to meet my needs.

In the case of FUXA, during communication with PLCs, it can only act as a client while the serial port server acts as a server. This means the IP address of the serial port server must remain fixed. However, in the production line, after the machines are sold, the IP addresses often change. This is the fundamental reason why I chose to develop a custom solution.

Additionally, I realized that what I need is a data reporting display rather than real-time interaction with a SCADA-like application (even though FUXA could fulfill this, I felt it didn’t quite fit my specific needs, like implementing Gantt charts).

Overall, FUXA is a great project, and its scripting module gives it unlimited potential. I'm sorry for the delayed response, and I will test it as soon as possible. Once I have the results, I will reply with my findings.@rikugun

**Comment by Fragile-boy** [comment]
Hi，由于另外一个服务高频使用串口服务器的原因，我再使用fuxa连接串口服务器，虽然能够连接成功，但是并没有获取到数据。所以我没有能够验证他是否能够串行的获取数据。对此我很抱歉

**Comment by Fragile-boy** [comment]
Hi, due to another service frequently using the serial port server, although I was able to connect to the serial port server using FUXA, I couldn't retrieve any data. As a result, I wasn't able to verify whether it can successfully obtain serial data. I apologize for this.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by henjoe** [comment]
Hi I dont know what is the issue here but I tried the same setup I have 2 Modbus serial slaves connected to a modbusTCP gateway where Fuxa connected to it. Something like this below:

![image](https://github.com/user-attachments/assets/b349b6b2-e6a0-457c-9406-2b656aee2893)


And it works fine for me, I can connect to both Slave IDs 1 & 2 for modbusTCP gateway (192.168.1.1), I just simply create 2 device connections and add their slaveIDs accordingly, (very similar on what you did). And I view both the data. 
The thing is I didn't use the reuse socket cause I am on the old version (V1.2.0) and I can confirm that it works fine to me.
