### ISSUE TITLE
[FEATURE]Alarm function display opinions

### ISSUE THREAD

**Issue by KWYHDHJ** [frangoteam/FUXA#1350]
**Describe the feature**
Hi，
I know that the alarm function can display the alarm information of the entire project configuration in the small bell, but for the alarm view in the multi view function, can the background color be modified to make the background color consistent between views, or can a list component for displaying alarm information be provided in the view editor, which can directly display the alarm information on the page.

**Comment by unocelli** [comment]
#1310
