### ISSUE TITLE
How to stop a script execution?

### ISSUE THREAD

**Issue by alexey-fedchishyn** [frangoteam/FUXA#1352]
I want a script is stoped when a user leaves a page. Is there any way to do that? How to stop a script at all?

Otherwise all the scripts needed only for some particular view continue working consuming server's resources even if noone needs them.

**Comment by Fragile-boy** [comment]
Perhaps you could try using a button trigger or a similar method instead of triggering the script execution at fixed intervals

**Comment by alexey-fedchishyn** [comment]
> Perhaps you could try using a button trigger or a similar method instead of triggering the script execution at fixed intervals

Yes, I understand that. But what is the sense of having the option if I can't use it? And I'm really surprised that I can specify conditions to start a script but there is no way to stop it when I need.

**Comment by Fragile-boy** [comment]
It's quite simple. You add a variable as a condition for the script to run. When the variable has the specified value, the script runs. Otherwise, the script directly returns without performing any logical processing.

**Comment by alexey-fedchishyn** [comment]
> It's quite simple. You add a variable as a condition for the script to run. When the variable has the specified value, the script runs. Otherwise, the script directly returns without performing any logical processing.

It can work. But I still have no way to stop a script when a user leaves the page where the scrip is supposed to run. And I think it should be a part of the setting but not a part of the logic.

**Comment by alexey-fedchishyn** [comment]
> Is the scripts running on a specific interval let say every 1m,5m or 1h and etc, and it is running at backend?

Not exactly. It's an infinite loop. So technicaly the script runs just once. I tried to run it on the server and the a client. No difference.

**Comment by Fragile-boy** [comment]
> > Is the scripts running on a specific interval let say every 1m,5m or 1h and etc, and it is running at backend?
> 
> Not exactly. It's an infinite loop. So technicaly the script runs just once. I tried to run it on the server and the client. No difference.

Running on the client side refers to the script running in the browser, while running on the server side refers to the script running in a Node.js environment. You can place the code that executes after user interaction on the client side, and the code that needs to run continuously in the background on the server side. Otherwise, once the client is closed, the script will stop executing.

I believe your issue can still be solved by adding a variable. In your infinite loop, continuously check the value of the variable, and if the value changes, stop execution until it changes back to the execution state.

**Comment by mauroalexandre** [comment]
@unocelli we can create Event for "onViewChanged", what you think about?

**Comment by unocelli** [comment]
Hi, how do we handle the fact that a view is displayed several times on the same page?
@mauroalexandre we should also add events to views: 'load', 'close'
