### ISSUE TITLE
[BUG]Language error occurs when refreshing the interface

### ISSUE THREAD

**Issue by chlove12345** [frangoteam/FUXA#1360]
**Describe the bug**
Language error occurs when refreshing the interface

**To Reproduce**
1. Switch language to any language except English
2. Go to the Alarms settings interface to add an alarm and start it
3. refresh page

**Expected behavior**
Expect any language except English

**Screenshots**
![image](https://github.com/user-attachments/assets/630d47b9-fd42-45ab-87d6-af3e5f017500)
![image](https://github.com/user-attachments/assets/9f327334-381a-4bf4-b46f-88b18a68a90b)

**Environment**
 - FUXA version: 1.2.0
 - Node.js version: 18.19.1
 - npm version:9.6.6
 - Platform/OS:windows
 - Browser:edge

**Comment by unocelli** [comment]
Hi, I can't confirm.

**Comment by chlove12345** [comment]
> Hi, I can't confirm. 嗨，我无法确认。

https://github.com/user-attachments/assets/74897e41-d895-4657-95da-f337e8c8217c

Actually I located the problem code,        this.translateService.get('alarm.property-enabled').subscribe(
            (txt: string) => {
              this.enabledText = txt;
            }
          );When the page is refreshed，The txt is in English and not the language of my choice。But I add the latency by 500ms，
like this ，            (txt: string) => {
                setTimeout(() => {
                    this.enabledText = this.translateService.instant('alarm.property-enabled');
                }, 500);

            },The issue was fixed。I think it's a delay somewhere, the loading of the language pack, but I can't find it.

**Comment by unocelli** [comment]
Hi, Adding a timer that delays the translation does not make much sense, I see that you are in debug mode (port 4200)!
