### ISSUE TITLE
[BUG] Siemens String to OPCUA

### ISSUE THREAD

**Issue by LAB-KN** [frangoteam/FUXA#1361]
**Describe the bug**
If the datatype "String" is selected in Siemens PLC OPC UA server, it will not show datatype in Fuxa OPC UA Client
If datatype is changed to WString in PLC, Fuxa can see it as a String.

**To Reproduce**
1. Setup OPC UA in Siemens PLC (via TIA portal)
2. Set a Tag as datatype "String"
3. Add Device  "OPCUA" in Fuxa
4. Find PLC OPC server Interface, and look for String Tag
5. String Tag will be missing Datatype

**Expected behavior**
Expected to see datatype for String

**Screenshots**
![image](https://github.com/user-attachments/assets/ba074c43-bc9f-4518-a98d-11dd15b814ab)
![image](https://github.com/user-attachments/assets/0f36a16d-4b00-4dcc-8e71-4795a324a919)

**Environment**
 - FUXA version: v1.2.0
 - Platform/OS: Windows 11
 - Browser: Chrome
 - Siemens Tia: v17 & v19

**Comment by unocelli** [comment]
Hi, I can't reproduce it.
![opcua-string](https://github.com/user-attachments/assets/2bd4dd16-c289-4934-9576-703d6761271c)

**Comment by LAB-KN** [comment]
I have found that this is a siemens plc issue, i will close this as it is not a Fuxa bug.

![image](https://github.com/user-attachments/assets/e7150be8-cad5-44b1-a032-ff202646755e)
