### ISSUE TITLE
[BUG] View Background Color not working

### ISSUE THREAD

**Issue by LordNetro** [frangoteam/FUXA#1363]
**Describe the bug**
The background color and behaviour of the view is lost whenever you acces the view by an event.
_If you acces the view via the side menu the behaviour is the expected (it works). The bug only happens when you acces the view via a button in a different view_

**To Reproduce**
1. Add a button to a view
2. Add an **mouse down** / **open page** event to the button
3. Assign a view that has a different background color than the default to the event
4. Try it and see that the background color is white and not the one that you assigned before

**Expected behavior**
See the view with the expected background color and behaviour.

**Screenshots**
View accessed via button in different view
<img width="770" alt="image" src="https://github.com/user-attachments/assets/6e4b2f23-4dd1-4ecc-a4d5-22fb4659834b">

View accesed via side menu
![image](https://github.com/user-attachments/assets/74a25e32-892a-4cbf-b180-2d922d95b53a)

**Environment**
 - FUXA version: 1.2.0-1751
 - Node.js version: v18.20.3
 - npm version: 10.7.0
 - Platform/OS: Windows 10 Pro
 - Browser: Microsoft Edge

**Comment by henjoe** [comment]
I checked the logic for this, the sideNav has different logic from the button (navigating to other page). 

If you can edit a code, you can simply change the **fuxa-view.component.ts** under client\src\app\fuxa-view

Search the code below: (loadPage)
```
 loadPage(param: any, viewref: string, options: any) {

        let view: View = this.getView(viewref);
        if (view) {
            if (options?.variablesMapping) {
                this.loadVariableMapping(options.variablesMapping);
            }
            this.loadHmi(view);
            if (param.scaleMode) {
                Utils.resizeViewRev(this.dataContainer.nativeElement, this.dataContainer.nativeElement.parentElement?.parentElement, param.scaleMode);
            }
        }
    }
```

and change the _this.loadHmi(view)_ to _this.loadHmi(view, true)_
```
loadPage(param: any, viewref: string, options: any) {

        let view: View = this.getView(viewref);
        if (view) {
            if (options?.variablesMapping) {
                this.loadVariableMapping(options.variablesMapping);
            }
            this.loadHmi(view, true);
            if (param.scaleMode) {
                Utils.resizeViewRev(this.dataContainer.nativeElement, this.dataContainer.nativeElement.parentElement?.parentElement, param.scaleMode);
            }
        }
    }
```

**Comment by henjoe** [comment]
By the way, how you manage all the controls (sliders, gauges and etc.) to have a little bit of transparent background? 

This is awesome.

**Comment by henjoe** [comment]
> By the way, how you manage all the controls (sliders, gauges and etc.) to have a little bit of transparent background?
> 
> This is awesome.



> By the way, how you manage all the controls (sliders, gauges and etc.) to have a little bit of transparent background?
> 
> This is awesome.

Nevermind, I knew it. What a dumb question 😄

**Comment by LordNetro** [comment]
> I checked the logic for this, the sideNav has different logic from the button (navigating to other page).
> 
> If you can edit a code, you can simply change the **fuxa-view.component.ts** under client\src\app\fuxa-view
> 
> Search the code below: (loadPage)
> 
> ```
>  loadPage(param: any, viewref: string, options: any) {
> 
>         let view: View = this.getView(viewref);
>         if (view) {
>             if (options?.variablesMapping) {
>                 this.loadVariableMapping(options.variablesMapping);
>             }
>             this.loadHmi(view);
>             if (param.scaleMode) {
>                 Utils.resizeViewRev(this.dataContainer.nativeElement, this.dataContainer.nativeElement.parentElement?.parentElement, param.scaleMode);
>             }
>         }
>     }
> ```
> 
> and change the _this.loadHmi(view)_ to _this.loadHmi(view, true)_
> 
> ```
> loadPage(param: any, viewref: string, options: any) {
> 
>         let view: View = this.getView(viewref);
>         if (view) {
>             if (options?.variablesMapping) {
>                 this.loadVariableMapping(options.variablesMapping);
>             }
>             this.loadHmi(view, true);
>             if (param.scaleMode) {
>                 Utils.resizeViewRev(this.dataContainer.nativeElement, this.dataContainer.nativeElement.parentElement?.parentElement, param.scaleMode);
>             }
>         }
>     }
> ```

Thank you so much!

**Comment by unocelli** [comment]
@henjoe Thanks a lot!

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
