### ISSUE TITLE
Modbus data decimals

### ISSUE THREAD

**Issue by T1bbY** [frangoteam/FUXA#137]
Hi,

I work on an interface for my heatpump and i get the data through modbus tcp.
That works fine :)

But the values are send as integer like here the temperature: 509

![image](https://user-images.githubusercontent.com/4282929/116934783-b13a6280-ac65-11eb-9608-bc225a870965.png)

But the temperature is 50,9.
Under "Interativity"->"Property" ->"Format digits", FUXA only adds ".0" to my value.

How can i tell FUXA to do this?

Thanks for you help :)

**Comment by unocelli** [comment]
Hi,
You are right in modbus is missing, I added the feature, You can now set a divisor in tag property of device, so we have the converted value for all controls. [Modbus Tags with divisor](https://github.com/frangoteam/FUXA/commit/11df175afc4b30bb1c82152b1e1a48827effa9aa) 
![image](https://user-images.githubusercontent.com/48684550/117064389-6df3f880-ad26-11eb-9f81-71f76539c654.png)

**Comment by T1bbY** [comment]
Wow, that was fast :)

Problem solved :)
![image](https://user-images.githubusercontent.com/4282929/117073693-8cf88780-ad32-11eb-8fcf-fb92ee46ac36.png)
