### ISSUE TITLE
[BUG] Switch value boolean

### ISSUE THREAD

**Issue by TMC-PC** [frangoteam/FUXA#1377]
**Describe the bug**
When using a switch element, if the "Off Value" is set to "0" (default) and "On Value" is set to "1", toggling the switch will only set the value 1 initially. The change shows up right away on my second front-end monitor (it takes effect on the FUXA Server). However when toggling the switch to "Off", it remains "1" (at least evaluates true in any case) on the server and no amount of toggling the switch will cause any effect.

This is fixed by setting the "Off Value" to "false" and the "On Value" to "true" from the Switch settings.

**Expected behavior**
I would expect the defaults of "0" and "1" to function.

**Environment**
The fuxa docker container
 - FUXA version: 1.2.0
 - Platform/OS: NixOS
 - Browser: Chromium

**Comment by henjoe** [comment]
Works fine to me, 
Are you using internal tags?
