### ISSUE TITLE
[BUG] User login not showing?

### ISSUE THREAD

**Issue by wonka929** [frangoteam/FUXA#1381]
**Describe the bug**
Enabling login i should see a login page, but nothing is appearing.

**Expected behavior**
It should just make me do the login process.
But no, it just takes me in as administrator

**Screenshots**

![image](https://github.com/user-attachments/assets/b4b2dd44-6bfe-4e16-9762-c426514c08b2)

**Environment**
 - FUXA version: latest
 - Platform/OS: Docker on Linux
 - Browser: chrome

**Comment by unocelli** [comment]
Hi, try to enable the Authentication Token
![image](https://github.com/user-attachments/assets/9240292d-8a5e-4ae5-bf02-11f311a0c597)

**Comment by unocelli** [comment]
there are settings that involve restarting the server
