### ISSUE TITLE
[BUG] Siemens S7 Connection indicator doesn't update

### ISSUE THREAD

**Issue by gabrielbalincaaeg** [frangoteam/FUXA#1385]
**Describe the bug**
- Siemens S7 Connection doesn't update it's status if it loses the connection after initial connection. Even though the UI says it's connected, it isn't, even after the pc reconnects to the PLC.
- In console (the server side) I receive this error :

```
2024-09-16T10:26:50.794Z [ERR]  'S7Test' 599878: Error:  ISO : An error occurred during send TCP : Connection reset by peer
```

**To Reproduce**
1. Make a Siemens s7 connection
	- Go To Options -> Connections -> Add Siemens S7 connection. (Must connect to a device so the connection should be ```'connect-ok'``` or green circle )
2. Simulate a connection drop between PLC and FUXA
	- Disable your network card or remove the PLC from network to simulate a connection drop

Now the connection indicator should be red. <-- This is the problem, it isn't red.

**Expected behavior**
The connection indicator should be red, when connection between FUXA and Siemens PLC is dropped

**Screenshots**

**Environment**
 - FUXA version: 1.2.0-1887
 - Node.js version: 18.20.4
 - npm version: 6.14.18
 - Platform/OS: Windows
 - Browser: Google Chrome 128.0.6613.114 (64-bit)

**Comment by unocelli** [comment]
Hi, you have configured a Tag to read? 
I have the same issue if I configure a S7 device without Tags, that doesn't make much sense

**Comment by unocelli** [comment]
I will therefore close this issue, feel free to re-open it if something is still not working.
