### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'view')

### ISSUE THREAD

**Issue by gabrielbalincaaeg** [frangoteam/FUXA#1386]
**Describe the bug**

- If the current view is a container view and is selected second time from side menu (from home not editor) we can see the next error in the browser console :

```
main.273c8160951ff866.js:329 ERROR TypeError: Cannot read properties of undefined (reading 'view')
    at r.onGoToPage (main.273c8160951ff866.js:3:77715)
    at main.273c8160951ff866.js:3:68497
    at kE (main.273c8160951ff866.js:329:2937189)
    at Object.V [as next] (main.273c8160951ff866.js:329:2937359)
    at T.next (main.273c8160951ff866.js:329:2770909)
    at I._next (main.273c8160951ff866.js:329:2770593)
    at I.next (main.273c8160951ff866.js:329:2770288)
    at main.273c8160951ff866.js:329:2768250
    at E (main.273c8160951ff866.js:329:2786464)
    at WD.next (main.273c8160951ff866.js:329:2768089)

``` 

**To Reproduce**
1. Make 3 views, one a container view and two canvas/SVG.
2. Add all of them in the navigation side menu
3. Now go to the home screen (not editor) and select two times container view screen (if its the currently displayed screen), the error should be on the browser console.

**Expected behavior**
Selecting the second time a container view from navigation side menu should not generate any error.

**Screenshots**

**Environment**
 - FUXA version: 1.2.0-1887
 - Node.js version: v18.20.4
 - npm version: 6.14.18
 - Platform/OS: Windows 10
 - Browser: Google Chrome Version 128.0.6613.114

**Comment by unocelli** [comment]
Hi, Thanks for the report

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
