### ISSUE TITLE
[BUG] getDevice script returns an empty object

### ISSUE THREAD

**Issue by gabrielbalincaaeg** [frangoteam/FUXA#1390]
**Describe the bug**
Function $getDevice return an empty object.

**To Reproduce**
1. Create a simple script
2. Write in that script next line :
```
console.log(JSON.stringify($getDevice('LocalKepServer', false)));
```
3. Click ```Run TEST```

**Expected behavior**
I was expecting to return an object since it already return an empty one.

**Environment**
 - FUXA version: 1.2.0-1887
 - Node.js version: 18.20.4
 - npm version: 6.14.18
 - Platform/OS: Windows 10
 - Browser: Google Chrome Version 128.0.6613.114
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -

**Comment by unocelli** [comment]
Hi, this is not a bug, the JSON.stringify or the console can't show you the object, that don't depend of FUXA, if you debug you can see the object and the method. For the methods you can refer to the code of the respective device.

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
