### ISSUE TITLE
How to turn off API log output

### ISSUE THREAD

**Issue by WuBingo12** [frangoteam/FUXA#1398]
![2024-09-20_000457](https://github.com/user-attachments/assets/35a26793-5d97-4f3e-ad37-e50e47337d55)
How to turn off API log output
Too many terminal logs when I read id values ​​in a loop with a script
please help me，thanks！

**Comment by mauroalexandre** [comment]
Pull request here

https://github.com/frangoteam/FUXA/pull/1424

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
