### ISSUE TITLE
Does fuxa-editor support generating icons using code？How?

### ISSUE THREAD

**Issue by Daysons** [frangoteam/FUXA#1400]

**Comment by unocelli** [comment]
Please give an example

**Comment by Daysons** [comment]
> Please give an example

Our current functionality allows us to select an icon on the left side and generate it on the right canvas by clicking. I want to implement this process using code. I've managed to select the icon on the left, but now I want to place the icon on the canvas using code instead of mouse clicks.
![Uploading 微信图片_20240923084709.png…]()

**Comment by Daysons** [comment]
> Please give an example
Our current functionality allows us to select an icon on the left side and generate it on the right canvas by clicking. I want to implement this process using code. I've managed to select the icon on the left, but now I want to place the icon on the canvas using code instead of mouse clicks.
<img width="513" alt="da2e4f0711d93c8484c63b640d4a24d" src="https://github.com/user-attachments/assets/28387f69-9286-444d-89a9-65cc0bd26024">

**Comment by unocelli** [comment]
if you intend to execute a script when the button is clicked, you must write a script and then associate the script with the click

**Comment by Daysons** [comment]
> if you intend to execute a script when the button is clicked, you must write a script and then associate the script with the click

i

> if you intend to execute a script when the button is clicked, you must write a script and then associate the script with the click



> if you intend to execute a script when the button is clicked, you must write a script and then associate the script with the click

The documentation related to click events is the source code of the https://github.com/frangoteam/svgedit repository?

**Comment by unocelli** [comment]
No, the handler of button click is in FUXA frontend (client)

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
