### ISSUE TITLE
[BUG] Add Widget Error

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#1401]
**Describe the bug**
I am not actually sure if this is BUG or Not, but I was just trying the add widget feature, I simply npm start on the server and on the client (ng serve) and use the 
```
dynamicIndicatorTestButtonSVG-init-edit.svg
```
as the test svg file, When I imported it, it gives me this error:
```
 [webpack-dev-server] [HPM] Error occurred while proxying request localhost:4200/resources/dynamicIndicatorTestButtonSVG-init-edit.svg to http://localhost:1889/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**To Reproduce**
1. Add Image Link control and look for the sample SVG.

**Expected behavior**
Added new widget. 

**Screenshots**
![image](https://github.com/user-attachments/assets/b109ea5a-8b05-4a40-ae68-25da94c686e5)

**Environment**
 - FUXA version: just the master branch
 - Node.js version: V18.xx
 - npm version: 10.2.3
 - Platform/OS: Windows
 - Browser: Chrome

**Comment by unocelli** [comment]
Hi, try to import it via 'Image tool (embedded)' 
![image](https://github.com/user-attachments/assets/5b261b27-31ca-499c-b20f-feda05438161)

**Comment by henjoe** [comment]
Using the Image Tool (embedded) 

![image](https://github.com/user-attachments/assets/95bb6fbb-fa78-4830-89f3-4f1d17d664f3)

**Comment by unocelli** [comment]
Hi, I don't know what you are trying 😉 
![widget-test3](https://github.com/user-attachments/assets/e294ccf7-15c8-4df6-8111-1d2b57888164)

**Comment by henjoe** [comment]
Does this works when in debug mode (ng serve on the client)?  Or the client should be build first? 
I am not quite sure whats wrong in here, but I might need to check more.

**Comment by unocelli** [comment]
should work in debug mode too

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
