### ISSUE TITLE
[BUG]Bar chart is showing total kWh consumption

### ISSUE THREAD

**Issue by jlumalang02** [frangoteam/FUXA#1406]
Im having a problem with showing data using bar chart. Are they anyway i can group the consumption of kWh to daily or monthly consumption? 

![Screenshot 2024-09-25 145931](https://github.com/user-attachments/assets/a096f00a-6d57-4972-8e02-dd0445c014d3)

It's showing hourly but it seems the data is cumulative.

**Comment by unocelli** [comment]
Yes, the tag that you have bind to chart is in KW? please provide how you have configured your bar chart.

**Comment by jlumalang02** [comment]
![image](https://github.com/user-attachments/assets/964eb3f9-0883-4a86-8e56-271c3f4f95fd)

![image](https://github.com/user-attachments/assets/a0bc0e32-3238-4708-8319-476064ff99c8)

Here's the configuration of the bar chart. Im pretty new here on fuxa and have little experience in SCADA. I hope you can help with this. 

The tag is in kWh and i need to get the daily consumption, monthly consumption and yearly consumption. 

Fuxa version: V1.2.00
Running on windows 11

**Comment by unocelli** [comment]
Hi, we have to fix and extend the options

**Comment by jlumalang02** [comment]
hi already updated the fuxa application however only hour sum still showing and the data is still cumulative but grouped as per hour.

**Comment by unocelli** [comment]
In the branch master you can try the version with the fix, please let me know if the calculation is correct.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
