### ISSUE TITLE
[FEATURE] Retain the last value added into the input value 

### ISSUE THREAD

**Issue by prac05** [frangoteam/FUXA#1408]
**Describe the feature**
My colleague is using an input value controller to store the desired value of a parameter. He says that after several reboots, these values have been lost. Is there any feature that prevents data loss? Does the DAQ storage configuration influence this? Also he is using Dialog Mode of input field.

**Additional context**
![imatge](https://github.com/user-attachments/assets/47e35c54-1b66-41dd-8d43-184becf41b14)
![imatge](https://github.com/user-attachments/assets/1a4c8f6a-3547-4c8d-a15f-ee4f8953209f)

**Comment by MatthewReed303** [comment]
@prac05 you should be using retain variables on the PLC and not with Fuxa. If the variable is changed on the PLC it's stored within the PLC

**Comment by prac05** [comment]
The variable is already being stored in the PLC via Node-red.  It is not practical that when the value inserted in the input is lost, it has to be looked for elsewhere.  So is there some way to always see the last value inserted in case the PLC suffers a power failure?

**Comment by MatthewReed303** [comment]
@prac05 that's exactly what retain value does in the PLC, if power is cycled it's still retained? What PLC are you using? On the Input make sure you have the updates enabled 

![image](https://github.com/user-attachments/assets/4e6f4e59-c3de-4040-a025-229956d61ad3)

**Comment by prac05** [comment]
Hi Matthew,

On the input settings, what is the function of the value parameter?

![imagen](https://github.com/user-attachments/assets/86b1ebff-ece2-4ef8-bd72-b4a18ddee38b)

**Comment by unocelli** [comment]
Hi, you can use enable the restore option on the Tag

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible

**Comment by andy8601** [comment]
> 嗨，您可以在标签上启用恢复选项

“to restore” This does not take effect for external DAQ storage。 InfluxDB
