### ISSUE TITLE
Circular Gauge setting 

### ISSUE THREAD

**Issue by fengchenyu** [frangoteam/FUXA#1409]
Angular version 17.3.6；The following error occurred in the Circular Gauge setting
![Circular ](https://github.com/user-attachments/assets/0dc987aa-b748-40c2-abe2-b6c4c8c42a61)
![Angular](https://github.com/user-attachments/assets/d70f748b-6234-45dc-80be-50fabb8ffce6)

![error](https://github.com/user-attachments/assets/c977055f-fb00-425e-8e2b-3976181bcb0e)

**Comment by unocelli** [comment]
Hi, fuxa currently uses version 15, and will eventually upgrade to 16, I don't understand what you expect and why you post this issue
