### ISSUE TITLE
need more label and value in select setting

### ISSUE THREAD

**Issue by peakcontrol** [frangoteam/FUXA#141]
![image](https://user-images.githubusercontent.com/63614880/117531116-88beb980-b013-11eb-8229-c1e1799a9d4e.png)
How to modify the code to get more label and value

**Comment by studuino** [comment]
Here too, total events in the button settings for "set from input" count only four and a half.
![image](https://user-images.githubusercontent.com/2291009/117532586-4cd52580-b00e-11eb-904b-8d7fe9594139.png)

**Comment by unocelli** [comment]
Hi, thanks for your report, I will fix it

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
