### ISSUE TITLE
[BUG] some objects disappear with no-admin users

### ISSUE THREAD

**Issue by zblack88** [frangoteam/FUXA#1411]
**Describe the bug**
If you enable the authentication with token, when you are logged with a non-admin account some objects (lines, rectangles, etc.) disappear, even if no visibility has been set on them.
It seems random, because on identical pages different objects disappear.

With admin account everything works fine.

Any idea for solving it?

**Environment**
 - FUXA version: 1.2.0
 - npm version: 8.11.0
 - Platform/OS: Windows 10
 - Browser: Edge and Chrome

**Comment by unocelli** [comment]
Hi, please provide a example.

**Comment by zblack88** [comment]
This is the output:
admin account:
![image](https://github.com/user-attachments/assets/c1177911-c674-4537-b1ad-1a8c5f50fb79)

view account (all privileges but "Administrator"):
![image](https://github.com/user-attachments/assets/06c9c239-73a7-4260-b525-65a90fe8a590)

No authorization has beeen set for any object:
![image](https://github.com/user-attachments/assets/3deece5f-4e60-44a5-9982-c26d81c69ca8)

If you want I can share the .json project in pvt

**Comment by unocelli** [comment]
Yes, please send me your project [4frango@gmail.com](mailto:4frango@gmail.com)

**Comment by unocelli** [comment]
Hi, This issue should be fixed in the latest master branch version. let me know if you have any issues.

**Comment by zblack88** [comment]
Thank you very much, it works now.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
