### ISSUE TITLE
Any additional event trigger type for "Open Dialog" other than user "Click"?

### ISSUE THREAD

**Issue by studuino** [frangoteam/FUXA#142]
Hi @unocelli, great project.
Is there any update on the way regarding action like "Open Dialog" triggered from sensor value change rather than user click action.
thank you for the great project again.
![image](https://user-images.githubusercontent.com/2291009/117541164-95093d80-b038-11eb-9a6f-a484f22c1b88.png)

**Comment by unocelli** [comment]
Hi, Thanks.
Interesting, were you thinking of events such as mouse over?...do you have an example

**Comment by studuino** [comment]
Actually I am thinking of to open dialog(e.g. Yes or No question) for operator to answer.
The dialog popup is due to a certain sensor value change.
Sorry if I cannot make it clear.

**Comment by unocelli** [comment]
I think that what you mean is more a warning or info notification as dialog form (showed by a certain sensor value change), but this one is independent from controls and shapes event (like click)?

**Comment by studuino** [comment]
Yes, this is exactly what I mean. I couldn't express it in proper way.
Thank you for the correction.

**Comment by unocelli** [comment]
I like the feature :)
A simple way to add it is to extend the Alarms (as Alarms and Notifications) with the possibility to define the trigger action to show a View as Dialog, the action could be a email too.

**Comment by studuino** [comment]
Yes, I am thinking of the output that trigger dialog/card over value change. sorry I am noob to the programming.

**Comment by studuino** [comment]
Something like this
![image](https://user-images.githubusercontent.com/2291009/120909963-b2b1dd00-c6a0-11eb-8f87-c8d46b0e5056.png)

**Comment by unocelli** [comment]
added in v1.1.4 
going to close this as resolved. let me know if you have any issues.
