### ISSUE TITLE
[BUG] при перезагрузке контроллера не обновляются состояния  элементов управления (не корректно отображается заливка). при этом значения с панели управления отправляются

### ISSUE THREAD

**Issue by peacedoorballl** [frangoteam/FUXA#1421]
при перезагрузке контроллера не обновляются состояния открытой страницы браузера (не корректно отображается заливка). при этом значения с панели управления отправляются

ps не читаются mqtt сообщения. но стоит перезагрузить страницу браузера, все работает

pps поставил галочки "регистрация включена" и "сохранять значения по изменению" и всё заработало

**Comment by unocelli** [comment]
Hi, please translate the title and description into English

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
