### ISSUE TITLE
Question: displaying a tag value string

### ISSUE THREAD

**Issue by relihanl** [frangoteam/FUXA#1423]
I think i must be going crazy but I want to display a string tag value in a view. The value can be changed dynamically at any time by an MQTT topic. Which control do I use to do this, and how should i configure it?

My version is FUXA V.1.2.0-1909

**Comment by henjoe** [comment]
Just use the Output control. and bind the Tag under the Value

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
