### ISSUE TITLE
[BUG] Button Fails to Function Properly Without Displaying Variable on Screen

### ISSUE THREAD

**Issue by martinjug** [frangoteam/FUXA#1441]
First video demonstrates that pressing the "AUTO" button (Action[click] Event[toggleValue] -> V0.7) doesn't function properly. However, if you add that variable to the screen using an "Input Value" element, the button starts working as expected.

https://github.com/user-attachments/assets/c7f109f2-2757-4124-8d34-f7b8c8d39085

**Environment**
 - FUXA version: **1.2.0-1956**
 - Node.js version:  **v14.21.3**
 - npm version: **6.14.18**
 - Platform/OS: **Windows 10**
 - Browser: **Brave**
 - Driver: **node-snap7": "1.0.6"**

Second video is showing previous version, everything works as expected.

https://github.com/user-attachments/assets/5c60209b-33d1-49df-b209-30898b64de88

**Environment**
 - FUXA version: **1.1.19-1619**
 - Node.js version:  **v14.21.3**
 - npm version: **6.14.18**
 - Platform/OS: **Windows 10**
 - Browser: **Brave**
 - Driver: **node-snap7": "1.0.6"**

Third video is showing same problem as first video. This time I created fresh project with modbus driver connecting to modbus server. Button(toggleValue) doesn't function properly.(fails to toggle value) However, if you add that variable to the screen using an "Input Value" element, the button starts working as expected.

https://github.com/user-attachments/assets/ce29557b-73c4-43c1-b1b4-4759b6670579

**Environment**
 - FUXA version: **1.2.0-1956**
 - Node.js version:  **v14.21.3**
 - npm version: **6.14.18**
 - Platform/OS: **Windows 10**
 - Browser: **Edge**
 - Driver: **modbus": "8.0.16"**

**Comment by martinjug** [comment]
I realize my previous explanation might not have been clear. I've made another recording demonstrating the problem. On the left side of screen is Modbus server publishing one coil. On the right side of screen is FUXA.

"ToggleValue" button works as expected in version V1.19 but does not work in V1.20. Specifically, in V1.20, it fails to toggle value of a coil(you can see it's not changing on modbus server). **I think that script that toggles value is not executed in V1.20.**

When toggling the value directly in the Modbus server, both V1.19 and V1.20 reflect the change correctly. However, when using the toggle button in FUXA, it works as intended in V1.19 but fails in V1.20.


https://github.com/user-attachments/assets/d1bf527b-5344-4059-b580-f1946468018b

https://github.com/user-attachments/assets/fc52912a-7ba5-4347-824e-eae4209add43

**Comment by unocelli** [comment]
![toggle](https://github.com/user-attachments/assets/f4e08d27-4b64-463f-b63e-2ae17de8681e)

**Comment by martinjug** [comment]
Your example seems to be working as expected. If I'm able to reproduce the bug, I'll post the details here. It's definitely strange behavior.

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
