### ISSUE TITLE
[FEATURE] Slider background colour or opacity adjustment.

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#1442]
As per the title, the slider is nice however my background is not white so it looks silly, am I mussing how to change this or is this a feature that could be added?

![image](https://github.com/user-attachments/assets/5886db97-595e-4d81-bc66-17a6973c56ae)

**Comment by MatthewReed303** [comment]
@lewsut just select the slider in the editor and set background to none 

![image](https://github.com/user-attachments/assets/5e129001-cd51-4679-a0ec-a6ddf3521559)

The white with the red cross

**Comment by lewsut** [comment]
Perfect!
