### ISSUE TITLE
[BUG] Scripting doesn't work (401 Unauthorized)

### ISSUE THREAD

**Issue by Brandon-sistein** [frangoteam/FUXA#1447]
I tried this script:

let test1 ="Hello world";

let test2 = "`SELECT * " + test1 + "`"
console.log(test2);

and show me this error:

```
>Http failure response for http://192.168.0.11:1881/api/runscript: 401 Unauthorized
>Unauthorized!
```

How can I solve it? and  why it is happening?

Environment
 - FUXA Docker
 -Raspberry

**Comment by Brandon-sistein** [comment]
This is the sistem error:

![image](https://github.com/user-attachments/assets/18d9c669-314f-4cc8-b469-a01f76c71c43)
![image](https://github.com/user-attachments/assets/624cd7ce-91a4-416a-b6ca-17085ad75e27)

**Comment by robbudge** [comment]
Same Issue also 

Version 1.2.0-1956 
npm 10.7.0
node v18.20.4
SeeedStudio RPI-200 running buster

![image](https://github.com/user-attachments/assets/c0b32584-6851-480e-a841-828504cd53dd)
This was working fine, very recently and can only be related to the project configuration.
Only major change was to enable security.
I have since disabled security and still the same will keep looking

**Comment by robbudge** [comment]
Quick Update, this is also noted on a previous post.
if you have any script with an error, it will cause this issue with all script executions.

I had a simple scratch script that I use getTag to obtain the tags uuid for grafana. Obviously this was a  script full of junk.
Once it was deleted all my other scripts worked fine.

**Comment by Brandon-sistein** [comment]
I deleted all the scripts and create a "hello world" and still showing the error

**Comment by unocelli** [comment]
Hi, I confirm that there are some problems if you leave code commented with // in scripts. we are investigating, for the time being we recommend not using // to comment code

**Comment by WuBingo12** [comment]
If there is a comment at the last line of any script using // to comment code, this issue will occur

**Comment by unocelli** [comment]
@WuBingo12 Thanks for the report, is exactly what I was looking for

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
