### ISSUE TITLE
[BUG]为什么我将livedemo里的项目导入到最新版的fuxa里，但是他不工作了，是要设置哪里吗？

### ISSUE THREAD

**Issue by wen089130** [frangoteam/FUXA#1448]
**Describe the bug**
A clear and concise description of what the bug is.为什么我将[livedemo](https://frangoteam.github.io/)里的项目导入到最新版(v1.2.0)的fuxa里，但是他不工作了，是要设置哪里吗？
![image](https://github.com/user-attachments/assets/3e8983cb-29d6-45fb-8fac-fc5437cf666e)
我在lab里设置值的时候各个组件都是正常工作的，但是我点击按钮或者拉动滑块的时候并不能改变标签的值？
![image](https://github.com/user-attachments/assets/5353e949-3e77-4fe4-9b30-e91a6879813b)
![image](https://github.com/user-attachments/assets/9ad351ac-f03f-4e0e-a507-99cec28083b7)
我在lab测试发现他的指令不一样，一个是put Tag Byte 72.0  而另一个是Device A - Tag Byte=51.0 。我不知道是不是这个原因
**To Reproduce**
[fuxa-project.json](https://github.com/user-attachments/files/17455877/fuxa-project.json)

**Expected behavior**

**Screenshots**

**Environment**
 - FUXA version: 
 - Node.js version: 
 - npm version:
 - Platform/OS:
 - Browser:

**Comment by unocelli** [comment]
Hi, You must activate Device A

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
