### ISSUE TITLE
server connection failed

### ISSUE THREAD

**Issue by DHIAFIQ** [frangoteam/FUXA#1449]
hi fuxa team, 

can I know, what the factor of causes the sever connection failed,
my polling right now is 1.5 sec but the error still occur.

this the picture of the error
![server connection failed](https://github.com/user-attachments/assets/35458b6f-f773-4ef8-95b0-3464da37d7af)

**Comment by ShahxlaN** [comment]
i had the same problem..the command prompt does not show any error, but suddenly the error occur

may i know the main factor of this error causes?
before this it never happen,
i already use the latest version but the error still occur.

**Comment by unocelli** [comment]
Server send every 10 seconds ALIVE message to every connected client, the client that don't receive ALIVE after 20 seconds show this error. I would look to see if the server is blocked.

**Comment by DHIAFIQ** [comment]
I run the fuxa in the same pc, so its no firewall between the server and the client

**Comment by unocelli** [comment]
Try to investigate with chrome devtools

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
