### ISSUE TITLE
How to add arrows to regular path components

### ISSUE THREAD

**Issue by crane168** [frangoteam/FUXA#1450]
Now I can add arrow attribute control in the line component, but I cannot control arrow attributes in the path component. I don't know how to handle it now, author. Do you have any other configuration methods?
![image](https://github.com/user-attachments/assets/ba950e5c-8ad9-4aca-97c3-0024b2b24f3c)

![image](https://github.com/user-attachments/assets/c01366b2-dd23-43ba-937d-b0475b1bcf95)

Later, it was found that whether the tag control is displayed or hidden in flux-edit.min.js is not very convenient to handle. Is there any other convenient method? teacher
![image](https://github.com/user-attachments/assets/94fd86f7-1bca-4252-8b5b-4ce90f4787c0)

**Comment by unocelli** [comment]
Hi, try frangoteam/FUXA

**Comment by crane168** [comment]
> Hi, try frangoteam/FUXA
now,I can control whether arrow mark attributes are displayed by controlling the SVG component type, without relying on editor.js

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
