### ISSUE TITLE
[BUG] shape's properties not copied as per issue #1015 

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#1453]
I'm sure this issue was fixed however It seems to be back?

https://github.com/frangoteam/FUXA/issues/1015#issuecomment-1861503817

**Environment**
 - FUXA version: Version 1.2.0-1825

**Comment by lewsut** [comment]
OK so sometimes this works and some times it does not, I shall investigate....

**Comment by zblack88** [comment]
I found that if you cut and paste in place (multiple times) works always

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
