### ISSUE TITLE
How to create more types of charts？

### ISSUE THREAD

**Issue by zzzecho0611** [frangoteam/FUXA#146]
Hello, this project is very good, can the chart control in the project be more rich, and the chart in echars can be introduced. Is it complicated? What documents need to be changed? Thank you very much. My angular is not very good.

**Comment by unocelli** [comment]
Yes I planed to use more of the uplot functionality, as soon as I find the time.
To add echart should not be so complicate, I'm coming to change from dygraph to uplot, if you look in the repo at this you will understand ;)
