### ISSUE TITLE
发布事件为什么同时发送了2条数据呢？

### ISSUE THREAD

**Issue by zhangxuehuaf** [frangoteam/FUXA#1461]
![微信图片_20241029182935](https://github.com/user-attachments/assets/5a8d94fb-7b1a-4d5b-ad5c-b430dff97be4)
![微信图片_20241029182947](https://github.com/user-attachments/assets/e76f3eaa-6c0e-44f1-95c3-e039cef0f27d)

**Comment by unocelli** [comment]
Hi, please translate the title and description into English and give more info

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
