### ISSUE TITLE
[BUG]@script

### ISSUE THREAD

**Issue by andy8601** [frangoteam/FUXA#1469]
After the 1.2.1 update, the script that was stable in 1.2.0 will not run properly, and if you cancel the days of the week to save the project, the system will crash. docker Snap7 version.
![image](https://github.com/user-attachments/assets/9406fe05-9fd0-4cc2-8918-3dcc9a3a3952)

**Comment by mauroalexandre** [comment]
I couldn't reproduce the issue. Could you provide more details or maybe record a video of the problem?
