### ISSUE TITLE
"POST" Method for Sensor values to store in FUXA SQL Database

### ISSUE THREAD

**Issue by studuino** [frangoteam/FUXA#147]
Hi,
Is there any plan in the future to have sensor value store in FUXA sqlite3 db.
Now its only GET.  That'd be definitely a cool feature to have.

![image](https://user-images.githubusercontent.com/2291009/118250280-4e9a5f80-b4cc-11eb-88d8-736eda115030.png)

**Comment by unocelli** [comment]
Hi,
Yes, I'm agree with you it is a cool feature to have ;)
Have you a idea how we can design the UI to configure the POST message with the sensor history data?

**Comment by unocelli** [comment]
There would be something similar available in version 1.1.11 #650
