### ISSUE TITLE
[FEATURE] SMTP Mailing for Alarms

### ISSUE THREAD

**Issue by Kiruthick-Roxx** [frangoteam/FUXA#1475]
**Describe the feature**
It would be good feature to add SMTP mailing for individual alarms in the action configuration panel, so that any critical alarms will be immediately notified by mail.

**Describe the solution you'd like**
![Screenshot 2024-11-03 085928](https://github.com/user-attachments/assets/ab271473-8c1a-41dd-a459-974dd569f0ef)
In the alarms action property panel, one more option like SMTP can be added and if possible additional settings to send the mail for the alarms can also be added. Upon selecting that, a mail should be sent to the receiver based on the configuration.

**Additional context**
It would be really helpful in the industry as the responsible person will be immediately notified rather than someone noticing the alarm and then taking action. It would also be good if I'm able to store historical alarms to Influxdb..

**Comment by henjoe** [comment]
That's what notifications do. 
![image](https://github.com/user-attachments/assets/529d16e9-df44-4cf6-81cd-b848c86a668c)

**Comment by Kiruthick-Roxx** [comment]
But that doesn't work for individual alarms right? Correct me if I'm wrong.

**Comment by niektuytel** [comment]
This can been done easily from outside this project.

**Comment by Kiruthick-Roxx** [comment]
Can you please share some idea?

**Comment by unocelli** [comment]
I suppose that a good compromise could be to add $sendMail function to de script

**Comment by unocelli** [comment]
I'm working on this issue $sendMessage
