### ISSUE TITLE
Is there any example FUXA script that implemented Alarms & Notification?

### ISSUE THREAD

**Issue by studuino** [frangoteam/FUXA#148]
Hi,
Anyone has any example.
I have trouble testing alarms and notification feature.
I do not see any sign even after alarms settings are enabled.

Thanks.

**Comment by unocelli** [comment]
Hi, 
Have you enabled in Setup->Layout->Header to show alarms?
![image](https://user-images.githubusercontent.com/48684550/118520146-15672700-b73a-11eb-9079-d35f59d067a7.png)

**Comment by studuino** [comment]
@unocelli Thank you for your reply. I got it now.
When I click "Layout", the layout settings page pop up but took up almost the whole windows and tabs are invisible without mouse scroll up.

**Comment by unocelli** [comment]
Hi,
Let me know if something doesn't work as expected
