### ISSUE TITLE
[BUG]After running for a few hours, the interface is not refreshing 

### ISSUE THREAD

**Issue by WuBingo12** [frangoteam/FUXA#1492]
After running for a few hours, the real-time table or chart is not refreshing and the pipeline is not running dynamically. Please help analyze the reasons. The client is running in webview2. Clicking the refresh button in the table does not work, but clicking the pop-up dialog box can restore the refresh of the interface, or reloading the page can also restore it 
The image below is not refresh 
![图片](https://github.com/user-attachments/assets/87f54154-6b44-4c9c-a60f-ed14bdd8f191)
The image below is stop or run very slow
![图片](https://github.com/user-attachments/assets/dbba0045-144b-4277-896c-e5bd784e525c)
Click the pop-up dialog box can restore the refresh of the interface
![图片](https://github.com/user-attachments/assets/a8672a64-7970-4f23-8bb4-0dc1d2213945)

**Comment by unocelli** [comment]
Hi, I suppose that you will show to many records in a html table, for this type of control there are limits

**Comment by WuBingo12** [comment]
It feels like after a period of time, no user clicks the trigger, and the angular client enters a dormant state. Now I use a script to regularly trigger the table refresh button on the interface to keep it active, and it has always been normal. But I think this is not a correct solution. Do you have any good suggestions? Is it a memory overflow? Or how to maintain activity normally when there is no user operation?

> Hi, I suppose that you will show to many records in a html table, for this type of control there are limits

**Comment by unocelli** [comment]
Hi, which browser are you using? try investigating with browser devtool.
