### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by andy8601** [frangoteam/FUXA#1501]
How do I hide the buttons in the Header Navigation Bar from specific users? My attempt to modify the permissions in the properties does not work, the navigation side menu is valid, or can I access the specified page directly through the unique URL address, which hides all navigation bars and only one configuration page?
![image](https://github.com/user-attachments/assets/bf7538c5-fb5e-49fe-8a28-018c860d7166)
![image](https://github.com/user-attachments/assets/ad535e2e-2508-4271-ba7f-f3d5df22c3e0)
![image](https://github.com/user-attachments/assets/40834461-d5b9-4aa7-8384-28e624ac325c)

**Comment by unocelli** [comment]
I'm working on this feature

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
