### ISSUE TITLE
[BUG]Enabling 'Only for Editor' on the settings page has not taken effect

### ISSUE THREAD

**Issue by yzkqq345** [frangoteam/FUXA#1505]
![image](https://github.com/user-attachments/assets/c18c7800-6426-4e4a-9881-e9bac960ec73)
I found that the '/api/settings' interface did not set 'secureOnlyEditor' to 'runtime.settings.secureOnlyEditor';

I don't understand Node.js, please forgive me if I'm wrong

**Comment by mauroalexandre** [comment]
Your token are expiring with this option enabled?

**Comment by yzkqq345** [comment]
> Your token are expiring with this option enabled?

No, token is valid
'post /api/settings' did not handle the parameter 'secureOnlyEditor'
![image](https://github.com/user-attachments/assets/2121c1dd-5702-4027-85dd-34dd3c421208)
![image](https://github.com/user-attachments/assets/acdf096e-50af-4bec-b659-883633f2db9d)
![image](https://github.com/user-attachments/assets/69de1423-5279-4642-b58e-47ead00d5d68)

**Comment by yzkqq345** [comment]
> Your token are expiring with this option enabled?

The parameter 'secureOnlyEditor' is only written to the 'mysettings. json' file, so it needs to be restarted in the Docker container to take effect

**Comment by unocelli** [comment]
Hi, some settings require a restart of the backend and this is one of them

**Comment by yzkqq345** [comment]
> Hi, some settings require a restart of the backend and this is one of them

So why not add a prompt on the settings page?

**Comment by robsori** [comment]
> > Hi, some settings require a restart of the backend and this is one of them
> 
> So why not add a prompt on the settings page?

Hello, did you get positive results with restarting the backend? In my case the token expires in any situation: with or without the "Only for Editor" option. It expires after every 24 hours. I mention that the operator works very rarely on the application. After the token expires, no script works anymore.
![PHOTO-2024-12-07-11-47-49](https://github.com/user-attachments/assets/01d9856d-aec3-42cf-97ce-0da12511fee2)

**Comment by unocelli** [comment]
Hi, Please let me know more details!

**Comment by robsori** [comment]
The philosophy of working with tokens was quite confusing until I understood how it worked. Initially I thought that when the token expired, the backend would also stop working, which would not have been right. We can close this topic. Thank you very much for the support.
