### ISSUE TITLE
How to retrieve all alarms in the script

### ISSUE THREAD

**Issue by s5314203** [frangoteam/FUXA#1512]
How to retrieve all alarms in the script

**Comment by unocelli** [comment]
I'm working on this feature

**Comment by unocelli** [comment]
I just added the feature in master branch

const activeAlarms =  await $getAlarms();
/* result in activeAlarms = [
    {
        "name": "temperature^~^highhigh",
        "type": "highhigh",
        "ontime": 1733074995709,
        "offtime": 1733075016983,
        "acktime": 0,
        "status": "NF",
        "text": "Alarm temperature",
        "bkcolor": "#FF4848",
        "color": "#FFF",
        "toack": 1
    }, {...}
] */

const ackResult = await $ackAlarm('temperature', ['highhigh', 'high']); // to ack 'highhigh' and 'high of alarm temperature
/* result ackResult = [true, ...] */

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
