### ISSUE TITLE
What is the difference between card and dialog in the event dropdown options?

### ISSUE THREAD

**Issue by crane168** [frangoteam/FUXA#1514]
In the event dropdown options, there are two options: card and dialog. It seems that these two types are the same. What are their specific differences? In what scenarios will it be used?

![image](https://github.com/user-attachments/assets/1dc7ed57-6e21-408f-b3bb-6d6f5de8fd0a)

**Comment by unocelli** [comment]
Hi, Dialog is a modal used for example to confirm a setting

**Comment by crane168** [comment]
> Hi, Dialog is a modal used for example to confirm a setting

ok,thank you
