### ISSUE TITLE
set view to panel can not work  in 1.2.1

### ISSUE THREAD

**Issue by serite** [frangoteam/FUXA#1522]
**Describe the bug**
set view to panel can not work  in 1.2.1 
**To Reproduce**
1. make ViewA,ViewB,ViewC
2. in ViewC put a Button a panel 
3. set Button event "set view to panel"
4. run
**Expected behavior**
ViewA show in panel

**Screenshots**
![image](https://github.com/user-attachments/assets/db95376e-1d7a-4729-ab85-03af7f947072)
![image](https://github.com/user-attachments/assets/3fb444f2-fecd-49eb-816a-77514af5f21f)

**Environment**
the newest docker

**Comment by robsori** [comment]
You are missing a tag in the "Tag FUXA" section.

**Comment by serite** [comment]
I set a tag (defined in FUXA), it's not work yet.


***@***.***
 
From: robsori
Date: 2024-12-05 15:40
To: frangoteam/FUXA
CC: serite; Author
Subject: Re: [frangoteam/FUXA] set view to panel can not work in 1.2.1 (Issue #1522)
You are missing a tag in the "Tag FUXA" section.
―

**Comment by robsori** [comment]
Sorry, I didn't pay attention to your images, if you use the "Set View to Panel" function directly it works very well and you don't have to use any tags. I tested it now and everything is ok.

**Comment by serite** [comment]
may be i use the newest version (1.2.1) on ubuntu 20.04. use set value (bind tag of FUXA) or "set view to panel" , it is can not work. 




***@***.***
 
From: robsori
Date: 2024-12-05 20:38
To: frangoteam/FUXA
CC: serite; Author
Subject: Re: [frangoteam/FUXA] set view to panel can not work in 1.2.1 (Issue #1522)
Sorry, I didn't pay attention to your images, if you use the "Set View to Panel" function directly it works very well and you don't have to use any tags. I tested it now and everything is ok.

**Comment by unocelli** [comment]
@serite Hi, I suppose that you are using the version of master branch, I just fixed it

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by fanchunyong** [comment]
@unocelli I have the same situation, what should I do?
