### ISSUE TITLE
[Question] [Edit] Save project does not reflect changes on "save project as" file location. - option to save at external location 

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [frangoteam/FUXA#1529]
It's has been  joy of using FUXA as go to dashboard maker.
I'm curious, where or at which location file get save after "Save project" button pressed. 
I can use "Save project as", but cant imagine what is "default" project save location which reflects changes done.(`it supposed to be overwrite "save project as" file location.`)

![save-project](https://github.com/user-attachments/assets/24e6abcc-44b4-4feb-a2dc-a69d230b32aa)

## Fuxa Version 1.2.1-1988

![fuxa-version](https://github.com/user-attachments/assets/0f634184-3f77-47fa-894d-444ba995a664)

**Comment by unocelli** [comment]
Hi, in [wiki](https://github.com/frangoteam/FUXA/wiki/HowTo-save-load-Project) you have little description

**Comment by OptifySudarshanPatil** [comment]
> Hi, in [wiki](https://github.com/frangoteam/FUXA/wiki/HowTo-save-load-Project) you have little description

Thanks!
