### ISSUE TITLE
SQLITE_NOTADB: file is not a database

### ISSUE THREAD

**Issue by studuino** [frangoteam/FUXA#153]
Hi, I got an error at the start of the script.
![image](https://user-images.githubusercontent.com/2291009/119928741-32092780-bfa2-11eb-9fee-8bab0ff18181.png)

**Comment by unocelli** [comment]
Hi,
I think it is related to the issue #154. I will take care of it as soon as possible.

**Comment by unocelli** [comment]
I solved the issue. I will therefore close this issue, feel free to re-open it if something is still not working.
