### ISSUE TITLE
[QUESTION] How to add Tags from the WebAPI

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#1546]
**Describe the Question**
I have a web api server running on HTTP://localhost:5050/api/test

And this return a dummy data: 
```
[
    {
        id: 'tempA',     // UUID
        name: 'tempA',
        value: 123,
        type: 'number'  // number|boolean|string,`
    },
    {
        id: 'tempB',    // UUID
        name: 'tempB',
        value: 23.5,
        type: 'number'  // number|boolean|string,`
    }
]
```
When adding a device with type WebAPI, I can successfully received this data.

![image](https://github.com/user-attachments/assets/2b6fe11b-f1c4-48f1-b6f3-2567035a3054)

Now my question is how can I add the Tags from the WebAPI device? when I tried to browse the Tags it gives me something like this: 
![image](https://github.com/user-attachments/assets/f3e3869e-32ea-4fdd-bda2-fa58b6a28a8f)

The issue is I cannot select the Tag to add on my Device Taglist. 
Am I doing something wrong here?

**Comment by unocelli** [comment]
It is an array, select the ID and Value
![image](https://github.com/user-attachments/assets/754d75c4-3664-430a-9cb8-59774654c42f)

**Comment by henjoe** [comment]
Hi @unocelli  thanks for clarification, I will try this. I am thingking that it should have a checkbox (like on the opcua). 

Regards,
