### ISSUE TITLE
Do you support sharing as hyperlinks?

### ISSUE THREAD

**Issue by wangganggit** [frangoteam/FUXA#1548]
If sharing as a hyperlink is supported, just embed it on the page, I think it's great!

**Comment by unocelli** [comment]
Hi, I am not sure what you mean: try `http://localhost:4200/view?name=<your view name>`

**Comment by wangganggit** [comment]
> 嗨，我不确定你的意思：试试`http://localhost:4200/view?name=<your view name>`


Thank you for your answer!
