### ISSUE TITLE
Modbus exception 3: Illegal data value (value cannot be written to this register)

### ISSUE THREAD

**Issue by studuino** [frangoteam/FUXA#155]
Hi, I am having issue as per title. Just to report.
Could the error be more specific like which register has  the issue to read/write

![image](https://user-images.githubusercontent.com/2291009/120077470-988c6380-c0d0-11eb-9fd9-5feabc91565f.png)

**Comment by alpaslanske** [comment]
the register you want to write a value is readonly. you can not write to readonly registers.

**Comment by studuino** [comment]
I messed up with high pool rate(500ms) and fragmentation for couple hundreads of data registers. Now seems ok now.
