### ISSUE TITLE
FSevents

### ISSUE THREAD

**Issue by alpaslanske** [frangoteam/FUXA#160]
Hi,

is this warning important?

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by unocelli** [comment]
Hi,
I think in development phase could be ignored. it would be nice to solve them, if possible ;)

**Comment by alpaslanske** [comment]
Guide me. Let me try.

**Comment by alpaslanske** [comment]
i searched and result is this is not an issue about Windows. Windows users can ignore this warning.

What's happening here is that a package called chokidar is being used to "watch" filesystem directories for "events" (like files being added). chokidar is a wrapper for Linux-, Windows-, and Mac-specific filesystem-watching packages, of which fsevents is the Mac variant. So,projects that uses chokidar is going to have fsevents as an optional dependency,  this WARN message can be safely ignored, as chokidar supports all common desktop architectures.

I am closing this issue.

**Comment by unocelli** [comment]
Thanks :)
