### ISSUE TITLE
Alarms feature

### ISSUE THREAD

**Issue by zesava** [frangoteam/FUXA#166]
Possibility select individual bits for alarms from  let's say variable of datatype WORD. In this case one variable will cover 16 alarms. This approach is used in most industrial PLC's. Thanks.

**Comment by alpaslanske** [comment]
It also decrease traffic. We must consider this.

**Comment by zesava** [comment]
Any progress with this ? :)

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
