### ISSUE TITLE
modbusTCP 5 digits to 6 digits

### ISSUE THREAD

**Issue by anhthe** [frangoteam/FUXA#177]
I am interested in FUXA, and i have a problem with modbusTCP.
I created new tag with address is 400001 and map with 40001 in modbus tool as pitures below:
![image](https://user-images.githubusercontent.com/4360577/126935652-4171f6cb-2e4d-4ceb-9a89-10f29b7a5243.png)
![image](https://user-images.githubusercontent.com/4360577/126935720-df3b22b9-5555-45b7-ba37-6a1d8091de97.png)
 But I got a error:  'modbus' _readMemory error! Error: Modbus exception 2: Illegal data address (register not supported by device)

Please show me what is the error?

Thank you!

**Comment by alpaslanske** [comment]
that is not about Fuxa. Try this settings.
![image](https://user-images.githubusercontent.com/59701410/127001820-4b86162b-ed6b-4ab3-bd2b-26732a68593b.png)

**Comment by anhthe** [comment]
> that is not about Fuxa. Try this settings.
> ![image](https://user-images.githubusercontent.com/59701410/127001820-4b86162b-ed6b-4ab3-bd2b-26732a68593b.png)

Thank you Alpaslanske!
