### ISSUE TITLE
Email Service

### ISSUE THREAD

**Issue by eyadalhanafi** [frangoteam/FUXA#184]
Hi,
Functionality to send email updates, reports, and notifications through an email service  is important. Will it be considred in future?

**Comment by unocelli** [comment]
HI,
yes it's in the To-Do list, the idea is to apply it to alarms and messages. 
about reports, I think we need the feature first, that don't look very simple to implement.

**Comment by unocelli** [comment]
This works in the latest version. let me know if you have any issues.
