### ISSUE TITLE
Group control

### ISSUE THREAD

**Issue by franzhefekranz** [frangoteam/FUXA#185]
Hi, I would like to have a feature where I can group some controls together , to reuse the group as another high level control.
For example, when you click a control, you open a popup with further info, interlocks, alarms, graphs, settings ...

**Comment by unocelli** [comment]
Hi, sorry for the delay.
It is a nice feature that currently is missing, What you can do is create a view and bind the gauge tag to a internal device, to use as context variables when you will show the view for example press a button (in events)
