### ISSUE TITLE
cannot choose different images

### ISSUE THREAD

**Issue by spiderock98** [frangoteam/FUXA#187]
I'm trying to choose a new background image for dashboard but after I chose a new image then clicked outside to put it on dashboard editor, but the previous image that i chose before is chosen instead

![image](https://user-images.githubusercontent.com/28623503/128988267-20fead1b-81a1-4e37-bea8-8da7f6bcf1c6.png)

**Comment by unocelli** [comment]
I fixed, Thanks

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
