### ISSUE TITLE
save multiple projects

### ISSUE THREAD

**Issue by YasithAri** [frangoteam/FUXA#188]
Hi, i am checking the FUXA for a project and seems to be very interesting. have a requirement that create multiple projects on same server and same db , is that possible? for ex. user A logging to the FUXA and create a project and also user B creates a project. so both should save in db and access accordingly. as i understand it override the same project with new one. please advise

**Comment by unocelli** [comment]
Hi,
I don't understand your goal? 
it is possible to start multiple fuxa instances by defining different ports.

**Comment by YasithAri** [comment]
if we set the different ports , will it be share the same app db and other d files? my goal is one user has set of api devices and other user have serperate devices . so if i use one port for both users, can db handle both data at same time?

**Comment by unocelli** [comment]
we analysed the feature and realised that require a redesign that would need many resources.
