### ISSUE TITLE
Modbus TCP Floating Point

### ISSUE THREAD

**Issue by eyadalhanafi** [frangoteam/FUXA#189]
Thank you for your support.
We are using Modbus TCP driver to connect to a PLC and poll some floating points. The communication was established fine and we could receive the data but the data received are integers, not deiciml numbers. I checked valuse using MODSCAN and the data received are with decimals. 
![Fuxa floating points](https://user-images.githubusercontent.com/26257832/130056087-df54aec9-8e52-4609-b8c4-c2eede364c9b.jpg)

I don't know if i missed anything in the configuration so that i received that. Please advise.

**Comment by unocelli** [comment]
Hi,
you are looking at the right address? which value you receive if you address to 402565 ?

**Comment by eyadalhanafi** [comment]
Hi,
The address 402565 gives wrong value.

**Comment by unocelli** [comment]
Hi,
Interesting is that if I set the value from FUXA or from the modscan32 I see the correct value
![image](https://user-images.githubusercontent.com/48684550/130362242-490b4483-7f9f-432a-96ca-4c228af975f4.png)

**Comment by eyadalhanafi** [comment]
Hi
I tried another SCADA system with modbus driver, I received the correct value. It is weired

**Comment by eyadalhanafi** [comment]
I tried to write on floating point signal from FUXA,  I didn't get the value in Modscan. I received incorrect value.

**Comment by unocelli** [comment]
I added the LittleEndian type, maybe this was the problem?

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
