### ISSUE TITLE
I need to change the fill color of several objects.

### ISSUE THREAD

**Issue by rlleixa** [frangoteam/FUXA#194]
I need to change the fill color of several objects.
I try to explain.
I have a map of a factory. I have a drop down box where I select for example "Hot water installation". I need that when selecting this option, all the objects of the hot water circuit are painted in one color (for example red).
How can I do it?

**Comment by unocelli** [comment]
Hi,
you can define a device 'internal' with a tag. then define a control select that change the tag value. then you configure the shapes property to change color, always using the same tag.

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
