### ISSUE TITLE
Swapped Float 32

### ISSUE THREAD

**Issue by Litenfantasi** [frangoteam/FUXA#195]
Hi,

Just tried installing FUXA to try it out. I want to collect data over Modbus TCP. And values are swapped float32, not float32 - the only alternative I see under adding a tag/device. Is it possible to somehow specify little or big endian?

**Comment by unocelli** [comment]
Hi, thanks for the report. I added the feature

**Comment by unocelli** [comment]
I will therefore close this issue, feel free to re-open it if something is still not working.
