### ISSUE TITLE
MQTT error

### ISSUE THREAD

**Issue by haitan981** [frangoteam/FUXA#196]
I am researching MQTT protocol in FUXA. But I can not creat tag subscribe, only creat public tag. 
But when runtime, I public tag only receive data from another MQTT client but can not sent data to that MQTT client
See details in below link
https://drive.google.com/drive/folders/1Cw5_qdQOA2MxkmTR3lwmm5YRee9koDPA?usp=sharing
Thank you so much.

**Comment by unocelli** [comment]
Hi,
I did some refactoring in MQTT client...maybe solve the issues.

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
