### ISSUE TITLE
Modbus plugin installation not work

### ISSUE THREAD

**Issue by adolfosan** [frangoteam/FUXA#200]
When installing the modbus plugin it shows me the message: "Installing ... OK!", but when I go to select a Modbus device it is not found in the fuxa server connections, in the terminal it shows me the caution message: "try to create d but plugin is missing! "
![modbus-installed](https://user-images.githubusercontent.com/55285509/136234603-820deaa4-9eca-43d3-9bb7-8ce5101b5714.png)
![Modbus](https://user-images.githubusercontent.com/55285509/136234623-0d62f779-f54d-4e0f-8361-3f1d0ce03d5c.png)

**Comment by adolfosan** [comment]
I am using npm, the version is 1.1.1

**Comment by adolfosan** [comment]
I installed with first option: npm  and I'm using 1.1.1 version

**Comment by unocelli** [comment]
I'm sorry is there a bug in css you have to click in the corner
![image](https://user-images.githubusercontent.com/48684550/136250490-677826b7-d4a8-4fb0-85dd-6cc2c035d359.png)

**Comment by unocelli** [comment]
I have already fixed but not release in a version. Coming soon.
you still have the problem with the modbus plugin?

**Comment by adolfosan** [comment]
> you still have the problem with the modbus plugin?

Yes

**Comment by adolfosan** [comment]
> look good...I just tested on ubuntu 20 without any problems... you can try to install your self [modbus](https://www.npmjs.com/package/modbus-serial):
> 
> > cd server
> > npm i --save modbus-serial

Ok, let me try, I have a question:
Cuando yo instale modbus-serial , saldra en la creacion de un dispisitivo los tipos:,Modbus RTU,Modbus TCP?
