### ISSUE TITLE
Chart issues

### ISSUE THREAD

**Issue by w4Rd3n** [frangoteam/FUXA#209]
Hello
Charts do have some bugs. Follow popup does not show values. 
and if you add more than 3 Datapoints the legend on bottom is getting cut. see below:
![image](https://user-images.githubusercontent.com/1331530/138814869-fd97bcba-6392-48ca-a9f6-88d5a9852c03.png)

Also would be very nice to have some other charts. as exemple daily and monthly kWh charts:
![image](https://user-images.githubusercontent.com/1331530/138815411-3cdf3ca9-8f37-46fb-addb-9993e70bed44.png)

**Comment by w4Rd3n** [comment]
i did replace the 2 files on docker. restarted fuxa but it does not work.
Do i need to reinstall entire fuxa ?
i ll loose my history. is there another way ?

**Comment by unocelli** [comment]
Now I updated the docker image too, try again.

**Comment by w4Rd3n** [comment]
Yes! i like it. you also changed the legend on bottom. it works now on 2 lines . Great!
I lost my historic data. Now i deplyoed with an external volume and mapping
/usr/src/app/FUXA/server/_db

lets see if its working with the next update :)

**Comment by unocelli** [comment]
@w4Rd3n 
Hi, I have a Issue #247 about the persistent storage, have you solved your?
If so, could you explain how to do it #247, I'm also interested ;)
Thanks

**Comment by w4Rd3n** [comment]
> @w4Rd3n Hi, I have a Issue #247 about the persistent storage, have you solved your? If so, could you explain how to do it #247, I'm also interested ;) Thanks

![image](https://user-images.githubusercontent.com/1331530/148366270-37acb1fb-5dec-471c-b9fc-370c5ebadf9b.png)

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
