### ISSUE TITLE
fuxa how to customize controls

### ISSUE THREAD

**Issue by struggle3** [frangoteam/FUXA#212]
Hello: fuxa how to customize controls

I have done the following work:

1. Added htmlyecomponent using angular cli

2. The code of editor.component.html file is modified as follows:
`<div class="svg-tool-button" matTooltip="{{'editor.controls-ye' | translate}}" [ngClass]="{'svg-tool-active': isModeActive('html_ye')}"
                                (click)="setMode('html_ye')">
                                <span class="icon-tool icon-text"></span>
                            </div>`
3. The editor.component.ts file code is modified as follows:
`private getGaugeTitle(type) {
        let msg = '';
        if (type.startsWith(HtmlInputComponent.TypeTag)) {
            this.translateService.get('editor.controls-input-settings').subscribe((txt: string) => { msg = txt });
        } else if (type.startsWith(HtmlYeComponent.TypeTag)) {
            this.translateService.get('editor.controls-ye-settings').subscribe((txt: string) => { msg = txt });
        } else if (type.startsWith(ValueComponent.TypeTag)) {
            this.translateService.get('editor.controls-output-settings').subscribe((txt: string) => { msg = txt });
        } else if (type.startsWith(HtmlButtonComponent.TypeTag)) {
            this.translateService.get('editor.controls-button-settings').subscribe((txt: string) => { msg = txt });
        } else if (type.startsWith(HtmlSelectComponent.TypeTag)) {
            this.translateService.get('editor.controls-select-settings').subscribe((txt: string) => { msg = txt });
        } else if (type.startsWith(GaugeProgressComponent.TypeTag)) {
            this.translateService.get('editor.controls-progress-settings').subscribe((txt: string) => { msg = txt });
        } else if (type.startsWith(GaugeSemaphoreComponent.TypeTag)) {
            this.translateService.get('editor.controls-semaphore-settings').subscribe((txt: string) => { msg = txt });
        } else {
            this.translateService.get('editor.controls-shape-settings').subscribe((txt: string) => { msg = txt });
        }
        return msg;
    }
`

4. The code of gauges.component.ts file is modified as follows:
`// list of gauges with input
    static GaugeWithInput = [HtmlInputComponent.prefix, HtmlSelectComponent.prefix, HtmlSwitchComponent.prefix,HtmlYeComponent.prefix.toLowerCase,HtmlWangComponent];
    // list of gauges tags to check who as events like mouse click
    static GaugeWithEvents = [HtmlButtonComponent.TypeTag, GaugeSemaphoreComponent.TypeTag, ShapesComponent.TypeTag, ProcEngComponent.TypeTag,
        ApeShapesComponent.TypeTag];
    // list of gauges tags to check who as events like mouse click
    static GaugeWithActions = [ApeShapesComponent, PipeComponent, ProcEngComponent, ShapesComponent, HtmlButtonComponent, HtmlSelectComponent,
        ValueComponent, HtmlInputComponent, GaugeSemaphoreComponent,HtmlYeComponent,HtmlWangComponent ];
    // list of gauges components
    static Gauges = [ValueComponent, HtmlInputComponent, HtmlButtonComponent, HtmlBagComponent,
        HtmlSelectComponent, HtmlChartComponent, GaugeProgressComponent, GaugeSemaphoreComponent, ShapesComponent, ProcEngComponent, ApeShapesComponent,
        PipeComponent, SliderComponent, HtmlSwitchComponent,HtmlYeComponent,HtmlWangComponent];

    initInEditor(ga: GaugeSettings, res: any, ref: any) {
        if (ga.type.startsWith(GaugeProgressComponent.TypeTag)) {
            GaugeProgressComponent.initElement(ga);
        } else if (ga.type.startsWith(HtmlButtonComponent.TypeTag)) {
            HtmlButtonComponent.initElement(ga);
        } else if (ga.type.startsWith(HtmlYeComponent.TypeTag)) {
            HtmlYeComponent.initElement(ga,true);
        }  else if (ga.type.startsWith(HtmlChartComponent.TypeTag)) {
            delete this.mapGauges[ga.id];
            let gauge = HtmlChartComponent.detectChange(ga, res, ref);
            this.setChartPropety(gauge, ga.property);
            this.mapGauges[ga.id] = gauge;
        } else if (ga.type.startsWith(HtmlBagComponent.TypeTag)) {
            this.mapGauges[ga.id] = HtmlBagComponent.detectChange(ga, res, ref);
        } else if (ga.type.startsWith(PipeComponent.TypeTag)) {
            return this.mapGauges[ga.id] = PipeComponent.detectChange(ga, res, this.winRef);
        } else if (ga.type.startsWith(SliderComponent.TypeTag)) {
            return this.mapGauges[ga.id] = SliderComponent.detectChange(ga, res, ref);
        } else if (ga.type.startsWith(HtmlSwitchComponent.TypeTag)) {
            return this.mapGauges[ga.id] = HtmlSwitchComponent.detectChange(ga, res, ref);
        }
        return false;
    }
`

5. From the code, I found that the ext-bundle.min.js file should also be modified. Whether the file code is automatically generated and whether there is a method to modify this file.

**Comment by unocelli** [comment]
Hi, 
currently you can add shapes yourself but you can't add controls yourself.
what kind of control you would like to add?

**Comment by struggle3** [comment]
If I need checkbox,radio box group, pie, and bar, how can I better implement it

**Comment by unocelli** [comment]
If you agree, we can collaborate to add new controls. I would start by
implementing the chart bar...

**Comment by unocelli** [comment]
I will add the chart bar manager in the editor and preparing the components structure 'html-bargraph' in a branch 'bar-graph'.
you can contact me 4frango@gmail.com to not fill this issue with comments.

**Comment by AlexandruAndrei3** [comment]
Hello,
Same as @struggle3 I have been trying to insert a basic control object but I didn't manage to do that. Have you done any progress regarding this issue? I want to contribute by trying to add gauges from this library: https://nicolas-van.github.io/steelseries/. It would be helpful for me to have a better understanding on how should approach this issue or if I should try to add another section similar to how adding new shape sections works.

**Comment by unocelli** [comment]
OK, lets me try to add a basic control object so that you can define your own content and add as much as you like...

**Comment by struggle3** [comment]
At present, I have not successfully added the control




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月12日(星期五) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] fuxa how to customize controls (Issue #212)





 
Hello,
 Same as @struggle3 I have been trying to insert a basic control object but I didn't manage to do that. Have you done any progress regarding this issue? I want to contribute by trying to add gauges from this library: https://nicolas-van.github.io/steelseries/. It would be helpful for me to have a better understanding on how should approach this issue or if I should try to add another section similar to how adding new shape sections works.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IonuDragomir1** [comment]
Hello, @unocelli
As @struggle3 tried, I also want to add a new control. Do you have some sort of steps to be followed in order to successfully add a new control?
Following fuxa's html-select component example, what I did was to create a new component, to add it in editor.component.html, editor.component.ts and ext-bund;e.min.js. Now in browser's console I get this error:

> ERROR TypeError: Cannot read properties of undefined (reading 'theme')
>     at ProjectService../app/_services/project.service.ts.ProjectService.getLayoutTheme (project.service.ts:311)
>     at header.component.ts:55
>     at SafeSubscriber.schedulerFn [as _next] (core.js:3563)
>     at SafeSubscriber.push.../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:253)
>     at SafeSubscriber.push.../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:191)
>     at Subscriber.push.../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:129)
>     at Subscriber.push.../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:93)
>     at EventEmitter.push.../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next (Subject.js:53)
>     at EventEmitter.push.../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit (core.js:3535)
>     at ProjectService../app/_services/project.service.ts.ProjectService.notifyToLoadHmi (project.service.ts:487)

Many thanks in advance and please let me know if there is any other information I could provide!

**Comment by unocelli** [comment]
Hi, sorry for the delay.
You have to update the project. The error has nothing to do with creating a controller...is about black/white theme

**Comment by unocelli** [comment]
I added in the latest version the iframe control. you can follow in code.
