### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by sjimenez44** [frangoteam/FUXA#214]
Hello

I would like to contribute with the spanish translation.

**Comment by unocelli** [comment]
Yes! great! you are welcome...you know how?

**Comment by sjimenez44** [comment]
Is it creating a file to i18n? but I don't know how to test the translation

**Comment by unocelli** [comment]
If you look the issue #130 

You have to add in 'client/src/app/editor/app-settings/app-settings.component.ts' to 'languageType' array variable:
{ text: 'dlg.app-language-es', value: 'es' }

You have to compile the client:
`cd .\client`
if you don't have installed the node_modules by client
`npm install`
then
`ng build --prod`
