### ISSUE TITLE
Duplicated shape animation 

### ISSUE THREAD

**Issue by eyadalhanafi** [frangoteam/FUXA#226]
Hi,
If we duplicate a shape with animation, the duplicated shape doesn't have animation.

**Comment by unocelli** [comment]
Hi,
you mean that the actions values aren't copied? how you duplicate the shape with actions?

**Comment by eyadalhanafi** [comment]
I mean color change fill property. I tried both "duplicate element" and "copy & paste"

**Comment by unocelli** [comment]
![anim-clone](https://user-images.githubusercontent.com/48684550/143498278-cacc42d5-6fc1-44d8-b2a1-3ca38806877c.gif)

**Comment by eyadalhanafi** [comment]
Thank you for your efforts.
I meant by that general shape like rectangle. I configured fill property for that shape. Same shape duplicated, the fill property is not propagated to the duplicated shape.

**Comment by unocelli** [comment]
You mean the rectangle of **General** and not of **Shape**, I can reproduce it and will fix it as soon as possible.
Thanks

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
