### ISSUE TITLE
User should give project name instead of default "fuxa-project.json"

### ISSUE THREAD

**Issue by JohannesFriedrich** [frangoteam/FUXA#228]
Thanks for the great framework!

In my opinion the user should be given the choice to assign a project name and not save it by default in "fuxy-project.json".
Otherwise the user has to rename it on the drive manually.

**Comment by unocelli** [comment]
Hi, thanks,
I'm agree with you, I added to my todo list. Thanks

**Comment by unocelli** [comment]
This works in the latest version. let me know if you have any issues.
