### ISSUE TITLE
Strange grid behavior when zooming out

### ISSUE THREAD

**Issue by JohannesFriedrich** [frangoteam/FUXA#229]
To reproduce the behavior:

1. Add new view
2. Change property to e.g. 1920 x 1080
3. Activate grid

![image](https://user-images.githubusercontent.com/15369350/143450997-0f96dde5-39f1-467a-8a91-a7d49f1ab730.png)

4. deactivate grid
5. zoom out with ctrl + down
6. activate grid

![image](https://user-images.githubusercontent.com/15369350/143451139-607c6ba0-4a77-4a18-a324-15839ed4bd82.png)

**Comment by unocelli** [comment]
Hi, thanks for your report, I will investigate as soon as possible.
