### ISSUE TITLE
flex-variable component is not different with demo site

### ISSUE THREAD

**Issue by echolove38** [frangoteam/FUXA#231]
![xz1](https://user-images.githubusercontent.com/12425497/143975908-092ae6ce-bbc3-492a-afab-061a7722f555.png)
![xz2](https://user-images.githubusercontent.com/12425497/143975918-cef179a9-6b57-4391-ba56-69d069020908.png)
look at these two pics, the first( code downloaded from your github) have no device binding ui,
are you sure the github code is the newest code ?

**Comment by unocelli** [comment]
Hi, yes you're right the **demo is an old version** that I still have to update it. in any case, the current version is on the master branch

**Comment by echolove38** [comment]
> Hi, yes you're right the **demo is an old version** that I still have to update it. in any case, the current version is on the master branch

will you provide a uncompressed fuxa-editor.js，I want to extend something When need

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
