### ISSUE TITLE
Mulitpile device use same view

### ISSUE THREAD

**Issue by s001mtzniot** [frangoteam/FUXA#234]
Hi:
   This is a powerfaul solution, for embed to other it system, how can i set one view to reused for all same sensor, for examle, i create one view for one device ie. temputre A, But how user select device B(also is a tempure sensor) how to reuse the view?
thanks

**Comment by unocelli** [comment]
Hi,
You have to define a device as 'internal' and some variable (Tag) and bind it to the controls of reusable 'View' and than with events click to show the 'View' as 'Page', 'Dialog', 'Card' add context variable to bind: internal variable to device tag...I want to add an explanation in wiki as soon as possible.

**Comment by eyadalhanafi** [comment]
Further to the same point, we have 20 valves. We created one "Card" (faceplate) and define internal variables to bind with the actual valve tags. We are wonder how can we map Internal variable to none device Tag like Valve Name. Each card has a label for the Valve ID and some other texts that are unique for each valve.  Those changed based on the valve selection
Appreciate your efforts.

**Comment by unocelli** [comment]
Let me try to explain:
I defined a valves view and a valve dialog to configure
![image](https://user-images.githubusercontent.com/48684550/148057122-1aed3a07-5126-4fa1-bc75-994a16e8bd16.png)
![image](https://user-images.githubusercontent.com/48684550/148057183-e0f101c7-4629-4fd8-b921-bfad7c7abfd8.png)

I bind the 2 valves value to 2 Modbus tag
![image2](https://user-images.githubusercontent.com/48684550/148059195-6dbf7b3b-c1ea-4d93-a4da-226ea80d6441.gif)

I defined a internal 'device' with a variable (tag) for the title dialog and a variable for the input value and i bind the controls
![image](https://user-images.githubusercontent.com/48684550/148057908-fbcf4100-f0c3-4352-aee0-c0c6c6f9a2d0.gif)

I defined in Valves view the 2 valve shape the 'Events': 
- click to open the card with context variable and bonded the internal variable to the Modbus tag
- click to set value for the dialog title
![image3](https://user-images.githubusercontent.com/48684550/148059809-eefe51a1-1c99-4a09-a089-3d3b0967567c.gif)

You can define a dialog button to confirm the input value and close the dialog
![image4](https://user-images.githubusercontent.com/48684550/148060049-38d21b57-1ca7-4093-989b-7a61841dd6ab.gif)

You can use with key ENTER or with confirm button
![image5](https://user-images.githubusercontent.com/48684550/148060373-c3787eb0-04b8-4dd2-a607-bb48f5b06175.gif)

**Comment by eyadalhanafi** [comment]
Thank you so much.
