### ISSUE TITLE
Up and down animation works only once

### ISSUE THREAD

**Issue by burner-** [frangoteam/FUXA#236]
I add internal variable and add switch to set 0/1 value to it and then bind that piston thing to up&down animation to values. Then I try switch it on and of and then on again. It works only once but at second time it wont work. If I change animation type to clockwise it works each time.

**Comment by unocelli** [comment]
Hi, 
have you also added the stop animation for the value 0 ?

**Comment by burner-** [comment]
Yes. And with rotation animation it works as expected.

**Comment by burner-** [comment]
Oh sorry. I just notice that I had 1.1.0 version. I update to latest and it works. Sorry of wasting your time.
