### ISSUE TITLE
Import a list of tags Feature

### ISSUE THREAD

**Issue by cjmccoy2** [frangoteam/FUXA#240]
It would be great to import a list of tags from excel. This would make this process much more efficient.

Device, Tag Name, Address
![image](https://user-images.githubusercontent.com/88991771/147367062-7fa72ec4-d11b-4467-817b-4a5c02139709.png)

Great work so far!

**Comment by unocelli** [comment]
hi, I think it is a good idea, but from a csv file and not from excel

**Comment by unocelli** [comment]
Hi,
I added the feature, let me know if you have any issues.

**Comment by Kortenbach** [comment]
Wow, that's a great addition! Will look into it next week.
BTW, (off topic) is there some way to make a graph of measurements that are like 4 weeks old? Can Grafana be used with FUXA?

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
