### ISSUE TITLE
Cant browse mqtt topics in latest version

### ISSUE THREAD

**Issue by thingstanje** [frangoteam/FUXA#242]
Today i run the fuxa docker edition with latest edition. Doing the same setup for my mqtt driver, I cant browse the topics like i did last friday on version v1.1.3. Its working perfectly in v1.1.3 docker edition

How to pull the docker edition of v.1.1.3?

**Comment by thingstanje** [comment]
![image](https://user-images.githubusercontent.com/97078598/148015311-ea84f573-3fd7-43f1-bf26-3beb3700c00b.png)

**Comment by thingstanje** [comment]
The above image is appeared when i use v.1.1.3

**Comment by thingstanje** [comment]
> The above image is appeared when i use v.1.1.3

**Comment by unocelli** [comment]
I have just tested it without any issues.
you have some error in browser console or in server logs?

**Comment by thingstanje** [comment]
Problem was due to my internet connection. sorry for inconvenience

**Comment by thingstanje** [comment]
Dear unocelli,
I checked again this morning. Unfortunately I cant browse the mqtt topics again. No error displayed from fuxa runtime. I tried both local VM & VPS at vultr. both not working. 
I run on docker environment latest edition.
How to run v1.1.3 on docker ?

**Comment by unocelli** [comment]
with which version are you having problems?

**Comment by thingstanje** [comment]
v1.1.4 run docker edition.

**Comment by unocelli** [comment]
can you try the npm version 1.1.4 ?

**Comment by thingstanje** [comment]
Okey. I’ll try this morning. Do you have a step on how to make it as docker
container?

**Comment by unocelli** [comment]
No, I'm sorry.
new in docker version 1.1.4 is that I build a image for more OS/ARCH and npm does it.

**Comment by MikeEitel** [comment]
In node-red dashboard clearing browser cache helps..

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
