### ISSUE TITLE
document persistent storage

### ISSUE THREAD

**Issue by burner-** [frangoteam/FUXA#247]
Can you document docker persistent storage path and maybe add them to samples. That will help updates.

**Comment by unocelli** [comment]
Hi, so you leave application data (project), daq (tags history) and logs as persistent storage:

`sudo docker run -d -p 1881:1881 -v fuxa_appdata:/usr/src/app/FUXA/server/_appdata -v fuxa_db:/usr/src/app/FUXA/server/_db -v fuxa_logs:/usr/src/app/FUXA/server/_logs  frangoteam/fuxa:latest`
