### ISSUE TITLE
ODBC Data Source in Fuxa

### ISSUE THREAD

**Issue by eyadalhanafi** [frangoteam/FUXA#248]
Hi; 
Suggestion to have ODBC data source connection in Fuxa that can be used to monitor real time data from any ODBC data source, including Microsoft Access Databases and Excel Spreadsheets.

**Comment by unocelli** [comment]
Hi,
Interesting... but not currently a high priority

**Comment by MatthewReed303** [comment]
@eyadalhanafi Fuxa now has ODBC check out the Wiki https://github.com/frangoteam/FUXA/wiki/HowTo-ODBC
