### ISSUE TITLE
为什么不升级为最新的NPM ，boss

### ISSUE THREAD

**Issue by sunxiaotianmg** [frangoteam/FUXA#249]
为什么不升级为最新的NPM ，boss

**Comment by unocelli** [comment]
?

**Comment by lake518j** [comment]
为什么不升级为最新的NPM ，boss
---------- translate :
why not upgrade NPM to the new version ?

**Comment by unocelli** [comment]
Hi,
in npm you have the released version, if you will play with the latest you have to pull from github the master branch
