### ISSUE TITLE
Embed iframe directly to canvas

### ISSUE THREAD

**Issue by dsepulvedar** [frangoteam/FUXA#250]
Is it possible (or maybe will it be possible) to embed an iframe directly into the canvas? 
As of today, one can load an iframe through the on-click event option of a general shape but not directly into de canvas. 

I'll appreciate if anyone could shade some light into this.

**Comment by harli91** [comment]
it should be possible to copy all the elements from a view to another view

**Comment by unocelli** [comment]
Hi,
@dsepulvedar interesting feature, need to be investigated because the iframe would be inserted  in `<foreignObject>` svg element.
@harli91 select the elements / CTRL-C / CTRL-V

**Comment by unocelli** [comment]
This works in the latest version. let me know if you have any issues.
