### ISSUE TITLE
hi, how to stop animate

### ISSUE THREAD

**Issue by echolove38** [frangoteam/FUXA#251]
About the animation type element
I set an action with runs when ranges 20~80,  
firstly I give a value 60, it start animate,
after a while , I give a value 1000, the animate still exist, 
so how to stop the animate
![image](https://user-images.githubusercontent.com/12425497/149057903-a4e7fb24-ac7c-4fe3-8d1b-dc7188fbeed0.png)

**Comment by unocelli** [comment]
Hi,
you have to configure the 'stop' action, for example in the range 80~2000

**Comment by echolove38** [comment]
> 
I don't think this is a good thinking, It should stop when out of the given range

**Comment by unocelli** [comment]
you have to see like a trigger that start a job, the stop is more like a reset...it could be interesting when in the future there will be more animations and you want to combine them...

**Comment by unocelli** [comment]
This works in the latest version. let me know if you have any issues.
