### ISSUE TITLE
how add controls lad this to projact 

### ISSUE THREAD

**Issue by AbdalaMask** [frangoteam/FUXA#252]
![image](https://user-images.githubusercontent.com/37013638/149074010-ed37ed7c-0573-40ff-ad19-465fa45b4885.png)
to /
FUXA

**Comment by unocelli** [comment]
Hi,
I suppose there are on/off images and you can use with actions hide and show

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
