### ISSUE TITLE
How to increase the connection type of a device

### ISSUE THREAD

**Issue by jcxjcx123** [frangoteam/FUXA#258]
Hello,I want to know  how to increase the connection type of a device，could you give some help?

**Comment by unocelli** [comment]
Hi,
you have to look the other device and the sample [template]https://github.com/frangoteam/FUXA/tree/master/server/runtime/devices/template) in server side and add the it in DeviceType in [frontend](https://github.com/frangoteam/FUXA/blob/master/client/src/app/_models/device.ts)

**Comment by jcxjcx123** [comment]
I also want to ask, when my computer ID address changes, the project cannot be started, what should I do，thanks a lot

**Comment by unocelli** [comment]
Sorry for the delay,
the error message from the server?

**Comment by jcxjcx123** [comment]
Yes, because my IP address has changed,  it's reported an error when I started the project. OPCUA can't connect to the server,and i don't known how should i do

**Comment by unocelli** [comment]
can you send me the error reported?

**Comment by jcxjcx123** [comment]
This is an error message  ‘2022-01-24T07:10:23.253Z [WAR]  'opcua' working (connection || polling) overload!   ‘

**Comment by jcxjcx123** [comment]
2022-01-24T07:11:00.808Z [ERR]  'opcua' connect failure! Error: The connection may have been rejected by server,
Err = (connect ETIMEDOUT 172.16.33.xxx:xxxxx)

**Comment by unocelli** [comment]
that you have changed the IP of the machine where fuxa is located should not play any role.
I suppose that you have tried to connect the server with an other client?

**Comment by unocelli** [comment]
Since there has been no answer to the question above, I'm assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
