### ISSUE TITLE
Script possibility ?

### ISSUE THREAD

**Issue by ffred** [frangoteam/FUXA#260]
Hello,
just discovered FUXA and it looks great !
I saw a few messages about an eventual script possibility. did you progress on it ?
is there some kind of roadmap somewhere, about what could already be on your future TODO list..?
thanks !

**Comment by unocelli** [comment]
Hi, thank you for your interest.
yes script is an important feature and I would like finally start with this, I have some ideas how to have to look. 
I have a todo list but not a roadmap. I'm going by inspiration and motivation. However, I believe that fuxa should maintain a certain simplicity ;-)

**Comment by ffred** [comment]
Ok, thanks..!
