### ISSUE TITLE
import svg

### ISSUE THREAD

**Issue by patson12** [frangoteam/FUXA#261]
Hello,

i am going to import svg but installing in my local pc it doenst work as it works in your site.. have i miss anything?
some svg in not import properly .. just half part of svg imports.. also i cant chaange the color of svg...group ungroup not working only border stroke color can be change...

thanks in advance

**Comment by unocelli** [comment]
Hi,
can you send me the svg file please?

**Comment by patson12** [comment]
plz find attchment. group and ungroup is not working after importing this file..i this in github some old code thant that in your live project .. i have downloaded code from github latest version but color change also not working in local pc.. if there is another code , can you plz upload this??

thanx .. :)
![svg](https://user-images.githubusercontent.com/96180028/151288653-2b9cb005-794c-4f80-8510-7fa861056b2d.svg)

**Comment by unocelli** [comment]
I don't know what you are trying to do, but currently imported svg images or grouped shapes don't support the set colors by logic, you can use the FUXA shapes, configure the logic and then group them.

**Comment by patson12** [comment]
imported svg support set color in fuxa demo link.. but not working in github latest code. . can you share latest code which is in demo site..

thank you...

**Comment by unocelli** [comment]
Hi,
yes I was able to reproduce the color issue, I have to investigate.
regarding the image where a piece is missing, check that you do not have any other images on front, add it in a new view.
can you tell me your os and browser used?

**Comment by patson12** [comment]
it is svg. there is no any other images on front.. added in a new view. find screenshot.. 
os:- windows 10.
browser : ch
![Capture123](https://user-images.githubusercontent.com/96180028/151519634-94322c3c-9463-4599-8fc0-89a16139eeb9.PNG)
rome

**Comment by unocelli** [comment]
This is from my local pc with the last master version.
![image](https://user-images.githubusercontent.com/48684550/151522295-0ded7288-3618-4494-b1a5-0d5c2f4bd2f0.png)

The demo code is in [frangoteam/www](https://github.com/frangoteam/www)

**Comment by patson12** [comment]
given demo code link is not working.. :(.. can you send me back?
and thank you so much for your help.. :)

**Comment by unocelli** [comment]
Sorry,
The demo code is in [demo](https://github.com/frangoteam/frangoteam.github.io)

**Comment by patson12** [comment]
my problem is solved .. thank you so much ...

**Comment by patson12** [comment]
did something i miss?
after ungroup element i found thi
![Capturesfsf](https://user-images.githubusercontent.com/96180028/151530268-507ce552-01b1-4f1c-8ff7-3d8880a01a9f.PNG)
s

**Comment by unocelli** [comment]
i suppose with the old demo library? happens on all group and ungroup images? try to clear the browser cache

**Comment by patson12** [comment]
now it is working fine.. i have updated all new files..
