### ISSUE TITLE
Alarm details

### ISSUE THREAD

**Issue by patsonkaushik** [frangoteam/FUXA#262]
i want to know how alarm will work.. its not working in my pc..

**Comment by unocelli** [comment]
This is not a report of a issue! Please describe better...
I suppose you have already look the [wiki](https://github.com/frangoteam/FUXA/wiki/HowTo-setup-Alarms), is old but give you a idea what you have to do...

**Comment by unocelli** [comment]
I don't know what you are trying to do, but currently imported svg images or grouped shapes don't support the set colors by logic, you can use the FUXA shapes, configure the logic and then group them.
