### ISSUE TITLE
Allen Bradley EthernetIP

### ISSUE THREAD

**Issue by Scolari** [frangoteam/FUXA#263]
I'm unable to obtain any data from a 1769-L30ER Compactlogix using the EthernetIP Driver.
I don't get an error in the connector using xxx.xxx.xxx.xxx:44818 but none of the tags I add retrieve any data.
Please Help!

**Comment by unocelli** [comment]
Hi,
look at #118 and [AlexCastro-Prog video](https://www.youtube.com/watch?v=iTz7ryccLWw) maybe can help you.

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
