### ISSUE TITLE
Button settings - Actions

### ISSUE THREAD

**Issue by isalogi** [frangoteam/FUXA#276]
Hi all, 

Can you please let me how the following actions should work when clicking a button? 

* Open card
* Toggle value 
* Set from input 
* Close

![image](https://user-images.githubusercontent.com/33707540/154767482-e772a186-dc22-4e20-b747-7f0d2686a6cf.png)

Thanks!

**Comment by unocelli** [comment]
Hi,
I have updated [HowTo configure events](https://github.com/frangoteam/FUXA/wiki/HowTo-configure-events)
