### ISSUE TITLE
Shape fill color after blink action stopped.

### ISSUE THREAD

**Issue by daisuke0604** [frangoteam/FUXA#278]
When I set the data in the following order with the below settings, 
I want it to be gray at the end, but it does not change from red.

test1 = 1   : Filled with gray (OK)
test1 = 100 : Filled with red (OK)
test1 = 50  : Blink start (OK)
test1 = 100 : Blink stop and filled with red (OK)
test1 = 1   : Filled with red (NG)

This only happens when blinking, not when rotating.
I'm running Version 1.1.5-625 on docker.

Settings:
![2022-02-22 10-09-40](https://user-images.githubusercontent.com/5103426/155046259-796d0d61-751d-460a-9fb2-36bd9cf7c295.png)
![2022-02-22 10-10-11](https://user-images.githubusercontent.com/5103426/155046266-25792589-e921-4196-8dd0-ae8be3b0ead2.png)

**Comment by unocelli** [comment]
Hi, thanks for the report, I have to fix it.

**Comment by unocelli** [comment]
Let me know if something doesn't work as expected
