### ISSUE TITLE
how to get list array of all object ...

### ISSUE THREAD

**Issue by harshad89** [frangoteam/FUXA#279]
Dear FUXA developers,
i want list of all object which is in view-window in an array but
i got all which are also deleted .. i would get only elements which are on view ..
please find the attachment..and code..

Kind regards
```
openEditGauge(settings, callback) {
```
    let tempsettings = JSON.parse(JSON.stringify(settings));
    let hmi = this.projectService.getHmi();
    let dlgType = GaugesManager.getEditDialogTypeToUse(settings.type);
    let eventsSupported = this.isWithEvents(settings.type);
    let actionsSupported = this.isWithActions(settings.type);
    let defaultValue = GaugesManager.getDefaultValue(settings.type);
    console.log("gs111",this.currentView.items)
    let names = Object.values(this.currentView.items).map((gs) => gs.name);
    let names_id = Object.values(this.currentView.items).map((gs) => gs.name+"("+gs.id+")");
    // set default name
    if (!tempsettings.name) {
      tempsettings.name = Utils.getNextName(
        GaugesManager.getPrefixGaugeName(settings.type),
        names
      );
    }
```
```

![CaptureSCsc](https://user-images.githubusercontent.com/16508617/155125309-4fb46fab-c158-48e2-92fc-b494dcd6cfdf.PNG)
![Capture](https://user-images.githubusercontent.com/16508617/155521271-6252d00a-af77-4216-a3d7-0c2010bfc4e2.PNG)

**Comment by unocelli** [comment]
Hi, thanks for the report. I have to fix it by cleaning the list.

**Comment by unocelli** [comment]
Hi, I'm try to reproduce the issue without success. it is possible that this happens because you are debugging?

**Comment by unocelli** [comment]
is available in the latest version (although it is still not perfect)
