### ISSUE TITLE
"Userack" is not working properly

### ISSUE THREAD

**Issue by AutomationDummy** [frangoteam/FUXA#280]
Hi,

User acknowledgement is not pushing the user value into database, here is the sample images.

![image](https://user-images.githubusercontent.com/99320798/155321743-a4e38e50-44d3-4804-8bc3-29e1c3fa716b.png)

![image](https://user-images.githubusercontent.com/99320798/155321980-fe4639d1-8b1d-4cf2-8988-dbc6f2938522.png)

**Comment by unocelli** [comment]
Hi, thanks for the report. I have to fix it.

**Comment by unocelli** [comment]
Let me know if something doesn't work as expected
