### ISSUE TITLE
Limitation with Input Value control

### ISSUE THREAD

**Issue by frostpun** [frangoteam/FUXA#281]
"Output value" can be any data type, even String, but "Input value" only works with numerical data. Is there a way to set from input string instead of only numbers?

**Comment by unocelli** [comment]
Hi,
which version you are using and what type of device and tag you have tried?

**Comment by frostpun** [comment]
FUXA V.1.1.4-623
the device is an opc ua server created on my local computer, I can change the string tag remotely from my computer but when I try to use FUXA, the input value control is only accepting pushing a numerical string when I push a button to set from input.

**Comment by unocelli** [comment]
You have some error message in backend or frontend?
![input-string](https://user-images.githubusercontent.com/48684550/155944090-7fcf242d-04f9-473e-8017-de11a1346fa9.gif)

**Comment by frostpun** [comment]
no there are no errors, I am able to change the value to either numerical or string from my computer and from FUXA if the button is set, but not set from input

https://user-images.githubusercontent.com/96480690/155978614-3f3973f8-0d10-47ff-a1cd-e1d3e3ea4c1f.mp4

**Comment by unocelli** [comment]
Thanks for the report. I will fix it
