### ISSUE TITLE
Modbus RT over serial

### ISSUE THREAD

**Issue by stovesy** [frangoteam/FUXA#282]
I have installed the modbus plugin, and receive the 'Modbus' connect failed Error Could not locate the bindings file.
Then a list of places to search for the bindings.node file.

I have done npm install serialport

I have no idea what a bindings.node file is..

Thanks.

**Comment by unocelli** [comment]
Hi,
please, report of which version you are using.

**Comment by stovesy** [comment]
Fixed.
npm install modbus-serial
