### ISSUE TITLE
A bug when ungroup a shape

### ISSUE THREAD

**Issue by khajegan** [frangoteam/FUXA#29]
In editor page when i use a Proc.Eng shape like 'motor-simb', and after i click on ungroup option, the forecolor and backcolor of the shape automaticcaly sets to black.

**Comment by unocelli** [comment]
Thanks khajegan,
I will fix it by disabling the ungroup button by selecting a ‘Controls’ or a ‘Proc. Eng.’ shape.

**Comment by khajegan** [comment]
Dear unocelli
Please don't do that , i want ungroup capability for 'Proc. Eng' or any complex shape. please fix it.
Thanks

**Comment by unocelli** [comment]
Dear khajegan,
would you explain to me what is your goal by trying to ungroup this shape?
These shapes are built as groups and have an attribute in order to be identified, if you try to ungroup and group again the shape loses the attribute (I can't distinguish that I'm groupping again a old shape).
The feature to creating your own shapes library is planned but later.

Regards

**Comment by khajegan** [comment]
Dear unocelli
I want to use my own complex shape as svg file like your 'Proc. Eng' (i could do that by using your import function), and our users may want to change these shapes as they want or maybe they want to ungroup these shapes and then group some parts of them and create another complex shape.

**Comment by unocelli** [comment]
Dear khajegan,
of course you will be able to ungroup and group again your complex shape, composed with a 'Proc. Eng' shape.
As explained you can not ungroup the only 'Proc. Eng' shapes alone...Let's discuss again after my modification.

Regards

**Comment by khajegan** [comment]
Dear unocelli
Thanks , please tell me after you're done.
Please add another new options to add own complex shape as SVG, more easier than this.
Thanks a lot

**Comment by ATwins-8** [comment]
Indeed, we all want to add our own SVG. I try to drag my own SVG from the mat expansion panel tag to the canvas, but it will fail. Do you want to change the function svgeditor. Addextension () in ext-bundle.min.js? Thank you for your reply!

**Comment by unocelli** [comment]
Hi,
It's planned to create the possibility to import your own Shapes and Gauges. But I can't provide the exact date. I opend a new issue #41 and I will work with it soon.

**Comment by unocelli** [comment]
Fixed:  ungroup a control or shape is prevented
