### ISSUE TITLE
Error in S7 conection has misspelled tags

### ISSUE THREAD

**Issue by AgrisNN** [frangoteam/FUXA#291]
Dear FUXA team,

FUXA V.1.1.5-625

There's a bug with variables update when you have misspelled tag
![image](https://user-images.githubusercontent.com/101255573/157423882-73cd46ab-3f2c-49ff-8c65-1b8b5240c9ec.png)

On picture below you may see tag "M0.1" which works great when this is an only tag in list
![image](https://user-images.githubusercontent.com/101255573/157426051-bed6409f-2f33-4aeb-83df-39ba1462034c.png)

Once you add some tag which is NOT in correct, situation goes wrong.
a: previously working tags in list break their updates and NOT pulling correctly and seem to stuck.
b: error log "fuxa-err.log" becomes full of messages
```
2022-03-09T10:39:47.198Z [error] TypeError: this._getErr is not a function
     at /home/pi/FUXA-1.1.5/server/runtime/devices/s7/index.js:430:38
```
c: list of connections displays status: "Busy" periodically, or always, or sometimes.
d: Save Project button occasionally results "Project save failed". 

P.S.
By the way, when pressing "Save Project" in Editor mode, no pop-up appears at all so you may non be sure the project got saved.

**Comment by unocelli** [comment]
Hi, Thanks for the report. I need to add the input verification...

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
