### ISSUE TITLE
svgeditor  opensource

### ISSUE THREAD

**Issue by VansirCQ** [frangoteam/FUXA#297]
The files under svgeditor are basically processed in binary. Is it necessary to add SVG through this editor component? Can the source code of this part be open source? I want to add a custom SVG component to FUXA. Do you have any questions? any suggestion, thanks a lot
![image](https://user-images.githubusercontent.com/37134815/158100718-41c3d788-f924-4455-9996-a5f707fbe087.png)

![image](https://user-images.githubusercontent.com/37134815/158101288-abd25f48-0d6d-4cdb-acce-4a2b64f56aa2.png)

At the same time, I also noticed that your team also provides open source svgedit. I don’t know how this open source project is related to the binary files in my screenshots. Is FUXA completely open source?  thanks a lot ~

**Comment by VansirCQ** [comment]
> 
emmmm..... " example how I added the iframe control ", where is it?  
When I see an issue in 2019, you want to open source this fuxaeditor. It seems that fuxa fans have been waiting too long. Hahaha, when can you open source it? Let's improve it together

**Comment by unocelli** [comment]
I accept the criticism...I wonder how you plan to help me if you haven't understood how to add your own control just by looking in the code :wink:

**Comment by xiaote0225** [comment]
@unocelli Hi unocelli,I also have the same questions?1.How to add your own control in FUXA? Is there any document or video？2.When do you want to or  plan to publish fuxa-editor? 

Looking forward to your reply.

**Comment by unocelli** [comment]
fuxa-editor is [svg-edit](https://github.com/SVG-Edit/svgedit) packaged to work with angular.

**Comment by concept10** [comment]
> @unocelli Hi unocelli,I also have the same questions?1.How to add your own control in FUXA? Is there any document or video？2.When do you want to or  plan to publish fuxa-editor? 
> 
> 
> 
> Looking forward to your reply.
It took me a couple of weeks of digging in the code, but building components are not difficult, especially with all of the Angular examples out there. 

It's really not that difficult to follow and duplicate what's already there. The SVGEditor source alone will not get you anywhere.

**Comment by xiaote0225** [comment]
Hi Tracey,thanks for you answer.
Our urgent requirement is to extend the echarts chart into fuxa.
You mean that I can integrate echarts by looking at the existing code in the Fuxa project, right?

发自我的iPhone

**Comment by concept10** [comment]
@xiaote0225 I was looking to accomplish the same a few weeks back but took another route. I'm going to give it another shot.

**Comment by unocelli** [comment]
An example: the Bar graph control was added without modifying the editor library. ![image](https://user-images.githubusercontent.com/48684550/219179615-75bfbb1c-f8d9-4e5b-939d-31934480d437.png)

**Comment by xiaote0225** [comment]
Thank you very much.It means that I can insert a echarts control in FUXA follow the bar graph control without modify the editor library，right？

发自我的iPhone

**Comment by xiaote0225** [comment]
> 

@concept10 , Could you specify your idea. Maybe we can cooperate to achieve this goal.

**Comment by unocelli** [comment]
Yes, you can

**Comment by xiaote0225** [comment]
@unocelli Hi, guy,I am viewing code related to socket.io. I feel that the logic of this block of data processing code is complex. Do you have any good suggestions.

**Comment by unocelli** [comment]
Hi, to add your own control, you must not use or modify anything related to socket.io
