### ISSUE TITLE
Internal Plugin is missing 

### ISSUE THREAD

**Issue by eyadalhanafi** [frangoteam/FUXA#300]
Thank you for your support.
 
When i created Internal device plugin, I got the below warning message 
[WAR]  try to create LocalTags but plugin is missing!

Fuxa version: 1.1.5-642

**Comment by unocelli** [comment]
Hi,
I don't understand, you don't create internal device plugin, you install the plugin? which one?

**Comment by eyadalhanafi** [comment]
In connections, i created a device type "internal". I defined device tags.
when run the application i started getting a warning "Plugin is missing"
hope it is clear now.

**Comment by unocelli** [comment]
Hi,
Yes, I can reproduce it, the warning message is wrong because the internal device is only in frontend (don't need plugin). I will fix it...Thanks

**Comment by unocelli** [comment]
Let me know if something doesn't work as expected
