### ISSUE TITLE
How to switch between two multi views containers and how to open a card on a position specified by user?

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#304]
Hello!

I've run some tests and I found the following issues:
1. I can't switch between two multi views containers. For example, I have two  multi views containers (MVC1 and MVC2) and a Canvas/SVG view. I can't switch directly from MVC 1 to MVC2. To do so I must switch from MVC1 to Canvas/SVG view and then to MVC2.
2. If I open a card when pressing a button, it opens on a random position. How could I open the card on a position specified by user?
3. I have seen in [your example](https://github.com/frangoteam/FUXA/wiki/HowTo-use-same-view) that I can use the same view on different objects. Your example is working fine because you close Valve A card and then open Valve B card.  If you'd open Valve B card while Valve A card is opened, the text "Settings Valve A" is replaced with "Settings Valve B".  
Many thanks in advance!

**Comment by unocelli** [comment]
Hi, thanks for the report.
1. is a bag that I have to fix.
2. and 3.  are new features, they are not implemented.
I would appreciate if you could separate the 3 issues so that they are clearer to manage.

**Comment by unocelli** [comment]
#306 #307 #308
