### ISSUE TITLE
Chart control problem

### ISSUE THREAD

**Issue by lifeihub** [frangoteam/FUXA#305]
Hello, I hope you have time to optimize this control
![image](https://user-images.githubusercontent.com/87174373/159442740-c7bc85e5-6c18-4317-89dd-d2e980027c70.png)
Hello, can you optimize the chart control? When the control is zooming in and out, there will be adaptive problems. The font has no adaptive size, and the most important thing is that the curve will be lost in the control. I hope you can optimize it when you have time. Thank you very much and look forward to your reply.
![image](https://user-images.githubusercontent.com/87174373/159440844-01f9360e-667c-4590-a273-b68de2a2abb8.png)

**Comment by lifeihub** [comment]
Hello, I hope you have time to optimize this control
![image](https://user-images.githubusercontent.com/87174373/159442740-c7bc85e5-6c18-4317-89dd-d2e980027c70.png)

**Comment by unocelli** [comment]
Hi, sorry for the delay.
what do you propose, I can't change the font, maybe we can limit the zoom?

**Comment by lifeihub** [comment]
> 你好，抱歉耽搁了。 你有什么建议，我不能改变字体，也许我们可以限制缩放？

Well, first of all, thank you for your reply. I think the way to change is to introduce three-party chart controls. At present, this adaptive situation can not meet the demand. If you have a better method, I look forward to your reply. Thank you again.

**Comment by unocelli** [comment]
I think uplot is light, simple and performant, a good compromise for an application like fuxa. 
I am open to other suggestions but I don't have resource.
