### ISSUE TITLE
Bugs in imported views

### ISSUE THREAD

**Issue by jcxjcx123** [frangoteam/FUXA#309]
Hi!
I found a problem, I exported a view yesterday and I wanted to import it into the project today, but when I imported it, I found that the view did not display correctly and the view window kept flashing, is this a BUG?
![动画](https://user-images.githubusercontent.com/41283780/159648909-da11c9c2-fd41-4766-b2bd-c282edaf3a5f.gif)

**Comment by unocelli** [comment]
Hi,
I can't reproduce it...It's the issue in the view that you have exported? can you share me?

**Comment by jcxjcx123** [comment]
hi,
ok,sure,thanks for your help.
[josn.txt](https://github.com/frangoteam/FUXA/files/8359329/josn.txt)

**Comment by jcxjcx123** [comment]
ok,sure.
thanks for your help.
[josn.txt](https://github.com/frangoteam/FUXA/files/8359334/josn.txt)

**Comment by unocelli** [comment]
I think that the problem is that you will import a view but you give a project file. 
Export a view:
![image](https://user-images.githubusercontent.com/48684550/160892016-ce498149-c3cf-4419-b288-8f67c7e6d014.png)

**Comment by unocelli** [comment]
Yes, the name is fuxa-view.json and not fuxa-project.json how you show in the first comment

**Comment by jcxjcx123** [comment]
Oh! Sorry,I's my mistake,I imported a project file instead of a view file. I also have a question. I noticed that the SVG shapes code in Fuxa was very short and rendered very well, but the graphics I exported with Inkscape tended to be very complex and very long. So I would like to ask you what tools you usually use to draw SVG shapes?

**Comment by unocelli** [comment]
It depends, I also use inkscape, which is full featured, for simpler things I use [diagrams.net](https://www.diagrams.net/).

**Comment by jcxjcx123** [comment]
Thank you very much for your answer Sir
