### ISSUE TITLE
how to change the svgeditor' language

### ISSUE THREAD

**Issue by nulIptr** [frangoteam/FUXA#31]
I find some templete in client\src\app\editor\editor.component.html named `svginfo_lang`
`<label>
          <span id="svginfo_lang">Language:</span>
          
          <select id="lang_select">
            <option id="lang_ar" value="ar">العربية</option>
            <option id="lang_cs" value="cs">Čeština</option>
            <option id="lang_de" value="de">Deutsch</option>
            <option id="lang_en" value="en" selected="selected">English</option>
            <option id="lang_es" value="es">Español</option>
            <option id="lang_fa" value="fa">فارسی</option>
            <option id="lang_fr" value="fr">Français</option>
            <option id="lang_fy" value="fy">Frysk</option>
            <option id="lang_hi" value="hi">&#2361;&#2367;&#2344;&#2381;&#2342;&#2368;, &#2361;&#2367;&#2306;&#2342;&#2368;</option>
            <option id="lang_it" value="it">Italiano</option>
            <option id="lang_ja" value="ja">日本語</option>
            <option id="lang_nl" value="nl">Nederlands</option>
            <option id="lang_pl" value="pl">Polski</option>
            <option id="lang_pt-BR" value="pt-BR">Português (BR)</option>
            <option id="lang_ro" value="ro">Română</option>
            <option id="lang_ru" value="ru">Русский</option>
            <option id="lang_sk" value="sk">Slovenčina</option>
            <option id="lang_sl" value="sl">Slovenščina</option>
            <option id="lang_zh-TW" value="zh-TW">繁體中文</option>
          </select>
        </label>`
but it don't work,and there's only 'client\src\assets\lib\svgeditor\fuxa-editor.min.js',I can't read it,may I have the source code?

**Comment by unocelli** [comment]
Hi nullptr,
you're right Internationalization (i18n) is missing, I added the issue that I will try to implement as soon as possible

best regards

**Comment by ATwins-8** [comment]
Hello! Unocelli. Why can't I find the SetColor function in this.winref.nativewindow.svgeditor during initialization? Console error: this.winref.nativewindow.svgeditor.setcolor is not a function? It seems very unstable

**Comment by unocelli** [comment]
Hi,
where do you have this problem, in FUXA_master or in your application?
if it is in your application you have added fuxa-editor.min.js to your
start page 'index.html'
    <script src="assets/lib/svgeditor/fuxa-editor.min.js"></script>

Il giorno sab 16 nov 2019 alle ore 04:08 ATwins <notifications@github.com>
ha scritto:

**Comment by ATwins-8** [comment]
The start page 'index. HTML' already exists, but if I add the dependency of node package in "scripts" in the. Angular-cli.json file, an error will be reported. However, during the first initialization, an error typeerror is reported: cannot read property 'SetColor' of undefined. Just execute this function for the second time.

**Comment by unocelli** [comment]
Hi,
I know that if you add in angular-cli.json an error will be reported.
You can try anyway to add in your start page and tell me if it worked?
You have to add in index.html the following dependencies (like in
FUXA\client) which are necessary for the editor:

    
    <link rel="stylesheet"
href="assets/lib/svgeditor/jquery-plugin.min.css">

    <link rel="stylesheet"
href="assets/lib/svgeditor/extensions/ext-html_button.min.css">
    <link rel="stylesheet" href="assets/lib/svgeditor/svg-editor.min.css">
    <link rel="stylesheet" href="assets/lib/ext-styles.css">

    
    <script src="assets/lib/svgeditor/jquery.min.js"></script>
    <script
src="assets/lib/svgeditor/jquery-ui-1.8.17.custom.min.js"></script>
    <script src="assets/lib/svgeditor/jquery-plugin.min.js"></script>

    <script src="assets/lib/dygraphs/dygraph-combined.js"></script>
    <script src="assets/lib/dygraphs/dygraph-extra.js"></script>
    <script src="assets/lib/dygraphs/dygraph-synchronizer.js"></script>

    <script
src="assets/lib/svgeditor/extensions/ext-markers.min.js"></script>
    <script
src="assets/lib/svgeditor/extensions/ext-bundle.min.js"></script>

    <script src="assets/lib/svgeditor/fuxa-editor.min.js"></script>

    <script src="assets/lib/svg/svg.min.js"></script>
    <script src="assets/lib/svg/raphael.min.js"></script>





Il giorno gio 21 nov 2019 alle ore 02:55 ATwins <notifications@github.com>
ha scritto:

**Comment by ATwins-8** [comment]
I've removed the dependency package in the angular-cli.json file and included all the import files you mentioned in the index.html file. However, ERROR TypeError: Cannot read property 'setColor' of undefined in the first load

**Comment by unocelli** [comment]
Hi,
can you send me the source code?

Il giorno mar 26 nov 2019 alle ore 08:00 ATwins <notifications@github.com>
ha scritto:

**Comment by ATwins-8** [comment]
`<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="assets/lib/svgeditor/jquery-plugin.min.css">

    <link rel="stylesheet" href="assets/lib/svgeditor/extensions/ext-html_button.min.css">
    <link rel="stylesheet" href="assets/lib/svgeditor/svg-editor.min.css">
    <link rel="stylesheet" href="assets/lib/ext-styles.css">

    
    <script src="assets/lib/svgeditor/jquery.min.js"></script>
    <script src="assets/lib/svgeditor/jquery-ui-1.8.17.custom.min.js"></script>
    <script src="assets/lib/svgeditor/jquery-plugin.min.js"></script>


    <script src="assets/lib/dygraphs/dygraph-combined.js"></script>
    <script src="assets/lib/dygraphs/dygraph-extra.js"></script>
    <script src="assets/lib/dygraphs/dygraph-synchronizer.js"></script>

    <script src="assets/lib/svgeditor/extensions/ext-markers.min.js"></script>
    <script src="assets/lib/svgeditor/extensions/ext-bundle.min.js"></script>
    
    

    <script src="assets/lib/svgeditor/fuxa-editor.min.js"></script>


    <script src="assets/lib/svg/svg.min.js"></script>
    <script src="assets/lib/svg/raphael.min.js"></script>
    
    <script src="assets/lib/echarts.min.js"></script>
  </head>
  
  <body>
    <app-root>Loading...</app-root>
  </body>`

Console error：
core.js:1440 ERROR TypeError: Cannot read property 'setColor' of undefined
    at EditorComponent.setFillColor (editor.component.ts:500)
    at EditorComponent.onSelectView (editor.component.ts:798)
    at EditorComponent.loadHmi (editor.component.ts:243)
    at eval (editor.component.ts:121)
    at SafeSubscriber.schedulerFn [as _next] (core.js:4331)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:239)
    at SafeSubscriber.next (Subscriber.js:186)
    at Subscriber._next (Subscriber.js:127)
    at Subscriber.next (Subscriber.js:91)
    at EventEmitter.Subject.next (Subject.js:56)


The reported file error is in editor.component.ts
`    private setFillColor(event) {
        let color = event;
        if (color.charAt(0) === '#')
            color = color.slice(1);
        let alfa = 100;
        this.winRef.nativeWindow.svgEditor.setColor(color, alfa, "fill");
        // this.fillcolor;
    }`

**Comment by unocelli** [comment]
Hi,
I think is a synchronization problem: the callback from server that enable
the frontend to load the project (loadHmi) and the svgEditor that it's not
ready yet. I will try to reproduce in my PC and to fix it.

Il giorno lun 2 dic 2019 alle ore 10:58 ATwins <notifications@github.com>
ha scritto:

**Comment by ATwins-8** [comment]
Thank you! If you find a solution, please let me know. I am also trying to solve this problem.
