### ISSUE TITLE
Can't enable/disable an object depending on the value of a tag.

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#311]
Hello,
I have seen that I can enable/disable an object depending on role assigned in Authorization. Is there a way to disable, for example, a button depending on the value of a tag? Hiding the button depending on the value of a tag is not an ideal solution.
Many thanks in advance!

**Comment by unocelli** [comment]
Hi,
It is currently not implemented but I think we should add it. Thanks

**Comment by unocelli** [comment]
Hi, is available in the latest version, via Script $enableDevice, let me know if you have any issues.
