### ISSUE TITLE
Bit selection

### ISSUE THREAD

**Issue by robsori** [frangoteam/FUXA#315]
Hi, 
I notice the need for a bit selection facility to change a property of a graphic object. I'm sending you a screenshot of WinCC Graphics Designer.
<img width="646" alt="Screen Shot 2022-03-30 at 16 14 22" src="https://user-images.githubusercontent.com/8734091/160845789-c75bbdca-a7f6-4f68-9174-57d021a3b437.png">
.

**Comment by unocelli** [comment]
Hi,
I am trying to add it, the work is in progress...

**Comment by unocelli** [comment]
I suggest you to join the discussion #295

**Comment by unocelli** [comment]
Let me know if something doesn't work as expected
