### ISSUE TITLE
plugin not saving when installing

### ISSUE THREAD

**Issue by Nug0** [frangoteam/FUXA#316]
hello,

Im trying to install the etherntIP plugin (same happens to modbus one aswell). When i hit the PLUS sign, it says in installing..OK!. I exit the menu by hitting ok and once i go back into plugins it says not installed. Cant see it when adding a new device either. Just doesn't save after install. Any ideas?

Using windows 2016 server.

Thanks

**Comment by unocelli** [comment]
Hi,
it seems that the interface for installing plugins is not very stable. however you can install it manually.

```
cd server
npm i nodepccc --save
```

**Comment by Nug0** [comment]
Yea cool i got it working. Well atleast talking to the PLC.

Has their been any material on how to do taggs for allen bradly PLCs (compactlogix mainly). When i add a tag i set the adress as the bit name from the PLC but doesnt seem to read it? eg: Name = plcpulse, Adress = CommStst.DN

Any material on how to tag for allen bradly would be good

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
