### ISSUE TITLE
Mathematical operations 

### ISSUE THREAD

**Issue by AlexandruAndrei3** [frangoteam/FUXA#318]
Hello,

FUXA currently has the option to do basic mathematical operations to tags? Like in the image below? 
![Simple_Operationspng](https://user-images.githubusercontent.com/94168341/161527208-38da3236-c71f-42eb-9b37-098f66ba38b7.png)
I think it would be useful to do basic mathematic operations inside proprieties of the output control and bar graph for better overall control of tags.

**Comment by unocelli** [comment]
Hi,
I suppose the only operation to do is division to convert a integer to a decimal. so I think it would be simpler to add the division operation like the modbus into the tags property.
![image](https://user-images.githubusercontent.com/48684550/161795800-452f474f-a3b4-4c49-a06a-fe6db7cadb94.png)

**Comment by AlexandruAndrei3** [comment]
Thanks for your answer, but I was wondering if there is something similar for SiemensS7? Or if it will be added?
![Screenshot 2022-04-06 092952s7zimmens](https://user-images.githubusercontent.com/94168341/161909796-3e6b2b07-e67c-40ee-8455-b31d346f69c8.png)

**Comment by unocelli** [comment]
I should add it

**Comment by unocelli** [comment]
This feature is available with Read/Wrirte Scale Script
