### ISSUE TITLE
Add support for InfluxDB

### ISSUE THREAD

**Issue by tisbris** [frangoteam/FUXA#32]
This project looks very good...

I would suggest that the historic data, incl. Alarms & Events are stored inInfluxDB, because this database is fast and dashboard tools are already available.

**Comment by Kortenbach** [comment]
Good idea! Once the data is in InfluxDB you can view it in Grafana or some other tool. It would be a tremendous enhancement!

**Comment by superkalt** [comment]
yes i love the tick stack! grafana to!

**Comment by Kortenbach** [comment]
Afaik, FUXA has no long therm data storage. InfluxDB provides an easy way to add long therm storage. Once added you can view the data using a tool like Grafana.

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.

**Comment by henjoe** [comment]
I hope there are still support for InfluxDB 1.8 version. 
The supported is only for V2.

![image](https://user-images.githubusercontent.com/49782655/200107348-b386fd1c-185a-49a5-b34f-4de67b5c096a.png)

**Comment by Kortenbach** [comment]
Great work!
