### ISSUE TITLE
Changing Views - any way to change view accordinly to Tag changes

### ISSUE THREAD

**Issue by AgrisNN** [frangoteam/FUXA#320]
Dear Fuxa Team,

My project has several views, one of them is set as "default" and is displayed on /home page.
The project also has few tags, linked to OPC server. Tags are updated correctly.
Once a tag changes a value, I need to change View.
But there's now way to do it - nor with Scripts, Alarms or anything else.
The only action to change View is available inside Button element.

Currently I have to use GreaseMonkey to monitor input field with tag linked and "re-click" a button.
Not a "clean" solution...

Help appreciated.

**Comment by unocelli** [comment]
Hi,
I was curious about the feature...so I added...in what context do you use it?

**Comment by AgrisNN** [comment]
Hi unocelli,

To clarify and satisfy curiosity: there;s a machine with hardware buttons being read by PLC and appropriate tag is being read by Fuxa over OPCUA. 
Once human presses a button, Fuxa must change View.
Two pics below shows how it looks like now (different buttons activated two screens)
![image](https://user-images.githubusercontent.com/101255573/162422832-22082ddb-be71-4b76-9208-3a9ee9f955cd.png)

I suspect I can find "view change" option here in future release?
![image](https://user-images.githubusercontent.com/101255573/162402881-8f9ac5f3-611a-46d1-b9af-97aef6474413.png)

**Comment by unocelli** [comment]
I already update by github master branch, and I'm coming to update docker rc version too, witch version are you using?

**Comment by AgrisNN** [comment]
My comment appeared a bit earlier, later I checkeed `master` branch and got update. 
Thanks for commiting the update.

**Comment by unocelli** [comment]
Let me know if something doesn't work as expected

**Comment by thewalk** [comment]
Is this full feature released with 1.16. I tried it, but the view not change every time.
![image](https://user-images.githubusercontent.com/1160402/168409708-6ac5ccaa-2afb-458f-9676-4ebe376e44d7.png)
![image](https://user-images.githubusercontent.com/1160402/168409714-cca44922-b211-4f7a-ba9d-af51469baf07.png)

**Comment by unocelli** [comment]
Hi,
try to set 'Time Delay' to 0

**Comment by thewalk** [comment]
it works, but only once, from the mainview to testview, and it could not go back from testview to mainview. does the start view configuration in layout affects?
