### ISSUE TITLE
How do I add a Text tag to a shape

### ISSUE THREAD

**Issue by jcxjcx123** [frangoteam/FUXA#322]
Hi!
I want to import a shape with letters, but I don't know how to add the text tags and tspan tags. Could you give me some help? Thank you in advance！
![text](https://user-images.githubusercontent.com/41283780/162377211-45b5d2dd-d66e-4bc8-a193-f4d8e28ffb27.png)
![19](https://user-images.githubusercontent.com/41283780/162377248-497fa9dc-5c0c-4593-a0c9-80fa82c34e06.svg)

**Comment by unocelli** [comment]
Hi,
you can add a text, tspan doesn't seem to work :disappointed:.
`{ id: '', type: 'text', attr: { x: '10', y: '10' }, content: 'my text' }`

**Comment by jcxjcx123** [comment]
Great. That worked. thanks a lot
