### ISSUE TITLE
Blinking actions for different values of the same tag not working

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#326]
Hi,
I'm encountering a problem on multiple blinking actions for different values of the same tag. For example, I want a rectangle to blink red-gray for a value of TagWord1 and green-gray for another value of same tag, TagWord1.
![image](https://user-images.githubusercontent.com/58516894/163139195-a038d7a0-bead-4fe7-bd6f-f20d3cfbc5eb.png)
For the above configuration, my rectangle is blinking only for value 8192 as you can see in the below video.
https://user-images.githubusercontent.com/58516894/163147373-edb7dc24-7b64-4992-a446-1bc0253e4ec5.mp4
If for green color I would use tag TestWord1 and for yellow I'd use another tag, let's say TestWord2, it would work perfect. 
It also works fine if I use a blink and show action for the same tag instead of 2 blink actions.
Why isn't working if I use the same tag for both blink action?

**Comment by unocelli** [comment]
Hi, Thanks for the report.
The conflict is because there is a shape restore when the tag value is not in the range to blink.
If you configure on the same tag, the action is checked for each time it has been configured, in your case 2 times, so you will have that once activates the blink while the second does the restore, depending on the sequence

**Comment by IonuDragomir1** [comment]
Thank you for replying!
I understand what did you write, but it's not ok how it is working. As you can see in the video sent in my initial post, when the word has the value 0, the shape is restored. In my opinion, the normal functionality is to blink green when TestWord1 has the value 4096 or blink yellow when TestWord1 has the value 8192. If TestWord1 has any other value, the shape should be restored.

**Comment by unocelli** [comment]
Let me know if something doesn't work as expected
