### ISSUE TITLE
Why iframe window is not displaying several links?

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#327]
Hello,
When I try to access several links using Open iframe action, some of them are not opening. Why is this happening? The tests I've run:
![image](https://user-images.githubusercontent.com/58516894/163361169-42cc9952-2db4-468d-9369-3d79e2529f01.png)
![image](https://user-images.githubusercontent.com/58516894/163361288-39a039d2-77c2-42c4-9540-f610cccc8bfa.png)
The result:
![image](https://user-images.githubusercontent.com/58516894/163361837-290644f9-8ef0-4ac3-b5f4-ea062d56f016.png)
I tried also some other popular sites like: google, microsoft; but the is not displayed.

**Comment by unocelli** [comment]
Hi,
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
