### ISSUE TITLE
Siemens S7 ports

### ISSUE THREAD

**Issue by balincagabrielalin** [frangoteam/FUXA#330]
Hi!

I tested Siemens S7 communication and I found out that whatever number I enter in port field, the connection is working properly if the ip address is correct. 
Also what is fragmentation option on modbus used for ?

**Comment by unocelli** [comment]
Hi,
you are right, I will remove the port setting, the drive used [node-snap7](https://github.com/mathiask88/node-snap7) does not look very interested to the port number.

From #154
With fragmentation: the adjacent addresses are grouped together to split the query to read.
Without fragmentation: the read query is in one, from smaller tag address to biggest tag address (eventually split by 1000 for to big query).
Some devices do not support queries that are too large.

**Comment by balincagabrielalin** [comment]
Thank you.

**Comment by unocelli** [comment]
Let me know if something doesn't work as expected
