### ISSUE TITLE
Angular build

### ISSUE THREAD

**Issue by balincagabrielalin** [frangoteam/FUXA#331]
Hi!

I think you installed sass module without --save flag because I have trouble compiling it. Also I think you are using older version of sass module because the compiler is giving me errors here : 

```
 .my-header-filter /deep/ .mat-sort-header-button {
    display: block;
    text-align: left;
    margin-top: 5px;
}

.my-header-filter /deep/ .mat-sort-header-arrow {
    top: -12px;
    right: 20px;
}
```

In the file device-map.component.scss, I removed /deep/ and now its working.

Screenshots : 
![image](https://user-images.githubusercontent.com/32384258/164244119-408d2e8a-fc79-4d04-8fab-434be2f4cbcd.png)
![image](https://user-images.githubusercontent.com/32384258/164244195-12aa69f4-4bcc-4e3c-bc10-522b41abf09f.png)

**Comment by unocelli** [comment]
Hi,
thanks for the report, /deep/ is deprecated and in any case the device-map.component don't need it anymore, so i removed too. 
Interesting that I don't receive the error, witch global angular cli version are you using?

**Comment by balincagabrielalin** [comment]
This is the angular version :

![image](https://user-images.githubusercontent.com/32384258/164388286-e7b8f8d8-67d3-4b83-bca6-377b2f4184c9.png)

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
