### ISSUE TITLE
Connection error for Siemens s7 1212C

### ISSUE THREAD

**Issue by gabrielbalinca** [frangoteam/FUXA#337]
Hi!

I have a Siemens S7 1212C plc behind a TP-Link GSM router with static IP. I can connect to it with WinCC and Kepware OPC Server but I can't do that with FUXA using Siemens S7 driver. Is there a settings or something that I am missing ?

**Comment by unocelli** [comment]
Hi,
I suppose you want to connect with opc ua? it could be a problem with permissions or certificate. have you tried removing them on the server? what's on the log file?

**Comment by balincagabrielalin** [comment]
Sorry, I forgot to specify, I'm using the siemens driver.

**Comment by unocelli** [comment]
you mean S7 protocol? I'm using [node-snap7](https://github.com/mathiask88/node-snap7) driver

**Comment by balincagabrielalin** [comment]
I re-edited my original post. This problem is only for this type of plc (siemens s7 1212c) with newer ones, works fine.
