### ISSUE TITLE
Remove all Tags feature isn't working

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#338]
Hello,

![image](https://user-images.githubusercontent.com/58516894/165733854-2d384401-f70c-4daf-a055-82aec9bf5b5b.png)

When I remove all tags from a connection, they are deleted. If I exit from the connection and get back, the tags are still declared there. Do you have any idea why it's happening this?

**Comment by unocelli** [comment]
Hi,
Thanks for the report

**Comment by IonuDragomir1** [comment]
You're welcome!

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
