### ISSUE TITLE
internal variables not working for scripts ?

### ISSUE THREAD

**Issue by w4Rd3n** [frangoteam/FUXA#348]
![image](https://user-images.githubusercontent.com/1331530/166412508-bf87af7d-2f20-4930-b425-3c222d7a6214.png)
based on the example in the wiki.
value does not increment.

**Comment by AngelFernandezSobrino** [comment]
https://github.com/frangoteam/FUXA/issues/314

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
