### ISSUE TITLE
Arduino + LVGL support

### ISSUE THREAD

**Issue by garudaonekh** [frangoteam/FUXA#350]
Hi, 

I love this HMI. I am familiar with PLC. I use Arduino/ESP32 with TFT touchscreen which use LVGL library.

Is it possible or already version of FUXA for LVGL?

Thanks

**Comment by unocelli** [comment]
Hi,
No I'm sorry but you need a browser

**Comment by garudaonekh** [comment]
Ok, I got you. 
I also use UI for my esp32 project: (https://github.com/s00500/ESPUI). I use it regularly but its UI component is limited to basic widget like button and textbox, etc. Anyhow, I need to have a flow and animation structure so it's easier to understand and control.

Is it possible to add your components to this library?

**Comment by unocelli** [comment]
No, the widget component work in fuxa frontend only
