### ISSUE TITLE
Adding a custom alarm control

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#352]
Hello,

It'd be useful if an user could add an alarm control on a certain page. I know that FUXA has the alarm feature which is available for the entire project. The alarm control I propose is meant to display only the alarms of a certain mechanism. For example, in the below image, I'm showing you, from WinCC, a window (faceplate) which is used to control and monitor a pump. This window has multiple tabs. One of it contains an alarm control which displays only pump's alarms. 
![Untitled (1)](https://user-images.githubusercontent.com/58516894/167360797-b8e3b96b-c930-44c3-89dd-a3880057c2c9.jpg)

**Comment by Kiruthick-Roxx** [comment]
Hi,
Any updates on this?

**Comment by unocelli** [comment]
Hi, is available in the latest version (Table control), let me know if you have any issues.
