### ISSUE TITLE
Modbus TCP Plugin is not working

### ISSUE THREAD

**Issue by eyadalhanafi** [frangoteam/FUXA#361]
Hi.
It seems there is an issue in Modbus TCP plugin.
It doesn't read data from slave device.
I used Modsim32 to simulate slave device.

I'm using Fuxa Version 1.1.6-688
Node.js v16.15.0.

![MB and Modsim](https://user-images.githubusercontent.com/26257832/168483284-e8f5ad91-4145-40a2-a647-42fc42847512.png)
![status](https://user-images.githubusercontent.com/26257832/168483288-f165d049-0711-4bef-89cb-114379769a37.png)

**Comment by unocelli** [comment]
Hi,
I would try with Node.js v14?

**Comment by eyadalhanafi** [comment]
Hi,
I tried with Node.js Version 14 and it is the same. You can give it a try as well.

**Comment by unocelli** [comment]
I just tested with ModRSsim2, in ubuntu, windows and raspberry, work fine!

try to remove and reinstall node_modules

**Comment by eyadalhanafi** [comment]
I removed Fuxa and reinstall it again but it is the same. Any idea what could be the issue?

**Comment by unocelli** [comment]
something is still not clear to me:
old versions worked and with the new one it no longer works?
have you tried another modbus simulator (ModRSsim2)?

**Comment by Rainproof** [comment]
Hi,
I have FUXA installed on my Raspberry Pi.
In the attached video, the connection with modbus poll is modbus tcp.
I got anxious about the new version of FUXA and decided to check it out.
![mb-tcp-1](https://user-images.githubusercontent.com/19856627/169662842-d4a5aecd-8b9b-4789-b9e6-e0beff133852.gif)

**Comment by eyadalhanafi** [comment]
Old version of Fuxa, Modbus was working smoothly. This happened when i installed the latest version.
I will try with reinstall old version and check again.

**Comment by eyadalhanafi** [comment]
I tested also on version Version 1.1.6-727 but it is not working also.
