### ISSUE TITLE
Error while installing fuxa

### ISSUE THREAD

**Issue by rslord8** [frangoteam/FUXA#363]
Hello. Error while installing fuxa
![image](https://user-images.githubusercontent.com/96974096/169766516-476cb2b8-929b-41c3-b721-e3eb14c4eb7c.png)
Tell me how can I fix it?

**Comment by rslord8** [comment]
please tell me how to completely remove FUXA?
I want to reinstall FUXA.

**Comment by unocelli** [comment]
npm uninstall -g --unsafe-perm @frangoteam/fuxa

**Comment by rslord8** [comment]
an error occurs during reinstallation.

And also tested on the docker, polling via Modbus TCP, OPC UA does not work.

![image](https://user-images.githubusercontent.com/96974096/170022807-47d2d64c-a71b-49d1-971e-7a244a3ae055.png)

![image](https://user-images.githubusercontent.com/96974096/170022894-af58eadf-d79c-4bb1-a0f2-6dbcf4f7cbe2.png)

**Comment by unocelli** [comment]
I saw that you added feature requests and wondered if this issue was resolved?

**Comment by rslord8** [comment]
Reinstalled docker and FUXA on docker. Modbus TCP does not interrogate the slave device.

![изображение](https://user-images.githubusercontent.com/96974096/174222545-5eddd837-b0fa-4205-baf7-ce06905f9e62.png)
![изображение](https://user-images.githubusercontent.com/96974096/174222617-778d55fc-af8f-465f-a036-354802ec3549.png)
![изображение](https://user-images.githubusercontent.com/96974096/174224297-7cb404b2-d1ec-4d4e-8a9c-2e89d5b7d126.png)

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.

**Comment by rslord8** [comment]
Hello,
Thanks, everything is working now.
