### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by rslord8** [frangoteam/FUXA#364]
Hello, thank you so much for developing free open source scada!

Would you like to support the following features:
work with serial modem for SMS alerts?
Notification, sending files, photos via Telegram?
Reports (pdf, xlsx)?
Working with ip cameras?

Please take a look at scada at the link, maybe you will find new ideas for FUXA.

https://github.com/intrahouseio?tab=repositories

Thank you! Wish you luck!

**Comment by unocelli** [comment]
Thanks to have separate your suggestions.
