### ISSUE TITLE
Cutting function of components

### ISSUE THREAD

**Issue by lifeihub** [frangoteam/FUXA#365]
Hello, I found that the cutting function of components in your editing status does not work. Could you please improve this function point? Thank you very much.
![image](https://user-images.githubusercontent.com/87174373/169771699-7fea886a-9eb5-4d74-8d66-b40497cece88.png)

**Comment by unocelli** [comment]
Thanks for the report

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
