### ISSUE TITLE
when tag timer set at 1000, tag value will updated continuosly that time chrome get crashed. and app is hanged.. 

### ISSUE THREAD

**Issue by patsonkaushik** [frangoteam/FUXA#368]

**Comment by patsonkaushik** [comment]
https://user-images.githubusercontent.com/77775964/169958568-b7c456f3-f49d-4de9-bdc3-36a061878bc8.mp4

**Comment by unocelli** [comment]
You are using your FUXA version with your issues :wink:

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
