### ISSUE TITLE
How to change the FUXA Title and Logo?

### ISSUE THREAD

**Issue by top58525785** [frangoteam/FUXA#382]
HI Fuxa Team:

How to change the fuxa web title and logo through seetings?
Thanks

**Comment by unocelli** [comment]
Hi,
from the UI its not possible but you can change and deploy your self the frontend angular project

**Comment by top58525785** [comment]
thanks for reply
You mean just to modify the UI source code，it is in the client floder -index.html？
thanks again
Jason



发自我的iPhone


------------------ Original ------------------
From: Umberto Nocelli ***@***.***&gt;
Date: Fri,Jun 3,2022 11:58 PM
To: frangoteam/FUXA ***@***.***&gt;
Cc: top58525785 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [frangoteam/FUXA] How to change the FUXA Title and Logo? (Issue#382)





 
Hi,
 from the UI its not possible but you can change and deploy your self the frontend angular project

**Comment by unocelli** [comment]
Hi,
the client folder is to develop then you have to deploy you change that are saved in dist folder.  [ https://angular.io/start/start-deployment](https://angular.io/start/start-deployment)

**Comment by mauroalexandre** [comment]
Check #491

**Comment by unocelli** [comment]
This works in the latest version. let me know if you have any issues.
