### ISSUE TITLE
InternalVariables plugin is missing

### ISSUE THREAD

**Issue by GTB4** [frangoteam/FUXA#394]
Hi, 

I have an issue with the internal variables. When i try to create an internal variable i do have an error on my terminal : [WAR] try to create InternalVariables but plugin is missing and when i try to write a value on the variable the value of the var don't change.

 
![Var](https://user-images.githubusercontent.com/106732492/172329869-e7bb1cf7-8c9b-4d00-8173-7da920b28d11.gif)
![Script](https://user-images.githubusercontent.com/106732492/172329889-77ff5d79-2656-4494-9bb5-77388d60e171.gif)

Thanks.

**Comment by unocelli** [comment]
internal device is only for frontend function, the flow don't go to backend, I have to remove it from the choose, please use FUXA Server tags

**Comment by GTB4** [comment]
Thanks a lot for you reply !

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
