### ISSUE TITLE
Boolean type problems

### ISSUE THREAD

**Issue by jcxjcx123** [frangoteam/FUXA#401]
Hi,
I seem to be running into some problems. My current Boolean data is of true/false type, but it seems to bind only 0/1 in fuxa system, so what should I do? Thank you very much for your help.
![img](https://user-images.githubusercontent.com/41283780/172792141-19982a66-8262-4b91-abd8-20379d7cded4.png)
![img2](https://user-images.githubusercontent.com/41283780/172792146-880d2ac8-d34f-4b52-9574-797ba2ddf0bf.png)

**Comment by unocelli** [comment]
Hi, I suppose you have try :wink:
0=false 
1=true

**Comment by unocelli** [comment]
FUXA make the convertion from boolean to number before process the logic.

**Comment by jcxjcx123** [comment]
But when I use the Led Gauge to bind a bool and add blinking events, the Led Gauge does not change. Am I setting it wrong
![gif1](https://user-images.githubusercontent.com/41283780/173001531-1db52e19-9dca-43c3-9af6-a19f49c86278.gif)

**Comment by unocelli** [comment]
I seem to see that your tag changes value quickly, each time it goes to 0 the blink is reset and the led returns to its initial state, so the blink animation does not start in time

**Comment by jcxjcx123** [comment]
I thought that was the reason at first, but when I increased the polling time to 5 seconds, the result was still the same, so I wanted to consult you

**Comment by unocelli** [comment]
I don't think that change the device polling is the solution...
![blink](https://user-images.githubusercontent.com/48684550/173005666-17ea0069-9ee3-4071-80f9-8c0c4d879e07.gif)

**Comment by jcxjcx123** [comment]
Well, thank you very much for your help. I will find the reason again

**Comment by unocelli** [comment]
let me know

**Comment by jcxjcx123** [comment]
I've done a lot of testing and I guess it might be the data type that causes this problem. I noticed that all the data types that subscribe via JSON are JSON. What's your opinion？
![pic3](https://user-images.githubusercontent.com/41283780/173019021-a67baa7f-505c-44c5-aa90-3cd29023e21c.png)
![pic4](https://user-images.githubusercontent.com/41283780/173019231-50b207be-8d6d-4742-8868-b498cdfabae5.png)

**Comment by unocelli** [comment]
Yes, you are right, I can reproduce it. I have to fix it...thank you very much

**Comment by jcxjcx123** [comment]
Hi,
Has this problem been fixed? I updated version V.1.1.6-727, but the same problem still seems to exist ...
![error](https://user-images.githubusercontent.com/41283780/173284575-010b242e-03af-4195-8ed0-6a34b6138ce2.gif)

**Comment by unocelli** [comment]
Hi,
this is another problem, not so critical but to be fixed, tags values are only sent to the frontend if there is a change, change of view or at start-up, and animations are only checked if the value of the respective tag has had a change. if you do an F5 refresh it should work as expected.
about the change of color of the border: I can't explain it, let me know if you can reproduce it.

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
