### ISSUE TITLE
Mqtt Loop time issue

### ISSUE THREAD

**Issue by top58525785** [frangoteam/FUXA#413]
HI Fuxa team:

I meet a MQTT issue about loop time setting
The min time is 200ms

How to set MQTT  the loop time to 10ms?
Is it support?
Because some sense data is fast at least 10ms ,if seeting 200ms loop,  i can not catch the data from mqtt

**Comment by superkalt** [comment]
? scada with 10ms ?

**Comment by top58525785** [comment]
This is the same issue as another topic issue (vedio shows)

**Comment by unocelli** [comment]
I don't think is a good idea. there is a work around:  you can export the devices settings, change the polling interval on the file and import it

**Comment by unocelli** [comment]
going to close this as resolved.
