### ISSUE TITLE
Is it compatible with angular 13?

### ISSUE THREAD

**Issue by Assur** [frangoteam/FUXA#424]
This project is written in angular 7.x. Can fuxa be perfectly migrated to the front-end project of angular 13 project?

**Comment by superkalt** [comment]
this is not a issues but a case for discussion! By the way, you are free to try it! => create a fork and get started!

**Comment by algismo** [comment]
That would be a welcomed change! But may require some work.

https://update.angular.io/?l=2&v=7.2-13.0

**Comment by unocelli** [comment]
Hi, I'm agree with you but it is a work to do step by step. the move to angular 9 is in progress, see the branch [angu9](https://github.com/frangoteam/FUXA/tree/angu9) but there are some issues to fix.
