### ISSUE TITLE
Is it possible to integrate to netcore backend ?

### ISSUE THREAD

**Issue by masterchen** [frangoteam/FUXA#43]
Is it possible to integrate to netcore backend ? if so please give some advice how to , thanks.

**Comment by unocelli** [comment]
Hi,
with asp.net core, I find it a good idea, the FUXA project already has its backend (node.js), a new repository should be created...then it would be better to create modules for the frontend: fuxa-editor to create the views and fuxa-view to show them

**Comment by masterchen** [comment]
Thanks! Do you have plan to give an example ?

**Comment by unocelli** [comment]
Hi,
I can try but next year...it is not so far.

**Comment by masterchen** [comment]
thanks

**Comment by q383186554** [comment]
HI,
have you start the project with asp.net core,dear author,I am excepting for it ,I really neet it.

**Comment by unocelli** [comment]
Hi,
yes i started, as soon as i have defined the structure i want to publish it so that maybe someone helps me.

**Comment by q383186554** [comment]
hi，
ok，i want to help, but it is really hard for me to build the hole program,i can only use or change some of it,If the backend program is ready i will use it and debug it

**Comment by unocelli** [comment]
I'm going to close this due to inactivity.

**Comment by w8w8w8** [comment]
hi, use .net6 or 7 is good idea in server. hope !!!

**Comment by luy710** [comment]
> I'm going to close this due to inactivity.

Where is the .NET Core version? Can I participate in it?
