### ISSUE TITLE
Is it possible to change the text of FUXA? on sidenav menu

### ISSUE THREAD

**Issue by tayfunonbasioglu** [frangoteam/FUXA#434]
Dear Fuxa Team,

First of all, congratulations on your work.
Is it possible to change the text of FUXA? on sidenav menu
thanks for everything..

<div _ngcontent-c15="" class="sidenav-menu sidenav-menu-icon ng-star-inserted" style="height: 100%; background-color: rgb(0, 0, 0); color: rgb(255, 255, 255);"><mat-list _ngcontent-c15="" class="mat-list mat-list-base" style="background-color: inherit;"><mat-list-item _ngcontent-c15="" class="mat-list-item" style="height: 35px; font-weight: bold; padding-left: 10px; padding-bottom: 10px; margin-bottom: 10px; width: unset; color: rgb(255, 255, 255);"><div class="mat-list-item-content"><div class="mat-list-item-ripple mat-ripple" mat-ripple=""></div><div class="mat-list-text"></div> **FUXA** </div></mat-list-item><mat-list-item _ngcontent-c15="" class="mat-list-item menu-item-icon ng-star-inserted" style="width: unset; color: rgb(255, 255, 255);"><div class="mat-list-item-content"><div class="mat-list-item-ripple mat-ripple" mat-ripple=""></div><div class="mat-list-text"></div><button _ngcontent-c15="" class="sidenav-btn mat-button" mat-button="" type="button"><span class="mat-button-wrapper"><div _ngcontent-c15="" class="menu-item-content-icon ng-star-inserted"><mat-icon _ngcontent-c15="" class="mat-icon notranslate material-icons mat-icon-no-color ng-star-inserted" role="img" aria-hidden="true">aspect_ratio</mat-icon></div></span><div class="mat-button-ripple mat-ripple" matripple=""></div><div class="mat-button-focus-overlay"></div></button></div></mat-list-item></mat-list></div>

![Ek Açıklama 2022-07-30 125239](https://user-images.githubusercontent.com/7642923/181905154-c1358c51-7d27-45ef-beca-20d37f163322.jpg)

**Comment by unocelli** [comment]
Hi,
this setting has not yet been implemented but is planned.

**Comment by tayfunonbasioglu** [comment]
thanks
