### ISSUE TITLE
Display the time and date 

### ISSUE THREAD

**Issue by Teguhgithub** [frangoteam/FUXA#437]
How to display the time and date on FUXA web scada?

**Comment by algismo** [comment]
I have a similar need as well. It would be a great feature to be able to add date/time to the "Navigation Bar Header" in settings. 
Time shall contain seconds. Date and time info should be picked up from the server. In such way clock works as a "liveliness" indicator as well. Very common in safety critical systems.

**Comment by serite** [comment]
create a script create time info ,and make a tag,  use setTag show the time per sec .

**Comment by luleipo** [comment]
Did you solve the problem? Please go public. Thank you

**Comment by algismo** [comment]
I was myself planning to extend the client side to allow user to add a tag in the "Header Navigation Bar". Then @serite  proposal could work for showing a time. If somebody will come with any better options, that is very welcomed!

**Comment by unocelli** [comment]
@algismo Great,
how about creating it first as a control (e.g. [widget](https://mostafa-kheibary.github.io/Clock.js/))?
let me know if you need some help...

**Comment by algismo** [comment]
@unocelli, what do you mean by saying "first as a control"? Can you elaborate more on your thoughts.

I myself envisioned something as simple as this: 
![top-bar-tag-widget](https://user-images.githubusercontent.com/71139387/194776524-75b0af97-de7b-4958-826b-ceba4f91cefa.png)

It could also be an option to add "+" button and allow user to setup multiple such "tags" in the header bar.

**Comment by unocelli** [comment]
Hi, yes it would be great to have this feature. 
The top right corner is already reserved for login/logout.
I propose you to create a more flexible interface, in the style of the navigation side, so you can configure label (tag value) or button (function like open card, open page, ...)

**Comment by algismo** [comment]
Hi. Ok, thanks for input. Configurable position would be best, agree.
I have to complete another extension that is burning for me as of now, then I will switch back to this.

**Comment by unocelli** [comment]
Ok, let me know if you need any help

**Comment by unocelli** [comment]
The feature is available in the latest version: Configurable header items: button, label and icons.

**Comment by Jue07** [comment]
> The feature is available in the latest version: Configurable header items: button, label and icons.

Hi can you help how to configure? Thanks in advanced.

**Comment by unocelli** [comment]
https://youtu.be/CgxWorE0Fkc?si=MrUlRALQDhPLJ6jJ
