### ISSUE TITLE
data is not the same in the table

### ISSUE THREAD

**Issue by hiwoodpecker** [frangoteam/FUXA#438]
Hi,
when I use table to show data,the data is not the same in another place.i use tag data tag-1 is 9.4,but in the table is 9.
Thanks.
![image](https://user-images.githubusercontent.com/33960888/182533600-14f51009-8076-4edc-b0b0-0ee383e8579e.png)
![image](https://user-images.githubusercontent.com/33960888/182533721-75e8d2cf-62d9-4191-87be-c265f15593df.png)

**Comment by algismo** [comment]
Hi,

what is the expected (correct) value and what do you see in FUXA?

Algirdas

**Comment by hiwoodpecker** [comment]
@algismo I want show is 9.4,but it is  9 in the table.
![image](https://user-images.githubusercontent.com/33960888/183580700-62b4d34c-15af-47f3-993a-4e0e07dc0067.png)

**Comment by unocelli** [comment]
Hi,
how have you set the formatting of the value in the cell? in the table is different.
![image](https://user-images.githubusercontent.com/48684550/183753694-aebb97fd-4bd7-44fd-a0c6-89e5139702af.png)

**Comment by hiwoodpecker** [comment]
@unocelli I known that.Thank you very much.

**Comment by unocelli** [comment]
can you show me what you have set?

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
