### ISSUE TITLE
ReactJS

### ISSUE THREAD

**Issue by sabrine2433** [frangoteam/FUXA#439]
Can fuxa be integrated in a React application as an editor !!??

**Comment by unocelli** [comment]
Hi, If you think of the frontend, there is the branch inmation where the frontend is a webcomponent and the communication with the backend is via a bridge. the branch is old but it can be use in a react project.

**Comment by Bykiev** [comment]
It's a good idea to provide a separate package with UI-control only. I don't need a NodeJS backend and would like to use only Angular control

**Comment by Bykiev** [comment]
@unocelli, what is a branch name?

**Comment by unocelli** [comment]
[
![image](https://user-images.githubusercontent.com/48684550/195837895-662a2679-9a20-41ff-ab61-17c50f4e4fa2.png)
](https://github.com/frangoteam/FUXA/tree/inmation)

**Comment by Bykiev** [comment]
> [ ![image](https://user-images.githubusercontent.com/48684550/195837895-662a2679-9a20-41ff-ab61-17c50f4e4fa2.png) ](https://github.com/frangoteam/FUXA/tree/inmation)

Thank you, can you please describe what is done and what need to be done?

**Comment by unocelli** [comment]
surely you must have **good angular skills**:
- you have to build the frontend `ng build --configuration=client`
- in dist folder you will find the library of fuxa frontend to use as webcomponent

**Comment by patsonkaushik** [comment]
give me link of this branch. i couldnt find it?.

**Comment by Bykiev** [comment]
https://github.com/frangoteam/FUXA/tree/inmation
