### ISSUE TITLE
mqtt datatype raw does not support number formatting,

### ISSUE THREAD

**Issue by acgiesbrecht** [frangoteam/FUXA#441]
feature request:

in order to format number read from mqtt suscription, a previous .parseFloat() would be necesary in order to have a usefull outcome from .toFixed(digits) in the output control

![image](https://user-images.githubusercontent.com/7153108/183131070-a3354889-1a04-44ad-a846-354cdfb9e12b.png)

![image](https://user-images.githubusercontent.com/7153108/183131120-580a3df7-c5b8-40eb-bd19-981e9dfdb5cd.png)

**Comment by unocelli** [comment]
Hi, Sorry for the delay and thanks for the report.

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
