### ISSUE TITLE
Hide content from pipes when stopped

### ISSUE THREAD

**Issue by unocelli** [frangoteam/FUXA#444]
### Discussed in https://github.com/frangoteam/FUXA/discussions/443

<div type='discussions-op-text'>

<sup>Originally posted by **mauroalexandre** August  6, 2022</sup>
First of all, thanks for your awesome project. I'm subscribed in patreon for contrib.

I'm making my first SCADA view using Fuxa and when I use pipes, I need hide de content from pipe when stopped to avoid user confusion.

It's possible? How?

Thanks</div>

**Comment by mauroalexandre** [comment]
I updated and tested it, it worked perfectly.

Thanks alot.

**Comment by Rafael-OliveiraBR** [comment]
Hi, i'm facing the same problem.

OFF:
![image](https://user-images.githubusercontent.com/18638490/186048039-c3db3294-98fc-49eb-b6a9-65d44ab706b7.png)

ON:
![image](https://user-images.githubusercontent.com/18638490/186048074-1ebea610-e94c-4e04-9763-d6511aba12c0.png)

Pipe settings:
![image](https://user-images.githubusercontent.com/18638490/186048428-ff510785-8118-4475-8b44-3a12c8fd7d70.png)


I'm doing something wrong?
I would like the pipes to be full grey when tag is 0.

**Comment by mauroalexandre** [comment]
@Rafael-OliveiraBR update your versio to 1.1.7-750 and use Hide in type.

**Comment by Rafael-OliveiraBR** [comment]
> @Rafael-OliveiraBR update your version to 1.1.7-750 and use Hide content in type.

sorry if I'm being noob here, but the last release is the 1.1.17.
How can I keep it updated?
I push some command in npm terminal?

**Comment by mauroalexandre** [comment]
> > @Rafael-OliveiraBR update your version to 1.1.7-750 and use Hide content in type.
> 
> sorry if I'm being noob here, but the last release is the 1.1.17. How can I keep it updated? I push some command in npm terminal?

git pull / npm build / npm start

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
