### ISSUE TITLE
How to add text to an SVG drawing?

### ISSUE THREAD

**Issue by lifeihub** [frangoteam/FUXA#446]
Hello, I want to add text in front of an SVG graphic, but I don't know the format to add. There is only (path, ellipse) in your file. I want to know how to add (text). Thank you very much!
![image](https://user-images.githubusercontent.com/87174373/183345571-c11be922-2654-49c3-917e-757a6a09fa51.png)

**Comment by jcxjcx123** [comment]
You can look at problem number #322

**Comment by lifeihub** [comment]
Thank you very much.

**Comment by lifeihub** [comment]
> You can look at problem #322
Thank you very much.

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
