### ISSUE TITLE
Navigate between views through scripts

### ISSUE THREAD

**Issue by lakii22** [frangoteam/FUXA#448]
Hello, I'm developing a project to keep track of plastic dosing units and so far its going really well.

My question is related to the fact that I choose to make one view for each equipment that I'm monitoring because I have a bunch of information per unit. As in plastic factories we could have a lot of dosing units, I would like to have a "Slide Mode" that when activated can cycle through the views giving me the option to show it in a Television inside the factory.

Would be perfect to me if I can do it with a SCRIPT, because with this I would be able to bind it to a Switch Button, however, I didn't managed to make it yet by myself.

So this is how my ideia is looking like right now:

(these are both from the same machine, just showing a example of how I imagine the UI)
![image](https://user-images.githubusercontent.com/7461434/183636221-ba0a4a79-8cd5-453b-b330-fe77bef56f7f.png)

**I'm using OPC UA to gather the data in realtime.

If someone could give a hint about how to change between views through scripts or maybe the correct way to do that, I'd be grateful.

Thanks in advance.

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
