### ISSUE TITLE
Rotate SVG shapes based on a tag value

### ISSUE THREAD

**Issue by algismo** [frangoteam/FUXA#450]
In some cases there may be a need to rotate SVG shapes/objects based on a tag value to make a more realistic visualization. In my case I wanted to visualize position of an air valve, like show in the image below:

![image](https://user-images.githubusercontent.com/71139387/184442753-1e589bd6-897a-4a43-9486-4ad1be143b76.png)

In commercial SCADA systems this is almost a standard feature, but I could not find any good way how to accomplish this with FUXA. To solve my problem I implemented functionality myself. The result is a new action with some additional parameters. It looks like this:

![image](https://user-images.githubusercontent.com/71139387/184443053-7177fe58-efc3-4207-80ec-39915cdcf4ed.png)

If ok, I can make a pull request.

**Comment by unocelli** [comment]
Hi, 
of course, it was missing and it would be great to add it

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
