### ISSUE TITLE
Input gauge is missing some key functionality

### ISSUE THREAD

**Issue by algismo** [frangoteam/FUXA#451]
Continuing on the input gauge topic (after #431). In my opinion it is missing some key functionality. 
To name:
1. Input validation. Now for example operator can write text in a number field. The result is a "facy" value being sent to the PLC. That is quite crazy!
2. No way to format the shown value. For example for the Text control one can define Units and Format digits, but input gauge has nothing like that. I was wondering why. I think both should have the same functionality available. It is tremendously useful.  
3. When "input dialog" is enabled, current value shall be shown side by side with the new value so that operator has full overview.

The result of all those changes could look like this:

![image](https://user-images.githubusercontent.com/71139387/184444942-d85ab2e9-7c01-4d9a-9eca-96ee08c3aa72.png)
![image](https://user-images.githubusercontent.com/71139387/184445048-9c59e363-bbb4-4e99-a32f-22469330d13d.png)
![image](https://user-images.githubusercontent.com/71139387/184444972-a9f12cb5-c00e-424e-86dd-14bcae6813d1.png)

**Comment by unocelli** [comment]
Great, I like it and it would be nice to add this too.
maybe in the future it will also be useful to add range validation with reference to dynamic values.

**Comment by unocelli** [comment]
Is enable in the last release. I am going to close this as resolved.
