### ISSUE TITLE
Retrofit fuxa

### ISSUE THREAD

**Issue by fxh31** [frangoteam/FUXA#452]
Hi，I have an question.
Does fuxa support inserting things like components written in HTML,CSS and JS? If so, how can I do that?

**Comment by mauroalexandre** [comment]
As far as I know no, but you could use an iframe for that.

**Comment by fxh31** [comment]
> As far as I know no, but you could use an iframe for that.

I know, but it can only use links,  I want to write HTML, CSS, JS directly in the interface.

**Comment by unocelli** [comment]
Hi,
the best and I think the only way is to add your components in the frontend in the angular project, like the guauges

**Comment by unocelli** [comment]
Let's close here, since there is nothing feasible
