### ISSUE TITLE
[Sugestion] Item navigation bar

### ISSUE THREAD

**Issue by mauroalexandre** [frangoteam/FUXA#454]
Today my project have a lot of elements SVG like engines below 

![image1](https://user-images.githubusercontent.com/68612845/185261913-a416cc07-ea58-4e1c-a479-1abb95fcd4d0.png)

It's more easy to me just hide/show SVG to show current state based on TAG values instead of develop one component for each kind of element to change colors.

But, is very hard manipulate the elements in the editor, because the elements have the same position.

I'm tried to find in svgeditor component one way to create one bar for can I select the element based on list, like my draft below

![image](https://user-images.githubusercontent.com/68612845/185262082-7b69b23c-5a87-4150-a5c0-1659c2e83289.png)

**Comment by jcxjcx123** [comment]
This is a good suggestion, and it's a useful feature, so I made a graphic list.  Users can select elements by clicking on item
![image](https://user-images.githubusercontent.com/41283780/185272545-bc585c5c-3f4a-477c-99b7-554308176ce8.png)

**Comment by unocelli** [comment]
I also think it is a great feature.
@jcxjcx123 looks good, what are you waiting for a PR :wink:

**Comment by jcxjcx123** [comment]
> I also think it is a great feature. @jcxjcx123 looks good, what are you waiting for a PR 😉

I'd love to share my new features, but it's not done yet, it needs more polish and testing, I'll PR when I'm done😁

**Comment by haitan981** [comment]
> > I also think it is a great feature. @jcxjcx123 looks good, what are you waiting for a PR 😉
> 
> I'd love to share my new features, but it's not done yet, it needs more polish and testing, I'll PR when I'm done😁

You done yet ? Is it possible to share?

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
