### ISSUE TITLE
[Sugestion] Option to determine if keep state in navigation link 

### ISSUE THREAD

**Issue by mauroalexandre** [frangoteam/FUXA#455]
Hello.

Sometimes I need open 3rd party systems inside fuxa.

In this example I show the problem, the user needs login again.

![Peek 2022-08-18 10-07](https://user-images.githubusercontent.com/68612845/185404310-4075bddc-e406-40f6-ac99-7345fec078a5.gif)

But, all the time the link is clicked the iframe reload again, my sugestion is create a option to "keep state" and not realod in every click, just hide/show.

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
