### ISSUE TITLE
Save value if changed  ?

### ISSUE THREAD

**Issue by tayfunonbasioglu** [frangoteam/FUXA#464]
i want to turn this off "Save value if changed" toggle disabled !   it is a bug? or is there any other method?

![image](https://user-images.githubusercontent.com/7642923/187790210-b55791c7-f50f-4856-b6ae-edf9d5dc27b1.png)

![image](https://user-images.githubusercontent.com/7642923/187790112-4e38b695-7afc-4235-9162-5a087847e584.png)

**Comment by unocelli** [comment]
Hi,
is a function yet to be implemented, the interval settings and the a timeout for the tag communication quality too

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
