### ISSUE TITLE
[Suggestion] 'add' button on 'Tag Selection'

### ISSUE THREAD

**Issue by Rafael-OliveiraBR** [frangoteam/FUXA#466]
Hi,

When selecting tags for components  the 'Tag Selection' window only shows the already existing ones, when creating a project on the fly makes a little hard to always have to do 'Setup > Connections > Edit Device Tags > Add tag' go back to layout, repeat the same process for a new component...

I suggest to add an 'add Tag' icon next to 'cancel button', this can pop up a new window where you select what physical device you want to create a new tag, or just move us faster to 'Device Settings' page.
![2022-09-01 20 04 03 127 0 0 1 a2998131b3722](https://user-images.githubusercontent.com/18638490/188045989-a0f404aa-33d9-481a-a850-4b2deac1b370.png)

Would be cool if the button pop up this window (👇), allowing to choose on the first dropbox what device we want to create a new tag.
![2022-09-01 23 45 05 127 0 0 1 d9491d830933](https://user-images.githubusercontent.com/18638490/188048350-0164c97e-dc64-4ced-9e89-909400d57c51.png)

keep up guys, this project rocks! 🤟

**Comment by unocelli** [comment]
Hi sorry for the delay.
The feature makes absolute sense, the problem is that there are at least 3 different dialog to configure the tag or topic: 
- Modbus/S7...
- MQTT
- OPCUA

**Comment by unocelli** [comment]
is available in the latest version,  let me know if you have any issues.
