### ISSUE TITLE
How does the "Align Right" button call the function

### ISSUE THREAD

**Issue by XiaoTongTang** [frangoteam/FUXA#47]
How does the "Align Right" button call the function?You don't use the "Onclick" property, nor is it a routing feature of the angular framework
![image](https://user-images.githubusercontent.com/46051006/72580232-549f2100-3916-11ea-93a1-393d865d7a61.png)
![image](https://user-images.githubusercontent.com/46051006/72580271-75677680-3916-11ea-8b4a-6c13019d49bc.png)

**Comment by unocelli** [comment]
Hi, no it isn't an angular component, in fact, it is a normal javascript ID
binding  made through fuxa-editor.min.js. The editor is a modified version
of SVG-edit (https://github.com/SVG-Edit/ SVG-edit).

Il giorno ven 17 gen 2020 alle ore 03:45 唐晓潼 <notifications@github.com> ha
scritto:

**Comment by XiaoTongTang** [comment]
Thank you very much for your help, in that case, I will go to check out the project you provided called "svg_edit"
