### ISSUE TITLE
怎么设置画布大小？

### ISSUE THREAD

**Issue by luleipo** [frangoteam/FUXA#471]
1.怎么设置画布大小呢？

**Comment by unocelli** [comment]
Hi, please translation...also in Italian is OK :wink:

**Comment by jcxjcx123** [comment]
@unocelli I'll answer it for him 😀
画布大小的话就是点击你视图旁边三个点，然后里面有个属性
![image](https://user-images.githubusercontent.com/41283780/188570547-b51155f5-56b7-4c45-8db3-1221c6034290.png)

首页画布全屏展示没太懂，你的意思是F11的全屏吗

**Comment by unocelli** [comment]
I am going to close this as resolved.
