### ISSUE TITLE
TypeError: Cannot read property 'retention' of undefined

### ISSUE THREAD

**Issue by balincagabrielalin** [frangoteam/FUXA#474]
I have found an issue, this error is thrown when we start the server :

(node:1520) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'retention' of undefined
    at E:\FUXA\server\runtime\storage\daqstorage.js:107:74
    at new Promise (<anonymous>)
    at Object.checkRetention (E:\FUXA\server\runtime\storage\daqstorage.js:105:12)
    at _clearStorage (E:\FUXA\server\runtime\jobs\cleaner.js:50:35)
    at E:\FUXA\server\runtime\jobs\cleaner.js:24:27
    at new Promise (<anonymous>)
    at Cleaner.execute (E:\FUXA\server\runtime\jobs\cleaner.js:19:16)
    at E:\FUXA\server\runtime\jobs\index.js:168:61
    at Array.forEach (<anonymous>)
    at E:\FUXA\server\runtime\jobs\index.js:166:26
    at new Promise (<anonymous>)
    at _checkJobs (E:\FUXA\server\runtime\jobs\index.js:163:16)
    at _checkStatus (E:\FUXA\server\runtime\jobs\index.js:98:25)
    at Timeout._onTimeout (E:\FUXA\server\runtime\jobs\index.js:31:17)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by unocelli** [comment]
:weary: Thanks a lot, i have to fix quickly.

**Comment by haitan981** [comment]
> 😩 Thanks a lot, i have to fix quickly. The default value is missing. the server still works and if you confirm the setting retention the problem should no longer occur ![image](https://user-images.githubusercontent.com/48684550/189194738-cfd29519-4a5f-4491-8ad0-09ad2f396ec8.png)

Did you find a way to fix this error? I want to use SQLite but can't. Only works with InluxDB but low efficiency

**Comment by unocelli** [comment]
yes, the problem has been fixed, try it to believe.

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
