### ISSUE TITLE
DAQ to CSV export script/feature

### ISSUE THREAD

**Issue by afbenevides** [frangoteam/FUXA#477]
Hello there, I just found your project and it seems really interesting. I searched but could not find a data-acquisition download data kind of feature. Is there already something available for that? I was thinking of a button with parameters to download data for value/tag 1-2-3 from date/time x to date/time y. That would export a CSV file. What do you think? For the rest of the HMI features its already awesome!

Thanks again

**Comment by unocelli** [comment]
Hi,
In History table you can export the content in CSV format.

**Comment by afbenevides** [comment]
OK thanks for the reply I will test that, that should work for me normally. Thanks again!

**Comment by afbenevides** [comment]
@unocelli It really does look to be exactly what we need, but I don't know what I do wrong but no data is showing in the table. Where can we add data to this table in the interface?

Thanks for your help

**Comment by afbenevides** [comment]
To make it clearer, the table can display live mata as shown here. See data fits the live graph on same tag. But when in history table (to get the csv download feature), no tags show up... is there a configuration needed other then columns?
I put for reference, table working, history table no data, history table setup window.
<img width="482" alt="Capture d’écran, le 2022-10-18 à 12 39 35" src="https://user-images.githubusercontent.com/19934301/196491481-9a15a1c6-7508-4ec2-a37a-4a70a0e3e4bd.png">
<img width="1277" alt="Capture d’écran, le 2022-10-18 à 12 36 47" src="https://user-images.githubusercontent.com/19934301/196491485-2b77c063-8241-4ccf-8114-548d748d5842.png">
<img width="1273" alt="Capture d’écran, le 2022-10-18 à 12 32 13" src="https://user-images.githubusercontent.com/19934301/196491491-d6924821-8ec3-483f-9450-9e7778302582.png">
<img width="1757" alt="Capture d’écran, le 2022-10-18 à 12 41 48" src="https://user-images.githubusercontent.com/19934301/196491800-61489ecd-98f2-4e8b-a398-255a28f06bff.png">

**Comment by unocelli** [comment]
Hi, Thanks for the report.
have you configured the tags property to be recorder for the history?
![image](https://user-images.githubusercontent.com/48684550/196497284-6100c286-7346-46e0-b9f6-a66a30946c11.png)

**Comment by afbenevides** [comment]
Hello thanks for the super fast reply. Yes I have put in fact 1 sec interval instead of 60 like in yours. It is the only difference. I can try with 60, should that do a problem?

**Comment by afbenevides** [comment]
@unocelli I have an update, I erased one tag of my history table setup, and if I have only time + a tag it works I get history data. As soon as I add another tag it doesn't work anymore.

Is there something you have in mind for me to test to resolve that?

Thanks
![Capture d’écran, le 2022-10-19 à 19 15 30](https://user-images.githubusercontent.com/19934301/196822293-cc475a33-d702-460b-b00e-47141d23bfc5.png)
![Capture d’écran, le 2022-10-19 à 18 56 01](https://user-images.githubusercontent.com/19934301/196822295-63b8ccb3-bc6b-48ba-b478-3b2a1d6a8080.png)

**Comment by afbenevides** [comment]
ok works as intended now. I activated login for the second value also.... Sorry for that...
Thanks this feature was exactly what I was looking for.
