### ISSUE TITLE
A feature that can change the FUXA text can be applied

### ISSUE THREAD

**Issue by tayfunonbasioglu** [frangoteam/FUXA#479]
A feature that can change the FUXA text can be applied

![image](https://user-images.githubusercontent.com/7642923/189548122-b90b4f67-c003-4f70-aeb4-34a9417c37fd.png)

**Comment by MatthewReed303** [comment]
I have been looking for a way to change this also. Would be nice to have a text and an image option so you can add a logo or similar

**Comment by mauroalexandre** [comment]
Check #491

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
