### ISSUE TITLE
Extend svg editor with new shapes

### ISSUE THREAD

**Issue by albosmart-ro** [frangoteam/FUXA#48]
how do i extend the svg editor to append new predefined shapes?

```
<div class="svg-tool-button" [ngClass]="{'svg-tool-active': isModeActive('custom-shape')}" (click)="setMode('custom-shape')">
              <span class="icon-tool icon-custom-shape"></span>
            </div>
```

**Comment by unocelli** [comment]
Hi,
I'm currently working on it, my goal would be to make editable
and extendable default shapes and with the possibility of setting events to
them.

Il giorno mer 5 feb 2020 alle ore 15:52 albosmart-ro <
notifications@github.com> ha scritto:

**Comment by unocelli** [comment]
Hi,
I just added the feature to extend shapes and to animate them 

Kind regards

**Comment by unocelli** [comment]
I integrated the following gauge [https://bernii.github.io/gauge.js/](https://bernii.github.io/gauge.js/)
