### ISSUE TITLE
[Feature] Layout settings for change sidebar text 'Fuxa' to custom image (resource).

### ISSUE THREAD

**Issue by mauroalexandre** [frangoteam/FUXA#491]
This feature is a necessity of my project, but I found another issues with similar subject.

I created this option, I don't know if it will be incorporated into the project, but I hope it will be accepted.

https://user-images.githubusercontent.com/68612845/190510202-f55cdb8a-32c1-4ef1-9d36-fd9dd42cdfc6.mp4

_TODO: The longo only changer after refresh page (maybe can't see this step in video)._

Feature in #490

**Comment by tayfunonbasioglu** [comment]
it's so nice of you to do this

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
