### ISSUE TITLE
Is there a way to write DAQ data to MySql?

### ISSUE THREAD

**Issue by tayfunonbasioglu** [frangoteam/FUXA#495]
Is there a way to write MySql log?

**Comment by unocelli** [comment]
Hi,
what do you mean with log?

**Comment by tayfunonbasioglu** [comment]
Hi,
In some projects, it may be necessary to save historical data to an existing mysql database. In this case, we can develop an easy and very useful method. I would like to share with you the method he developed for my own project.

[Video-Fri-Sep-30-2022-20-26-27.webm](https://user-images.githubusercontent.com/7642923/193324278-d5ab1cdc-8f10-41d6-80e4-8234ef601818.webm)

**Comment by saufister** [comment]
> Hi, In some projects, it may be necessary to save historical data to an existing mysql database. In this case, we can develop an easy and very useful method. I would like to share with you the method he developed for my own project.
> 
>  Video-Fri-Sep-30-2022-20-26-27.webm

Please share step how to do that, thanks
