### ISSUE TITLE
Cannot create device Tags from WebAPI Request

### ISSUE THREAD

**Issue by r0cheny** [frangoteam/FUXA#501]
Hi, 

I've been playing around with FUXA and I wanted to use my PostgreSQL DB in combination with postgREST as a Datasource, I was able to configure the Device and got my Request result: 
![grafik](https://user-images.githubusercontent.com/82642991/191524104-4a81aede-be61-4961-ba7c-0f5397c36ee8.png)

Now if i want to create a device tag, I can see the results but i cannot select anything as shown in the wiki. 
![grafik](https://user-images.githubusercontent.com/82642991/191524413-d819e221-2603-4e59-91c3-6c472c2fb3f3.png)

Is this intended? If so, what can I do to fix this issue? 
Thank you

**Comment by unocelli** [comment]
Hi, you have an array then you have to define the key of tag id and the key of tag value
![image](https://user-images.githubusercontent.com/48684550/191600912-7d96fe82-27f0-423d-88de-c4cc447b1f86.png)

**Comment by r0cheny** [comment]
Hi,
Thanks a lot, Now it works!
