### ISSUE TITLE
cannot find https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.3/napi-v6-linux-arm64.tar.gz 

### ISSUE THREAD

**Issue by zjjczzs** [frangoteam/FUXA#502]
![image](https://user-images.githubusercontent.com/6227647/191545643-fc9a7ac1-1a73-4aeb-b5c5-5781b677df38.png)

**Comment by unocelli** [comment]
Hi,
please os, node, npm version?
try to delete and reinstall node_modules

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
