### ISSUE TITLE
How to rounded float value? 

### ISSUE THREAD

**Issue by saufister** [frangoteam/FUXA#512]
Hey, can anyone helpme how to round float32 value from modbus tcp on fuxa ? Thank you.

**Comment by unocelli** [comment]
Hi, in some controls you can define the digits or you define a script and save the rounded value in a Tag of  FUXA device

**Comment by saufister** [comment]
Yes thanks, i already done it with javascript code , thank you very much😃

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
