### ISSUE TITLE
Can't connet to MODBUS-RTU.

### ISSUE THREAD

**Issue by minicoco** [frangoteam/FUXA#513]
Hello everyone. I want use FUXA to connect MODBUD-RTU device, this is my config:
![image](https://user-images.githubusercontent.com/5663256/192682953-80f41e0f-49ce-4fea-a88a-d3c135dc8934.png)

I use KEPServerEX create a modbus-rtu slave：
![image](https://user-images.githubusercontent.com/5663256/192682107-ce4360a6-9f40-4a89-be0f-5faee0e95546.png)

BUT they can't connet successfully:
![image](https://user-images.githubusercontent.com/5663256/192683408-5865f3bb-0018-4f15-a4eb-13532be15ddc.png)

I use other tools ,like "Mthings" ，they can communicate successfully:
VSPD look like :
![image](https://user-images.githubusercontent.com/5663256/192683040-2c868f64-17c9-4934-99dd-28f13050d3a6.png)

Sorry my poor english,I hope I made it clear。

Did I do something wrong? Please give me some suggestions. Thank you !

**Comment by unocelli** [comment]
Hi,
have you try to enable 'Fragmented' option?

**Comment by afbenevides** [comment]
Hello, has this issue been resolved? We have similar issue, can’t connect to modbus RTU on pi. Modbus works if out of fuxa, but cant connect through FUXA. Any clue?

**Comment by afbenevides** [comment]
Other info, we use /dev/tryusb0 as port address, is that right ? Or do we need to use another form to point to modbus?

**Comment by unocelli** [comment]
Hi, have you try to remove from FUXA plugins and install the driver from server folder?
`npm install modbus-serial`

**Comment by afbenevides** [comment]
Forgot to comment but installing Modbus-serial from npm fixed the issue for me. Thanks

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
