### ISSUE TITLE
Auto run script

### ISSUE THREAD

**Issue by haitan981** [frangoteam/FUXA#517]
Hi everyone
How to make script run automatically without Click or Release Event

**Comment by mauroalexandre** [comment]
Use "Script schedule".

![image](https://user-images.githubusercontent.com/68612845/193188324-e4c716e8-f09f-497c-b216-889221d29b01.png)

**Comment by haitan981** [comment]
Thank you. It worked fine

**Comment by Jue07** [comment]
I am using ver.1.1.7 of Fuxa. Which one should I choose to run the script automatically?

1.Loop with interval
2. Only on start
3. Scheduling

**Comment by unocelli** [comment]
Hi, interval at 0 seconds is not an interval...disabled!

**Comment by Jue07** [comment]
Thanks for the tip!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
