### ISSUE TITLE
Cannot start FUXA via cmd

### ISSUE THREAD

**Issue by haitan981** [frangoteam/FUXA#518]
Hi everyone
I start FUXA via command but got error like below image. If anyone knows how to fix it, please help me. Thank so much
![image](https://user-images.githubusercontent.com/44091731/193239440-a9c97df0-a640-4a15-9d54-83a208de17cd.png)

**Comment by unocelli** [comment]
Hi, The issue is already fixed https://github.com/frangoteam/FUXA/issues/474 where you find the a workaround

**Comment by unocelli** [comment]
I assume that in the meantime you have installed fuxa by following the instructions on the [wiki](https://github.com/frangoteam/FUXA/wiki/Installing-and-Running). let me know if you have any issues.

**Comment by haitan981** [comment]
> I assume that in the meantime you have installed fuxa by following the instructions on the [wiki](https://github.com/frangoteam/FUXA/wiki/Installing-and-Running). let me know if you have any issues.

I have reinstalled Node JS v14 and new FUXA 1.1.9 but still not working. How to fix that error.

![image](https://user-images.githubusercontent.com/44091731/195504341-f663d818-1865-4366-b203-54eb851fd6d6.png)

**Comment by malcore10** [comment]
please a screeshot:
node -v & npm -v

**Comment by haitan981** [comment]
> please a screeshot: node -v & npm -v
I did as per your request
![image](https://user-images.githubusercontent.com/44091731/195738967-44570a9b-34a4-4e8a-84cb-c445bb24cc83.png)
