### ISSUE TITLE
Why your screengrabs so damn fast?

### ISSUE THREAD

**Issue by dustymac** [frangoteam/FUXA#521]
Whoever thought that showing us blazing fast screengrab walkthroughs for your FAQ page needs to be fired.  Immediately.  I will gladly help you re-record each of them if you will at least admit they are abnormally too fast for the average Joe.  And perhaps even too fast for the average Schmo.

**Comment by unocelli** [comment]
?

**Comment by dustymac** [comment]
Apologies -- my frustration got the best of me, and resulted in a poorly worded issue on Github.  I actually ended up downloading your .gif WIKI videos and slowed them down at https://ezgif.com/speed.

Your WIKI is great.  Very helpful for me learning my way around FUXA.  But the speed of the .gif files is quite fast for trying to learn.

Like this one:

![image](https://user-images.githubusercontent.com/16970144/194412892-1a5d174d-5893-47ea-8e29-299e9f91b45d.png)

**Comment by mauroalexandre** [comment]
This is an open source project, including wiki. Please if you can contribute, do it, before creating poor issues.
