### ISSUE TITLE
Error: listen EADDRINUSE: address already in use 0.0.0.0:1881

### ISSUE THREAD

**Issue by haitan981** [frangoteam/FUXA#523]
When I start FUXA via cmd : fuxa
The screen shows the error as shown below. Can anyone help me fix this error?
 Thank you so much
![image](https://user-images.githubusercontent.com/44091731/193523875-0a7bf10f-3bbd-4d10-94eb-560b2fba6056.png)

**Comment by saufister** [comment]
Port 1881 already attach to another process, you have to check it with netstat and kill that process

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
