### ISSUE TITLE
'MODBUSTCPIP' _readMemory error! Error: Modbus exception 1: Illegal function (device does not support this read/write function)

### ISSUE THREAD

**Issue by haitan981** [frangoteam/FUXA#524]
The system is working normally, suddenly an error like the screenshot below appears, and the system stops working and cannot be restarted. Anyone know the cause, help me fix the error.
Thank you so much

![image](https://user-images.githubusercontent.com/44091731/193524705-9050689e-8d50-4611-92bb-f14bc6af531a.png)
![image](https://user-images.githubusercontent.com/44091731/193524906-116c45ed-8a2e-4864-82bb-5c8c5a62223e.png)
![image](https://user-images.githubusercontent.com/44091731/193525220-ea527d77-a556-4cdf-9411-e96bfbb0fd50.png)

**Comment by unocelli** [comment]
Hi, try to remove from FUXA plugins and install the driver from server folder.
`npm install modbus-serial`

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
In master branch you find a version where the library will be installed as standard.

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
