### ISSUE TITLE
How to fix Cannot start running FUXA 

### ISSUE THREAD

**Issue by haitan981** [frangoteam/FUXA#526]
The system is working normally, an error appears automatically as shown in the screenshot below, and the system stops working and cannot be restarted. Who knows the staff, help me fix the error.
 Error: ENOENT: no such file or directory, scandir
![image](https://user-images.githubusercontent.com/44091731/193771657-fe246138-2c65-408c-bb9d-738a6c083030.png)
![image](https://user-images.githubusercontent.com/44091731/193771911-38cecd03-f642-4898-b497-ab3aeb36ff7c.png)

**Comment by malcore10** [comment]
Hi,
check nodejs version. (supported v10-14)

**Comment by haitan981** [comment]
> Hi, check nodejs version. (supported v10-14)

I am using Node JS 18.9.0 . new latest

**Comment by malcore10** [comment]
now you know why it doesn't work. probably the other issues #524 #518 are also for the same reason

**Comment by haitan981** [comment]
> now you know why it doesn't work. probably the other issues #524 #518 are also for the same reason

I don't see any similarity in those errors

**Comment by haitan981** [comment]
> now you know why it doesn't work. probably the other issues #524 #518 are also for the same reason
This morning I started FUXA again this error appeared on the cmd screen.
How to fix that error ? Please help me . Thank you so much

![image](https://user-images.githubusercontent.com/44091731/194980506-f7132f81-c69e-45a2-88bc-1868f234da0b.png)

**Comment by unocelli** [comment]
I assume that in the meantime you have installed fuxa by following the instructions on the [wiki](https://github.com/frangoteam/FUXA/wiki/Installing-and-Running). let me know if you have any issues.
