### ISSUE TITLE
fuxa-editor.js source code?

### ISSUE THREAD

**Issue by patsonkaushik** [frangoteam/FUXA#527]
I want to see fuxa-editor.js source code, not fuxa-editor.min.js in client. Please tell me where I can find it. Thanks!

**Comment by unocelli** [comment]
fuxa-editor is another project, the source is the same  [svg-edit](https://github.com/SVG-Edit/svgedit)

**Comment by crane168** [comment]
> fuxa-editor is another project, the source is the same [svg-edit](https://github.com/SVG-Edit/svgedit)
There is indeed a need for this, as there are some modifications in editor.min.js that are difficult to handle at the moment. It would be best to provide an uncompressed fuxa-editor.js. Thank you
