### ISSUE TITLE
Error displaying real numeric value when set up value

### ISSUE THREAD

**Issue by haitan981** [frangoteam/FUXA#528]
Why is it that when the value is a real number, the decimal part after the comma is followed by a lot of other digits?
How to fix that display error. Although the value in the PLC is still the same as the value you want to set
![image](https://user-images.githubusercontent.com/44091731/194464963-049b52ad-d1df-437f-ab4c-55bf2149fc2b.png)

https://user-images.githubusercontent.com/44091731/194465009-62fde5fc-7384-4f87-b4cf-a00dfea55a46.mp4

**Comment by unocelli** [comment]
I will therefore close this issue, feel free to re-open it if something is still not working.
![image](https://github.com/frangoteam/FUXA/assets/48684550/a7c21f70-616c-41f0-b204-28f40dddeb29)
