### ISSUE TITLE
Why page home still show when not login yet? 

### ISSUE THREAD

**Issue by saufister** [frangoteam/FUXA#529]
Hi,  Is there a way to hide home page before user successfully log in ?

**Comment by unocelli** [comment]
there isn't a welcome page but you can set the navigation permissions

**Comment by mauroalexandre** [comment]
Maybe hide the view from background from login modal is a good feature.

@unocelli let me know your opnion and I'll try open PR.

**Comment by unocelli** [comment]
@mauroalexandre Hi and sorry for the delay. Yes I think is a good idea. I will wait your PR :D

**Comment by unocelli** [comment]
In the new versions at a logout the view jumps to the configured Start View, so I guess the issue is no longer current.
I will therefore close this issue, feel free to re-open it if something is still not working.
