### ISSUE TITLE
It would be nice if it had a similar effect to pipe and water

### ISSUE THREAD

**Issue by hxjack** [frangoteam/FUXA#53]
It would be nice if it had a similar effect to pipe and water.

**Comment by unocelli** [comment]
Hi, I agree, you have an idea of ​​how it should be looking?

**Comment by hxjack** [comment]
![3](https://user-images.githubusercontent.com/53986214/77814290-96083580-70ea-11ea-927e-18ecf00ba51e.png)
Similar to the picture above, the black blocks can be moved.

**Comment by unocelli** [comment]
Ok nice, I can try. thanks
