### ISSUE TITLE
Real digit format from Siemens S7

### ISSUE THREAD

**Issue by gosztek** [frangoteam/FUXA#531]
Hi, I have a problem - I do not see the option to set the number of decimal places in the display of values. Where should I look?
![image](https://user-images.githubusercontent.com/115475711/194873465-3ec0dc89-896d-4309-ba4e-3c04b0a25c1a.png)

![image](https://user-images.githubusercontent.com/115475711/194873737-5e40a5e4-ba70-40a5-a154-d5b7036c0d21.png)

**Comment by unocelli** [comment]
Hi, you should see like this:
![image](https://user-images.githubusercontent.com/48684550/194957533-556c94dc-eff3-4921-8eff-894e4eaac005.png)
which version are you using?

**Comment by haitan981** [comment]
> Hi, you should see like this: ![image](https://user-images.githubusercontent.com/48684550/194957533-556c94dc-eff3-4921-8eff-894e4eaac005.png) which version are you using?

what version are you using . I am using v1.1.8-821 ,so it do not have Format digits

**Comment by gosztek** [comment]
> Hi, you should see like this: ![image](https://user-images.githubusercontent.com/48684550/194957533-556c94dc-eff3-4921-8eff-894e4eaac005.png) which version are you using?

Many thanks for the prompt reply. I have 1.1.8-821 version.

**Comment by haitan981** [comment]
> > Hi, you should see like this: ![image](https://user-images.githubusercontent.com/48684550/194957533-556c94dc-eff3-4921-8eff-894e4eaac005.png) which version are you using?
> 
> Many thanks for the prompt reply. I have 1.1.8-821 version.
I also use the same version as yours. Why don't I have .You have up to 3 input boxes
![image](https://user-images.githubusercontent.com/44091731/195010511-230b0436-2eb2-4eee-b39f-4a2672bf8177.png)

**Comment by haitan981** [comment]
> > Hi, you should see like this: ![image](https://user-images.githubusercontent.com/48684550/194957533-556c94dc-eff3-4921-8eff-894e4eaac005.png) which version are you using?
> 
> what version are you using . I am using v1.1.8-821 ,so it do not have Format digits

**Comment by gosztek** [comment]
Do we know anything about displaying these float variables? Any additional ideas?

**Comment by unocelli** [comment]
to be sure I would install the last version 1.1.9

**Comment by gosztek** [comment]
FUXA works fine after upgrading to version 1.1.9. Regards
![image](https://user-images.githubusercontent.com/115475711/197116355-0792ae6f-80d4-4846-ab7c-c86129ba9a8b.png)
