### ISSUE TITLE
Unable to start Fuxa

### ISSUE THREAD

**Issue by haitan981** [frangoteam/FUXA#533]
What went wrong when I tried to start FUXA. Can anyone help me to fix this error? .Thank you so much
![image](https://user-images.githubusercontent.com/44091731/194981253-45323fe5-045c-4f3c-a7fd-8674a60702f4.png)
![Screenshot 2022-10-11 090036](https://user-images.githubusercontent.com/44091731/194981271-375e1b2d-c05b-49a6-ac73-1fbebff44934.png)

**Comment by unocelli** [comment]
I assume that in the meantime you have installed fuxa by following the instructions on the [wiki](https://github.com/frangoteam/FUXA/wiki/Installing-and-Running). let me know if you have any issues.
