### ISSUE TITLE
Multiple tag selection

### ISSUE THREAD

**Issue by AlexandruAndrei3** [frangoteam/FUXA#535]
Hi,

When i have a large number of tags in order to add them i have to click to select  each one of them (eg: If  have 1000 tags i have to click 1000 times in order to add them). I think it can be useful to add an Select All option sou users don't have to select each tag one by one.
![Capture2](https://user-images.githubusercontent.com/94168341/195308646-e0d8472d-d069-4cfd-b696-152de38205b6.PNG)

**Comment by mauroalexandre** [comment]
Hi! Thanks for the sugestion.
I developed this possibility.

Please check #536

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
