### ISSUE TITLE
Retain Information after restart

### ISSUE THREAD

**Issue by lakii22** [frangoteam/FUXA#550]
Hi, I'm creating a system that I need to store some information inside the FUXA Server and retain it after the server restart...
Example: Store the amount of machines in the project, so I could dynamically show the correct amount of devices in the view.

The problem is that even activating the "registration option" into the TAG options the "value" goes back to the original one after the restart because the DB file that was in use goes to the archive folder and a new one is created.

Before restart:
![image](https://user-images.githubusercontent.com/7461434/196455130-1b7dea20-97b3-4c7f-bf6c-9e394c006e2f.png)

After restart:
![image](https://user-images.githubusercontent.com/7461434/196452982-77c8a7c2-f893-4432-a90c-2dc4f13a93bf.png)

So is there a way to keep the values into the server database even after the archiving function?

Or is there a better way to store information that I can use in Fuxa?

I'm using FUXA v. 1.1.9-891

**Comment by unocelli** [comment]
Hi, to see the history you can use the chart control or the table, but it would not be correct to show a value from the history where you would expect the actual one

**Comment by lakii22** [comment]
Hi @unocelli, thank you for your quick answer, but I think that I've not expressed myself well in the comment above.

What I've tried to mean is, that I'd like to have the last "valid" value from a variable after a system restart (if the value haven't changed of course), instead of 0 or "empty".

But reading what you've wroted above I can imagine that this isn't possible right now because of the DAQ format.

Just to give you a tip of why I'm trying to "retain a value from a variable": My goal is to make a "setup page" where I can set the amount of machines present in the factory and some other informations about quantity that I can use to dinamically set the view size, layout, machine names and so on. 

So right now I think that the only option that I've is to use a SQL DB through WEBapi GET or to hardcode the value that I want into a script, right ? So I could keep the value even after a restart from the server.

**Comment by unocelli** [comment]
eventually you can try to save the values to a file with a script

```
const fs = require('fs');
fs.writeFileSync(filename, values);
```

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
