### ISSUE TITLE
Internal variables - Warning "Plugin is missing"

### ISSUE THREAD

**Issue by lakii22** [frangoteam/FUXA#551]
Creating a connection of the type "internal" is returning me the following warning:
![image](https://user-images.githubusercontent.com/7461434/196462143-b395ac26-246d-42c1-a58e-a5c967535a41.png)

After creating the connection I can still add the variables, however if I try to change the values nothing happens.
![1](https://user-images.githubusercontent.com/7461434/196463996-ba257a94-a65b-461e-935c-003f6cc3e873.gif)

Am I making a mistake or this is actually how it should work ?

**Comment by unocelli** [comment]
Hi, Thanks for the report.
It is a warning not a error. I will fix...in any case has no consequences on the functionality. 
internal device is used for frontend (client) logic, if you are using scripts you should use FUXA (server) or other device types (not internal)

**Comment by lakii22** [comment]
@unocelli Thank you again for the feedback. For me is clear... 

I've made a mistake about the function of these variables (even with the quote "Frontend only" in the connection creator 😅).

So I'm going to close this Issue.
