### ISSUE TITLE
Table of data feature

### ISSUE THREAD

**Issue by kotori94** [frangoteam/FUXA#56]
Hi, besides chart, I want to see table of data. For example, I want to see value of property each 30 minutes in last 3 days (can filter and choose value to add as well).
Hope you can help me. Thanks.
![image (1)](https://user-images.githubusercontent.com/48921618/79327321-c847ce80-7f03-11ea-8a2d-dddd656a7e51.png)

**Comment by unocelli** [comment]
Hi, I can add a function to export the chart data in CSV format in order to analyze in excel.

**Comment by kotori94** [comment]
Thanks. But How about the table in Scada HMI, like chart?. If it is to analyze, I can read sqlite db and analyze it later. A table in HMI can help me quickly see what is happening recent hours in the screen

**Comment by unocelli** [comment]
Personally, I prefer to look at a chart than a table, in any case I have also planned to implement the table or list controls, there is in my to do list. Thanks.

**Comment by kotori94** [comment]
Great! Hope it would be done soon.

**Comment by kotori94** [comment]
Hi, could you give me the source code of fuxa-editor.min.js, so I can add the new module likes tables by myself?. Or you can guide me how to do it. Thanks

**Comment by unocelli** [comment]
Hi, You don't need to change fuxa-editor.min.js, you can make it by add a new shape type with 'foreignObject' as type and then add new components (like for example table-property and ngx-table) in angular frontend. if you want I can try to guide you?

**Comment by kotori94** [comment]
Great. I really want to implement table component to see data on HMI. Could you make a guide about this? Thanks

**Comment by unocelli** [comment]
Hi, I created a 'ctrl-table' branch

**Comment by destiny456** [comment]
Hi,export the chart in csv format,Did you add this function？

**Comment by peakcontrol** [comment]
Hello,Do you have plans to merge Merge this branch  into master?

**Comment by unocelli** [comment]
Hi,
the branch is not current and doesn't contain the feature. I’m working on a cards view where you can define the content of the card as table, list, etc….it's coming soon.

**Comment by peakcontrol** [comment]
Looking forward it：）

**Comment by anand1606** [comment]
still waiting table component and reporting tools, any update ?

**Comment by unocelli** [comment]
Hi,
not yet, is always on the todo list...it would be better if you open another issue for the reporting tools and explain what you mean.

**Comment by unocelli** [comment]
going to close this as resolved. let me know if you have any issues.
