### ISSUE TITLE
Historic Trend is not shown

### ISSUE THREAD

**Issue by sodaGin** [frangoteam/FUXA#561]
First of all, very nice project!

I have set up a system with several SiemensS7_PLCs with an Live Line-Chart and a Historic Line-Chart.
For Historic Linechart I use the same variable like the live chart.
The variables are "Registration Enabled".

Somehow the historic trend is not working and not showing any values.
What I get is following Warning:
![grafik](https://user-images.githubusercontent.com/96730103/197815079-959330cc-8fc6-432a-b79b-4e1fb1e306fe.png)

When I set everything up with only one connection, I get the same warning.
I can´t find the Problem. What am I doing wrong?
Thx
sodaGin

**Comment by unocelli** [comment]
This happens when the polling interval is shorter than the time it takes the server to read and handle the tag values from the PLC.
How many PLC and Tags are you try to connect? HW? OS?

**Comment by gosztek** [comment]
It is similar for me - no data on historical charts.

![image](https://user-images.githubusercontent.com/115475711/199428278-4a0aa2ae-3b80-4881-a2e8-79972a3eb105.png)


Data collection configured correctly. Any ideas?

![image](https://user-images.githubusercontent.com/115475711/199428627-3dea4a4f-8def-46bc-8196-b5c0debd4831.png)

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
