### ISSUE TITLE
Trigger sudo halt from Fuxa before power_shutdown

### ISSUE THREAD

**Issue by afbenevides** [frangoteam/FUXA#563]
Woulds there be a way to trigger sudo halt from a Fuxa button for example? I looked at the script option, but don't think it is available for now.

System is running on a PI, but before killing power on system It would be useful to be able to sudo halt without having to ssh in the machine.

Thanks

**Comment by mauroalexandre** [comment]
I need test, but I believe if you create a script SERVER MODE with require('child_process').exec('halt -p') and your server is running from root user work can work.

**Comment by afbenevides** [comment]
Worked thanks!
