### ISSUE TITLE
TAG property in modbus, can't change registration interval

### ISSUE THREAD

**Issue by afbenevides** [frangoteam/FUXA#564]
Hello i have an issue, 
In modbus, i am in rtu
I know I did change values in this panel to 1sec at some point, but for now it is not possible to change it. Also I can't disable save on change. Only the enable toggle and disable toggle works.

What am I missing here? Any idea?

![Capture d’écran, le 2022-10-26 à 19 10 46](https://user-images.githubusercontent.com/19934301/198156207-20bc46ef-da6c-46ec-adac-874d200811ac.png)

**Comment by unocelli** [comment]
Hi,
the feature has just been added, so you can find it on the master branch

**Comment by afbenevides** [comment]
OK i see must have been in another test I did with master branch. Thanks
