### ISSUE TITLE
Why the alarm popup windows cannot keep on the front

### ISSUE THREAD

**Issue by leeallen1234** [frangoteam/FUXA#572]
when i click the alarm icon，the popup window show about 2 second ,and then automatically close。

**Comment by unocelli** [comment]
Hi, please let us know all the versions involved (hw, npm, node, fuxa, ...)

**Comment by leeallen1234** [comment]
> Hi, please let us know all the versions involved (hw, npm, node, fuxa, ...)

Is already solved！，I updated the browser version，Thanks a lot！！

**Comment by unocelli** [comment]
Great, please can you close the issue. Thanks
