### ISSUE TITLE
How to import a library in a script

### ISSUE THREAD

**Issue by mariorl** [frangoteam/FUXA#574]
Hi, I'm looking for a way of save several user values on a local db, for example sqlite. So I'm using the script feature. But if I try to import modules with 'require' on the script, it wont work for me, and server log shows a message like "sqlite3 module not found". Since I noticed the script are not .js files but db items in the project database, is there a way to include an external module? Thanks!

**Comment by unocelli** [comment]
Hi, I think the best solution is to add your code directly into the server, without use the script editor in fuxa.

**Comment by mariorl** [comment]
ok, but js is not a skill on me, i think it is better to leave the server quiet. Fortunately I foud another issue where you answered to another user about to use 'fs' module, (¿filesystem?) and it worked for me also, within script editor. I used it archiving small contents like iframe server config, so that I serve flask content inside fuxa iframe, and python reads the config form this config file.

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
