### ISSUE TITLE
Can't Write to opcua tag using a button

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#577]
I am trying to write "100" value on my simulation opcua server. 
However, it doesn't write well, here is my configuration on my button.

![image](https://user-images.githubusercontent.com/49782655/200108043-6edc70ea-405e-4460-baef-17238b2cce38.png)

**Comment by unocelli** [comment]
Hi, what type is it?

**Comment by henjoe** [comment]
Hi @unocelli , 

It is a float (number) type of data.

**Comment by unocelli** [comment]
Can you send me a screenshot of device settings?
![image](https://user-images.githubusercontent.com/48684550/200122130-227ad22b-eddf-4916-baaa-635b00a7caa7.png)

**Comment by henjoe** [comment]
Hi, 

fyr.

![image](https://user-images.githubusercontent.com/49782655/200128011-21a27580-20e4-4cd6-9153-53f1ad4470a0.png)

**Comment by unocelli** [comment]
Can you send me the log file, or the output error in server? can you change the value of the other Counter?

**Comment by unocelli** [comment]
I will therefore close this issue, feel free to re-open it if something is still not working.
