### ISSUE TITLE
How to use value from output field's properties?

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#579]
Hello,

I don't understand  the usage of value from output field's properties.
![image](https://user-images.githubusercontent.com/58516894/200266202-92c32e9c-256e-44d4-9b49-0f52f61660b8.png)
As you can see in the above image, I have set the value and the unit for an output field. The value _33_ and unit _m_ are not displayed on runtime. If instead of a value, a tag is assigned, the tag's value and the unit are displayed on runtime. My question is how this value field should be used?

Many thanks in advance!

**Comment by unocelli** [comment]
Hi, 
if you do not have a tag to bind to the output control then it is simply a text.
Value =>  init value, as long as the Tag don't have a value
Unit => can be fix or dynamic by bind to a Tag 
Format digits => number of digits (ex. 2 = 0.00) can be fix or dynamic by bind a Tag

I agree that it could be simpler, it has to be redesigned.
