### ISSUE TITLE
sqllite index.js has a bug

### ISSUE THREAD

**Issue by GitTurboy** [frangoteam/FUXA#586]
At line 445 of server\runtime\storage\sqlite\index.js
 if (file.indexOf(id) > 0 && fromTo && fromTo.from <= tots && fromTo.to >= fromts) 
should change to
if (file.indexOf('\_'+id+'\_') > 0 && fromTo && fromTo.from <= tots && fromTo.to >= fromts) 
to avoid query history data for FUXA Server, which id is "0"

**Comment by GitTurboy** [comment]
if (file.indexOf('\_'+id+'\_') > 0 && fromTo && fromTo.from <= tots && fromTo.to >= fromts)

**Comment by unocelli** [comment]
Hi, thanks for the reports.
I will fix it

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
