### ISSUE TITLE
Submit buttons for input and select fields/elements

### ISSUE THREAD

**Issue by albosmart-ro** [frangoteam/FUXA#59]
How do i add a submit button (with confirmation) to the input and select fields/elements?

**Comment by unocelli** [comment]
Hi, currently it is not possible but I think it is a good feature

**Comment by albosmart-ro** [comment]
ok, thanks, i linked the button with the inputs, i added a select in the button setting so when you click on it it takes the values form the selected input/select in the button section

**Comment by unocelli** [comment]
Hi,
 with the last commit this feature is possible, look by events 'Set Input'.

**Comment by unocelli** [comment]
I'm assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
