### ISSUE TITLE
Some times  the items in DateRange select options have not been translated

### ISSUE THREAD

**Issue by GitTurboy** [frangoteam/FUXA#591]
shown like the image below
![err](https://user-images.githubusercontent.com/5795632/201584674-ef517038-c842-4aba-ab2b-6c400c44acf7.png)

Does anyone know where the system do the translation job?

**Comment by GitTurboy** [comment]
I found the reason of this problem:
At line 733 of  [client/src/app/gauges/gauges.component.ts 
       this.translateService.get(chartRange[key]).subscribe((txt: string) => { chartRange[key] = txt; });
we subscribe the response from translateService, if this function take more time than normal , return the result before the chart rendered, the select option items will keep untranslated status.
@unocelli ,do you think this thougth is right?

**Comment by unocelli** [comment]
Hi, Thanks for the report. 
Yes, I think you are right, I can reproduce it. I have to fix it.

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
