### ISSUE TITLE
Bitmask missing on pipe's action settings

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#594]
Hello,

As you can see in the below image, a pipe control cannot be stopped, turned clockwise or anticlockwise or hidden content depending on non-boolean tag's bit value (bitmask) and the fields are slightly offset of the + button. 

![image](https://user-images.githubusercontent.com/58516894/201861625-988e5118-08a5-44c5-9acf-65802e45ced2.png)

Could you please update this control with bitmask feature?
EDIT: I have noticed that other controls (button, led gauge, etc) don't have this bitmask feature.
Many thanks in advance!

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
