### ISSUE TITLE
 Why some bar graph's settings are doubled? 

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#595]
Hello, 

Could you please tell me why some bar graph's settings (Title, Value Axis, Category Axis, Legend) are doubled? 
If I change, for example, title font size, this is done in both Title Font size fields.
![image](https://user-images.githubusercontent.com/58516894/201916554-13c81a63-5ace-4874-8eb9-c7e2efb30e50.png)

**Comment by unocelli** [comment]
Hi,
I can't reproduce it and if you want to get a response from reporting issue, you need to take the time to investigate and provide adequate information how we can reproduce it.

please version of: fuxa, os, node, npm, browser etc.

**Comment by IonuDragomir1** [comment]
Sorry, it was my mistake. I solved the issue. Thanks!
