### ISSUE TITLE
Unable Select multiple element by pressing CTRL + Click

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [frangoteam/FUXA#598]
Hello @frangoteam, 
**FUXA** is excellent in very way! 💚 
I come across hurdle, where unable Select multiple element by pressing CTRL + Click to align or distribute element already on canvas.
Is there any alternative way to perform this action.

Regards,
PS

**Comment by unocelli** [comment]
Hi,
do you mean SHIFT + Click?

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
