### ISSUE TITLE
Editor: load demo project from help menu

### ISSUE THREAD

**Issue by unocelli** [frangoteam/FUXA#6]

**Comment by ATwins-8** [comment]
An error will be reported in fuxa-editor.min.js file: 
console.log :1 error: < Path > attribute d: expected move to path command ('m 'or' m '), "L 5 L 10 10 10";

**Comment by unocelli** [comment]
Hi,
I know, I will try to fix it as soon as possible, however it has no
consequence on the correct functioning of the application.

Il giorno mar 26 nov 2019 alle ore 07:47 ATwins <notifications@github.com>
ha scritto:

**Comment by ATwins-8** [comment]
When Firefox is running editing projects, the console will report an error: error typeerror: "u.clear is not a function". The reason for the error is the code in fuxa.editor.min.js. When you select Firefox to edit, drag the shape icon on the left to the canvas to report the above error. Not in Google.

**Comment by ATwins-8** [comment]
Because you have packed the compressed code, I have not found the corresponding solution
