### ISSUE TITLE
Changing Fuxa theme no longer available

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#602]
Hello, 

I have noticed that changing the theme is no longer available like in earlier Fuxa version.  Is there a reason why this feature was removed? Could you please bring it back?

**Comment by unocelli** [comment]
Hi, involves more work, it would be interesting to know how many are interested in the light theme

**Comment by IonuDragomir1** [comment]
Thanks for reply!
It was a useful feature. Knowing that it was once available, I thought that it'd be easy to bring it back.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
