### ISSUE TITLE
Discord community for FUXA?

### ISSUE THREAD

**Issue by Rafael-OliveiraBR** [frangoteam/FUXA#607]
Hey guys.

A lot of open source communities have an discord channel for members to interact to each other (voron, printNC, flipper, for example).
Since this is a under development project, i think would be good for users to have a channel to interact with others without the need for open issues here.
Keeping people close bring new ideas to the table, makes feedback more reliable, can become a source for refference materials, people often try to help with issues from others. 
Having a discord channel could make FUXA evolve faster.
Just an idea.

: )

**Comment by unocelli** [comment]
Hi, thanks for the suggestion, really interesting. totally new to me, i just opened a channel (i think) can you give me some tips
https://discord.gg/Gp8H4w6Pmh

**Comment by unocelli** [comment]
Now available
