### ISSUE TITLE
Bar Graph - Color by value

### ISSUE THREAD

**Issue by AlexandruAndrei3** [frangoteam/FUXA#609]
Hi, it would be a nice feature if you could add a feature sou we can add bar graph colors like in image shown bellow. I saw that this on another objects alredy exists.
![BarGauge](https://user-images.githubusercontent.com/94168341/203817694-21789c9f-7b90-49ba-bd5a-65cbf58c6869.JPG)

**Comment by unocelli** [comment]
Hi, currently is not planned, but you could use several bar gauge in line and each has its own range.
![image](https://user-images.githubusercontent.com/48684550/203967895-0e5b73b4-8d7a-4485-a4a2-2616464dd548.png)

**Comment by AlexandruAndrei3** [comment]
Thanks i will keep in mind your suggestion but i would like that the color of the entire bar graph to be changed.

**Comment by unocelli** [comment]
Hi, #1285 with more options

**Comment by DHIAFIQ** [comment]
> Hi, it would be a nice feature if you could add a feature sou we can add bar graph colors like in image shown bellow. I saw that this on another objects alredy exists. ![BarGauge](https://user-images.githubusercontent.com/94168341/203817694-21789c9f-7b90-49ba-bd5a-65cbf58c6869.JPG

why in my fuxa not have option to add another min and max
