### ISSUE TITLE
No historical data displayed on the graph.

### ISSUE THREAD

**Issue by haitan981** [frangoteam/FUXA#611]
I don't see historical data showing up on the graph. Everything is empty. While Real Data is still available.How to enable data storage
Thank you so much.
![image](https://user-images.githubusercontent.com/44091731/203925169-48b3e4ae-8b1e-43ea-8533-1b2f750e3283.png)
![image](https://user-images.githubusercontent.com/44091731/203923986-97ff7e4f-e691-4422-9ea3-6af830752142.png)

**Comment by unocelli** [comment]
Hi, you have to enable the tags for history
![image](https://user-images.githubusercontent.com/48684550/203970841-d2cea7c1-8f5d-4116-9d80-19a31eacd04b.png)

**Comment by haitan981** [comment]
> Hi, you have to enable the tags for history ![image](https://user-images.githubusercontent.com/48684550/203970841-d2cea7c1-8f5d-4116-9d80-19a31eacd04b.png)

thank you so much. I done

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
