### ISSUE TITLE
Error when trying to open a FUXA project

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#625]
Hello,

When I want to open a project, I get in the right corner the message "Project save failed". Even though the project is loaded, I'm getting "TypeError: Cannot read property '0' of undefined" error on console when I want to open a project (please see the below image). 
I'm running FUXA version 1.1.9. 

![image](https://user-images.githubusercontent.com/58516894/205909536-096eb598-9253-4f4e-b640-8dcfaa0e7bb1.png)

How could I please solve this issue?

**Comment by unocelli** [comment]
Hi,
happens for any project? also happens when you create a project?

**Comment by IonuDragomir1** [comment]
I encountered this error only with some projects. When I create a new project, everything is OK.

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
