### ISSUE TITLE
Chart Functionality Not working

### ISSUE THREAD

**Issue by Harshid93** [frangoteam/FUXA#63]
Hi,
i just found that Chart is not working in this version.
i am not able to assign any TAG to Chart.
its not aalow me to assign any TAG in chart. Can you please check this...?

**Comment by unocelli** [comment]
Hi, you have defined the chart to assign to the chart object ?
[https://github.com/frangoteam/FUXA/wiki/HowTo-Chart-Control](https://github.com/frangoteam/FUXA/wiki/HowTo-Chart-Control)

**Comment by Harshid93** [comment]
Yes Thanks it is Working....!
