### ISSUE TITLE
Error: array exceeds max variables (20) that can be transferred with ReadMultiVars()

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#630]
Hello,

When I'm trying to add more than 20 tags in a device which connects to a Vipa M13C PLC, I'm getting " **__readVars error! TypeError: Array exceeds max variables (20) that can be transferred with ReadMultiVars()_**" error message (please see below image). For this connection I use SiemensS7 protocol, Fuxa version is 1.1.10 (I have tried also the version 1.1.9, but the error persists) . This error occurs when I add 21st tag and no value is displayed anymore until only 20 tags remain.
Could you please tell me why I get this error and how could it be solved?

![image](https://user-images.githubusercontent.com/58516894/206148452-e45e559b-4691-4358-a03e-45965abfce23.png)

**Comment by unocelli** [comment]
Hi,
let me know what version of nodejs and npm you have installed.

**Comment by IonuDragomir1** [comment]
Hi,

nodejs version: v14.17.4
npm: 6.14.14

**Comment by unocelli** [comment]
This issue should be fixed in the latest version.

**Comment by IonuDragomir1** [comment]
Hi,
I have tested on the last version and is not fixed.

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
