### ISSUE TITLE
Circular gauge background color

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [frangoteam/FUXA#631]
Hello @frangoteam,
Any way i can make circular gauge background color to custom or relative to angle of gauge?
![image](https://user-images.githubusercontent.com/91423165/206174683-adac23de-08f8-46bf-a29b-5713e16f986d.png)

Thanks!,
sdrshnptl

**Comment by OptifySudarshanPatil** [comment]
Resolved!
Click on bottom bar
![image](https://user-images.githubusercontent.com/91423165/206176216-b6ee45d8-2ed4-4e50-91cd-864486d5dbde.png)

Now look like this..
![image](https://user-images.githubusercontent.com/91423165/206176351-35cfe81e-7827-4afb-a3e1-edf6cf373b3f.png)

**Comment by H-hejin** [comment]
This is great
