### ISSUE TITLE
USe this With Raspberry Pi

### ISSUE THREAD

**Issue by Harshid93** [frangoteam/FUXA#64]
I want to use this scada in Raspberry pi.
How can i use it?

**Comment by unocelli** [comment]
Hi, in my raspi 3B work fine, a little warning by installation

python v2.7.13
nodejs v10.16.3
npm v6.9.0

 I tested it with modbus and opcua

**Comment by Harshid93** [comment]
csn you please provide with latest versions?

**Comment by unocelli** [comment]
what do you mean?

Il giorno dom 20 dic 2020 alle ore 12:10 Harshid93 <notifications@github.com>
ha scritto:

**Comment by Harshid93** [comment]
I only Want to Know , IF we want to run this over Latest Version of python 
nodejs npm is it possible?
Coz Every time i need to Downgrade My Software Version to Run this...

**Comment by concept10** [comment]
> I only Want to Know , IF we want to run this over Latest Version of python
> nodejs npm is it possible?
> Coz Every time i need to Downgrade My Software Version to Run this...

You should be able to run this software on any platform that supports the requirements, including raspberry pi.  You would be better served posting the versions of the software that you are currently attempting to run this on (for example node -v && npm -v).
