### ISSUE TITLE
Not found modbus tcp

### ISSUE THREAD

**Issue by jinyistudio534** [frangoteam/FUXA#644]
My **fxua is 1.1.10.** Install in windows 10 and **Node.js is v16.17.1.** 
I cann't found modbustcp !
![image](https://user-images.githubusercontent.com/121013147/208380579-ceb7ef14-8461-48ff-a3da-cdb26a3a67bc.png)

**Comment by sergey-grigorovich** [comment]
Hello! I think you need to install ModbusRTU plugin in plugins

**Comment by jinyistudio534** [comment]
ok
