### ISSUE TITLE
Import Project Issues

### ISSUE THREAD

**Issue by jiawentao-2004** [frangoteam/FUXA#646]
If the view backup file is selected when importing a project, Will cause system crash.

**Comment by unocelli** [comment]
Please, can you explain more in details what you mean?

**Comment by jiawentao-2004** [comment]
> 

https://frangoteam.github.io/
The demo environment has been down. You can analyze the reasons. This is caused by my import project.

**Comment by unocelli** [comment]
The demo is a offline version that work in your browser only, project are saved in LocalStorage
