### ISSUE TITLE
Cann't setting logo

### ISSUE THREAD

**Issue by jinyistudio534** [frangoteam/FUXA#647]
My fxua is **1.1.10**. Install in **windows 10** and Node.js is v**16.17.1**.
**I cann't select logo**
![image](https://user-images.githubusercontent.com/121013147/208821571-eba9337e-3a92-4cd6-8748-9fd205ed6698.png)

**Comment by unocelli** [comment]
Please look solved issues #543

**Comment by unocelli** [comment]
you have to search where npm have installed fuxa.
for example ubuntu in windows npm install in `c:\Users\[...]\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\[...]\.nvm\versions\node\v14.19.1\lib\node_modules\@frangoteam\fuxa`

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
