### ISSUE TITLE
View Editor - Alignment tools needed

### ISSUE THREAD

**Issue by concept10** [frangoteam/FUXA#648]
For view development purposes, it would be nice to have exposed alignment tools that distributes view elements (horizontally/vertically) evenly across the canvas.  

Inkscape screenshot (align and distribute tools)

<img width="413" alt="inkscapeCapture" src="https://user-images.githubusercontent.com/536986/209207463-0b3adc87-938d-4ce3-87ce-89cf8eb8f654.PNG">

**Comment by unocelli** [comment]
there are 
![image](https://user-images.githubusercontent.com/48684550/209566112-a989440f-5e66-40c8-aff3-21f07a93833d.png)

**Comment by concept10** [comment]
Thanks for commenting.  I'm sure I have worked with those tools before, but for some reason (possible older version) they were not showing up!   Closing issue!

**Comment by aniston** [comment]
![image](https://github.com/frangoteam/FUXA/assets/3067891/e1c05dba-40bc-4076-b427-34cc2c7fdeb0)

@unocelli in my Docker version 1.1.15-1269 of Fuxa the top Alignment tools are not showing up, the right side Align properties does show, any tip how to show them ?

**Comment by unocelli** [comment]
Hi, you have to select more than one element.

**Comment by aniston** [comment]
Oh, forgot about that, indeed it shows, Thanks, was concentrated on looking only at the right side align menu.

on a side note, i did select multiple elements before but did not realise that the "Selected Elements" alignment options would show up at the top arther than at the richt side "Alignment properties", hence i missed noticing the top "Alignment menu" and jumped onto this issue.

OffTopic: the MQTT addition is lovely addition, it opens up many possibilities, nice work there.
