### ISSUE TITLE
server tag - cant write string 

### ISSUE THREAD

**Issue by TomasAdvance** [frangoteam/FUXA#658]
Hi Fuxa team,
I found strange behavior of fuxa server tags, if you set up as string variable, then do not accept string value, only number value are accepted.

**Comment by unocelli** [comment]
Hi,
I suppose you mean the tags in FUXA Server...We'll fix it as soon as possible. Thanks for the report

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
