### ISSUE TITLE
Driven by opc-ua, when the data type is Boolean, when the value is true, the data display error.

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#659]
![image](https://user-images.githubusercontent.com/102520227/211276825-5d424aa2-08fb-49cc-a66d-58649d6dc848.png)

There is a problem with the latest version, the old version is fine

**Comment by hxjackcn** [comment]
Driven by opc-ua, some analogs also have problems.

**Comment by unocelli** [comment]
Hi,
We have tested with more than 1000 tags without noting any problems. drivers seem to work very well. try to reinstall node_modules (remove before)

**Comment by hxjackcn** [comment]
Already reinstalled node_modules, problem persists

![image](https://user-images.githubusercontent.com/102520227/212481775-6925022f-e23a-4211-9c10-fd4bc9730d25.png)


![image](https://user-images.githubusercontent.com/102520227/212481535-99aa1611-6326-4867-89b3-15d97d293493.png)

**Comment by unocelli** [comment]
Hi,
I think we have found and solved the issue

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
