### ISSUE TITLE
REPORT IS NOT WORKING 

### ISSUE THREAD

**Issue by patson12** [frangoteam/FUXA#661]
PLEASE FIND ATTCHMENT.. I GOT THIS ERROR EVRYTIME WHEN WE SEND REPORT.. 
![Capture](https://user-images.githubusercontent.com/96180028/211729098-b4bd1206-71e5-415f-ba4d-d370a4cb2e58.JPG)

**Comment by unocelli** [comment]
Hi,
have you configured and tested the SMTP?

**Comment by patson12** [comment]
yes i have configured.. problem is here in function report found is false..

**Comment by unocelli** [comment]
currently you find a version on the branch master that allows you to check the generated reports. we can try checking the log file.

**Comment by patson12** [comment]
ok its working fine in branch master.. 
thanks :)
