### ISSUE TITLE
specific tag payload - timestamp -  not processed correctly anymore in MQTT device

### ISSUE THREAD

**Issue by iw65ihg** [frangoteam/FUXA#662]
I experienced a change going from 1.1.9 to 1.1.10
 
the payload "01/16/2023, 19:33:33" was correctly processed in 1.1.9.
Same payload is received as "1" in 1.1.10

![mqtt_payload_1 1 9](https://user-images.githubusercontent.com/4488471/212879994-772307fe-c58f-4f5c-b6c6-04147cf71c3a.png)
![mqtt_payload_1 1 10](https://user-images.githubusercontent.com/4488471/212880026-8a4ba217-54c0-49e9-8859-e05559d60336.png)

**Comment by unocelli** [comment]
Thanks for the report. We have to fix the function that check if is a number.  
with date `01/16/2023` fails
```
    var num = parseFloat(n);
    return !isNaN(num) && isFinite(num);
```

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
