### ISSUE TITLE
chart history is not working device tag

### ISSUE THREAD

**Issue by patsonkaushik** [frangoteam/FUXA#663]
https://user-images.githubusercontent.com/77775964/213081488-670b9662-c881-4391-bdf3-d0561f59f915.mp4

**Comment by unocelli** [comment]
Hi,
you have configured a history chart. have you enabled the archiving of tags values?

**Comment by patsonkaushik** [comment]
where can i found option to archive tags?

**Comment by patsonkaushik** [comment]
And Internal device tag value after chart history possible ?

**Comment by unocelli** [comment]
to enable history #611.
No, internal device is only in frontend. you can use fuxa server tags.

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
