### ISSUE TITLE
report list bug 

### ISSUE THREAD

**Issue by patsonkaushik** [frangoteam/FUXA#664]
=>1 report generate list after 2 report generate not build generate but liist show resport file
=> report delete but file not delete

https://user-images.githubusercontent.com/77775964/213095335-a1cadab3-aa71-4a5c-8e45-ff913da94b12.mp4

**Comment by unocelli** [comment]
Hi, thanks for the report.
I have to add a validator so as not to have 2 reports with the same name. also because it makes no sense.

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
