### ISSUE TITLE
Daq with influx DB cannot read history chart

### ISSUE THREAD

**Issue by saufister** [frangoteam/FUXA#665]
Hi , i actually try to move from sqlite to influx db , all thing already setup and data saved successfully into influx db ( i see with influxdb data explorer ) , but data cannot show on history chart, in sqlite everything is OK, can you help me whats going on ?

**Comment by unocelli** [comment]
Hi, Thanks for the report

**Comment by saufister** [comment]
thanks for your help

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
