### ISSUE TITLE
How to running new update fuxa in docker container without losing data 

### ISSUE THREAD

**Issue by zuldemort24** [frangoteam/FUXA#666]
Hi, i am running fuxa on docker using image that i build from Dockerfile in fuxa repository  with this script : docker run -d -p 5500:1881 -v fuxa_appdata2:/usr/src/app/FUXA/server/_appdata -v fuxa_db2:/usr/src/app/FUXA/server/_db -v fuxa_logs2:/usr/src/app/FUXA/server/_logs  myFuxaImage . 

Now i want to rebuild docker image with new version of fuxa on master channel without losing my db data . How to do that ? , i try rebuild image docker and running script above : docker run -d -p 5500:1881 -v fuxa_appdata2:/usr/src/app/FUXA/server/_appdata -v fuxa_db2:/usr/src/app/FUXA/server/_db -v fuxa_logs2:/usr/src/app/FUXA/server/_logs  myNewImage. The data cannot be loading into history . Please help me. Thanks

**Comment by unocelli** [comment]
Hi,
you project are saved into _appdata, your daq history are saved into _db, the both are in external volumes, if you install the new docker version you should not lose the data

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
