### ISSUE TITLE
Add Internationalization of zh-cn

### ISSUE THREAD

**Issue by feast107** [frangoteam/FUXA#675]
Nice to meet you.
It seems Chinese internationalization resource has been un-updated for long.
What if I put some translation in which will be match with the latest en.json. Some unproper translation shall be fixed at the same time

**Comment by feast107** [comment]
By the way, Im working on connecting to SignalR Server as a new type of device, which is microsoft's real-time application and works like Websocket. Is there any possibility to add it into the main? The workflow can be seen in my fork.

**Comment by unocelli** [comment]
Hi,
of course you can update and complete the zh-cn translation, you are welcome.
on the subject of signalR we find it interesting. in which context you want to use it?

**Comment by feast107** [comment]
In ```Device Setting``` that can add new device whose type is ```signalR``` ,just use it to watch real-time value like mqtt's 'pub/sub' but working on another transportation protocol and a certain server.

**Comment by unocelli** [comment]
do you plan to define your own tag object?
