### ISSUE TITLE
Operator or Viewer only access

### ISSUE THREAD

**Issue by ViolentPillow** [frangoteam/FUXA#680]
I may be a complete fool, but I am failing to understand how an operator level person can view this remotely, as in, across a network without running the server on their machine. P.S. this is a great HMI software I am in love! It's quick and easy.

**Comment by Obaq-web** [comment]
The operator's computer needs to be in the same network as the server where fuxa is running on.

To connect from, lets say a mobile 5G-device, you need a VPN to the network where the server is running.

**Comment by ViolentPillow** [comment]
Forgive me, yes, my network was set to public and not private. My firewall was quietly swatting me. So, sorry!

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
