### ISSUE TITLE
Why is my menu missing some options

### ISSUE THREAD

**Issue by pengju97** [frangoteam/FUXA#681]
![image](https://user-images.githubusercontent.com/105717835/216221207-9c36e218-1d72-4d73-ad38-a63dbebc1b41.png)
https://frangoteam.github.io/
domo
![image](https://user-images.githubusercontent.com/105717835/216221275-ad3d749e-1d0e-4628-83aa-2a3f62df14e0.png)
I was deployed by docker，How to solve this p
blem？？

**Comment by unocelli** [comment]
Hi, which version are you using?

**Comment by pengju97** [comment]
![image](https://user-images.githubusercontent.com/105717835/216876795-46baf4d0-5b47-4c4f-8f7f-a6989db8eaaf.png)

**Comment by pengju97** [comment]
![image](https://user-images.githubusercontent.com/105717835/216876853-4c7aef02-da9c-47f8-9cfa-908f9deb4bde.png)

**Comment by pengju97** [comment]
> Hi, which version are you using?

![image](https://user-images.githubusercontent.com/105717835/217195619-d0012231-ad2d-4c34-a744-cd8a38b2fedc.png)

**Comment by unocelli** [comment]
You need to install the latest version
