### ISSUE TITLE
i want to add my own svg menu

### ISSUE THREAD

**Issue by patson12** [frangoteam/FUXA#693]
hello ,
i want to add my own svgs in menu .. or i want _images folder from client side right now i cant get this folder i get that error in error.jpg file
![error](https://user-images.github
![error2](https://user-images.githubusercontent.com/96180028/219283853-35ca6f68-cbbb-4daa-8709-e965d13ac917.JPG)
usercontent
![error](https://user-images.githubusercontent.com/96180028/219284190-c709565d-b868-41d3-afb4-68cc9e5aa49a.JPG)
.com/96180028/219283630-e62f297c-1a93-4260-85ca-2e524fd31a6f.JPG)

i want svgs like this from client side. which is only getting rightnow from server side.
![Capture2](https://user-images.githubusercontent.com/96180028/219283943-e0062996-bbbc-420e-8120-6c4666fb8dd5.JPG)

**Comment by unocelli** [comment]
Hi, you are in debug mode (http://localhost:4200), you have to use production port http://localhost:1881

**Comment by patson12** [comment]
what if i want to use http://localhost:4200/ ?? can ypu plz help me?

**Comment by unocelli** [comment]
url with port 4200 is used from angular to serve the frontend application in development and your resource (images) are available in fuxa web server (nodejs/express), url displayed in the console when starting the server.

**Comment by patson12** [comment]
ok done.. thanx
