### ISSUE TITLE
Already connected to MQTT, but topic cannot be found？

### ISSUE THREAD

**Issue by pystudy123** [frangoteam/FUXA#704]
![Snipaste_2023-02-22_09-50-23](https://user-images.githubusercontent.com/57655202/220500685-57c941ce-f944-4b32-abab-7c9d7ab0f5b2.png)

![Snipaste_2023-02-22_09-50-42](https://user-images.githubusercontent.com/57655202/220500716-58d4a6e4-5bb0-4846-80c8-201cf86c6d15.png)

![Snipaste_2023-02-22_09-51-00](https://user-images.githubusercontent.com/57655202/220500759-043e8523-5338-4430-92d4-3a8239509b64.png)

Already connected to MQTT, using emqx, you can see 2 topics, but the topic cannot be found.
Can you directly fill in the subject content, and then connect, what is wrong?

**Comment by jumpyBah** [comment]
I have the same problem too.
The mosquitto broker works fine

**Comment by schmicky** [comment]
Hi, I am not from the development team but I have this suggestion which worked for me:
press the Search Icon (i see in the screenshot you already pressed it), this puts FUXA in discovery mode,
then use some other tool to generate events on the addresses you want to add,
for example, I used MQTT Explore to change some values in the addresse. When I did that, Fuxa detected the mqtt traffi and the addresse showed up in the menu and i was able to subscribe to them.

Cheers,
George

**Comment by schmicky** [comment]
Please test if you can send the value 0 using MQTT, because this is the issue I have. I can send any numeric value except for 0

**Comment by unocelli** [comment]
Hi, I suppose that there are the same issue (#435, #242) and we will finally improving it. we will make a subscription available even without the topics browsing function.

**Comment by jumpyBah** [comment]
Works !
Thanks schmicky for the trick and thanks unocelli for the improvement

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
