### ISSUE TITLE
Historical data doesn't work properly.

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#711]
Hi,

I'm trying to display a graphic width historical data. For this I have created a connection to a S7_1500 Siemens PLC having 1 sec polling. Within connection, a tag with a save value interval of 180 seconds (3 minutes) was created.
![image](https://user-images.githubusercontent.com/58516894/221130231-05ff4723-c118-4955-b4e8-38620935ec64.png)
![image](https://user-images.githubusercontent.com/58516894/221130419-f9db2c9c-5e85-4ece-bef5-8d405d719f5d.png)
Then the tag was bound to a chart.
![image](https://user-images.githubusercontent.com/58516894/221131064-a1370de0-a7c3-490a-93e8-9b3bf6023f51.png)
Chart's settings are: 
![image](https://user-images.githubusercontent.com/58516894/221133981-cbe204fa-e63b-4289-9a8f-233ca76e7091.png)
The result is the following:
![image](https://user-images.githubusercontent.com/58516894/221131378-8a3eebf5-8de2-420a-bab4-20a37ea0d8eb.png)
As you can see in the below image, the graphic is showing tag's changing value after a second (connection's polling time). So my conclusion would be that the tag is not archived at each 3 minutes. I have used Fuxa v1.1.11 - 1064.

**Comment by ProfDrOetker** [comment]
Disable "Save value on change"

**Comment by IonuDragomir1** [comment]
@ProfDrOetker, thanks for your solution. It works now as expected.

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
