### ISSUE TITLE
svg image problem

### ISSUE THREAD

**Issue by patson12** [frangoteam/FUXA#712]
i have uploaded some svg file in _image folder in server side but when i put into editor it doent acctualy added in perticular place .. it places approx 1250 x and 1000 y every time.. attached my svg here..PFA
thanks and regards
![magicpattern-svg-chart-1676348018155 - Copy (2)](https://user-images.githubusercontent.com/96180028/221347911-bc192bc8-0e81-4532-ad58-2aed84443758.svg)

**Comment by unocelli** [comment]
Hi, your issue is not very clear or we can't reproduce it, we were able to add and place the image as expected
