### ISSUE TITLE
Could be used tag's name instead of tag's id?

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#715]
When I want to call a tag inside a script using a function, I get tag's ID. Did you consider using tag's name instead of its ID? 
![image](https://user-images.githubusercontent.com/58516894/221563490-a1352305-091d-4463-b1e5-feb46547356c.png)
The reason I'm asking this is because in case I reuse the script code in another project, I'd have to add each tag again in script because the IDs don't correspond anymore. I suppose it'd not be the case if tag's name would be used.

**Comment by unocelli** [comment]
Hi, 
but then the function parameters should be deviceName and tagName, otherwise you receive an array of tags.

**Comment by IonuDragomir1** [comment]
Hi @unocelli,
In all SCADA software, a tag is called by its name. I agree that each tag should have an unique id, but it shouldn't be displayed for user. 
So if an user has added 3 devices (D1, D2, D3). In D1 can be created  several tags (T1, T2, T3). In D2, the user shouldn't be allowed to create tags with names: T1, T2, T3. So if I want to call tag T1 in a script, I should see it by its name, not by its ID. 
Below you can see a screenshot from WinCC where a tag with same name cannot be created and another screenshot with how a tag is called in a script by name.
![image](https://user-images.githubusercontent.com/58516894/222092485-5f550ca5-a31b-4038-9c85-a1855d4e751c.png)
![image](https://user-images.githubusercontent.com/58516894/222096011-590320c1-a4d8-43ad-98f1-40bcf3243b1a.png)
Once I have tried to read some tag's values using an API. It's very hard to do this because the devices and tags were represented by ID, not by name.

**Comment by unocelli** [comment]
to uniquely identify a tag you can either use the name or a uuid, both are inefficient. a uuid is also definitely advantageous, example when you want to copy a device automatically. two devices can both have the same Tagname 'Temperature'.

**Comment by TomasAdvance** [comment]
Hi Fuxa team,
will be posible add function getTagName from TagId. Will be helpfull in some cases in scripts.
BR
T

**Comment by unocelli** [comment]
Hi, I would be grateful if you could add it as a new issue.
