### ISSUE TITLE
TypeError: Cannot set property 'value' of undefined

### ISSUE THREAD

**Issue by gabrielbalinca** [frangoteam/FUXA#719]
Hi,
I'm getting this message in console:

![image](https://user-images.githubusercontent.com/32384258/222668340-ba14fd3b-603d-4357-8e17-efb4d7d72062.png)

This error appears only when I assign an external tag's value to a server internal tag. The associations is made with a script.
```
var temp;
temp=$getTag('t_31b9efe4-f4c141b8' /* Local Kep Server - Test1 */);
$setTag('t_bdb44cbd-56eb4622' /* FUXA - int */, temp);
```
When I go to Connections to see internal tag's value but I do get the error in console.  Although I get the error, the script runs correctly and the value is transferred to the internal tag. Why I am getting this error?

**Comment by unocelli** [comment]
Hi,
internal tag are available only in frontend, we have to fix it so that you cannot choose in script editor the internal device tags.
I would use fuxa server tags.

**Comment by gabrielbalinca** [comment]
For testing I used tags created in FUXA server and I am aware of the fact that I cannot use frontend tags in scripts.
![image](https://user-images.githubusercontent.com/32384258/222708736-b9f8a3a3-9725-4f50-b7c9-37c4db9cfc44.png)

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
