### ISSUE TITLE
Background color and border of the output control

### ISSUE THREAD

**Issue by jcxjcx123** [frangoteam/FUXA#723]
Hi!
How to change the background color and border of the output control? I noticed that the output control has no background color, so I studied the code and tried to add the background color to the output control, but I don't know how to do it. Could you please give me some advice, thank you;
![image](https://user-images.githubusercontent.com/41283780/223329034-2ad65f67-0579-43e7-83b2-9a98c9787e9c.png)

**Comment by unocelli** [comment]
Hi,
in svg it is a simple text and there is no container, but you are still free to add it with a shape
