### ISSUE TITLE
date/time control

### ISSUE THREAD

**Issue by patson12** [frangoteam/FUXA#726]
i am going to add date/time control in control expansion panel.. but it shows me blank in editor.. can you help me to add this new control ? or can you add this to in your version??
![Capture123](https://user-images.githubusercontent.com/96180028/224016589-9bfdaff2-d24f-4ff5-a50d-46e0a9a1d8f3.JPG)

**Comment by unocelli** [comment]
Great, a datetime control is also in our TODO list, we can try to help you. We have created a 'datetime-control' branch where you can do the Pull Request with your changes.

**Comment by patson12** [comment]
can you help me to change current  date time live time in launch project

**Comment by unocelli** [comment]
is there any news? can you please explain why you don't solve it with a script?

**Comment by unocelli** [comment]
date/time control are in the last version available
