### ISSUE TITLE
Cannot add new connections? 

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#735]
The "type" field is disabled.
![image](https://user-images.githubusercontent.com/49782655/225320829-9918f9b2-3fd1-4645-b29f-02a4ab50a8f6.png)

who can I access this?

**Comment by mariorl** [comment]
The same happened to me, while accesing FUXA from another machine. To solve it I set up a remote desktop connection to the FUXA server (VNC or other) and lauch a browser session inside FUXA server, then I noticed the new connection dialog fields are allowed to edit. Once I created a new connection in this way, and click on save project, the dialog get working on remote machine also. I also restart FUXA in server machine, not sure if it was actually necesary.

**Comment by unocelli** [comment]
Hi,
This should happen because you open a session by going directly into edit mode without going through home.
We have to fix it, as workaround if you go to home and then go back to edit should work again

**Comment by henjoe** [comment]
Thanks! I'll confirm that.
