### ISSUE TITLE
About "AUTO" property on trend graph Y ranges scaling.

### ISSUE THREAD

**Issue by mariorl** [frangoteam/FUXA#736]
The auto property as a fixed option is useful as it always work. This is, whatever datalogging vars values will take, you will never get the trend lines off of the canvas, as it adapts the Y ranges to get traces inside. 
But in certain cases it is not desirable, because many measurements like PH, level etc, may vary very little, for example 0'2, so the graph stretchs the Y axis range in a way that appears as the measurements have got a great value change, but it didn't do.
![Screenshot 2023-03-15 at 22-15-57 FUXA](https://user-images.githubusercontent.com/6344456/225445780-df325888-b5d2-4fa4-abea-dc6484997a2b.png)

**Comment by unocelli** [comment]
Hi,
you mean that it would be useful to be able to set the min and max of the y-axis?

**Comment by mariorl** [comment]
> Hi, you mean that it would be useful to be able to set the min and max of the y-axis?

Yes

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
