### ISSUE TITLE
No page on navigation? 

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#738]
Hi, I already created 2 page on editor, but I cannot see it on my navigation? is this a bug? 

![image](https://user-images.githubusercontent.com/49782655/225574583-c6045f4e-72b6-4d6a-9524-e0c06c060b7f.png)

**Comment by malcore10** [comment]
[side navigation settings](https://github.com/frangoteam/FUXA/wiki/HowTo-UI-Layout)

**Comment by unocelli** [comment]
I am going to close this as resolved, let us know if you have any issues.
