### ISSUE TITLE
自定义得控件 怎么能让它拖拽出来

### ISSUE THREAD

**Issue by rgw123** [frangoteam/FUXA#740]
![image](https://user-images.githubusercontent.com/112950683/225799687-e5e73b74-215a-4f11-9a0f-177c2c086bec.png)

**Comment by rgw123** [comment]
就是只能在列表中显示出来 但是不能拖拽到编辑器页面上

**Comment by rgw123** [comment]
@concept10 @concept10 @NikolayMurha @tromgy @kevin100702

**Comment by unocelli** [comment]
?
