### ISSUE TITLE
Cannot read properties of undefined (reading 'tags') when refreshing Connections page

### ISSUE THREAD

**Issue by gabrielbalinca** [frangoteam/FUXA#745]
When I refresh Connections page this error show up in console : 

![Screenshot 2023-03-20 101947](https://user-images.githubusercontent.com/32384258/226285447-98792009-b122-4d75-9672-43e71c0e6ee2.png)

**Comment by unocelli** [comment]
Hi, Thanks for the report.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
