### ISSUE TITLE
Rotate and Move actions not available everywhere

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#747]
Hello,
If I'd want to rotate or move a shape (square) I have the possibility of rotating or moving the shape. This actions are no longer available  to a proc. eng. object, image or SVG (please see the attached picture). It'd be very useful if this this actions could be applied for every kind of object added on interface.

![image](https://user-images.githubusercontent.com/58516894/226336870-5e75556f-c9e4-46e3-bb11-fc14ba491442.png)

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
