### ISSUE TITLE
Editor issue

### ISSUE THREAD

**Issue by top58525785** [frangoteam/FUXA#748]
Version: FUXA-1.1.11-3
HI are u meet with this problem?
Index is OK
but the editor can not come out,always  flashing...
Look at the vedio? How to fix? 

https://user-images.githubusercontent.com/54358179/226567543-7da77dcb-f599-4d5d-aa54-cc12a0384f71.mp4

**Comment by top58525785** [comment]
Thanks
The server is ok&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Ionut ***@***.***&gt;
Date: Tue,Mar 21,2023 6:18 PM
To: frangoteam/FUXA ***@***.***&gt;
Cc: top58525785 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [frangoteam/FUXA] Editor issue (Issue #748)





 
Hi,
 Check if the server is running (maybe the console got stuck).

**Comment by unocelli** [comment]
Hi, 
the red progressbar on the top show that you have problem to communicate with the server, which version are you using?

**Comment by top58525785** [comment]
Version: FUXA-1.1.11-3

**Comment by top58525785** [comment]
Also when i using fux 1.1.12 it is not easy to install~~

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
