### ISSUE TITLE
Can't color a grouped object depending on a chosen color

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#749]
Hello,
I can't color a grouped object depending on a chosen color from a select value object. If I try to color, in the same manner, a rectangle for example, it works perfectly. 

![image](https://user-images.githubusercontent.com/58516894/226619827-e1711fff-d1f8-410b-b8ab-3133e8f3268d.png)

Select Value's Property settings:
![image](https://user-images.githubusercontent.com/58516894/226620444-3c856aca-78a2-4930-9732-44b2bdd16007.png)

Rectangle's and grouped object's Property settings:
![image](https://user-images.githubusercontent.com/58516894/226621398-7003b7fa-8723-4e9a-9956-efa31c419f28.png)

**Comment by unocelli** [comment]
Hi, Thanks for the report.
Grouped shapes have some limitation that we will improve as soon as possible

**Comment by IonuDragomir1** [comment]
Hi,
Do you have any update on this topic? It's a pretty important and useful feature.

**Comment by unocelli** [comment]
is available in the latest version,  let me know if you have any issues.

**Comment by IonuDragomir1** [comment]
Hi, it works great for an object formed out of two ore more grouped shapes. When trying to color an object created out of two ore more grouped polyline objects, I can't do that.

**Comment by unocelli** [comment]
Hi, fixed and available in master branch
