### ISSUE TITLE
suggestion, add a way to add formulas

### ISSUE THREAD

**Issue by cicci44** [frangoteam/FUXA#75]
got this values pulled via modbustcp
![bild](https://user-images.githubusercontent.com/1296978/92309101-d1b10080-efa2-11ea-86df-2b7d39e52a9a.png)
and need to put them into a matchmatic formula to get readings of efficiency
![bild](https://user-images.githubusercontent.com/1296978/92309055-5d765d00-efa2-11ea-83d6-d0168d750622.png)
not sure if its already possible via shape or so...

**Comment by unocelli** [comment]
Can be done using scripts, so I am closing this issue.
