### ISSUE TITLE
FUXA show imported svg wrong, but svg file works fine on inkscape and firefox/chrome

### ISSUE THREAD

**Issue by scottzhang** [frangoteam/FUXA#754]
Normal svg image:
![image](https://user-images.githubusercontent.com/183091/227448432-b65328e8-85d3-47cb-8ff7-5bfa32878351.png)

In Fuxa:
![image](https://user-images.githubusercontent.com/183091/227448525-e0f06ca1-7ca5-466b-afdd-6069f2dfbba1.png)

Please Check the file.
![AC-DC-01](https://user-images.githubusercontent.com/183091/227448374-8d5e0797-2f96-4ec5-a54b-7bfd5b3887c1.svg)

**Comment by unocelli** [comment]
Hi, Thanks for the report,
We have not yet investigated, in any case if you save the image from Inkscape in 'Optimised SVG' format and import it in FUXA should works as expected

**Comment by scottzhang** [comment]
Dear unocelli:
    Thanks for reply.
    I tried use inkscape to save as "optimised svg". Then copy path to my-shape.js, yes, the problem solved. Thanks. 
    Then I tried drag the newly saved img to fuxa. Yes. The image doesn't get distorted but get another problem. When drag and drop, the resize frame is offset from the image by the drag direction. Please  Look at the image below:
![图片](https://user-images.githubusercontent.com/183091/227704404-9f9410ef-5a71-47d6-9c0d-abd8e86ae412.png)

    And I have another problem,  I notice the svg path in my-shapes.js doesn't have "fill" property. So I newly added images doesn't look like the original one, which has 'black’ fill. But if I added the fill:black, my img looks well, but all following added images have fill:black too, which are wrong. How to solve this problem? Thanks.

**Comment by unocelli** [comment]
Hi, can you send me the object that you have add in my-shapes.js.
I try and my object works as expected

`        
{
            name: 'acdc', ico: 'assets/lib/svgeditor/shapes/img/acdc.svg', content: [
                { id: '', type: 'path', attr: { d: 'm106.37 5.8466h-89.153c-7.0771 0-12.809 5.603-12.809 12.521v87.144c0 6.9177 5.7322 12.521 12.809 12.521h89.153c7.0771 0 12.809-5.603 12.809-12.521v-87.144c0-6.9177-5.7322-12.521-12.809-12.521zm-95.301 12.521c0-3.318 2.754-6.01 6.1485-6.01h89.153c0.44833 0 0.88064 0.04695 1.297 0.14086l-96.454 94.281c-0.09607-0.42257-0.1441-0.84515-0.1441-1.2677zm101.45 87.144c0 3.318-2.754 6.01-6.1485 6.01h-89.153c-0.44832 0-0.88064-0.047-1.2969-0.14085l96.454-94.281c0.0961 0.42258 0.14411 0.84515 0.14411 1.2677z', fill: '#000000' } },
                { id: '', type: 'path', attr: { d: 'm64.21 102.37v-21.348h7.5415c7.7496 0 11.624 3.4745 11.624 10.408 0 3.3023-1.0888 5.9473-3.2504 7.9507-2.1776 2.0033-4.9636 2.9893-8.4061 2.9893zm4.6594-17.623v13.898h2.5298c2.2096 0 3.9389-0.64169 5.2038-1.9251 1.2649-1.2834 1.8894-3.0206 1.8894-5.2274 0-2.1285-0.65648-3.7719-1.9694-4.9613-1.313-1.1895-3.0262-1.7842-5.1237-1.7842zm33.769 16.84c-1.5852 0.76689-3.6667 1.1425-6.2125 1.1425-3.2824 0-5.8923-0.95471-7.8297-2.8798-1.9374-1.9251-2.8981-4.4918-2.8981-7.7003 0-3.3649 1.0728-6.1352 3.2343-8.2793 2.1616-2.1442 4.9476-3.2241 8.3581-3.2241 2.1295 0 3.9228 0.26607 5.3639 0.81385v4.3979c-1.4731-0.84515-3.1543-1.2677-5.0116-1.2677-2.1295 0-3.8428 0.67299-5.1237 2.0033-1.2809 1.3303-1.9214 3.0676-1.9214 5.2274 0 2.0972 0.60844 3.7875 1.8253 5.0552 1.2169 1.2834 2.8501 1.9094 4.9156 1.9094 1.9374 0 3.7147-0.45388 5.3159-1.3773v4.1788zm-63.118-56.515h-4.9796l-1.6012-4.8048h-7.7816l-1.5691 4.8048h-4.9476l7.8457-20.941h5.3639zm-7.6536-8.248-2.4338-7.262c-0.16012-0.45388-0.2722-1.0643-0.33624-1.8312h-0.1281c-0.04803 0.61038-0.17613 1.2051-0.36827 1.7686l-2.4498 7.309h5.7162zm25.186 7.4968c-1.5531 0.75124-3.5866 1.1269-6.1004 1.1269-3.2343 0-5.7802-0.93906-7.6856-2.8328-1.8734-1.8938-2.8341-4.4136-2.8341-7.5594 0-3.3023 1.0568-6.01 3.1703-8.1228 2.1135-2.0972 4.8515-3.1615 8.198-3.1615 2.0975 0 3.8428 0.26606 5.2518 0.7982v4.3197c-1.441-0.8295-3.0902-1.2364-4.9156-1.2364-2.0975 0-3.7627 0.65734-5.0277 1.9564-1.2489 1.299-1.8734 3.0206-1.8734 5.1178 0 2.0503 0.59243 3.7093 1.7773 4.9613 1.1849 1.2521 2.802 1.8781 4.8195 1.8781 1.9054 0 3.6507-0.45388 5.2198-1.346z', fill: '#000000' } }
            ]
},
`

**Comment by scottzhang** [comment]
The path in my-shapes.js works fine.

The problem is drag the svg file and drop into FUXA directly. Then drag the the image to another position, the drag & resize frame get offset from original image.

**Comment by w8w8w8** [comment]
@scottzhang This may be svgedit problem
