### ISSUE TITLE
Modbus RTU over TCP/IP needed.

### ISSUE THREAD

**Issue by RoystonDaCosta** [frangoteam/FUXA#755]
When using serial servers (i.e. Ethernet to RS485 devices) the data need to be sent in the RTU packet format but over TCP/IP.
Is this something that can be done?

**Comment by unocelli** [comment]
Hi,
I think it would be better to ask to the people who implemented the driver used in fuxa [modbus-serial](https://github.com/yaacov/node-modbus-serial)

**Comment by rvbatista** [comment]
I believe that Modbus-serial driver already implement RTU over TCP.

**Comment by rvbatista** [comment]
Implemented in pull request #780
This is my first collaboration with a meaningful opensource project, please be kind.

**Comment by unocelli** [comment]
@rvbatista you are welcome :wink:

**Comment by RoystonDaCosta** [comment]
Thanks a lot for this feature

**Comment by rvbatista** [comment]
@RoystonDaCosta please give a feedback after you test.

**Comment by RoystonDaCosta** [comment]
@rvbatista I have tested #780 and it works as expected. Thanks a ton.

**Comment by rvbatista** [comment]
Thanks for the feedback.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
