### ISSUE TITLE
Displays for characters according to value

### ISSUE THREAD

**Issue by cbsbaosen** [frangoteam/FUXA#76]
I want to add a new control in Controls that displays the corresponding string based on the input value.It is similar to HTML_select, but does not require select, just display.At first I wanted to do this and submit the code, but looking at the code I found that I didn't have the extent-bundle.min.js source code, so I couldn't do it.Can you add this control?Thank you very much @unocelli 
![image](https://user-images.githubusercontent.com/20582261/92994207-e7866e80-f52a-11ea-96ca-b3a3b21cafc4.png)

**Comment by unocelli** [comment]
Hi,
why don't you use the Output Control ![image](https://user-images.githubusercontent.com/48684550/93596355-76770900-f9b9-11ea-8b76-8ba2ad387c63.png)

**Comment by cbsbaosen** [comment]
I think the Output Control can only display the original value collected.Maybe I didn't make it clear.I want a control to do a simple mapping display, such as capture 1 to show "ONE" and 2 to show "TWO".I think the SELECT control has this capability, while the Output control does not. @unocelli

**Comment by unocelli** [comment]
sorry ... you are right, i believe i can add a configurable attribute to the select control

**Comment by cbsbaosen** [comment]
It doesn't matter.I think you could add a new control ,or add configuration to Output or select control, both of which would be good options. Thank you.
Finally, If you need me to improve the project together, I am willing to do my best.

**Comment by unocelli** [comment]
I added the readonly option to the select control...
You are welcome

**Comment by cbsbaosen** [comment]
Can it be displayed as a label instead of a selection box?Like the Output control.This makes the interface more user-friendly.
