### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by takkuumi** [frangoteam/FUXA#760]
old version will show button like this

<img width="169" alt="image" src="https://user-images.githubusercontent.com/9606668/227709861-55a3a588-5442-4e2d-8369-780ba4e31219.png">

but new version , the button not visable

**Comment by unocelli** [comment]
Hi, you mean switch control, I don't confirm the issue, the new version also works as expected

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
