### ISSUE TITLE
"Sucessfully project save" banner (green alert) shows also when open a project from disk

### ISSUE THREAD

**Issue by mariorl** [frangoteam/FUXA#763]
it's not important, but when you open a project and Fuxa tells about "saving ok" one thinks that the project that was intended to be opened has been overwritten.

**Comment by IonuDragomir1** [comment]
Normally when a project is opened, the message displayed should be "Project opened successfully".
More important is that the user is not notified when "Save Project" button is pressed as is notified when clicks on "Save Project As..." button.

**Comment by IonuDragomir1** [comment]
@unocelli, as I said above, the user should be notified when clicks Save button. There are moments when I click the button and don't know if the project was saved successfully.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
