### ISSUE TITLE
Unauthorized downloading Reports

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#767]
Hi, 

I am trying to download the sample reports I created.
![image](https://user-images.githubusercontent.com/49782655/228749292-c228c3ac-861f-456f-8110-38dd086fed64.png)

But the console gives me error "Unauthorized" 

I logged on as administrator.

Regards,
Henjoe

**Comment by unocelli** [comment]
Hi, 
I don't think it depends on fuxa, you have to look at the permissions of the platform and the `server/_reports` folder

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
