### ISSUE TITLE
improvement_  Opcua performance needs to be improved

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#768]
When the performance of the opcua server is fine, after my test, when the number of points exceeds 4000 in FUXA, the speed is very slow.

**Comment by hxjackcn** [comment]
When "disable the broadcast of all tags", the client web will not be displayed. What is the function of this function?
![image](https://user-images.githubusercontent.com/102520227/229954568-929cdfa2-5759-47e8-9aac-0e621fdf81d7.png)

**Comment by hxjackcn** [comment]
> Hi, I suppose it also happens if you disable the broadcast of all tags (explained in #772)?

When "disable the broadcast of all tags", the client web will not be displayed. What is the function of this function?
![image](https://user-images.githubusercontent.com/102520227/229958854-70e581c1-2360-4c2f-9d43-2d72a9d8e95d.png)

**Comment by unocelli** [comment]
Hi, sadly, the feature still has some problems. Have any values been displayed?
