### ISSUE TITLE
BUG_      The latest version of opcua does not display data.

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#772]
The latest version of opcua does not display data.
![image](https://user-images.githubusercontent.com/102520227/229761114-a3f22ed7-bbbc-4a7a-9896-0e19bcf8d422.png)

**Comment by unocelli** [comment]
Hi, thanks for the report. 
The new feature still has some issues...the workaround is to enable the broadcasting of all tags. we will fix it as soon as possible.
![image](https://user-images.githubusercontent.com/48684550/229905225-4f739abd-d803-428b-a014-008f41083909.png)

**Comment by hxjackcn** [comment]
Hi,you solved this not displaying problem, thank you.
