### ISSUE TITLE
improvement_       slow page loading

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#775]
Hi, when the number of pages increases and there are many graphic elements or pictures on the page, opening any one of the pages will become very slow. For example, the number of pages reaches 80.

**Comment by hxjackcn** [comment]
Can you improve the speed of browsing? The slow loading speed in the editing state mode is tolerable.

**Comment by unocelli** [comment]
In the last version I add the feature to add linked image. this should solve the problem. 
I’m going to close this as resolved. let me know if you have any issues.

**Comment by hxjackcn** [comment]
great.

Umberto Nocelli ***@***.***> 于2023年10月12日周四 03:40写道：

**Comment by yuhuan0669** [comment]
How to use the add linked image feature in the latest release(v1.2.3)？

**Comment by unocelli** [comment]
Hi, via Resources you can only add SVG images
