### ISSUE TITLE
【improvement】The address of the iframe can be set as a label

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#776]
![image](https://user-images.githubusercontent.com/102520227/230586581-5346d4bf-269d-442a-9f1f-ad3f3c6f1d64.png)

**Comment by hxjackcn** [comment]
In this way, different web page addresses can be called by passing values

**Comment by hxjackcn** [comment]
thank you for your work

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by jingshui127** [comment]
npm install -g --unsafe-perm @frangoteam/fuxa
The version pulled is not the latest.
