### ISSUE TITLE
How to add my own dynamic SVG?

### ISSUE THREAD

**Issue by fleffer** [frangoteam/FUXA#777]
I tried to add dynamic SVG to Resource，but it turned to static SVG.If I want to used my own dynamic SVG,how can I do?

**Comment by unocelli** [comment]
Hi, what do you mean with dynamic SVG?

**Comment by fleffer** [comment]
Sorry for my poor English.I want to add SVG which like the pipe stays moving.The SVG I wanted to add contains the label "<animate>"

**Comment by fleffer** [comment]
Sorry for my poor English.I wanted to add SVG which stays moving ,such as the pipe.The SVG I wanted to add contains the lable "animate"

**Comment by unocelli** [comment]
The pipe is quite complicated, if you want to change the animation you have to look in PipeComponent where the style is added to the DOM object. Whereas if you want to create your own control you can refer to iframe or Table

**Comment by fleffer** [comment]
> The pipe is quite complicated, if you want to change the animation you have to look in PipeComponent where the style is added to the DOM object. Whereas if you want to create your own control you can refer to iframe or Table

It's a great method, it works great, thank you for your reply

**Comment by fleffer** [comment]
> The pipe is quite complicated, if you want to change the animation you have to look in PipeComponent where the style is added to the DOM object. Whereas if you want to create your own control you can refer to iframe or Table
The iframe has scroll bars, can I adjust the style of the scroll bars?

**Comment by unocelli** [comment]
I think so
