### ISSUE TITLE
[BUGS] Button Toggle / SVG Issues etc

### ISSUE THREAD

**Issue by MatthewReed303** [frangoteam/FUXA#778]
Hi, There seems to be a bug when using mouse click and toggle value. If you create new project and add just a button and output value and an internal fuxa tag button wont update the value. But if you add toggle switch and use the switch once then the button works fine. 

I have also noticed with some SVG I add the move controls for objects start working in opposite directions ( this happens for all objects ) have to create new project to stop it. Example you move object to the right with mouse the object actually moves to the left

There are a bunch of weird little glitches and things not working as expected. SVG fill colours will not change, but if I test with blank shape the fill works. The hide and show. If I set image to hide and show when value is true, the image does not hide until value is toggled to true and then back to false. ( the initial value is set to 0 ) 

I'm using latest docker version Version 1.1.13-1176

**Comment by rvbatista** [comment]
Have the same issue of the toggle became with the value false and not 0 and stop working.

**Comment by unocelli** [comment]
Hi, Thanks for the report.
We have removed a feature that caused that some values were not sent to the frontend. Please test again with the new version on the master branch

**Comment by unocelli** [comment]
@MatthewReed303 could you please send us an example project with the issues?

**Comment by MatthewReed303** [comment]
Hi @unocelli still have all the same issues with pulling latest. Here is a link to some screen recordings:
[https://nextcloud.mrea.co.nz/s/zZHonrNH8SER9yP](url)

**Comment by unocelli** [comment]
@MatthewReed303 I have just updated the docker version (latest) with the master branch
![image](https://user-images.githubusercontent.com/48684550/230760874-67a358d5-9cc1-407b-bf3b-076532f1a667.png)

About the editor, try clearing the browser cache

**Comment by MatthewReed303** [comment]
@unocelli Thanks button is working correct again and now project also saves the image. I have linked the project which has weird issues with move direction when the SVG is added

[https://nextcloud.mrea.co.nz/s/ejXM4Gt4K26eNWy](https://nextcloud.mrea.co.nz/s/ejXM4Gt4K26eNWy)

**Comment by unocelli** [comment]
@MatthewReed303 Thanks for the example, I can reproduce it. 
You have added an svg image that cannot be seen but which has sent the editor in strange status.
![image](https://user-images.githubusercontent.com/48684550/230770192-47c846a0-6711-43c8-a9b2-20494ad49ca0.png)

**Comment by MatthewReed303** [comment]
Hi @unocelli here is a link to the SVG File. You will also notice it does not display the motor correctly also. 

[https://nextcloud.mrea.co.nz/s/iAWSNiBxxKYXoYs](https://nextcloud.mrea.co.nz/s/iAWSNiBxxKYXoYs)

The fill colour would not work on the motor also. If I add normal SVG shape the fill works correctly. In the mean time I was you going to hide and show all the different states until the fill works. I will have grey/green/orange/red/black so very time consuming to add all these different colour SVGs for different Items. 

For the fill to work is there an common ID in the SVGs you are using on the existing SVG shapes? Can I for example rename the motor body ID to the ID the other shapes use and will the fill work?

**Comment by MatthewReed303** [comment]
What if we had an option under shape property's to enter in the SVG ID we wish to edit with fill/blink etc 

![SVG ID Option](https://user-images.githubusercontent.com/63492864/230798192-f4b6a0a1-47af-450e-8a5e-6cb7df3494b5.png)

we would also need an SVG ID field under action and blink also

Would this be a suitable option until such time imported SVGs can be fully edited like the one's included in the shapes?

**Comment by unocelli** [comment]
@MatthewReed303 About the svg image imported that the move controls is working in opposite directions, I investigated and noticed that the image format is version 1.1 and is not supported in fuxa editor, if you get the latest version of inkscape you can save for version 1.0 and everything works as expected

**Comment by unocelli** [comment]
I added #789 issue for clarity.

**Comment by MatthewReed303** [comment]
Hi @unocelli just coming back to the project to continue and trying to save svg as v1.0  but can't find option in the latest inkscape to save as that version. Where did you set the v1.0??
