### ISSUE TITLE
Customized dashboard cannot be retrieved. 

### ISSUE THREAD

**Issue by rgw123** [frangoteam/FUXA#782]
https://user-images.githubusercontent.com/112950683/231191318-a68103cc-7913-46e4-afdb-38c0e10253cb.mp4

Customized dashboard cannot be retrieved. 

![image](https://user-images.githubusercontent.com/112950683/231191914-179a6696-08ce-4ab7-a507-6b7b7639632e.png)

**Comment by unocelli** [comment]
Hi, I do not understand what you mean for dashboard

**Comment by rgw123** [comment]
Thank you for your reply，I&nbsp; send you a video。
dashboard,It means' gauge 'in fuxa，
I added a component in Fuxa, but the newly added component cannot be dragged out. I can't find where my problem lies, and then I saw the prefix. I don't know how or where this prefix is defined







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 凌晨3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 
Hi, I do not understand what you mean for dashboard

**Comment by unocelli** [comment]
The editor insert a svg component with a id and prefix so by initialize the view will be search id and add the component to the item. The prefix is only a simple way to find where to append the component. if you debug you will see the DOM structure of `ele`.

`let htmlBag = Utils.searchTreeStartWith(ele, this.prefixD);`

**Comment by rgw123** [comment]
But if I want to define a gauge component myself, how should I define the prefix? Or does the prefix not need to be defined, but if it is not defined, I cannot drag the defined component out. I don't know the rules for defining the prefix, or in which file, such as prefixD: 'D-BAG', why is it D-BAG? What is the basis for it


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 凌晨2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 
The editor insert a svg component with a id and prefix so by initialize the view will be search id and add the component to the item. The prefix is only a simple way to find where to append the component. if you debug you will see the DOM structure of ele.
 
let htmlBag = Utils.searchTreeStartWith(ele, this.prefixD);

**Comment by rgw123** [comment]
Sorry to bother, is this code just a drag and drop code? But I have customized the filling and still cannot drag it out. What files do I need to pay attention to when writing custom components




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 凌晨2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 
The editor insert a svg component with a id and prefix so by initialize the view will be search id and add the component to the item. The prefix is only a simple way to find where to append the component. if you debug you will see the DOM structure of ele.
 
let htmlBag = Utils.searchTreeStartWith(ele, this.prefixD);

**Comment by unocelli** [comment]
Hi,
you must follow how one of the latest controls has been implemented: iframe (html-iframe) and Table (html-table).

**Comment by rgw123** [comment]
Thank you for your suggestion. I am now able to drag it out, but it cannot be displayed. Can you help me? Thank you for your reply















































------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月15日(星期六) 凌晨3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 
Hi,
 you must follow how one of the latest controls has been implemented: iframe (html-iframe) and Table (html-table).

**Comment by unocelli** [comment]
you have to share your code, I can't imagine what the issue is

**Comment by rgw123** [comment]
Excuse me
Thank you for your reply. If I want to add some attributes of the instrument pointer on the dashboard, how should I add them, such as the width of the instrument pointer and the color gradient of the instrument pointer.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 下午3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 
you have to share your code, I can't imagine what the issue is

**Comment by unocelli** [comment]
For the color gradient you need a ColorPicker control that support gradient too (I have not found).
Keep in mind that fuxa uses the [gauge.js](https://github.com/bernii/gauge.js) library and if you want to add an attribute that does not exist in the library you have to modify the library too.

**Comment by rgw123** [comment]
Thank you for your reply. If I want to define some new features, they must be defined in the gauges. js file, right? Which gradient color did you say ColorPicker was not found? I don't understand what you mean. Is this feature included in this FUXA project?What I mean is that the color of the dashboard pointer can be changed to a gradient color。Thank you very much for answering my question. I hope we can stay in touch




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 凌晨3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 
For the color gradient you need a ColorPicker control that support gradient too (I have not found).
 Keep in mind that fuxa uses the gauge.js library and if you want to add an attribute that does not exist in the library you have to modify the library too.

**Comment by rgw123** [comment]
Excuse me，I would like to ask where the specific functions in this gague.js are defined, such as staticZones. Is this function directly defined in this file







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 凌晨3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 
For the color gradient you need a ColorPicker control that support gradient too (I have not found).
 Keep in mind that fuxa uses the gauge.js library and if you want to add an attribute that does not exist in the library you have to modify the library too.

**Comment by unocelli** [comment]
```
Gauge.prototype.render = function() {
 ...
  if (this.options.staticZones) {
```

**Comment by rgw123** [comment]
Hello! I would like to confirm whether Fuxa supports WebAssembly and whether there is a wasm.ts file in this project that can be used to call this project through WebAssembly.Thank you for your response.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月3日(星期三) 凌晨4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 Gauge.prototype.render = function() {  ...   if (this.options.staticZones) {

**Comment by rgw123** [comment]
I'm sorry to bother you again. I would like to know where the modes like "select", "fhpath", "line", "circle" in the General list are defined in the code. I'm a student researching FUXA and I think it's great. I'm trying to customize and modify it. Thank you for your help.
The problem I'm currently facing is that my icon (SVG file) can be displayed in the General list but cannot trigger the click function and cannot be dragged out. I don't know where the code for "click="setMode("****")"" is triggered. Can you translate this into English?


















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月3日(星期三) 凌晨4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 Gauge.prototype.render = function() {  ...   if (this.options.staticZones) {

**Comment by unocelli** [comment]
you must follow how one of the latest controls has been implemented: iframe (html-iframe) and Table (html-table).
(click)="setMode('own_ctrl-iframe')"

**Comment by rgw123** [comment]
Sure, thank you for your response. I would like to ask about the click trigger function inside. I have found several files such as ext-bundle-min.js, but these are compressed files. Is there an uncompressed version of the ext-bundle.js file available?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月15日(星期一) 凌晨2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 
you must follow how one of the latest controls has been implemented: iframe (html-iframe) and Table (html-table).
 (click)="setMode('own_ctrl-iframe')"

**Comment by rgw123** [comment]
How can I add other protocols to this FUXA project?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frangoteam/FUXA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 凌晨3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frangoteam/FUXA] Customized dashboard cannot be retrieved.  (Issue #782)





 
For the color gradient you need a ColorPicker control that support gradient too (I have not found).
 Keep in mind that fuxa uses the gauge.js library and if you want to add an attribute that does not exist in the library you have to modify the library too.

**Comment by unocelli** [comment]
Hi, sorry for the delay...it seems more like a discussion...in server there is a template device
