### ISSUE TITLE
The menu cannot be linked

### ISSUE THREAD

**Issue by airtw** [frangoteam/FUXA#79]
As mentioned in the title, the jump page cannot be realized, can you help?

**Comment by unocelli** [comment]
Hi,
can you explain a little more in detail...I suppose you looked at the [wiki](https://github.com/frangoteam/FUXA/wiki/HowTo-View-Layout)
eventually you can send me an example that doesn't work

**Comment by airtw** [comment]
Sorry that my description is too vague. Create a Menu item → select'Link by Click' → enter a link. The final result did not work.

**Comment by unocelli** [comment]
I fixed, tanks
