### ISSUE TITLE
How to specify which view to display

### ISSUE THREAD

**Issue by YuGuoYun901006** [frangoteam/FUXA#791]
Multiple views were designed in the same project. I hope to be able to display different views through different urls.

**Comment by tayfunonbasioglu** [comment]
http://localhost:1881/mak_1  , not working !, it used to work..

**Comment by unocelli** [comment]
It is applied to home url http://localhost:1881/home/my_custom_page

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
