### ISSUE TITLE
【BUG】If the four elements containing the image are copied as a whole, the attributes of the elements will be lost.

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#794]
![image](https://user-images.githubusercontent.com/102520227/232263034-ab2715ea-de59-4d4f-a6aa-e430fdf5b344.png)
![image](https://user-images.githubusercontent.com/102520227/232263077-00911059-235b-4b7c-9828-8692ec9532e2.png)

**Comment by hxjackcn** [comment]
If the image is not included, the attributes of the image element are not lost.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
