### ISSUE TITLE
Cannot read Properties of null (reading 'type') when paste objects in editor

### ISSUE THREAD

**Issue by gabrielbalinca** [frangoteam/FUXA#797]
When I paste objects (Texts or Rectangles) this error shows up in the console of the browser (Google Chrome):

![Screenshot 2023-04-19 152421](https://user-images.githubusercontent.com/32384258/233074206-8d4de6bd-295e-4176-a268-ba2f0d8eeaa1.png)

EDIT: From my tests, only objects from General tab generates this error.

**Comment by unocelli** [comment]
Hi, thanks for the report

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
