### ISSUE TITLE
page change of link

### ISSUE THREAD

**Issue by tayfunonbasioglu** [frangoteam/FUXA#798]
Is there a method to change the page

http://localhost:1881/editor  or  http://localhost:1881/my_custom_page(this is not work)

thax...

**Comment by unocelli** [comment]
Hi,
you can't navigate to the view via url but you can go directly to a view: try http://localhost:1881/view?name=[the View name].
You can only via navigation menu. We will add the feature

**Comment by hxjackcn** [comment]
http://localhost:1881/my_custom_page](http://localhost:1881/my_custom_page
still not working

**Comment by unocelli** [comment]
It is applied to home url http://localhost:1881/home/my_custom_page

**Comment by hxjackcn** [comment]
![image](https://user-images.githubusercontent.com/102520227/233743792-5c922189-92f5-4f39-bf5b-76f6d69f2346.png)

**Comment by unocelli** [comment]
Hi, Thanks for the report. We have fixed

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
