### ISSUE TITLE
Where can I see the undamaged fuxa-editor.min.js?

### ISSUE THREAD

**Issue by halloweb** [frangoteam/FUXA#80]
Where can I see the undamaged fuxa-editor.min.js ?thanks！

**Comment by unocelli** [comment]
I planned to publish it but first I would like to make some code refactory...
look to [svg-editor-2.8.1](https://github.com/SVG-Edit/svgedit/archive/svg-edit-2.8.1.zip) I only removed some things that I don't need.
Regards

**Comment by halloweb** [comment]
thanks!
