### ISSUE TITLE
numeric input with virtual keyboard

### ISSUE THREAD

**Issue by franzhefekranz** [frangoteam/FUXA#803]
when using "only number" for input value with virtual keyboard then digits of the entered value are in the opposite order. E.g. you enter 123 then the value shown is 321

**Comment by unocelli** [comment]
Hi, the problem has already been fixed #783 but is not yet released, which version are you using?

**Comment by franzhefekranz** [comment]
I'm using last release 1.1.12

**Comment by unocelli** [comment]
you have to use the branch master or docker

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
