### ISSUE TITLE
How to show width and height properties when I click the cirle shape?

### ISSUE THREAD

**Issue by xiaote0225** [frangoteam/FUXA#807]
![企业微信截图_16825755612747](https://user-images.githubusercontent.com/20942273/234775487-954df816-ebd8-4349-9f7c-2a87f37de4fb.png)
![image](https://user-images.githubusercontent.com/20942273/234775515-8c9d33b3-0e07-4c77-8b09-2504bb4d6545.png)

**Comment by unocelli** [comment]
Hi,
Closing as its a duplicate #717 please track this issue there
