### ISSUE TITLE
Suggestions about rendering alarms or history alarms

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#811]
Hi,
The suggestions I'm about to make are available both for alarms and history alarms.
1. It'd be very useful if would run a progress bar (like the indeterminate progress-bar shown in [this example](https://material.angular.io/components/progress-bar/overview)) until alarms are being  displayed. If there are, for example, 10000 alarms/history alarms, the user doesn't know if there are any alarms to be displayed or if the system crashed. The progress bar would tell the user to wait until all alarms are displayed.
2. In the above scenario, 10000 alarms, there isn't available the option of going to the last or first page.

![image](https://user-images.githubusercontent.com/58516894/235105040-049b4ccf-b8da-48f6-a470-71a88ca20681.png)
So beside the next and previous page option, it'd be great if would exist the options: first and last page. This option would be useful also for tags.

**Comment by unocelli** [comment]
We added an indicator for alarm loading and a data range picker for history.
The option jump to last and first page is available but hide. I wonder if it is really required?
![image](https://user-images.githubusercontent.com/48684550/236321758-965af312-c971-4a95-861c-0d921304dfab.png)

**Comment by IonuDragomir1** [comment]
Hi,

Thank you for the update!
"The option jump to last and first page is available but hide." What do you mean by "but hide"? Yes it's really useful. Like I said in my topic, if one would have 10000 alarms and would want to see what are the last 10 alarms would have to click 100 times to get to last 10 alarms if there are 100 alarms displayed on page. So the option jump to last and first page should be available and visible.

**Comment by unocelli** [comment]
I mean that we have decided to hide the option. with the latest update you can filter the interval and make sure you don't have 10000 alarms.

**Comment by IonuDragomir1** [comment]
I don't see why going to first/last page is an option to be hidden. I'll test the update and come back with a review.

**Comment by IonuDragomir1** [comment]
Thanks for update! Please show the option jump to last and first page on alarms. This option should be available also for tags declared on devices settings.

![image](https://github.com/frangoteam/FUXA/assets/58516894/ea668dfe-ce8e-4235-b7cb-acd81e38537e)

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
