### ISSUE TITLE
【BUG】The pop-up Iframe cannot be closed in full-screen mode

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#813]
![image](https://user-images.githubusercontent.com/102520227/235392730-95e7e4bf-ef9a-4dc9-a535-a15ff7c75ae1.png)

Press F11 browser to enter full screen mode

![image](https://user-images.githubusercontent.com/102520227/235393449-337d082f-4117-42e5-9386-30c9befd305c.png)

**Comment by unocelli** [comment]
which browser are you using? in chrome it works as expected

**Comment by hxjackcn** [comment]
After I restarted the computer, it didn't happen anymore.
