### ISSUE TITLE
Device tag window resize

### ISSUE THREAD

**Issue by Bobblejot** [frangoteam/FUXA#815]
Hi on a lower resolution display 1024x768, the device tag window when browsing OPC tags doesn't resize correctly to show the checkboxes.  I need to go into Inspector and force scroll to check the boxes.

Would scroll bars on this window or a resize fix be possible?

**Comment by unocelli** [comment]
Hi, I think you can solve the problem very simply by using the browser zoom

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
