### ISSUE TITLE
change the scrollbar style of the iframe

### ISSUE THREAD

**Issue by fleffer** [frangoteam/FUXA#818]
could I change the scrollbar style of the iframe?
![image](https://user-images.githubusercontent.com/73601691/236368511-6aac196f-62d8-46d2-a7d4-64685ea6a9ee.png)

**Comment by unocelli** [comment]
Hi, I think that you can't change it. i try 
```
iframe {
    scrollbar-width: thin;
}
```
but don't work

**Comment by fleffer** [comment]
I found that when the link is a video link, the scroll bar is gone.Could I use `overflow:hidden` to hide the style bar?

**Comment by fleffer** [comment]
I tried to add `overflow:hidden`  to 'body'.The  scrollbar disappeared.
![image](https://github.com/frangoteam/FUXA/assets/73601691/36856179-166c-4534-8cf6-5ef60c7a7ec2)
![image](https://github.com/frangoteam/FUXA/assets/73601691/2e991fbf-3a73-41d2-ba08-6a296345475e)
But I just made the changes in Chrome. If I can made this change in the code, where should I add the  `overflow:hidden`?

**Comment by fleffer** [comment]
maybe replace `iframe {
    scrollbar-width: thin;
}` with  `iframe  body{
    scrollbar-width: thin;
}`will working,I guess.

**Comment by unocelli** [comment]
You can also try it with browser developer tools...don't work

**Comment by unocelli** [comment]
I’m closing this issue since there is nothing feasible.
