### ISSUE TITLE
Issues about bar graph customization

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#819]
Hi,

I encountered some issue when trying to change bar graph's theme and layout settings. I'm running the last version of Fuxa. Please check the below video:

https://user-images.githubusercontent.com/58516894/236440047-1b20286c-bf1f-4712-b3bf-7e3ca7744b46.mp4

As you can see, when I switch to dark theme, graph's title, X and Y axis disappear. Dark theme I suppose it's meant to display a black background for bar graph.
If I want to customize the theme, I see that title and legend color are changed accordingly. Grid's color doesn't color yellow. Value (Y) and Category (X) axis don't change the color. The same is available for datalabel.
Another issue is about layout's show grid toggle button. When it's switched off shouldn't hidden the grid? The Show tooltip button works as expected.

**Comment by unocelli** [comment]
Thanks for the report, we will fix it as soon as possible.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by Wannapayeot** [comment]
How do you add data to a chart?

**Comment by unocelli** [comment]
@Wannapayeot what is not working?

**Comment by unocelli** [comment]
@Wannapayeot I planed to make a video tutorial
