### ISSUE TITLE
S7 connection does not support adding ports

### ISSUE THREAD

**Issue by junanshi** [frangoteam/FUXA#820]
![image](https://user-images.githubusercontent.com/49215888/236668404-e05255b4-d7e5-438f-b698-760d748345e1.png)
![image](https://user-images.githubusercontent.com/49215888/236668412-3ff9ac42-619a-41db-9ecd-a39ceee72fe9.png)

**Comment by rvbatista** [comment]
The module that FUXA uses doesn't accept change port, but there is one method to get the remote port on client.
https://github.com/mathiask88/node-snap7/blob/master/doc/client.md

**Comment by unocelli** [comment]
I’m closing this issue since there is nothing feasible.
