### ISSUE TITLE
strange behaviour on svg import

### ISSUE THREAD

**Issue by nkn134** [frangoteam/FUXA#83]
Drag and drop an image (or an svg file) actually works, but imported element cannot be moved until it's ungrouped/grouped some times.
Chrome console return that 
![Screenshot from 2020-12-18 11-43-56](https://user-images.githubusercontent.com/76206659/102605927-54ab3080-4126-11eb-9dfb-c177a0d7a3a1.png)

Latest Google Chrome version
Latest Fuxa version
Ubuntu 20.04

**Comment by unocelli** [comment]
Hi,
can you send me one of these pictures?

**Comment by nkn134** [comment]
Happens with every image, anyway that's one of them
I can't upload svg files, so i renamed in png
That doesn't seem to be correlated to file format, but somewhat random
![drawing](https://user-images.githubusercontent.com/76206659/102628335-ce084a80-4149-11eb-9f57-ffce6c432d38.png)

**Comment by pedromartins200** [comment]
I had similar situation.
Add the following to your svg

xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svg="http://www.w3.org/2000/svg" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://web.resource.org/cc/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" version="1.1"

**Comment by unocelli** [comment]
I'm going to close this as resolved. let me know if you have any issues.
