### ISSUE TITLE
server tag - bad interpratation

### ISSUE THREAD

**Issue by TomasAdvance** [frangoteam/FUXA#833]
Hi Fuxa team,
I found one bug in server tags interpretation. If you create tag as string and send to them some value simila like number server will convert it to number automaticly.
For example I use one fuction whitch setup tag with value "15-16" as string (I checked data type). But server will interpert as number and show only 15.
It is looks like if string start with number or sometin usable as number the server convet it to number.
THX

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
