### ISSUE TITLE
OPCUA Problem PLCNext (Phoenix) issue

### ISSUE THREAD

**Issue by IngoDe** [frangoteam/FUXA#84]
Hi frangoteam,
first i have to say that I'am very new to FUXA so it is possible that i miss some basics!
I installed it on Linux (Kubuntu 2004-LTS) NPM and NODE no problem, example project was fascinating and a good entry point.
But my PLC (Phoenix Contact PLCNext) is running under WIN 10 so I set it up, NPM + NODE
was a torture but succeeded. 
Connect to the OPC UA server is successful it offers various Nodes (see attached picture).
![grafik](https://user-images.githubusercontent.com/76224345/102653856-decbb700-416f-11eb-819a-e0df65abc4a1.png)
But the context to add variables from the OPC-Server fails. I do not get the chance to add tags.
It seems so that always the last entry point to do this ends in a never ending loop.
I tested it under UAExpert, there I can see my variables offered by OPC UA.
Any experiance from other users other suggestions from the team ?
Regards Ingo

**Comment by unocelli** [comment]
Hi, thanks...I have to fix it, I update to the new version of node-opcua
and there are some problems.
in the meantime you can try the version 1.0.7
https://github.com/frangoteam/FUXA/releases/tag/v1.0.7

Regards
umberto

Hi frangoteam,
