### ISSUE TITLE
reports 

### ISSUE THREAD

**Issue by patson12** [frangoteam/FUXA#841]
i have many tags added in reports but it gives zero value in report mail.. do you have something how reports work? and i get error in alarm reports
PFA
![Capture](https://github.com/frangoteam/FUXA/assets/96180028/6b01b9a3-25db-4ece-ae01-7dc34c27de17)

**Comment by unocelli** [comment]
Hi, have you the registration of the tags enabled?
![image](https://github.com/frangoteam/FUXA/assets/48684550/74584e8e-73be-4c5b-8e28-347ebc956080)

**Comment by patson12** [comment]
ok now its working fine.. but it seems when select many tags then reports get cut .. like suppose i added 20 tags into reports it prints only 15 tags in landscape mode. remaining 5 should come in next pages and like wise. i think some layout  format issue

**Comment by unocelli** [comment]
we could put a limit on the table. i prefer that the users are free to decide when there are too many tags. what would you propose?

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by yu-1949** [comment]
> 好的，现在它工作正常..但是，当选择许多标签时，报告似乎会被删减..就像我在报表中添加 20 个标签一样，它在横向模式下只打印 15 个标签。剩下的 5 个应该会出现在下一页，同样明智。我认为一些布局格式问题
May I ask if you have solved the problem that the value of the download report is all 0 in the master branch? The ones I download now are all 0
