### ISSUE TITLE
Suggestions Split Project 

### ISSUE THREAD

**Issue by w8w8w8** [frangoteam/FUXA#850]
First, thanks for the good project.

I suggest splitting the client project into three projects

A:  the svg_editor (only tool), save UI and tags mapping to server
B:  the runtime, from server get tags and values
C:  the server, admin can add tags 

and A project Only choose tags by Server Api not set IP and so on. Then when run B project , The value of the tags (variable) is given by the server, for example socket or http.

And, I want to make a .net6 project for server project. Can you give me some advises

**Comment by unocelli** [comment]
Hi, sorry for the delay...I think that your scope is to have the frontend as standalone. there is a branch 'wc-editor' that it would be nice to continue it.
