### ISSUE TITLE
Report access for User

### ISSUE THREAD

**Issue by unocelli** [frangoteam/FUXA#861]
### Discussed in https://github.com/frangoteam/FUXA/discussions/845

<div type='discussions-op-text'>

<sup>Originally posted by **PaulRohlik** June 14, 2023</sup>
Hello,
please, is it possible to download reports from the HMI environment?
Not by email.

Thank you</div>

**Comment by jingshui127** [comment]
I think so.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
