### ISSUE TITLE
How to use WebAPI?

### ISSUE THREAD

**Issue by Doboo** [frangoteam/FUXA#864]
Hi;
I noticed that the latest released version mentions new features: 'New WebAPI' API/getTagValue 'and' API/setTagValue '.

But how can someone help with using this WebAPI?

**Comment by Doboo** [comment]
Thanks a lot!

**Comment by Doboo** [comment]
I have tested and there is no problem with “getTagValue”  . But when use "setTagValue", the numerical value has already been written, but the prompt message is: error: "not_found" Message: "tag id not found: t_5588a151-0dbf4300; t_080f5955-0fd54761;
I'm a bit confused.

**Comment by Doboo** [comment]
And another question: 
How can I use these  api  wiht token?

**Comment by unocelli** [comment]
Hi, currently is not supported, we have a apiKey planned.

**Comment by unocelli** [comment]
@Doboo about the error that you have reported "not_found" Message: "tag id not found: t_5588a151-0dbf4300; t_080f5955-0fd54761;
I suppose that you are try to write in tags that are not found, please check your code.

**Comment by Doboo** [comment]
I tested the simultaneous writing of two points, and the values have been successfully written. But the prompt 'tag id not found' is just a bit strange, but it does not affect the use of the function.

**Comment by Doboo** [comment]
I tested the simultaneous writing of two points, and the values have been successfully written. But the prompt 'tag id not found' is just a bit strange, but it does not affect the use of the function.

**Comment by unocelli** [comment]
Hi, thanks for the report, We can reproduce it and we will fix it

**Comment by RajatDas2020** [comment]
Hi I want to get and post tag values, from Rest API testing tool. How to expose this tag id "id": "t_2f47264f-b9e4451d" to the outside fuxa ?

**Comment by unocelli** [comment]
@RajatDas2020 look at #650

**Comment by RajatDas2020** [comment]
Thank you, but what is the complete url for post , do we need to specify tag in the url itself like get ?
POST /api/setTagValue

**Comment by unocelli** [comment]
No you don't need in the url but as parameter
