### ISSUE TITLE
Historical values in table not in the same row.

### ISSUE THREAD

**Issue by Bundyra** [frangoteam/FUXA#867]
Hello!
I have a problem with values stored in historical table. Values from the same device and same timestamp are not presented in the same row. Can i fix that somehow?

![fff](https://github.com/frangoteam/FUXA/assets/79423733/17b870d4-5a9d-4000-a835-5d99275047e2)

**Comment by wonka929** [comment]
i'm seeing the same issue right now.
The change has been merged?
Just to know if i have to pull again the docker container to see the fix.

Thanks a lot.

**Comment by unocelli** [comment]
Hi, yes is fixed
https://github.com/frangoteam/FUXA/commit/41173c449a74282341c5fe4da49d3ceb18e9bd5b

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
