### ISSUE TITLE
Third argument in call to copyFileSync function within ./server/main.js

### ISSUE THREAD

**Issue by mohmeri** [frangoteam/FUXA#87]
**The following call in ./fuxa/server/main.js**

    fs.copyFileSync(defaultSettings, userSettingsFile, (err) => {...}

**fails with the error below.  I am on a Raspberry Pi 4 with node version 15.5.0.  I believe it is because the copyFileSync function expects a number as the third parameter instead of a function.  That call/error was bypassed when I manually copied the settings.default.js fine into _appdata/settings.js.**

node:internal/fs/utils:801
                `_node:internal/fs/utils:801
            throw new ERR_INVALID_ARG_TYPE('mode', 'integer', mode);
            ^
        TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received type function ([Function (anonymous)])
            at Object.copyFileSync (node:fs:2043:10)
            at Object.<anonymous> (/home/pi/fuxa/server/main.js:43:8)
       
**Note: There was no issue with the code when I re-ran it on an Ubuntu 18.04.2 LTS machine, with node v13.14.0**

**Comment by unocelli** [comment]
Fixed, thanks
