### ISSUE TITLE
What are the minimum system requirements?

### ISSUE THREAD

**Issue by jingshui127** [frangoteam/FUXA#870]
I have an Ubuntu system, 4 core A9 processor, the main frequency up to 1.4GHZ; 32-bit high-speed DDR3 memory 512M. Can I install and run FUXA?

**Comment by Bundyra** [comment]
I run it on Orange Pi Zero2 with no problem.

**Comment by jingshui127** [comment]
root@he:~# docker pull frangoteam/fuxa:latest
Error response from daemon: manifest for frangoteam/fuxa:latest not found
root@he:~# docker pull frangoteam/fuxa:latest
Error response from daemon: manifest for frangoteam/fuxa:latest not found

**Comment by jingshui127** [comment]
![image](https://github.com/frangoteam/FUXA/assets/47803837/c427f512-8763-4ada-bf59-57dc0ddfaf7b)

from :  jessejamescox/fuxa:latest

**Comment by jingshui127** [comment]
![mmexport1689924218689.png](https://github.com/frangoteam/FUXA/assets/47803837/c41e0195-8fb9-4d13-9d8d-c9bec6bcd1aa)

**Comment by concept10** [comment]
FUXA should run only any device that nodejs version supports. You can't guarantee any acceptable level of performance beyond testing with those nachine specs in reality.

**Comment by jingshui127** [comment]
Use docker.
Cannot install from official. It can only be taken from a third party.

**Comment by jingshui127** [comment]
> Use docker.
> Cannot install from official. It can only be taken from a third party.

So I can't use the latest version.

**Comment by unocelli** [comment]
I’m closing this issue since there is nothing feasible and due to inactivity.
