### ISSUE TITLE
Adaptation of Fuxa screens

### ISSUE THREAD

**Issue by robsori** [frangoteam/FUXA#879]
I have noticed for some time that after maximizing the browser page on which Fuxa is running, the new pages called from the project no longer keep their adaptation after the first page. Also, the pages that contain the multi view container are not adapted either. This is a big inconvenience because each new page called must be readjusted individually. Is there any setting that needs to be done to solve this problem? Thank you.

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
