### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by EtherGraf** [frangoteam/FUXA#882]
I intend to create a german translation file. 

Is there any support in doing so, or does it possibly already exist in the pro version?

**Comment by unocelli** [comment]
Hi, the German translation is missing, would be great...you have to add the fuxa\client\src\assets\i18n\de.json file,  add `{ text: 'dlg.app-language-de', value: 'de' }` in [languageType](https://github.com/frangoteam/FUXA/blob/master/client/src/app/editor/app-settings/app-settings.component.ts) and to be able to test it you have to be able to compile the frontend in angular.

**Comment by EtherGraf** [comment]
Created a pull request #894.

**Comment by unocelli** [comment]
Thanks again
