### ISSUE TITLE
dbClick function 

### ISSUE THREAD

**Issue by focusstudio** [frangoteam/FUXA#884]
Hi, I would like to congratulate you for the project.  But I have a question if it would be possible to add a dbClick function to call a sample view.  Regards

**Comment by unocelli** [comment]
Hi, Tanks and sorry for the delay. The double click is practically deprecated in web applications

**Comment by crane168** [comment]
> Hi, Tanks and sorry for the delay. The double click is practically deprecated in web applications
Our project would use this dbClick too! so consider it  please
