### ISSUE TITLE
Token Is Missing

### ISSUE THREAD

**Issue by saufister** [frangoteam/FUXA#885]
Hi, after update fuxa to latest version  i am found error in terminal  like this "2023-08-07T06:43:47.128Z [ERR]  Token is missing!" , can you help me ? 

And how to setting log out after 8 hours ? 

thanks for your help

**Comment by unocelli** [comment]
Hi, sorry for the delay.
You have to look in [fuxa/server/_appdata/settings.js](https://github.com/frangoteam/FUXA/blob/master/server/settings.default.js) and set: 
```
 secureEnabled: true,
 tokenExpiresIn: '8h',
```

**Comment by saufister** [comment]
hi, thanks for your help . its work
