### ISSUE TITLE
WEBAPI BUG

### ISSUE THREAD

**Issue by pc007007** [frangoteam/FUXA#886]
WebAPI can not set/access the port attribute.

**Comment by unocelli** [comment]
Hi, I don't understand what you mean?
![image](https://github.com/frangoteam/FUXA/assets/48684550/6d702ff2-fb86-4047-9137-c3604dd45379)

**Comment by pc007007** [comment]
![image](https://github.com/frangoteam/FUXA/assets/13336244/db44c4c1-5311-4523-98c1-e724072ccef3)
for the localhost get nothing.
![image](https://github.com/frangoteam/FUXA/assets/13336244/390ebf27-a0d5-4b37-a2cb-18f72922021b)

**Comment by pc007007** [comment]
No issue la, I use another method to establish the webapi service

**Comment by pc007007** [comment]
No issue la, i use anthor method to establish the webapi service
