### ISSUE TITLE
What does static prefix = 'I-HXI_' stand for?

### ISSUE THREAD

**Issue by scottzhang** [frangoteam/FUXA#887]
I am trying to follow html-iframe to create my own component which works like HtmlSwitch but by switching 2 different svg img depends on bind value. 

I tried to use another name for prefix and but the view in editor doesn't look right. Then I search code ,find the prefix should be one of these following:

"HXI_","HXB_","HXS_","GXP_","HXC_","BAG_","SLI_","HXT_"

so what do they mean ?

**Comment by unocelli** [comment]
Hi, you have to use 'D-OXC_' for your own control, (don't look the other one) if you will bind to the <div> element in <foreignObject>. you can take suggestions from html-iframe and html-table.
