### ISSUE TITLE
How can i config HTTPS in fuxa server

### ISSUE THREAD

**Issue by buihuuduc** [frangoteam/FUXA#890]
Hi everyone,
Present i use the iframe for embed fuxa to our server and must be config https. How i config it in setting config file in fuxa folder. Thank you.

**Comment by jiekechoo** [comment]
Setting `SSL` for  `apache httpd` or `nginx`, use `proxy` feature, it works.

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
