### ISSUE TITLE
Questions about fuxa scripts

### ISSUE THREAD

**Issue by zpczpc** [frangoteam/FUXA#891]
How does fuxa's server-side script get the number entered in the input value text field

**Comment by unocelli** [comment]
Hi, the feature is missing. we have to add 'ENTER' event to input control.

**Comment by unocelli** [comment]
The feature is in the last version. I’m going to close this as resolved. let me know if you have any issues.

**Comment by unocelli** [comment]
Hi, create a script with a parameter and bind it to the enter event of input control (Value have to be void)
<img width="633" alt="image" src="https://github.com/frangoteam/FUXA/assets/48684550/fe6ff479-97e9-49de-a05d-9a7010e3e32b">
