### ISSUE TITLE
Edit SVG type path

### ISSUE THREAD

**Issue by Dungcream** [frangoteam/FUXA#892]
I'm trying to control the svg size of a path type, is there a way I can adjust the height and width using the input box. Thank

**Comment by unocelli** [comment]
Hi, I would do it with a script on the frontend, but currently the handling of the ENTER event for the Input control is missing.

**Comment by Dungcream** [comment]
Yes, thank you. Hopefully the earliest version will have the part I'm looking for.

**Comment by unocelli** [comment]
The feature is in the last version. let me know if solve your issue

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
