### ISSUE TITLE
Where to view  fuxa-editor.min.js source code， non confusing source code

### ISSUE THREAD

**Issue by gitzhangliang** [frangoteam/FUXA#903]

**Comment by unocelli** [comment]
#527

**Comment by gitzhangliang** [comment]
fuxa-editor.min.js  Which version is it built on SVG-Edit ？  i want to add new function

**Comment by gitzhangliang** [comment]
in other words， how to build fuxa-editor.min.js from  SVG-Edit ?        when i build SVG-Edit, have one file is Editor.js , this file is same with  fuxa-editor.min.js ?

**Comment by unocelli** [comment]
The version is the 2.9.x (last one I don't remember) you find it in the history. I can't use it to integrate in fuxa because I make some change but you can use to make your own fuxa.

**Comment by gitzhangliang** [comment]
can you provide the code of you changed ,and send to my email 906356464@qq.com, thank you very much
