### ISSUE TITLE
Where to view  ext-bundle.min.js  source code， non confusing source code

### ISSUE THREAD

**Issue by gitzhangliang** [frangoteam/FUXA#904]

**Comment by gitzhangliang** [comment]
I want to customize a component

**Comment by unocelli** [comment]
Hi, to add or customize a control you have to follow how one of the latest controls has been implemented: iframe (html-iframe) and Table (html-table). Don't forget to share your control (PR).

**Comment by gitzhangliang** [comment]
I just want to know how to implement the overall process of a control。I find some source code of html-table control  in  ext-bundle.min.js,  just like

`window.extOwnCtrl = function() {
    window.svgEditor && svgEditor.addExtension("own_ctrl", function(c)
`
so I want to know Where to view ext-bundle.min.js source code

**Comment by unocelli** [comment]
In fact with the latest addition to the library it is possible to define your own control without having to modify ext-bundle.min.js. 
 I am currently developing a new control and use the same strategy.
