### ISSUE TITLE
What is Resources menu for?

### ISSUE THREAD

**Issue by kekebanban** [frangoteam/FUXA#906]
this menu has nothing in it, I don't see a upload button to upload some resource
![11111](https://github.com/frangoteam/FUXA/assets/97713660/b13fc91d-7f92-4e49-8c2d-1d2b64186853)
![2222](https://github.com/frangoteam/FUXA/assets/97713660/e15fdf40-a4d9-4247-bed2-fc319b8dc8ae)

**Comment by unocelli** [comment]
Hi, sorry for the delay, the resource menu would be a function to display your own created graphic components (like a library).
