### ISSUE TITLE
Fuxa Svg Editor full source code (unminified)

### ISSUE THREAD

**Issue by Piotruch88** [frangoteam/FUXA#91]
Hi

Could I get your Fuxa Svg Editor existing in path "client/src/assets/lib/svgeditor/" full source code (unminified)?

Thank you in advance :)

**Comment by unocelli** [comment]
Hi,
I have not yet published the 'fuxa-editor' project. In any case the code is based on a little modified version of SVG-edit (https://github.com/SVG-Edit/ SVG-edit).

**Comment by Piotruch88** [comment]
OK

I will be very gratful when I get those sources because I can't figure out how to convert SVG editor to Angular SCADA editor somthing like FUXA.

So could I get some tips on how to do it or
could I get sources to your Fuxa editor?

Thank you in advance :)
