### ISSUE TITLE
From the perspective of large-scale use, there are two things that need to be improved to make it more efficient.

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#910]
1、In projects, pages that are similar to each other are often created, or multiple groups need to be repeated on the same page. At present, it is possible to achieve page cloning and group copy within the page. But it lacks the following functionality: batch search and replace for all element data sources.

2、The pictures on the page do not need to be placed in the database, but are loaded into the folder through links. Put it in the data, loading is too slow.

**Comment by hxjackcn** [comment]
The picture problem has been solved, it’s great.

**Comment by unocelli** [comment]
About the 1° comment, you can change the tags binding by use 'Edit bind of Tags' in context menu.
![image](https://github.com/frangoteam/FUXA/assets/48684550/dcd15186-13fb-4eb3-b7e9-a08971c5c99a)

or via 'View item list'
![image](https://github.com/frangoteam/FUXA/assets/48684550/0731eb59-9510-40de-9c27-99214e8310d2)

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
