### ISSUE TITLE
[BUG] Actions

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#914]
https://github.com/frangoteam/FUXA/assets/102520227/ec8b1dab-2280-49f2-a7ba-ef97b4b21a6a

**Comment by unocelli** [comment]
Hi, Thanks for the report

**Comment by hxjackcn** [comment]
Rotate has no effect.

![image](https://github.com/frangoteam/FUXA/assets/102520227/02d86dd7-d411-4378-b691-db615efe9056)

**Comment by unocelli** [comment]
This is not a issue, the rotation depend from the tag value too:
Min=0; Max= 90

**Comment by hxjackcn** [comment]
https://github.com/frangoteam/FUXA/assets/102520227/928208b6-739f-4110-9162-9f7e11590b1c

**Comment by unocelli** [comment]
![rotation](https://github.com/frangoteam/FUXA/assets/48684550/a25b0dd2-ce96-4838-a123-fd6abf99960a)

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
