### ISSUE TITLE
[BUG] Exporting Chinese fonts is garbled

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#915]
![image](https://github.com/frangoteam/FUXA/assets/102520227/8154aabd-2306-44e8-84eb-ab7e218784cb)

**Comment by unocelli** [comment]
usually an acronym such as CSV and JSON is not translated

**Comment by hxjackcn** [comment]
The exported json is correct, but the Chinese fonts in the exported csv are garbled. I think it's an encoding issue with cvs export.

**Comment by unocelli** [comment]
Thanks for the report. to reproduce the bug we need a project in Chinese, can you provide us please.
