### ISSUE TITLE
When to Open Source fuxa-editor.min.js  Source Code

### ISSUE THREAD

**Issue by gitzhangliang** [frangoteam/FUXA#916]
Do you have a time plan to Open Source fuxa-editor.min.js  Source Code

**Comment by unocelli** [comment]
Hi,
https://github.com/frangoteam/FUXA/issues/527

**Comment by gitzhangliang** [comment]
not svg-edit.js,  i mean the code is  you changed base on svg-edit.js

**Comment by crane168** [comment]
> not svg-edit.js, i mean the code is you changed base on svg-edit.js

@unocelli After reading many issues, everyone should have this requirement
