### ISSUE TITLE
Proposal. Add views templates for cards/dialogs

### ISSUE THREAD

**Issue by NikolayMurha** [frangoteam/FUXA#92]
Hello.

I have dashboard with >40 semaphores and I need dialog for each of them.
All dialogs identical, but variables different for each dialog. 
Now I create 40 different views for each dialog.
I think, will be good to make views templates with placeholders instead of variables names, and set variables names on dialog properties.

**Comment by unocelli** [comment]
I think the issue is solved. I'm therefore going to close it.
