### ISSUE TITLE
[BUG] Circular gage scale

### ISSUE THREAD

**Issue by Joky12** [frangoteam/FUXA#922]
When i want to bind a tag with a circular gauge, and i set the min and max value different to 0, then it back to 0 when i click in the OK button.

![image](https://github.com/frangoteam/FUXA/assets/14794882/2d87ae11-e7a2-4b72-91fe-85390fa485f7)

Then i press OK and it's like:

![image](https://github.com/frangoteam/FUXA/assets/14794882/793a75e1-95d4-4008-8857-dffb76df1baa)

When i open the circular gauge editor again, i see that:

![image](https://github.com/frangoteam/FUXA/assets/14794882/f7b2c9de-b004-41c0-8363-9a75f902fae0)

**Comment by unocelli** [comment]
Hi, thanks for the report

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.

**Comment by Joky12** [comment]
Hi. The bug is resolved. I updated fuxa and problem is solved. Thank you!!
