### ISSUE TITLE
Feature Request:Specify a base page and a destination on the event opening page to update the specified subpages when using a mixed container

### ISSUE THREAD

**Issue by fanhai** [frangoteam/FUXA#923]
Specify a base page and a destination on the event opening page to update the specified subpages when using a mixed container
在事件打开页面上指定一个基础页面和一个目的地，以便在使用混合容器时更新指定子页面
![74ea948e2bf7278f9ba5f0eabd17c81](https://github.com/frangoteam/FUXA/assets/9838830/f8fe9132-ce66-4bc3-959b-fe5dc947abf0)

**Comment by fanhai** [comment]
实现思路：

First, divide the mixed container into several sub pages, each of which serves as a base page. You can place the base control page or drag and drop other pages to combine.

If you drag and drop the switch button directly on this page, the Events of the button can specify the basic sub page.

1）先将混合容器分成几个子页面，每个子页面作为一个基础页面，可以放基础控件页可以拖放其他页面进行组合。
如果这个页面直接拖放切换页面的按钮，按钮的Events可以指定基础子页面
2）如果这个页面直接拖放切换页面的按钮，按钮的Events可以指定基础子页面

**Comment by unocelli** [comment]
We have added the Panel control, see if that solves your request
