### ISSUE TITLE
how to replace sqllite database to mysql or mongodb

### ISSUE THREAD

**Issue by vipulmistry1792** [frangoteam/FUXA#93]
Hello sir,
i want to use mongodb or mysql database not sqllite

**Comment by unocelli** [comment]
Hi,
if you mean to replace the DAQ (Data acquisition) database, you have to recode the 'daqstorage.js' and 'daqnode.js' by 'server\runtime\storage'...when you have finished don't forget to make a pull request ;)

**Comment by vipulmistry1792** [comment]
Ok thankyou for the information
