### ISSUE TITLE
Can you introduce the features of the pro version?

### ISSUE THREAD

**Issue by jingshui127** [frangoteam/FUXA#930]
"I would like to see what features the pro version has. If it has the features I need, I would like to make a purchase. Also, is it possible to buy it using Chinese yuan?"

**Comment by jingshui127** [comment]
For example, currently there are not enough versions in the image library. Login information is not recorded and modification records cannot be tracked either.

**Comment by unocelli** [comment]
Hi, images library and login information are also included in the [pro version](https://frangoteam.org/releases).
