### ISSUE TITLE
[improvement] Page size changes, content automatically scales

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#932]

**Comment by mauroalexandre** [comment]
Can you reproduce it in any project that you can send us? Is the one that gives the error a project that we can access?

**Comment by hxjackcn** [comment]
The first situation. The following is the settings page. The page settings are relatively small, as shown in the figure below:
![image](https://github.com/frangoteam/FUXA/assets/102520227/e355f882-6e15-4d23-927a-87a586a9d8ec)
The effect of visiting this page alone is as follows:
![image](https://github.com/frangoteam/FUXA/assets/102520227/6e76293d-54d0-4e8c-92ad-f2204aec21d9)
In fact, you may want the following effect:
![image](https://github.com/frangoteam/FUXA/assets/102520227/690395a3-05d3-4621-9bb4-6d300bc01b2b)
The second situation. The page is larger and the settings are as follows:
![image](https://github.com/frangoteam/FUXA/assets/102520227/ed15090b-0b86-4623-99cf-70abe7bc07d2)
The display effect is as follows:
![image](https://github.com/frangoteam/FUXA/assets/102520227/96849563-0c88-44e4-bca1-6f8fcd31382c)
When the page becomes smaller, the effect is as follows:
![image](https://github.com/frangoteam/FUXA/assets/102520227/d0f18cb6-c64e-4011-b085-989d0d59798d)
In fact, the effect you want may be as follows:
![image](https://github.com/frangoteam/FUXA/assets/102520227/0fa01016-ba82-44ce-946e-bbf2ded94f57)

**Comment by unocelli** [comment]
Thanks for the report

**Comment by unocelli** [comment]
Hi, the feature should be available in the latest commit

**Comment by hxjackcn** [comment]
Thanks a lot, great work.

**Comment by LordNetro** [comment]
@unocelli Is there any option to keep the aspect ratio? Also the Cards that are opened are not resized.

Thank you in advance!

**Comment by unocelli** [comment]
@LordNetro you can't define a size of open card, the card take the size of view

**Comment by zblack88** [comment]
> @unocelli Is there any option to keep the aspect ratio? Also the Cards that are opened are not resized.
> 
> Thank you in advance!

Also for me it would be very useful to have a zooming option that auto-resize but keeping the original aspect ratio.

If youbset "Manual" zooming, when you have to insert a value on a input field, after clicking on it the page moves even without keeping the mouse button pressed, very annoying.
