### ISSUE TITLE
Dialog Close Script, or Hide Window close 'X'

### ISSUE THREAD

**Issue by unocelli** [frangoteam/FUXA#939]
### Discussed in https://github.com/frangoteam/FUXA/discussions/936

<div type='discussions-op-text'>

<sup>Originally posted by **robbudge** October 19, 2023</sup>
Any way to run a script on dialog close?
or to disable the close 'x' in the top right.
i use a common dialog and tag structure in the PLC for read only information, so when the use clicks on a device the  PLC is sent an index  to copy into the standard structure.
Write tags we use the Variable bind.
When the 'Close' button is clicked a value of 255 is written to the PLC inform the PLC the common structure is not  required. This common structure can be upwards  of 30 Variables Binding them would be a nightmare for 50 devices.

The problem arrises when the user simply clicks the 'X' and the dialog closes. the PLC is still copying  the data and the common area is  utilized.

a simple option would be  make the 'X' White so still active just not visible, Any ideas ???
</div>

**Comment by robbudge** [comment]
Works Great
