### ISSUE TITLE
Animation not working.

### ISSUE THREAD

**Issue by guiview** [frangoteam/FUXA#942]
in animation when i change the value , it rotate in same direction ,means when i set value first time in clockwise direction,it rotate in clockwise direction , after i change the value for anticlockwise rotation , it will rotate in same direction means in clockwise direction.

![image](https://github.com/frangoteam/FUXA/assets/149062747/909155bd-5e83-471d-bced-8d5ea5070b05)

**Comment by unocelli** [comment]
Thanks for the report

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
