### ISSUE TITLE
Number Formatting for Very Small Floating Point Numbers 

### ISSUE THREAD

**Issue by robbudge** [frangoteam/FUXA#943]
Currently running Version 1.1.16-1325
Some floating point numbers with scientific notation in the region of e-6 and less fail to render on both the output box and table object.

Raw Data Via OPCua
![image](https://github.com/frangoteam/FUXA/assets/15365138/13de3848-179b-4d15-899c-1ceb361ff730)
Dialog View
![image](https://github.com/frangoteam/FUXA/assets/15365138/4a526b36-b01b-48da-a01e-070ec422550d)

Even with extended formatting 10 Digits for the Output box and 0.000000 for the table we either get Zero or NAN.

**Comment by unocelli** [comment]
Hi, sorry for the delay. What type of data is that? (Double, Float, ...)

**Comment by robbudge** [comment]
That’s Float data.
The other image shows the raw data in the connections.
The data is OPCua of origin.

Best regards,
Robert Budgen
System Engineer Technical Solutions Expert

Bürkert Fluid Control Systems
Burkert Contromatic Inc.
5002 South Service Road<x-apple-data-detectors://4/1>
Burlington ON  L7L 5Y7<x-apple-data-detectors://4/1>
Cell:  (905) 630-0694<tel:(905)%20630-0694>
Phone: (905) 632-3033<tel:(905)%20632-3033>
Fax:     (905) 632-3833<tel:(905)%20632-3833>
***@***.******@***.***>
www.burkert.ca<http://www.burkert.ca/>

Sent from IPhone


On Nov 2, 2023, at 5:27 PM, Umberto Nocelli ***@***.***> wrote:

﻿

Hi, sorry for the delay. What type of data is that? (Double, Float, ...)

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
