### ISSUE TITLE
How to install on embedded devices, armv8/armv7

### ISSUE THREAD

**Issue by liulujian00** [frangoteam/FUXA#946]
**Describe the bug**
1.Nodejs is installed on the arm and can be used normally.
https://nodejs.org/dist/v18.18.2/node-v18.18.2-linux-arm64.tar.gz

2.A series of errors occurred when installing fuxa
2.1
![3](https://github.com/frangoteam/FUXA/assets/57060942/4a964aaf-4134-4736-a816-fdab19a6ae69)
![4](https://github.com/frangoteam/FUXA/assets/57060942/d430717c-fcdc-47a0-bb13-cf79bc53d8bc)

2.2 download   gcc-arm-10.3-2021.07-aarch64-aarch64-none-elf.tar.xz

https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-aarch64-aarch64-none-elf.tar.xz

with gcc-arm-10.3-2021.07-aarch64-aarch64-none-elf.tar.xz install fuxa，error follow

![1](https://github.com/frangoteam/FUXA/assets/57060942/c596b9b3-3c5e-46af-9f5c-28644e459b01)
![2](https://github.com/frangoteam/FUXA/assets/57060942/c0a30824-4c03-4c71-8125-9cb978b38335)

3. How to install on embedded devices, armv8/armv7？？？

**Comment by unocelli** [comment]
Hi, the problem is the node-snap7 (driver for Siemens PLC).
You have 2 options:
- remove the node-snap7 from package.json on server
- use nodejs version 14.21.3

**Comment by liulujian00** [comment]
This problem has troubled me for many days. Thank you for your suggestion. I followed your first suggestion and successfully installed FUXA. Thank you very much.
