### ISSUE TITLE
Line chart improvement

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#951]
Hi,

Line chart is working as expected, but is there a way of improving the zoom in action? When an user wants to zoom in a chart, the entire window is moving. Also, can't be zoomed a specific part of chart by simply selecting it.

Thanks in advance!

**Comment by unocelli** [comment]
Hi,
I suppose the reason is because you have enabled the zoom in the Layout setttings and this has priority over the chart zoom.

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
