### ISSUE TITLE
[BUG]Bar charts do not show historical data

### ISSUE THREAD

**Issue by vifun** [frangoteam/FUXA#955]
**Describe the bug**
The data has been configured and saved。Bar charts do not show historical data

**To Reproduce**
1. Go to 'Bar chart Settings'
2. Select 'date range'
3. The bar chart do not show historical data

**Screenshots**
<img width="365" alt="Annotation 2023-11-09 132240" src="https://github.com/frangoteam/FUXA/assets/57388686/0f7f7c6e-c437-4ee5-80d3-c9a5c6e080ab">

**Environment**
 - FUXA 1.1.14-1208: 
 - Node.js 14.15.1: 
 - npm 6.14.8:
 - Platform/OS:
 - Browser:

**Comment by unocelli** [comment]
Hi, thanks for the report, I will fix it as soon as possible

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
