### ISSUE TITLE
What's the usage of "Broadcast to client (frontend) all tags values" setting?

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#957]
Hi,

Sorry if this question has been already put, but what's the usage of "Broadcast to client (frontend) all tags values" setting from System tab?

**Comment by unocelli** [comment]
Hi, 
if active the backend sends all the values of the configured tags to the frontend regardless of the active view, otherwise it only sends those of the active views. However, it is recommended to deactivate the functionality for performance reasons, particularly if you have many tags.

**Comment by IonuDragomir1** [comment]
Thanks for your reply, @unocelli!
Though I didn't understand completely your explanation. 
"if active the backend sends all the values of the configured tags to the frontend regardless of the active view, otherwise it only sends those of the active views." So if broadcast enabled,  the backend sends all the values of the configured tags to the frontend regardless of the active view. If broadcast disabled, what happens?

For example I have 10 tags and 2 views (v1 and v2). v1 has 3 output fields with 3 of the 10 tags. v2 has 7 output fields with the remaining 7 tags.
**Case 1 - broadcast enabled:**
If active view is v1, this means that backend sends to view (frontend) the value of the 3 tags to be displayed on output fields. The other 7 tag values are not send. Am I right?

**Case 2 - broadcast disabled:**
No mater which view is active, all 10 tag values are send from backend to frontend?

**Comment by unocelli** [comment]
exactly but in the opposite, disabled sends only the necessary tags and enabled sends all
