### ISSUE TITLE
[BUG] Device connection Modbus TCP

### ISSUE THREAD

**Issue by Bundyra** [frangoteam/FUXA#959]
**Describe the bug**

**To Reproduce**
1. Go to Devices
2. Click on Add device
3. Add device ModbusTCP device
4. See Status "-"

**Expected behavior**
Device status "OK"

**Screenshots**
Device settings on FUXA version 1.1.5:
![image](https://github.com/frangoteam/FUXA/assets/79423733/b3aa3468-8e74-4404-80be-f85ad99ce314)
Device status:
![image](https://github.com/frangoteam/FUXA/assets/79423733/823de343-381e-4ff0-95fa-c9f7bd22aeb5)
![image](https://github.com/frangoteam/FUXA/assets/79423733/c556afd0-bd04-4612-b77a-66e61d12d3f5)
Device settings on FUXA version 1.1.2:
![image](https://github.com/frangoteam/FUXA/assets/79423733/bbc39ab5-f433-4a33-b002-9018374f5e7e)
Device status:
![image](https://github.com/frangoteam/FUXA/assets/79423733/5b0738a5-00af-419b-a12d-b75b3a472462)

**Environment**
 - FUXA version: 1.1.5
 - Node.js version: 14.21.3
 - npm version: 6.14.18
 - Platform/OS: Linux Ubuntu 22.04.3
 - Browser: Opera

**Comment by unocelli** [comment]
Hi, thanks for the report.
are there any error messages in the log file?

**Comment by Bundyra** [comment]
The only errors i got in log file are:
![image](https://github.com/frangoteam/FUXA/assets/79423733/2ec5ca63-7fd4-4f82-a8a3-fef71932ba33)
And i got the same errors in console.

**Comment by unocelli** [comment]
Nothing has changed between version 1.1.12 and version 1.1.15 for TCP. you have only more options for this connections. have you try version 1.1.14?

**Comment by dougkite** [comment]
I had the same problem on 1.1.15-1324.  Modbus tcp connections seemed to work but no status or value data updates. I confirmed there was network traffic 
Reverted to 1.1.14-1243 and it works.

**Comment by Bundyra** [comment]
On version 1.1.14 im getting error: "Cannot get /".

**Comment by Bundyra** [comment]
After reinstalling everything and starting with new clean project i tried adding device. Still status "-" but in error logs i got something like this: 
![image](https://github.com/frangoteam/FUXA/assets/79423733/65aa953b-eac3-40fd-bb97-3222b5d43bff)

**Comment by Bundyra** [comment]
Tried now version 1.1.13 and got same issue (Status "-") and no values on tags.

**Comment by Bundyra** [comment]
Just realized i have version 1.1.14-1243 installed on my server, and it works fine.

**Comment by Bundyra** [comment]
Just realized that i have version 1.1.14-1243 installed on my server and it works fine.
Device configuration on this version:
![image](https://github.com/frangoteam/FUXA/assets/79423733/875783b1-7ab8-4e43-923e-f363213177dd)
Same device but on version 1.1.15-1324:
![image](https://github.com/frangoteam/FUXA/assets/79423733/2a1081dd-a093-4179-9f21-a7e1a8b28b79)
I changed polling rate to 10sec. so i dont get readMemory errors in the logs, no new errors status still "-" and no values in the tags.

**Comment by unocelli** [comment]
Hi, the change between the two versions should not be relevant for the modbus. is the test on the same platform? are you able to debug it?

**Comment by Bundyra** [comment]
Test is on the same platform but i am not able to debug it

**Comment by unocelli** [comment]
Please tell me again what is your OS platform

**Comment by Bundyra** [comment]
Linux Ubuntu 22.04.3 only in terminal version

**Comment by unocelli** [comment]
you have installed from npm?

**Comment by Bundyra** [comment]
I've installed from source files

**Comment by unocelli** [comment]
I just tested it on Ubuntu 22 with nodejs v14.21.3 and a modbus simulator (ModRSsim2.exe), everything works as expected, try deleting and reinstalling node_modules

**Comment by Bundyra** [comment]
I removed node_modules dir and package-lock.json file, but it didnt help

**Comment by unocelli** [comment]
try connecting with another device like the simulator ModRSsim2...I have no idea, sorry

**Comment by Bundyra** [comment]
I just installed fresh version but from npm. It works.

**Comment by Bundyra** [comment]
Im gonna close as it works. Thank you for your time.
