### ISSUE TITLE
What's the difference between Image tool (embedded) and Image (link)?

### ISSUE THREAD

**Issue by IonuDragomir1** [frangoteam/FUXA#960]
Hi,

I've seen that in the last version, 1.1.15, was added Image (link) in Controls category. What's the difference between Image tool (embedded) and Image (link)? I've seen that's no difference on settings available for each control.

**Comment by unocelli** [comment]
Hi,
with embedded you add the full content of the image into the view, that can make the size of view really big. with link you save the image on the server and the view show it after have downloading it. with link if you export the project you have to take _upload_files on server too
