### ISSUE TITLE
MQTT not publishing  on-change (or otherwise) of linked internal tags 

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#964]
We have the ability to set up a MQTT JSON Keyed payload, Brilliant!

![image](https://github.com/frangoteam/FUXA/assets/25065897/a47fb7be-f8b9-4a39-a272-ed9377b829cd)

We can create internal tags!

![image](https://github.com/frangoteam/FUXA/assets/25065897/1fe9645f-0b0e-456a-a91e-7a0a79b20522)

We can assign the MQTT keys to internal tags ...

![image](https://github.com/frangoteam/FUXA/assets/25065897/869074bf-01dc-479c-9199-569a0b7388bc)

This is where that ends for me, interestingly if i link to the MQTT status I get published topics.

![image](https://github.com/frangoteam/FUXA/assets/25065897/276ff0a2-ff98-4a17-85b3-e271780dc7e2)

However changing the values linked to internal tags elicits nothing that I can detect. I'm fairly sure this is my user error ,  I have now tried everything I can think of, this seems like it should be fairly simple... 

Perhaps internal tags are simply just for the front end (that would be a shame)? If so is there another way to directly point to an MQTT topic's key from the frontend? 

Perhaps tag binding is the solution? But you cannot select a MQTT topic's Key, simply the parent. 

Keep up the good work :)

**Comment by unocelli** [comment]
Hi, internal tags are only to be used on the frontend, they do not communicate with the backend and therefore cannot be published

**Comment by lewsut** [comment]
It would perhaps be woth having them made unavailable from the backend selections then?

**Comment by unocelli** [comment]
you are right, it is not consistent in all settings
