### ISSUE TITLE
[BUG] Why use a single project? Can multiple projects be supported?

### ISSUE THREAD

**Issue by LJH95224** [frangoteam/FUXA#966]

**Comment by LJH95224** [comment]
在实际使用过程中，多项目才更符合普遍的业务需求。那么有没有什么办法可以支持多个项目的运行嘛？

**Comment by LJH95224** [comment]
In practical use, multiple projects are more in line with common business needs. Is there any way to support the operation of multiple projects?

**Comment by unocelli** [comment]
Hi, you can install and start more instance of FUXA, you have only to change the port. In any case this feature is not planed
