### ISSUE TITLE
Script string issue.  

### ISSUE THREAD

**Issue by lewsut** [frangoteam/FUXA#967]
In order to show a string as opposed to a number you have to start with a letter or some non number bases character. I wanted to show '22'+':'+'55' I will get the correct result in the console test but I will just get 22 once passed to the tag.

If a letter is placed in front of this, it's interpreted as a string e.g.   'x22'+':'+'55'  (x22:55 at tag)

Here are some simple examples.

![image](https://github.com/frangoteam/FUXA/assets/25065897/469149da-636c-4a14-aa4f-c4cc9ee7e9b8)

![image](https://github.com/frangoteam/FUXA/assets/25065897/833648dd-63e3-4906-bc02-1320661bfb12)

**Comment by lewsut** [comment]
@unocelli Did you change anything? Grabbed the latest docker (5 days old) and the scripts work as expected, I still have the old container and it doesn't work, as above

**Comment by unocelli** [comment]
then it can be closed

**Comment by lewsut** [comment]
Just checking as you never replied to "needs investigating" nor were there ever any updates on it...
