### ISSUE TITLE
[BUG] working (connection || polling) overload! 

### ISSUE THREAD

**Issue by zxywind** [frangoteam/FUXA#975]
**Describe the bug**
After starting yarn start, all OPC UA type device connections fail with the error "working (connection || polling) overload!". On the device page, all devices except the first node FUXA Server are listed as disconnected. Clicking "Edit" and then "OK" will reconnect the device, and everything will work normally after that. And, It seemed only OPC UA devices are  affected by this issue.

**noScreenshots**

**Environment**
 - FUXA version: 1.1.14-1243
 - Node.js version: 16.20.2
 - npm version: 8.19.4
 - Platform/OS: rocky 9.2
 - Browser: edge

**Comment by robbudge** [comment]
I also see this, Plus some other strange  errors


2023-11-23T18:02:47.853Z [ERR] 	'ns=4;s=|var|Edge Controller PIO3.Application.PVL.Config.LTun.Recipe.Transfer[0].Max_Volume' _startMonitor Error: Invalid Channel after performing transaction on CreateMonitoredItemsRequest
2023-11-23T18:02:47.909Z [ERR] 	'ns=4;s=|var|Edge Controller PIO3.Application.PVL.Config.LTun.Recipe.Transfer[0].Min_Flow' _startMonitor Error: Invalid Channel after performing transaction on CreateMonitoredItemsRequest
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit

**Comment by unocelli** [comment]
Hi, how many opcua devices have you configured?

**Comment by robbudge** [comment]
Single Device, 900 tags

**Comment by unocelli** [comment]
Have you try to separate the connection in more devices? there seems to be a limit of monitoring subscription, can be on FUXA but in opcua server too

**Comment by zxywind** [comment]
I have separated the connection in more devices(split 4000 tags to 4 devices)
but It looks still working wrong.
 and reconnect is not working now.
thanks

**Comment by unocelli** [comment]
Hi, it would be interesting to know on which opcua server and plc are you connecting, and also to know from how many subscriptions do you start having problems?

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
