### ISSUE TITLE
[BUG] Changing view from layout button.

### ISSUE THREAD

**Issue by Bundyra** [frangoteam/FUXA#978]
**Describe the bug**
Layout button that allows 'view on click' function is not working properly when we redirect view to another 'subview' via button.

**To Reproduce**
1. Go to view 'Test1' by layout 'view on click' function.
2. Click on button 'SUBVIEW' with open page function to view 'SUBVIEW'
3. Click on layout button 'Test1' with 'view on click function'.
4. See no action, we are still on 'SUBVIEW' page.

**Expected behavior**
Redirection to view connected to layout button with function 'view on click'.

**Screenshots**
1. Layout button with view 'Test1'
![image](https://github.com/frangoteam/FUXA/assets/79423733/6623835d-1a8f-482e-b956-77002f912788)
2. Page 'Test1' with button that opens page 'SUBVIEW'
![image](https://github.com/frangoteam/FUXA/assets/79423733/85111956-8f2b-4857-99fb-1aa34c6eb0a7)
3. Layout button doesn't open view 'Test1'
![image](https://github.com/frangoteam/FUXA/assets/79423733/ab29fe99-6c49-45f3-bb60-7da3429bb6d0)

**Environment**
 - FUXA version: 1.1.15-1324
 - Node.js version: v16.21.3
 - npm version: 8.19.4
 - Platform/OS: Windows 10
 - Browser: Opera

**Comment by unocelli** [comment]
Hi, Thanks for the report

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
