### ISSUE TITLE
[BUG] Caton

### ISSUE THREAD

**Issue by Beyond2324** [frangoteam/FUXA#980]
**Describe the bug**
Click on the properties to select the page to jump to or open the form program to directly pause.

Has the author encountered this situation before? Is it related to having too many tags? I have over a thousand tags and many pages that need to be redirected, which I have never encountered before

**Comment by unocelli** [comment]
Hi, 
certainly the performance depends on the platform where FUXA is installed, devices and protocols used. With more than a thousand tags I would disable the broadcast.
![image](https://github.com/frangoteam/FUXA/assets/48684550/a29ef513-f3ff-4aea-8f98-22a72a2340a7)

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
