### ISSUE TITLE
[BUG] Bar chart doesn't change date range.

### ISSUE THREAD

**Issue by Bundyra** [frangoteam/FUXA#984]
**Describe the bug**
Bar chart doesn't change date range (it's always shown for option 'Last day' group: 'hours').

**To Reproduce**
1. Go to 'Bar chart settings'
2. Select data range
3. Change data range for last week.
4. See no changes in the chart.

**Expected behavior**
Bar chart changes data range. 

**Screenshots**
Chart settings (in English: Last week, group: Days):
![image](https://github.com/frangoteam/FUXA/assets/79423733/9bc970b1-c5e5-4ca9-a052-bb9323a92571)
Chart:
![image](https://github.com/frangoteam/FUXA/assets/79423733/8d4624de-b5ea-404e-8f11-398bae56307c)

**Environment**
 - FUXA version: 1.1.15 - 1324
 - Node.js version: 16.21.3
 - npm version: 8.19.4
 - Platform/OS: Windows 10
 - Browser: Opera

**Comment by Bundyra** [comment]
okay so maybe i am wrong in terms of values, but does the data range change works for you?

**Comment by unocelli** [comment]
Yes

**Comment by unocelli** [comment]
I’m going to close this as resolved. let me know if you have any issues.
