### ISSUE TITLE
[BUG] Historical chart doesn't work with negative values.

### ISSUE THREAD

**Issue by Bundyra** [frangoteam/FUXA#986]
**Describe the bug**
Historical chart doesn't work with negative values. Chart is blank.

**To Reproduce**
1. Go to 'Chart settings'
2. Set historical chart option
3. Use chart with negative values
4. See blank chart

**Expected behavior**
Historical chart works and shows negative values.

**Screenshots**
Chart settings:
(English: Historical, last 8 hours):
![image](https://github.com/frangoteam/FUXA/assets/79423733/5130d750-0142-4ad3-9ebc-6c54162bd634)
Tag that i want to display:
![image](https://github.com/frangoteam/FUXA/assets/79423733/fda20173-1e9a-4b4b-80d6-fe3d76a15c7e)
Historical chart:
![image](https://github.com/frangoteam/FUXA/assets/79423733/637fbee5-58d1-4922-aed3-b8c80722e36e)
Normal chart with **negative** value:
![image](https://github.com/frangoteam/FUXA/assets/79423733/226ad757-b3ea-40da-8bcc-6d81f26f40bd)
Historical chart with **positive** value:
![image](https://github.com/frangoteam/FUXA/assets/79423733/b547fee1-d145-4796-a346-0478e94993f0)

**Environment**
 - FUXA version: v1.1.15 - 1324
 - Node.js version: 16.21.3
 - npm version: 8.19.4
 - Platform/OS: Windows 10
 - Browser: Opera

**Comment by unocelli** [comment]
Hi, I can't confirm the issue.
Are data from what kind of device?

**Comment by Bundyra** [comment]
Its a modbusTCP connection with Solar-Log 2000

**Comment by Bundyra** [comment]
Got it now, changed it from Input register to holding register and it works fine.
