### ISSUE TITLE
[BUG] Confguration of InfluxDB address 

### ISSUE THREAD

**Issue by robbudge** [frangoteam/FUXA#995]
Testing  on Version 1.1.17-1370

When configuring Daq Connection Influx 2+,
Failure to Specify protocol in Server URL will break the runtime after a  'Restart' Command. Leaving no accesses to the system.
Daq Server URL 192.168.10.13:8086 would result in failure.
/server/_appdata/mysettings.json has to be manually edited too include http:// or https:// 
http://192.168.10.13:8086

Perhaps a validation check could be included to ensure https:// or http:// is included in the Daq Servers URL.

**Comment by robbudge** [comment]
I was modifying the catalog setting on the V1.17 release and omitted the http:// prefix for my InfluxDB server. 

Obviously I got lots of errors. 
thinking it was a change error I restarted the Fuxa Process and it failed to launch and exited on startup. 
knowing what I had just changed, I modified the base file with the correct http:// prefix. 
restarted and all was good.

**Comment by mauroalexandre** [comment]
#1062

**Comment by unocelli** [comment]
This issue should be fixed in the latest version. let me know if you have any issues.
