### ISSUE TITLE
[BUG] No state shown for MQTT connection

### ISSUE THREAD

**Issue by 23Errors** [frangoteam/FUXA#998]
Hi, I have a Mosquitto broker running on my PC. Connecting FUXA to the broker works fine accordig to the Terminal. But in the connections list there is no state shown. If I subscribe to a topic mosquitto shows the subscription of FUXA, but I never get values into FUXA over this subscription. Also publishing doenst work.

**Comment by lewsut** [comment]
I have the same setup, it works fine for me... perhaps post your connections and setup details?  like this:

![image](https://github.com/frangoteam/FUXA/assets/25065897/6e8af2d9-408a-46e3-8643-aa28051dfa39)

![image](https://github.com/frangoteam/FUXA/assets/25065897/994f8dbf-66bf-4383-b3ec-eb717e8dfffd)

**Comment by 23Errors** [comment]
I have the same setup like you posted. The only difference is my adress. I am connecting the FUXA server to the Mosquitto broker over `mqtt://localhost:1883`

**Comment by lewsut** [comment]
Just for fun, try using the IP address. Have you used something like MQTT Explorer to make sure everything is working as it should, Mosquitto can be a bit finicky to get working as intended (I find).

**Comment by lewsut** [comment]
Show me your Mosquitto config please, I assume it has the following?


![image](https://github.com/frangoteam/FUXA/assets/25065897/9d99c1dc-9aed-4ee5-be4e-ba51cd595e0b)

**Comment by 23Errors** [comment]
[mosquitto.txt](https://github.com/frangoteam/FUXA/files/13632065/mosquitto.txt)
Thats my config. I didnt changed much, but yes I changed allow_anonymous to true. But the listener wasnt configured by me, because the default port is 1883.

**Comment by lewsut** [comment]
please try with the port specified...

**Comment by 23Errors** [comment]
I tried with specified port, but nothing changed. 😕

**Comment by 23Errors** [comment]
What I noticed is, that there is also no state shown in the FUXAServer. Is this normal maybe this is also an issue and I have to look on other settings than MQTT.

**Comment by 23Errors** [comment]
Ok, I tried the installation directly over npm. Before I was using the downloaded sourcecode and started FUXA with `npm start`.
And what should I say with the direct installation over npm it works flawless.

**Comment by 23Errors** [comment]
Ok, I tried the installation directly over npm. Before I was using the downloaded sourcecode and started FUXA with `npm start`.
And what should I say with the direct installation over npm it works flawless.
It was a stupid mistake in the installation process.
But anyways thanks for the help.
