### ISSUE TITLE
[FEATURE]Choose device tags support from JSON 

### ISSUE THREAD

**Issue by gxherror** [frangoteam/FUXA#999]
I get the JSON from ohter platform using WebAPI device, the JSON format is unable to change, I want the tag like this:  temperature->25, version->1.0, but it don't work, how can I do this?
```JSON
{
    "temperature": [
        {
            "ts": 1701939648842,
            "value": "25"
        }
    ],
    "version": [
        {
            "ts": 1701939648842,
            "value": "1.0"
        }
    ]
}
```

my version:FUXA-1.1.15

**Comment by lewsut** [comment]
read how to use JSON.parse then use a script in edit project to manipulate the data into the tags you want ...
![image](https://github.com/frangoteam/FUXA/assets/25065897/e0e39655-9cef-405f-ba73-80b7256ac5e7)

**Comment by gxherror** [comment]
thanks, i will try this
